### DISCUSSION TITLE
Error with cluster Restore

### DISCUSSION THREAD

**Discussion by Abhiger** [vmware-tanzu/velero#3273] [Community support Q&A] [answered]
Hi All,

Cluster: error restoring mutatingwebhookconfigurations.admissionregistration.k8s.io/aks-webhook-admission-controller: MutatingWebhookConfiguration.admissionregistration.k8s.io "aks-webhook-admission-controller" is invalid: webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"
Namespaces: <none>

While restoring an AKS cluster I get the following error 
_Cluster: error restoring mutatingwebhookconfigurations.admissionregistration.k8s.io/aks-webhook-admission-controller: MutatingWebhookConfiguration.admissionregistration.k8s.io "aks-webhook-admission-controller" is invalid: webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "Namespaces: <none>_

Will Velero restore not work if the SideEffects Key is set to "UnKnown"  ?
Do we have to explicitly set the value to "None" or  "NoneOnDryRun" ?

**Comment by nrb** [comment]
@Abhiger Velero doesn't modify the webhook properties that get backed up. This is due to AKS having support only for 2 values on its webhook side effect field, as shown in the error message.

Were you migrating between versions of AKS? That may have introduced this new constraint.

**Comment by HizzyCO** [comment]
I have this same error and haven't migrated version. @nrb wnat info do you need to help resolve this?

**Comment by taisyo7333** [comment, marked as answer]
I have the same issue. 
My environment is the following.

# Environment
* Velero v1.5.2
* Amazon EKS v1.18.9-eks-d1db3
* Chart v2.14.1
* Helm v3.4.2
 
# Log
```json
{"level":"info","logSource":"pkg/restore/restore.go:1170","msg":"error restoring pod-identity-webhook: MutatingWebhookConfiguration.admissionregistration.k8s.io \"pod-identity-webhook\" is invalid: webhooks[0].sideEffects: Unsupported value: \"Unknown\": supported values: \"None\", \"NoneOnDryRun\"","restore":"velero/velero-backup-20201224075249-20201224173831","time":"2020-12-24T08:39:14Z"}
```
# Describe -> Errors
```yaml
Errors:
  Velero:     <none>
  Cluster:  error restoring mutatingwebhookconfigurations.admissionregistration.k8s.io/pod-identity-webhook: MutatingWebhookConfiguration.admissionregistration.k8s.io "pod-identity-webhook" is invalid: webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"
  Namespaces: <none>
```

# Work around
The work around I did is the below.

```
velero restore create --from-schedule velero-backup  --exclude-resources MutatingWebhookConfiguration.admissionregistration.k8s.io
```
