### DISCUSSION TITLE
Velero selects wrong snapshotclass for CSI backed PVC's when multiple VolumeSnapshotClass resources available

### DISCUSSION THREAD

**Discussion by togoschi** [vmware-tanzu/velero#3388] [Community support Q&A]
We've deployed the v1beta1 snapshot feature on kubernetes and testing Velero's CSI feature for PVC backup's. Basically it works but with multiple SnapshotClasses available Velero doesn't pick up the right snapshotClass for the corresponding StorageClass. It seems that behaviour is random though the comment https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/v0.1.2/internal/util/util.go#L127 indicates that's already implemented. Is it possible that we miss any annotation/parameter to select explicitly the VolumeSnapshotClass for a backup resource? In addition changing the snapshot.storage.kubernetes.io/is-default-class annotation of the volumeSnapshotClass definition has no impact on this malformed behaviour.
 
Our test environment runs with
- Kubernetes v1.18
- Ceph-CSI v3.2.1
- CSI external-snapshotter v3.0.3
- Velero v1.5.2 (+ v1.5.3) with enabled CSI feature
- Velero Plugin-for-CSI v0.1.2
- multiple deployed RBD StorageClass resources accompanied by its corresponding VolumeSnapshotClass resources

Each VolumeSnapshotClass uses the same provisioner and is illustated by the following example definition:

```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: csi-rbd-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "false"
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: rbd.csi.ceph.com
deletionPolicy: Delete
parameters:
  clusterID: xxxxxxxx-xxxx-xxxx-xxxxxxxx
  csi.storage.k8s.io/snapshotter-secret-name: csi-rbd-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: kube-system
```
