### DISCUSSION TITLE
Performing ONLY Restic Volume backups

### DISCUSSION THREAD

**Discussion by Angelin01** [vmware-tanzu/velero#3479] [Community support Q&A]
We are trying to setup scheduled backups for some of our applications, but would like to backup only the data, not anything else, as we use helm charts and other automation to control the infrastructure, and as such those backups are unnecessary.

Using the helm chart, we tried setting up a backup schedule similar to this one:  
```yaml
schedules:
  myapplication:
    schedule: "30 2 * * *"
    template:
      ttl: "720h"
      includedNamespaces:
      - myapplication
      includedResources:
      - pv
      - pvc
```

The values also included the necessary Restic values, including the default Restic to volumes option (minimized here, obviously):
```yaml
configuration:
  defaultVolumesToRestic: true

backupsEnabled: true

snapshotsEnabled: false

deployRestic: true
```

However, we noticed that this did not produce any Restic backups, probably due to us pointing the only resources to the PVs and PVCs. We also tried disabling backups (`backupsEnabled: false`) and leaving all resources enabled, which works as we intend (Restic backups are created normally, nothing else is), but has the side effect that the default storage location is not created on a `helm install` if it didn't exist previously, which is not ideal.

I searched through the documentation and issues and did not find anything similar, surprisingly. I must admit, my knowledge of Kubernetes is still a bit lacking, so there's a considerable chance this is just ignorance on my part.

So, we'd like to know: is there a way to perform this operation without excluding all resources? Should I point my backups only to one specific resource? If so, which one?
