### DISCUSSION TITLE
Creating a restore spec without executing it

### DISCUSSION THREAD

**Discussion by headyj** [vmware-tanzu/velero#3620] [Community support Q&A] [answered]
Hello,

I need to create a specific restore spec, as I need an init container with a mounted volume, which is not possible with the init.hook.restore.velero.io annotations.

How can I create a restore spec without executing it now? Something like we do with the schedule spec: we specify the configuration for the backup (init containers, etc), and then we can run this schedule later on.

What could be great would be to have both backup and restore hooks in schedule spec, as we already can restore from a schedule using velero restore create --from-schedule

**Comment by ashish-amarnath** [comment, marked as answer]
Here is a restore spec that you can use to craft your restore spec
```
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: r2
  namespace: velero
spec:
  backupName: b3
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  includedNamespaces:
  - '*'
  hooks:
    resources:
    - name: restore-hook-1
      includedNamespaces:
      - csi-app
      postHooks:
      - init:
          initContainers:
          - name: restore-hook-init1
            image: alpine:latest
            volumeMounts:
            - mountPath: /restores/pvc1-vm
              name: pvc1-vm
            command:
            - /bin/ash
            - -c
            - echo -n "FOOBARBAZ" >> /restores/pvc1-vm/foobarbaz
          - name: restore-hook-init2
            image: alpine:latest
            volumeMounts:
            - mountPath: /restores/pvc2-vm
              name: pvc2-vm
            command:
            - /bin/ash
            - -c
            - echo -n "DEADFEED" >> /restores/pvc2-vm/deadfeed
```

I can see how it would be useful to embed restore hooks in the backup spec. This can be something that we can discuss with the community. 

Marking this as answered..
