### DISCUSSION TITLE
Restic volumes not restored when remapping namespace

### DISCUSSION THREAD

**Discussion by thecodinglab** [vmware-tanzu/velero#3650] [Community support Q&A] [answered]
Hello, I am trying to restore a volume backed up using the restic integration into a different namespace. However the `restic-wait` init-container is stuck idenfinitely waiting for that restore to happen. Restoring into the same namespace is working perfectly fine.

As far as I understand the design documentation [pv-cloning.md](https://github.com/vmware-tanzu/velero/blob/e9c997839ebbb04688a88ffb981eeb74de51b380/design/Implemented/pv-cloning.md) and the [restic integration limitations](https://velero.io/docs/v1.5/restic/#limitations) cloning a volume into a different namespace should be possible right? 

During my investigation I found [this line](https://github.com/vmware-tanzu/velero/blob/e9c997839ebbb04688a88ffb981eeb74de51b380/pkg/restic/restorer.go#L100) which might be the culprit. To my understanding this creates the `ResticRepository` custom resource for the source namespace and not the target namespace specified through the namespace mapping.

## Steps to reproduce

1. Install velero in a new k8s cluster
```
$ velero install \
  --use-restic \
  --default-volumes-to-restic \
  --plugins velero/velero-plugin-for-aws:v1.2.0 \
  --secret-file ./aws-creds \
  --no-default-backup-location \
  --use-volume-snapshots=false

$ velero backup-location create default \
  --access-mode ReadWrite \
  --provider aws \
  --bucket app \
  --config region=default \
  --config s3ForcePathStyle=true \
  --config s3Url=https://aws-s3-compatible-storage-system
```

2. Deploy some application using a dynamically allocated PVC
```
$ kubectl create namespace app
$ kubectl -n app apply -f app.yaml
```

```yaml
# app.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
```

3. Copy a small file into the persistent volume to verify restore (optional)
```
$ kubectl -n app cp some-file task-pv-pod:/usr/share/nginx/html/some-file
```

4. Create a backup of the `app` namespace
```
$ velero backup create test --include-namespaces app --default-volumes-to-restic --wait
```

5. Restore the backup into a new namespace
```
$ velero restore create --from-backup test --namespace-mappings app:other
```
