### DISCUSSION TITLE
Velero Restore components that still exists

### DISCUSSION THREAD

**Discussion by ghost** [vmware-tanzu/velero#3690] [Community support Q&A]
Installed velero and using velero-plugin-for-aws

```
image:
  repository: velero/velero
  tag: v1.5.2
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.1.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
```

Is Velero strictly meant for disaster recovery? 

For instance say I have a statefulset running a database that I want to backup before I upgrade. Statefulset, PersistentVolumeClaims, and PersistentVolumes all succeed in the backup process.  After the upgrade I find the applications that integrated to the database fail (version changes, table changes, etc...). Therefore I want to restore to said backup. I attempt the restore, and it completes with warnings `could not restore, persistentvolumes .... already exists ...`.  Is there a way to force the restore where it will purposely override what's already running without having to manually delete those components?
