### DISCUSSION TITLE
velero mounting RWO PV in restic pods?

### DISCUSSION THREAD

**Discussion by Raboo** [vmware-tanzu/velero#3817] [Community support Q&A] [answered]
Hi

I installed velero with restic using the helm chart using following values

```yaml
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.2.0
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  provider: aws
  backupStorageLocation:
    name: default
    bucket: velero
    caCert:
    default: true
    config:
      region: minio
      s3ForcePathStyle: "true"
      s3Url: https://backup:9000
  logFormat: json
credentials:
  useSecret: true
  name: minio-auth
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=A
      aws_secret_access_key=B
backupsEnabled: true
snapshotsEnabled: false
deployRestic: true
restic:
  podVolumePath: /opt/rke/var/lib/kubelet/pods
  privileged: false
```

Now it has mounted all our Ceph RBD devices in the restic pod(s). These PV's are RWO, which means that the deployment/pods using those PV's can't start anymore, is this a feature, bug or by design?
Is there a way around this?

```text
$ kubectl exec -it restic-2lb2s -- bash
root@restic-2lb2s:/# mount|grep rbd
/dev/rbd2 on /host_pods/a7b6003e-4da5-4702-9124-b81c5c3c72b2/volumes/kubernetes.io~rbd/pvc-dbdcb865-c514-41df-8a67-5497bc41152c type ext4 (rw,relatime,stripe=1024,data=ordered)
/dev/rbd3 on /host_pods/d997360a-841f-433a-aa5d-3afbb2659618/volumes/kubernetes.io~rbd/pvc-4d8a223a-8a31-4845-b242-f6ab6525db70 type ext4 (rw,relatime,stripe=1024,data=ordered)
/dev/rbd0 on /host_pods/c4ce451c-a0c7-411a-b7ed-4e1646209766/volumes/kubernetes.io~rbd/pvc-b7d0a84d-23a4-45c8-a68e-cf318ae3798c type ext4 (rw,relatime,stripe=1024,data=ordered)
/dev/rbd1 on /host_pods/0982f6a0-8887-49c8-9726-4fa713d12519/volumes/kubernetes.io~rbd/pvc-d6b3b1fc-d3c3-4fa4-9fbc-6332fca3121f type ext4 (rw,relatime,stripe=1024,data=ordered)
```

Environment:

- Velero version: v1.6.0
- Kubernetes version: v1.20.6
- Kubernetes installer & version: Rancher Kubernetes Engine & Rancher v2.5.8
- Cloud provider or hardware configuration: on-prem
- OS: RancherOS
