### DISCUSSION TITLE
Velero doesn't delete associated CSI volumesnapshot and volumesnapshotcontents during backup deletion

### DISCUSSION THREAD

**Discussion by burakovsky** [vmware-tanzu/velero#3943] [Community support Q&A]
Hello, 

I use Velero for backup persistent volumes created by AWS EBS CSI driver. Velero creates EBS snapshots during backups, but doesn't delete it when backup is expired. Here is my configuration:

EKS - 1.18
Velero - 1.6.1 (also checked with 1.5.1 version)
velero-plugin-for-aws - 1.2.0 (1.1.0 for 1.5.1 version)
velero-plugin-for-csi - 0.1.2

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  labels:
    velero.io/csi-volumesnapshot-class: "true"
  name: csi-sc
deletionPolicy: Delete
driver: ebs.csi.aws.com
```

Example of created backup and associated volumesnapshot and volumesnapshotcontents:
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/source-cluster-k8s-gitversion: v1.18.9-eks-d1db3c
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: 18+
  labels:
    app.kubernetes.io/instance: cluster.production.velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.13.3
    velero.io/schedule-name: velero-daily-pv-snapshot
    velero.io/storage-location: default
  name: velero-daily-pv-snapshot-20210707000044
  namespace: velero
spec:
  defaultVolumesToRestic: false
  hooks: {}
  includedNamespaces:
  - '*'
  includedResources:
  - persistentvolumeclaims
  - persistentvolumes
  - volumesnapshots
  - volumesnapshotcontents
  storageLocation: default
  ttl: 168h0m0s
status:
  completionTimestamp: "2021-07-07T00:01:26Z"
  expiration: "2021-07-14T00:01:04Z"
  formatVersion: 1.1.0
  phase: Completed
  progress:
    itemsBackedUp: 279
    totalItems: 279
  startTimestamp: "2021-07-07T00:01:04Z"
  version: 1
  warnings: 1
```

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  finalizers:
  - snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
  - snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
  generateName: velero-test-backup-
  labels:
    velero.io/backup-name: velero-daily-pv-snapshot-20210707000044
  name: velero-test-backup-492cd
  namespace: production
spec:
  source:
    persistentVolumeClaimName: test-backup
  volumeSnapshotClassName: csi-sc
status:
  boundVolumeSnapshotContentName: snapcontent-cb7737c9-a794-4bd0-ac37-edf9cbf2dd5c
  creationTime: "2021-07-07T00:01:09Z"
  readyToUse: true
  restoreSize: 28Gi
```

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  finalizers:
  - snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection
  labels:
    velero.io/backup-name: velero-daily-pv-snapshot-20210707000044
  name: snapcontent-cb7737c9-a794-4bd0-ac37-edf9cbf2dd5c
spec:
  deletionPolicy: Delete
  driver: ebs.csi.aws.com
  source:
    volumeHandle: vol-0d1519bcd3c55b6a2
  volumeSnapshotClassName: csi-sc
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1beta1
    kind: VolumeSnapshot
    name: velero-test-backup-492cd
status:
  creationTime: 1625616069000000000
  readyToUse: true
  restoreSize: 30064771072
  snapshotHandle: snap-0f786f848485a49ac
```

During backup creation I see such warning message in Velero logs
```
DeletionPolicy on VolumeSnapshotClass csi-sc is not Retain; Deletion of VolumeSnapshot objects will lead to deletion of snapshot in the storage provider.
```
I guess it should delete related volumesnapshot and volumesnapshotcontent but it doesn't. 

If I deleted volumesnapshot manually, volumesnapshotcontent is also deleted (and related EBS snapshot in my AWS account).
