### DISCUSSION TITLE
PV cannot be restored if requested size is under 1GiB

### DISCUSSION THREAD

**Discussion by benjaminxie** [vmware-tanzu/velero#4095] [Community support Q&A] [answered]
**What steps did you take and what happened:**
I installed velero with \velero-plugin-for-microsoft-azure:v1.2.0 and velero-plugin-for-csi:v0.1.2.
I deployed the following resources to AKS:
```
apiVersion: storage.k8s.io/v1 
kind: StorageClass 
metadata: 
    name: disk.csi.azure.com 
provisioner: disk.csi.azure.com 
parameters: 
    skuname: StandardSSD_LRS 
reclaimPolicy: Delete 
volumeBindingMode: Immediate 
allowVolumeExpansion: true
---
apiVersion: snapshot.storage.k8s.io/v1beta1 
kind: VolumeSnapshotClass 
metadata: 
    name: csi-azuredisk-vsc
    labels:
        velero.io/csi-volumesnapshot-class: "true"
driver: disk.csi.azure.com 
deletionPolicy: Retain 
parameters:
    tags: 'foo=aaa,bar=bbb'
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-azuredisk
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
      name: nginx-azuredisk
      command:
        - "/bin/sh"
        - "-c"
        - while true; do echo $(date) >> /mnt/azuredisk/outfile; sleep 1; done
      volumeMounts:
        - name: azuredisk01
          mountPath: "/mnt/azuredisk"
  volumes:
    - name: azuredisk01
      persistentVolumeClaim:
        claimName: pvc-azuredisk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-csi
```
If I backup my pvc and pv using `velero create backup --include-resources pvc,pv onegibi`, delete the pod and pvc, redeploy the pod, and restore the pvc and pv using `velero create restore --from-backup onegibi`, then, as expected, my pvc and pv will be restored with all the data that was previously there.

However, if my pvc requests less than 1Gi of storage, say 0.5Gi, then when I go through the same process of backing up and restoring, the pvc will be stuck in Pending status. For some reason the snapshot size will be 1Gi which is too large for the 0.5Gi volume.

Here is the result of `$kubectl describe pvc pvc-azuredisk`
```
Name:          pvc-azuredisk
Namespace:     default
StorageClass:  managed-csi
Status:        Pending
Volume:        
Labels:        velero.io/backup-name=halfgibi
               velero.io/restore-name=halfgibi-20210901163225
               velero.io/volume-snapshot-name=velero-pvc-azuredisk-f2nh6
Annotations:   velero.io/backup-name: halfgibi
               velero.io/volume-snapshot-name: velero-pvc-azuredisk-f2nh6
               volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
               volume.kubernetes.io/selected-node: aks-nodepool1-35937786-vmss000000
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
DataSource:
  APIGroup:  snapshot.storage.k8s.io
  Kind:      VolumeSnapshot
  Name:      velero-pvc-azuredisk-f2nh6
Mounted By:  nginx-azuredisk
Events:
  Type     Reason                Age               From                                                                                               Message
  ----     ------                ----              ----                                                                                               -------
  Normal   WaitForPodScheduled   16s               persistentvolume-controller                                                                        waiting for pod nginx-azuredisk to be scheduled
  Normal   ExternalProvisioning  3s (x2 over 16s)  persistentvolume-controller                                                                        waiting for a volume to be created, either by external provisioner "disk.csi.azure.com" or manually created by system administrator
  Normal   Provisioning          3s (x5 over 16s)  disk.csi.azure.com_csi-azuredisk-controller-5f5fd47d9c-94rz8_a82f8335-4c4f-4832-ba7a-f55fc654ef21  External provisioner is provisioning volume for claim "default/pvc-azuredisk"
  Warning  ProvisioningFailed    3s (x5 over 16s)  disk.csi.azure.com_csi-azuredisk-controller-5f5fd47d9c-94rz8_a82f8335-4c4f-4832-ba7a-f55fc654ef21  failed to provision volume with StorageClass "managed-csi": error getting handle for DataSource Type VolumeSnapshot by Name velero-pvc-azuredisk-f2nh6: requested volume size 536870912 is less than the size 1073741824 for the source snapshot velero-pvc-azuredisk-f2nh6

```
**What did you expect to happen:**
The pvc and pv would be restored.
**Environment:**
- Velero Version
Client:
  Version: v1.6.3
  Git commit: 5fe3a50bfddc2becb4c0bd5e2d3d4053a23e95d2
Server:
  Version: v1.6.3 
- Kubernetes Version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-16T01:10:02Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Azure Kubernetes
