### DISCUSSION TITLE
Is there is a suitable way to config velero request resource for a cluster that continues to grow

### DISCUSSION THREAD

**Discussion by chrislinan** [vmware-tanzu/velero#4312] [Community support Q&A]
when we deploy velero to our cluster, we need to set up the resources, for exmaple:
```
resources:
    limits:
      cpu:1
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
```
But, if my cluster continues growing up, velero will use more and more memory resource to proceed backup. Finally, the velero pod will got 'oomkilled'. 
I tried to use VPA for velero pod, it also kills velero pod frequently, every time the vpa gives a recommendation the velero pod restarts, and backup crash.
I want to know, is there a suitable way to satisfy this scenario?
