### DISCUSSION TITLE
Select pod by custom label

### DISCUSSION THREAD

**Discussion by tonsV2** [vmware-tanzu/velero#4314] [Community support Q&A] [answered]
I have the following pod

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2021-11-03T15:13:24Z"
  generateName: something2-database-postgresql-
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: something2-database
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    controller-revision-hash: something2-database-postgresql-86c7d55b95
    dhis2-postgresql-id: "11"
    helm.sh/chart: postgresql-10.9.2
    role: primary
    statefulset.kubernetes.io/pod-name: something2-database-postgresql-0
  name: something2-database-postgresql-0
  namespace: whoami
...
```

I can create a backup by executing the below command.

`velero backup create backup-name-1 --include-resources pvc,pv --selector app.kubernetes.io/instance=something2-database --include-namespaces whoami`

And by describing the backup I can see that it includes two resource, the pvc and pv, in the backup.

However if I try to create a backup using the below command. It does not work, neither the pvc or the pv is included in the backup.

`velero backup create backup-name-2 --include-resources pvc,pv --selector dhis2-postgresql-id=11 --include-namespaces whoami`

I tried quoting the id. Eg. "11" but that doesn't make a difference. Any clue about what I'm doing wrong?
