### DISCUSSION TITLE
Velero Snapshots on Different Azure Resource Groups than Azure Disks

### DISCUSSION THREAD

**Discussion by dmakeroam** [vmware-tanzu/velero#4399] [Community support Q&A]
I have a question if Velero supporting backup Azure disks and store snapshots in different resource group. Like if we have Azure disks in resource group A, Can we use Velero to create snapshots of them and store in resource group B ?. 

If so, Please share us the instructions to have this done. 

Thank you in advance!

**Comment by Matusalterway** [comment]
Hello, 
  you  can declare a few SnapshotLocation with the specific ressourcegroup then you can set the associated schedule.


apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: velero.io/azure

  config:
    apiTimeout: 5m
    # The name of the resource group where volume snapshots should be stored, if different
    # from the cluster's resource group.
    #
    # Optional.
    resourceGroup: RG1
    subscriptionId: XXXXX
    # Azure offers the option to take full or incremental snapshots of managed disks.
    # - Set this parameter to true, to take incremental snapshots.
    # - If the parameter is omitted or set to false, full snapshots are taken (default).
    #
    # Optional.
    incremental: "true"

and 

apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: secondary
  namespace: velero
spec:
  provider: velero.io/azure

  config:
    apiTimeout: 5m
    # The name of the resource group where volume snapshots should be stored, if different
    # from the cluster's resource group.
    #
    # Optional.
    resourceGroup: RG2
    subscriptionId: XXXXX
    # Azure offers the option to take full or incremental snapshots of managed disks.
    # - Set this parameter to true, to take incremental snapshots.
    # - If the parameter is omitted or set to false, full snapshots are taken (default).
    #
    # Optional.
    incremental: "true"

**Reply by dmakeroam** [reply]
Hi @Matusalterway 

I configured the snapshot location as your suggestion as follows:

```yaml
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  generation: 3
  labels:
    component: velero
  name: kafka
  namespace: velero
spec:
  config:
    apiTimeout: 5m
    resourceGroup: [my-resource-group]
    subscriptionId: [my-subscription-id]
  provider: azure
```

And ran the command to backup my workload (kafka): 

```sh
$ velero schedule create [my-schedule-name] --include-namespaces "kafka-dev" --storage-location kafka-location --schedule "00 19 * * *" --volume-snapshot-locations kafka --ttl 168h0m0s
```

Once the backup was done, I went to the snapshot location resource group and I didn't find any volume snapshots in it

Do you have any idea for this?
