### DISCUSSION TITLE
Snapshot PVs from single namespace

### DISCUSSION THREAD

**Discussion by caruccio** [vmware-tanzu/velero#4474] [Community support Q&A]
Despite the fact that PVs are cluster-wide objects, is there any way to snapshot only a portion of PVs, i.e. any one bound to PVCs from an specific namespace?

**Comment by aglees** [comment]
I'd be very interested in finding out how this can be achieved. Having all PVs for a cluster snapshot isn't practical or desirable.

**Reply by caruccio** [reply]
I believe it could filter for matching `pv.status.phase==Bound` and `pv.spec.claimRef.namespace==$desiredNamespace`.

```
apiVersion: v1
kind: PersistentVolume
...
spec:
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: prometheus-monitoring-kube-prometheus-prometheus-db-prometheus-monitoring-kube-prometheus-prometheus-0
    namespace: monitoring
...
status:
  phase: Bound
```
