### DISCUSSION TITLE
Velero backup cost a long time

### DISCUSSION THREAD

**Discussion by chrislinan** [vmware-tanzu/velero#5069] [Community support Q&A]
Hi community,
When I backup my cluster, I found that velero costs a lot of time, for example, the following backup starts at 20:56:59 and ends at 21:52:01. Is that normal?
```
status:
  completionTimestamp: '2022-07-01T21:52:01Z'
  expiration: '2022-07-03T20:56:59Z'
  formatVersion: 1.1.0
  phase: Completed
  progress:
    itemsBackedUp: 58976
    totalItems: 58976
  startTimestamp: '2022-07-01T20:56:59Z'
  version: 1
```
In addition, many newly(10 hours ago) created backups even doesn't have status, it just shows:
```
status: {}
```
Can you help? Thanks a lot.
