### DISCUSSION TITLE
Create  backup from CI/CD pipeline, rbac issue.

### DISCUSSION THREAD

**Discussion by mikkeschiren** [vmware-tanzu/velero#5121] [Community support Q&A] [answered]
So I am trying to figure out how to set permissions for gitlab runner to create backups.

I have added:

```
- apiGroups:
  - velero.io
  resources:
  - '*'
  verbs:
  - '*'

```

To my gitlab runner clusterrole, but I am getting:
```
An error occurred: backups.velero.io is forbidden: User "system:serviceaccount:gitlab-runner:default" cannot create resource "backups" in API group "velero.io" in the namespace "velero"
```
