### DISCUSSION TITLE
backup-sync - error getting object backups/xxx/velero-backup.json: NoSuchKey: The specified key does not exist.

### DISCUSSION THREAD

**Discussion by Raboo** [vmware-tanzu/velero#5541] [Community support Q&A]
Hi

My velero pod keeps getting spammed with this messages.

```json
{
  "backup": "cluster-wide-20220928194652",
  "backupLocation": "default",
  "controller": "backup-sync",
  "level": "info",
  "logSource": "pkg/controller/backup_sync_controller.go:219",
  "msg": "Attempting to sync backup into cluster",
  "time": "2022-11-02T14:04:52Z"
}
{
  "backup": "cluster-wide-20220928194652",
  "backupLocation": "default",
  "controller": "backup-sync",
  "error.file": "/go/src/github.com/vmware-tanzu/velero/pkg/persistence/object_store.go:294",
  "error.function": "github.com/vmware-tanzu/velero/pkg/persistence.(*objectBackupStore).GetBackupMetadata",
  "error.message": "rpc error: code = Unknown desc = error getting object backups/cluster-wide-20220928194652/velero-backup.json: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: 1723C98CA4F8D968, host id: ",
  "level": "error",
  "logSource": "pkg/controller/backup_sync_controller.go:223",
  "msg": "Error getting backup metadata from backup store",
  "time": "2022-11-02T14:04:52Z"
}
```

I'm running velero v1.9.2 installed via Helm.
My helm values look something like this

```yaml
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.5.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  provider: aws
  backupStorageLocation:
    name: default
    bucket: velero
    default: true
    config:
      region: minio
      s3ForcePathStyle: "true"
      s3Url: https://backup.service.domain.com:9000
  volumeSnapshotLocation:
    name: default
    config:
      region: minio
  backupSyncPeriod: 1m
  resticTimeout: 1h
  clientQPS: "20.0"
  clientBurst: "30"
  logFormat: json

credentials:
  useSecret: true
  name: minio-auth
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=xxx
      aws_secret_access_key=xxx

backupsEnabled: true
snapshotsEnabled: false

deployRestic: true
restic:
  podVolumePath: /var/lib/kubelet/pods # /opt/rke/var/lib/kubelet/pods on flatcar
  privileged: false
```

I also have a cluster wide backup defined like this

```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: cluster-wide
  namespace: velero
spec:
  schedule: '@every 6h'
  template:
    hooks: {}
    includedNamespaces:
    - '*'
    ttl: 720h0m0s # 30 days
    excludedResources:
    - events
    - events.k8s.io
  useOwnerReferencesInBackup: false
```

The backups are failing. But there there are no errors in the log (`velero backup logs cluster-wide-20221102074854`).

velero describe backup cluster-wide-20221102074854:
```
Name:         cluster-wide-20221102074854
Namespace:    velero
Labels:       velero.io/schedule-name=cluster-wide
              velero.io/storage-location=default
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"velero.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"cluster-wide","namespace":"velero"},"spec":{"schedule":"@every 6h","template":{"hooks":{},"includedNamespaces":["*"],"ttl":"720h0m0s"},"useOwnerReferencesInBackup":false},"status":{}}

  velero.io/source-cluster-k8s-gitversion=v1.22.9
  velero.io/source-cluster-k8s-major-version=1
  velero.io/source-cluster-k8s-minor-version=22

Phase:  Failed (run `velero backup logs cluster-wide-20221102074854` for more information)

Errors:    0
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2022-11-02 08:48:54 +0100 CET
Completed:  2022-11-02 08:50:26 +0100 CET

Expiration:  2022-12-02 08:48:54 +0100 CET

Total items to be backed up:  6163
Items backed up:              6163

Velero-Native Snapshots: <none included>

Restic Backups (specify --details for more information):
  Completed:  2
```

kubectl -n velero  get backup cluster-wide-20221103074855 -o yaml | yq e ".status"

```yaml
completionTimestamp: "2022-11-03T07:50:27Z"
expiration: "2022-12-03T07:48:55Z"
failureReason: 'rpc error: code = Unknown desc = EOF'
formatVersion: 1.1.0
phase: Failed
progress:
  itemsBackedUp: 6184
  totalItems: 6184
startTimestamp: "2022-11-03T07:48:55Z"
version: 1
```

What am I doing wrong? What is my next step to find out what is wrong?
