### DISCUSSION TITLE
why do we not need to specify bucket of VolumeSnapshotLocation?

### DISCUSSION THREAD

**Discussion by 13567436138** [vmware-tanzu/velero#5749] [Community support Q&A]
```
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: aws-default
  namespace: velero
spec:
  provider: velero.io/aws
  credential:
    key: cred
    name: credentials-velero
  config:
    region: minio
    profile: "default"
```
