### DISCUSSION TITLE
How to use backup_name generated from schedule backup in pre hook exec commands

### DISCUSSION THREAD

**Discussion by adsri** [vmware-tanzu/velero#5868] [Community support Q&A]
Hi team, I am trying to use schedule backup to generate pg_dump of postgres. but the file is getting overriten on each schedule backup because it is using same name. 

How can i pass schedule backup name to the prehook exec command such that each schedule backup generates a unique backup pg_dump file

```
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: test-data-schedule
  namespace: velero
spec:
  schedule: "*/1 * * * *"
  template:
    includedNamespaces:
    - '*'
    csiSnapshotTimeout: 10m0s
    defaultVolumesToRestic: false
    hooks:
      resources:
      - name: postgres-backup-hook
        includedNamespaces:
        - db
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: postgresql
        - exec:
            container: postgresql
            timeout: 6m
            command:
            - /bin/bash
            - '-c'
            - "PGPASSWORD=$POSTGRES_PASSWORD pg_dump -w -U postgres -d postgres -h db-pgpool.db.svc.cluster.local -p 5432 > /backuplocation/test-data-schedule.sql"

```
