### DISCUSSION TITLE
where is backup metadata gone？

### DISCUSSION THREAD

**Discussion by 13567436138** [vmware-tanzu/velero#6044] [Community support Q&A]
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  labels:
    velero.io/storage-location: minio
  name: nginx-backup
  namespace: velero
spec:
  csiSnapshotTimeout: 10m0s
  metadata:
    labels:
      test: test1
  includedNamespaces:
  - '*'
  labelSelector:
    matchLabels:
      app: nginx
  storageLocation: minio
  volumeSnapshotLocations:
  - minio

```
test: test1 for where?
