### DISCUSSION TITLE
velero CLI node agent securityContext

### DISCUSSION THREAD

**Discussion by aDingil** [vmware-tanzu/velero#6353] [Community support Q&A]
Hey,

thx for your awesome project and hard work.

I´ve to set the securityContext inside the node-agent daemonset, so that backups are working correctly.
Here my customization:

```yaml
spec:
  template:
    spec:
      containers:
      - name: node-agent
        securityContext:
          privileged: true
```

Is it possible to set the securityContext via installation with the cli?
Here my install string:
`velero install --provider gcp --plugins velero/velero-plugin-for-gcp --bucket {BUCKET} --secret-file {SECRET} --use-node-agent --default-volumes-to-fs-backup`

Regards
