### DISCUSSION TITLE
Resource filtering: exclude all volumes of a storageclass

### DISCUSSION THREAD

**Discussion by r10r** [vmware-tanzu/velero#6379] [Community support Q&A] [answered]
Hi,

I've a storage class **local-ssd-cache**.
Restic should not backup any volume with this storage.
How can I achive this with resource filtering (using `–exclude-resources` ?)

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app.kubernetes.io/instance: local-volume-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: provisioner
    helm.sh/chart: provisioner-2.6.0-alpha.1
  name: local-ssd-cache
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

**Comment by sseago** [comment, marked as answer]
`--exclude-resources` does not support this use case, since that's based on resource type -- i.e. to exclude all PVCs. However, you should be able to use th enew 1.11 resource policy filter to accomplish this:
https://velero.io/docs/v1.11/resource-filtering/#resource-policies

**Comment by r10r** [comment]
@sseago Thanks! The following simple policy worked as expected:

```yaml
version: v1
volumePolicies:
- conditions:
    storageClass:
    - local-ssd-cache
  action:
    type: skip
```
