### DISCUSSION TITLE
AKS backup and restore using restic for File shres and CSI for disks via Velero

### DISCUSSION THREAD

**Discussion by MrGeorgo404** [vmware-tanzu/velero#6657] [Community support Q&A] [answered]
Hello

currently, I am in a situation where I would like to use Velero to backup and restore the backup to another AKS cluster however, I would like to use restic to backup Azure File Shares and CSI to backup Azure Disks. I have not found in Velero documentation whether this is possible or not. Is it in fact possible or not? 

In fact backup goes through well, the disk has a snapshot in rg however, when I perform a restore in another AKS cluster only the File share volume type goes through and and PV for disk is not created and PVC for disk is stuck in pending with following error: (does not have permission to perform action 'Microsoft.Compute/disks/beginGetAccess/action' on the linked scope)
[![enter image description here][1]][1] 

Do you have any idea what should be done? To whom am I supposed to assign rights because I could not find this object ID in AAD (it is neither me or velero)

For Velero installation on both clusters I used command specifying CSI and restic as well: 
```
velero install --provider azure --plugins velero/velero-plugin-for-microsoft-azure:v1.7.0,velero/velero-plugin-for-csi:v0.5.0 --bucket 'velero' --secret-file <name-of-yaml-document>.yaml --backup-location-config resourceGroup='<name-of-velero-rg>',storageAccount='<name-of-velero-storage-account>',subscriptionId='<subscription-id-where-velero-rg-resides>'  --snapshot-location-config apiTimeout=5m,resourceGroup='<name-of-velero-rg>',subscriptionId='<subscription-id-where-velero-rg-resides>' --image velero/velero:v1.11.1 --uploader-type restic --use-node-agent --features=EnableCSI
```

And also I installed volumesnapshotclass for Azure disk on original AKS cluster:
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-azuredisk-vsc
  annotations:
    # Optional annotation to set this VolumeSnapshotClass as default
    snapshot.storage.kubernetes.io/is-default-class: "true"
  labels:
    # Required label for Velero
    velero.io/csi-volumesnapshot-class: "true"
driver: disk.csi.azure.com
deletionPolicy: Delete
parameters:

```
And lastly, I also performed annotation of pods in which File share type volumes are mounted in following fashion: (documenation https://velero.io/docs/v1.9/restic/)
```
kubectl -n YOUR_POD_NAMESPACE annotate pod/YOUR_POD_NAME backup.velero.io/backup-volumes=YOUR_VOLUME_NAME_1,YOUR_VOLUME_NAME_2,...
```

I do have storage account for velero backups with rg, service principal for velero and CSI drivers in AKS cluster as well: 
```
NAME                 ATTACHREQUIRED   PODINFOONMOUNT   STORAGECAPACITY   TOKENREQUESTS   REQUIRESREPUBLISH   MODES                  AGE
disk.csi.azure.com   true             false            false             <unset>         false               Persistent             61m
file.csi.azure.com   false            true             false             <unset>         false               Persistent,Ephemeral   61m
```

  [1]: https://i.stack.imgur.com/YKGjv.png
