### DISCUSSION TITLE
Restore example with PV doesn't work

### DISCUSSION THREAD

**Discussion by jackchuong** [vmware-tanzu/velero#6908] [Community support Q&A]
Hi all,
I have an internal K8S build by K3S
I have QNAP NAS device as NFS server and using [csi-driver-nfs](https://github.com/kubernetes-csi/csi-driver-nfs) for storage provider (support volume snapshot)
```
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-csi-nfs-sgnnas03
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: "192.168.7.107"
  share: /k8s-nfs-sgnnas03
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-nfs-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: nfs.csi.k8s.io
deletionPolicy: Delete

kubectl get sc,VolumeSnapshotClass
NAME                                                                  PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
storageclass.storage.k8s.io/storageclass-csi-nfs-sgnnas03 (default)   nfs.csi.k8s.io             Retain          Immediate           true                   7d2h

NAME                                                            DRIVER           DELETIONPOLICY   AGE
volumesnapshotclass.snapshot.storage.k8s.io/csi-nfs-snapclass   nfs.csi.k8s.io   Delete           7d2h
```

I installed Velero server by Helm 3 , here my values
```
image:
  repository: velero/velero
  tag: v1.12.0
initContainers:
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v0.5.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.8.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  backupStorageLocation:
  - name:
    provider: aws
    bucket: backup
    prefix: velero
    config:
      region: "ap-southeast-1"
  volumeSnapshotLocation:
  - name:
    provider: aws
    config:
      region: "ap-southeast-1"
  features: EnableAPIGroupVersions,EnableCSI
credentials:
  useSecret: true
  name:
  existingSecret: velero
deployNodeAgent: true
nodeAgent:
  podVolumePath: /var/lib/kubelet/pods
  privileged: true

helm -n velero list
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
velero  velero          4               2023-10-03 15:57:03.107909122 +0700 +07 deployed        velero-5.0.2    1.11.1

velero backup-location get
NAME      PROVIDER   BUCKET/PREFIX             PHASE       LAST VALIDATED                  ACCESS MODE   DEFAULT
default   aws        backup-logtechub/velero   Available   2023-10-03 12:31:03 +0700 +07   ReadWrite     true

velero snapshot-location get
NAME      PROVIDER
default   aws
```

I created namespace `nginx-example` and apply this with-pv.yaml
```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-logs
  namespace: nginx-example
  labels:
    app: nginx
spec:
  storageClassName: storageclass-csi-nfs-sgnnas03
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-logs
          persistentVolumeClaim:
           claimName: nginx-logs
      containers:
      - image: nginx:1.17.6
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false
      - image: ubuntu:bionic
        name: fsfreeze
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false
        command:
          - "/bin/bash"
          - "-c"
          - "sleep infinity"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-nginx
  namespace: nginx-example
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
```

I created backup successfully , I can see backup files in S3 bucket backup/velero
```
velero backup create nginx-backup --include-namespaces nginx-example --snapshot-move-data
Backup request "nginx-backup" submitted successfully.
velero backup get
NAME                           STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
nginx-backup                   Completed   0        0          2023-10-03 11:17:40 +0700 +07   29d       default            <none>

kubectl get volumesnapshot,volumesnapshotcontent

NAME                                                                                             READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER           VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT                              VOLUMESNAPSHOTNAMESPACE                   AGE
volumesnapshotcontent.snapshot.storage.k8s.io/snapcontent-a741765d-b875-4791-959d-921f98de92a1   true         0             Retain           nfs.csi.k8s.io   csi-nfs-snapclass     name-0b2e05a0-dae1-4f1c-a07e-4905686c511c   ns-0b2e05a0-dae1-4f1c-a07e-4905686c511c   2m3s
```

I deleted with-pv.yaml
```
kubectl delete -f with-pv.yaml
persistentvolumeclaim "nginx-logs" deleted
deployment.apps "nginx-deployment" deleted
service "my-nginx" deleted

kubectl get pv
NAME                                                                           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                                                          STORAGECLASS                    REASON   AGE
persistentvolume/pvc-4e817c40-be2f-4819-b37d-8b2b55e6d524                      50Mi       RWO            Retain           Released   nginx-example/nginx-logs                                                       storageclass-csi-nfs-sgnnas03            10m
```

I delete PV and volumesnapshotcontent of nginx example , I also delete folder pvc-4e817c40-be2f-4819-b37d-8b2b55e6d524 from NFS server.
```
kubectl -n nginx-example delete persistentvolume/pvc-4e817c40-be2f-4819-b37d-8b2b55e6d524 volumesnapshotcontent.snapshot.storage.k8s.io/snapcontent-a741765d-b875-4791-959d-921f98de92a1
Warning: deleting cluster-scoped resources, not scoped to the provided namespace
persistentvolume "pvc-4e817c40-be2f-4819-b37d-8b2b55e6d524" deleted
volumesnapshotcontent.snapshot.storage.k8s.io "snapcontent-a741765d-b875-4791-959d-921f98de92a1" deleted
```

I create restore
```
velero restore create --from-backup nginx-backup
Restore request "nginx-backup-20231003112354" submitted successfully.
Run `velero restore describe nginx-backup-20231003112354` or `velero restore logs nginx-backup-20231003112354` for more details

velero restore get
NAME                          BACKUP         STATUS      STARTED                         COMPLETED                       ERRORS   WARNINGS   CREATED                         SELECTOR
nginx-backup-20231003112354   nginx-backup   Completed   2023-10-03 11:23:54 +0700 +07   2023-10-03 11:23:58 +0700 +07   0        0          2023-10-03 11:23:54 +0700 +07   <none>
```

But it doesn't work
```
kubectl -n nginx-example get pod,pvc,pv,volumesnapshot,volumesnapshotcontent
NAME                                    READY   STATUS              RESTARTS   AGE
pod/nginx-deployment-78964c9995-8g7zw   0/2     ContainerCreating   0          2m10s

NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                    AGE
persistentvolumeclaim/nginx-logs   Bound    pvc-4e817c40-be2f-4819-b37d-8b2b55e6d524   50Mi       RWO            storageclass-csi-nfs-sgnnas03   2m10s

NAME                                                                           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                                          STORAGECLASS                    REASON   AGE
persistentvolume/pvc-4e817c40-be2f-4819-b37d-8b2b55e6d524                      50Mi       RWO            Retain           Bound    nginx-example/nginx-logs                                                       storageclass-csi-nfs-sgnnas03            2m10s

NAME                                                             READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT                  RESTORESIZE   SNAPSHOTCLASS       SNAPSHOTCONTENT                        CREATIONTIME   AGE
volumesnapshot.snapshot.storage.k8s.io/velero-nginx-logs-9vgdd   true                     velero-velero-nginx-logs-9vgdd-ctvl9   0             csi-nfs-snapclass   velero-velero-nginx-logs-9vgdd-ctvl9   2m10s          2m10s

NAME                                                                                             READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER           VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT                              VOLUMESNAPSHOTNAMESPACE                   AGE
volumesnapshotcontent.snapshot.storage.k8s.io/velero-velero-nginx-logs-9vgdd-ctvl9               true         0             Retain           nfs.csi.k8s.io   csi-nfs-snapclass     velero-nginx-logs-9vgdd                     nginx-example                             2m10s
volumesnapshotcontent.snapshot.storage.k8s.io/snapcontent-a741765d-b875-4791-959d-921f98de92a1   false                      Delete           nfs.csi.k8s.io   csi-nfs-snapclass     velero-nginx-logs-9vgdd                     nginx-example                             2m10s

kubectl -n nginx-example describe pod/nginx-deployment-78964c9995-8g7zw
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    24m                   default-scheduler  Successfully assigned nginx-example/nginx-deployment-78964c9995-8g7zw to k3s-hq-master1
  Warning  FailedMount  2m25s (x10 over 22m)  kubelet            Unable to attach or mount volumes: unmounted volumes=[nginx-logs], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition
  Warning  FailedMount  2m23s (x19 over 24m)  kubelet            MountVolume.SetUp failed for volume "pvc-4e817c40-be2f-4819-b37d-8b2b55e6d524" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs -o hard,nfsvers=4.1 192.168.7.107:/k8s-nfs-sgnnas03/pvc-4e817c40-be2f-4819-b37d-8b2b55e6d524 /var/lib/kubelet/pods/778d3b21-b06b-41c1-936d-e4deeec9f6fa/volumes/kubernetes.io~csi/pvc-4e817c40-be2f-4819-b37d-8b2b55e6d524/mount
Output: mount.nfs: mounting 192.168.7.107:/k8s-nfs-sgnnas03/pvc-4e817c40-be2f-4819-b37d-8b2b55e6d524 failed, reason given by server: No such file or directory
```

Please give me some advices, thank you very much.
