### DISCUSSION TITLE
How to correctly use full and incremental backup of '/velero backup create'?

### DISCUSSION THREAD

**Discussion by lizhifengones** [vmware-tanzu/velero#6987] [Community support Q&A]
**env**: minio + openebs(+ nfs) + velero(v.12) + openes.io/velero-plugin

**My data scenario**: It cannot be deleted or tampered with, so there will be more and more data.

**What I am doing**: Back up openebs rwo pvc, including --snapshots-volumes

1. I hope that when using `/velero backup create`, I can selectively perform full and incremental backup of volume snapshot. Is it completely controlled by the plug-in? I see we provide incremental parameters for `velero-plugin-for-microsoft-azure`;
2. If the incremental backup is controlled by a plug-in, how is the incremental backup capability of shedule backup implemented? (I realized from many comments that schedule is an incremental backup!)
3. If I execute /velero backup create (new full backup) with `<the same prefix name>-<timestamp>`, which backup will the next schedule backup be incrementally based on?

**Comment by draghuram** [comment]
Hi, Can you clarify what type of Velero backup are you doing? Are they snapshots, file system backups, or in case of 1.12, snapshot data mover backups?

**Reply by lizhifengones** [reply]
I am using csi snapshot of velero-plugin

**Comment by sseago** [comment]
Note that a velero backup includes kubernetes resources as well as volume data. Kubernetes metadata is never incremental -- that's always full. So regarding incremental backups, that will only apply to volume data. Whether a volume backup is incremental, is a function of the plugin used (if a native snapshot -- i.e. velero-plugin-for-aws, etc.), the CSI driver (if using csi plugin), or the fs backup method (currently we support kopia and restic, and both should generate incremental backups).

This is based on the volume being backed up, not the backup name, etc. It doesn't matter what the backup name is or whether the backup is created by schedule. Backup schedules function much like cron job -- their main purpose is to  create backups at certain times. Once created, the schedule is not really relevant to the backup anymore.

**Reply by lizhifengones** [reply]
One very important question: this is based on the volume being backed up, not the backup name etc.
So when my pv name always remains the same and the plugin uses snapshots, is it always incremental backup and unable to do a full backup again?

If I use schedule for backup, and I have no way to re-trigger the full backup by deleting the shedule and generating a new_name_schedule, when the first backup of the schedule expires, does it mean that I can no longer recover the data? My second new_name_schedule is also meaningless?

More relevant here is about the redundancy of complete backup data.

**Comment by lizhifengones** [comment]
```sh
114M    20231031175950 # velero backup create
114M    20231031180708 # velero backup create
114M    inc-backup-2-20231031102014 # schedule 2
140K    inc-backup-2-20231031103416 # schedule 2
140K    inc-backup-2-20231031103514 # schedule 2
114M    inc-backup-20231031101021 # schedule 1
140K    inc-backup-20231031103426 # schedule 1
140K    inc-backup-20231031103514 # schedule 1
```
I’m not sure if I misunderstood it. It seems that full backup + additional backup can be implemented from scratch based on different schedule names. This is the function I want. Thank you for your replies.

**Comment by Praveen-98cs** [comment]
I am using velero in azure cloud to back up the persistent enabled redis cluster. I am trying to use the CSI snapshot method as cloud provided snapshot method cannot be performed since the persistent volumes that were created are in anothere resource group which i dont have the permission. 

I am using the velero helm chart and i want to know to enable the incremental backup have I implemented it correctly and how can i check if the incremental backup thing is happening. thanks in advance.

my values.yaml 

```
velero:
    image:
      repository: velero/velero
      tag: v1.15.2
      pullPolicy: Always
  
    upgradeCRDs: true
  
    cleanUpCRDs: true
  
    configuration:
      backupStorageLocation:
      - name: default
        provider: azure
        bucket: velero
        accessMode: ReadWrite
        config: 
          resourceGroup: choreo-dev-database-rg  # Your azure resource group name
          storageAccount: choreovelerobackup   # Your azure  storage account name
          subscriptionId: <sub_id> 
        annotations: {}

      volumeSnapshotLocation:
      - name: default
        provider: velero.io/azure
        credential:
          name: velero-credentials
          key: cloud
        config:
          incremental: "true"
          resourceGroup: "choreo-dev-database-rg" 
  
      defaultSnapshotMoveData:
      features: EnableCSI
      defaultVolumesToFsBackup: false
  
    rbac:
      create: true
      clusterAdministrator: true
      clusterAdministratorName: cluster-admin
  
    backupsEnabled: true
    snapshotsEnabled: true
  
    deployNodeAgent: false
  
    schedules: 
      redis-backup:
          schedule: "*/30 * * * *"   # every 30 minutes
          template:
            ttl: "48h"
            includedNamespaces:
              - redis
            snapshotVolumes: true
            storageLocation: default
  
```
