### DISCUSSION TITLE
How to use like opt-in approach for CSI Snapshot Data Movement?

### DISCUSSION THREAD

**Discussion by Abbas-b-b** [vmware-tanzu/velero#7196] [Community support Q&A]
How to create a backup (or schedule) to include all resources (namespace and clustered) and disable Snapshot Data Movement (default behavior) for all PVCs and include some PVCs in some specific namespaces to be backed up using Snapshot Data Movement approach like the opt-in method used for File System Backup?

**Comment by shubham-pampattiwar** [comment]
Currently the opt-in label based approach is only supported for File system Backups.

**Comment by navilg** [comment]
So currently we do not have anyway to exclude specific PVC and data inside it for csi snapshot way of backup with data movement ?

**Reply by Abbas-b-b** [reply]
I couldn't find any workaround so I separated the backups and schedules.

**Comment by andreyolv** [comment]
I guess it's possible to create a backup or schedule for general backups with data movement disabled, and create another backup or schedule only for specific resources that require data movement.

I've thought about this, but haven't tested it. A project maintainer can confirm whether my idea makes sense and, if they think it's appropriate, add this hypothesis, which isn't currently clear, to the documentation.


```
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: yyyyyy
  namespace: velero
spec:
  includedNamespaces:
  - '*'
  includedResources:
  - '*'
  storageLocation: xxxxx
  volumeSnapshotLocations: 
  - xxxxx
  ttl: 24h0m0s
  snapshotMoveData: false
```

```
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: yyyyyy2
  namespace: velero
spec:
  includedNamespaces:
  - 'specific'
  includedResources:
  - persistentvolumeclaims
  - persistentvolumes
  labelSelector:
    matchLabels:
      velero-data-movement: true
  storageLocation: xxxxx
  volumeSnapshotLocations: 
  - xxxxx
  ttl: 24h0m0s
  snapshotMoveData: true
```
