### DISCUSSION TITLE
volumepolicy to ignore "local-path", but still getting warnings about hostPath volume

### DISCUSSION THREAD

**Discussion by strowi** [vmware-tanzu/velero#7440] [Community support Q&A]
Hi,

i am trying to ignore rancher's local-path storageClass, but am still getting warnings in `velero backup describe`:

```yaml
---
# storageClass "local-path"
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: local-path
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
# k get configmap volumepolicy
apiVersion: v1
data:
  velero-policy.yml: |
    version: v1
    volumePolicies:
    - conditions:
        volumeTypes:
          - emptyDir
      action:
        type: skip
    - conditions:
        storageClass:
        - local-path
      action:
        type: skip
kind: ConfigMap
```

```bash
~> velero backup create --resource-policies-configmap volumepolicy --default-volumes-to-fs-backup --include-namespaces harbor,sonarqube backup-test8`

~> velero backup describe backup-test8
...
Warnings:
  Velero:     <none>
  Cluster:    <none>
  Namespaces:
    sonarqube:   resource: /pods name: /sonarqube-694b5fb984-4k28v message: /Volume sonarqube in pod sonarqube/sonarqube-694b5fb984-4k28v is a hostPath volume which is not supported for pod volume backup, skipping
                 resource: /pods name: /sonarqube-postgresql-0 message: /Volume data in pod sonarqube/sonarqube-postgresql-0 is a hostPath volume which is not supported for pod volume backup, skipping
...
```

Although the backup is completed, these warnings make alerting on metrics impossible. Am missing sth about the configuration?

regards,
strowi
