### DISCUSSION TITLE
How to enable kubernates pvc incremental snapshot?

### DISCUSSION THREAD

**Discussion by smarimus** [vmware-tanzu/velero#7616] [Community support Q&A]
**k8s:**

1. Rancher kubernetes distribution
2. Longhorn for storage.
  These configs are in place. https://longhorn.io/docs/archives/1.4.2/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot/

**Velero configs(below override-values.yaml):**

- velero plugin for csi to initiate volumesnapshot.
- velero-plugin-for-aws to upload to aws s3 bucket.
- backupStorageLocation is aws s3

I'm able to do the backup to aws s3 and restore from aws s3. I'm not clear on to enable incremental backup with velero. Can anyone help?

**override-values.yaml**

```
snapshotEnabled: true
deployNodeAgent: true
nodeAgent:
  podVolumePath: /var/lib/kubelet/pods
  priorityClassName: ""
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
initContainers:
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v0.7.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.9.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  features: EnableCSI
  uploaderType: kopia
  logLevel: debug
  backupStorageLocation:
  - name:
    provider: "velero.io/aws"
    bucket: magnit-velero-backup-test 
    default: true
    config:
      region: us-east-1    
  volumeSnapshotLocation:
  - name:
    provider: "velero.io/aws"
    bucket: backup-test    
    config:
      region: us-east-1   
credentials:
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=
      aws_secret_access_key=
```
