### DISCUSSION TITLE
Error restoring backup from minio deployed in vmware

### DISCUSSION THREAD

**Discussion by AndreCbrera** [vmware-tanzu/velero#7698] [Community support Q&A]
I have been testing a velero + minio in kubernetes, this is my configuration I deployed in k8s:

Velero helm version 4.1.3
MInio helm version  14.1.7

```
USER-SUPPLIED VALUES:
affinity: {}
annotations: {}
backupsEnabled: true
cleanUpCRDs: false
configMaps: {}
configuration:
  backupStorageLocation:
  - accessMode: ReadWrite
    bucket: velero
    config:
      insecureSkipTLSVerify: true
      region: minio
      s3ForcePathStyle: true
      s3Url: http://minio-api.lab-k8s.map.com/
    credential:
      key: cloud
      name: cloud-credentials
    default: true
    name: velero
    prefix: /
    provider: aws
    validationFrequency: null
  backupSyncPeriod: null
  clientBurst: null
  clientPageSize: null
  clientQPS: null
  defaultBackupStorageLocation: null
  defaultBackupTTL: null
  defaultRepoMaintainFrequency: null
  defaultVolumeSnapshotLocations: null
  defaultVolumesToFsBackup: null
  disableControllers: null
  extraEnvVars: {}
  features: null
  fsBackupTimeout: null
  garbageCollectionFrequency: null
  logFormat: null
  logLevel: null
  metricsAddress: null
  namespace: velero
  pluginDir: null
  profilerAddress: null
  restoreOnlyMode: null
  restoreResourcePriorities: null
  storeValidationFrequency: null
  terminatingResourceTimeout: null
  uploaderType: null
  volumeSnapshotLocation: null
containerSecurityContext: {}
credentials:
  existingSecret: {}
  extraEnvVars: {}
  extraSecretRef: ""
  name: cloud-credentials
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=xxx
      aws_secret_access_key=xxx
  useSecret: true
deployNodeAgent: true
dnsConfig: {}
dnsPolicy: ClusterFirst
extraObjects: []
extraVolumeMounts: []
extraVolumes: []
image:
  imagePullSecrets: []
  pullPolicy: IfNotPresent
  repository: velero/velero
  tag: v1.11.0
initContainers:
- image: vsphereveleroplugin/velero-plugin-for-vsphere:v1.5.1
  imagePullPolicy: IfNotPresent
  name: velero-plugin-for-vsphere
  volumeMounts:
  - mountPath: /target
    name: plugins
- image: velero/velero-plugin-for-aws:v1.7.0
  imagePullPolicy: IfNotPresent
  name: velero-plugin-for-aws
  volumeMounts:
  - mountPath: /target
    name: plugins
kubectl:
  annotations: {}
  containerSecurityContext: {}
  image:
    repository: docker.io/bitnami/kubectl
  labels: {}
  resources: {}
labels: {}
lifecycle: {}
livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /metrics
    port: http-monitoring
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 5
metrics:
  enabled: true
  nodeAgentPodMonitor:
    additionalLabels: {}
    annotations: {}
    autodetect: true
    enabled: false
  podAnnotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8085"
    prometheus.io/scrape: "true"
  prometheusRule:
    additionalLabels: {}
    enabled: false
    spec: []
  scrapeInterval: 30s
  scrapeTimeout: 10s
  service:
    annotations: {}
    labels: {}
  serviceMonitor:
    additionalLabels: {}
    annotations: {}
    autodetect: true
    enabled: false
nodeAgent:
  affinity: {}
  annotations: {}
  containerSecurityContext: {}
  dnsConfig: {}
  dnsPolicy: ClusterFirst
  extraEnvVars: {}
  extraVolumeMounts: []
  extraVolumes: []
  labels: {}
  lifecycle: {}
  nodeSelector: {}
  podSecurityContext:
    runAsUser: 0
  podVolumePath: /var/lib/kubelet/pods
  priorityClassName: ""
  privileged: true
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  tolerations: []
  useScratchEmptyDir: true
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
priorityClassName: ""
rbac:
  clusterAdministrator: true
  clusterAdministratorName: cluster-admin
  create: true
readinessProbe:
  failureThreshold: 5
  httpGet:
    path: /metrics
    port: http-monitoring
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 5
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 128Mi
schedules: {}
serviceAccount:
  server:
    annotations: null
    create: true
    labels: null
    name: velero
snapshotsEnabled: true
terminationGracePeriodSeconds: 3600
tolerations: []
upgradeCRDs: false
```

The backups works perfectly:

![image](https://github.com/vmware-tanzu/velero/assets/38178990/74a139d8-ec60-41c4-9529-ee7aadecffce)

In the  first case **postgresa01** it is saved correctly in minio:

![image](https://github.com/vmware-tanzu/velero/assets/38178990/d26fa2e1-b635-44c9-97ff-41be0092110c)

and this is the restore:

![image](https://github.com/vmware-tanzu/velero/assets/38178990/44ca4211-25f2-48bf-8eb7-b5078c1864f3)

The databases in postgres:

the origin:

![image](https://github.com/vmware-tanzu/velero/assets/38178990/c422a998-6115-4fd7-bc18-0151dd63bcef)

the restore:
![image](https://github.com/vmware-tanzu/velero/assets/38178990/19e6046c-0782-479d-b6b3-fa4105340de7)

and this is my backup object in k8s:

```
# velero describe backup postgresa01 --details
Name:         postgresa01
Namespace:    velero
Labels:       velero.io/storage-location=velero
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.27.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=27

Phase:  Completed


Namespaces:
  Included:  postgresa
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  velero

Velero-Native Snapshot PVs:  auto
Snapshot Move Data:          auto
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  1h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2024-04-17 12:19:46 +0200 CEST
Completed:  2024-04-17 12:20:01 +0200 CEST

Expiration:  2024-05-17 12:19:46 +0200 CEST

Resource List:
  apiextensions.k8s.io/v1/CustomResourceDefinition:
    - ciliumendpoints.cilium.io
  apps/v1/ControllerRevision:
    - postgresa/my-postgresql-54cb67b546
  apps/v1/StatefulSet:
    - postgresa/my-postgresql
  cilium.io/v2/CiliumEndpoint:
    - postgresa/my-postgresql-0
  discovery.k8s.io/v1/EndpointSlice:
    - postgresa/my-postgresql-fjm7p
    - postgresa/my-postgresql-hl-bqpjn
  networking.k8s.io/v1/NetworkPolicy:
    - postgresa/my-postgresql
  v1/ConfigMap:
    - postgresa/kube-root-ca.crt
  v1/Endpoints:
    - postgresa/my-postgresql
    - postgresa/my-postgresql-hl
  v1/Namespace:
    - postgresa
  v1/PersistentVolume:
    - pvc-661c8fe4-7727-4e38-9033-896b02c4b660
  v1/PersistentVolumeClaim:
    - postgresa/data-my-postgresql-0
  v1/Pod:
    - postgresa/my-postgresql-0
  v1/Secret:
    - postgresa/my-postgresql
    - postgresa/sh.helm.release.v1.my-postgresql.v1
  v1/Service:
    - postgresa/my-postgresql
    - postgresa/my-postgresql-hl
  v1/ServiceAccount:
    - postgresa/default
    - postgresa/my-postgresql

Backup Volumes:
  <error getting backup volume info: DownloadRequest.velero.io "postgresa01-d4c1cbc2-cc7a-4fac-b475-90415ce5439d" is invalid: spec.target.kind: Unsupported value: "BackupVolumeInfos": supported values: "BackupLog", "BackupContents", "BackupVolumeSn
apshots", "BackupItemOperations", "BackupResourceList", "BackupResults", "RestoreLog", "RestoreResults", "RestoreResourceList", "RestoreItemOperations", "CSIBackupVolumeSnapshots", "CSIBackupVolumeSnapshotContents">
```

and my restore:

 ```
velero describe restores postgresa01
Name:         postgresa01
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:                       Completed
Total items to be restored:  20
Items restored:              20

Started:    2024-04-17 12:39:26 +0200 CEST
Completed:  2024-04-17 12:39:39 +0200 CEST

Warnings:
  Velero:     <none>
  Cluster:  could not restore, CustomResourceDefinition "ciliumendpoints.cilium.io" already exists. Warning: the in-cluster version is different than the backed-up version.
  Namespaces:
    postgresa-restore:  could not restore, ConfigMap "kube-root-ca.crt" already exists. Warning: the in-cluster version is different than the backed-up version.
                        could not restore, Endpoints "my-postgresql-hl" already exists. Warning: the in-cluster version is different than the backed-up version.
                        could not restore, Endpoints "my-postgresql" already exists. Warning: the in-cluster version is different than the backed-up version.

Backup:  postgresa01

Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io, csinodes.storage.k8s.io, volumeattachments.storage.k8s.io, backuprepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  postgresa=postgresa-restore

Label selector:  <none>

Or label selector:  <none>

Restore PVs:  true

Existing Resource Policy:   <none>
ItemOperationTimeout:       1h0m0s

Preserve Service NodePorts:  auto
```

what I'm doing wrong? 

thanks
