### DISCUSSION TITLE
Question about cluster- and namespace resource inclusion

### DISCUSSION THREAD

**Discussion by PieterVoet** [vmware-tanzu/velero#7797] [Community support Q&A] [answered]
Hi all,

what I want to get done here is to create a backup that includes everything from a namespace, e.g. 'myns'.
In that namespace some operators are installed, which create corresponding clusterroles and clusterbindings,
which I also want to be included in the backup.
I found that the clusterroles/bindings are labelled : _olm.owner.namespace=myns_

I tried this Backup CR :

```
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: myns-s3backup-try-2024-05-13
  namespace: openshift-adp
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: false
  hooks: {}
  includedNamespaces:
  - myns
  itemOperationTimeout: 4h0m0s
  snapshotMoveData: false
  storageLocation: backup-s3-1
  ttl: 720h0m0s
  orLabelSelectors: 
  - matchLabels:
      olm.owner.namespace: myns
```

This creates a Backup that backs up everything that matches the label, however I was expecting that this backup would back up :
  - the 'myns' namespace recursively
  - all clusterscoped resources with the label

Splitting this into two backups sort of gives my what I want : the namespace with it's resources, and the corresponding 
clusterroles/bindings,  but I prefer to have just _one_ backup to manage.

( NOTE : I know that after restoring a namespace backup, deleting the operator CSV's will trigger a reinstall, 
  including the recreation of the required clusterroles/bindings, but the restore then will take a little longer )

OpenShifts OADP operator has Velero 1.12.4. Searching the web, I found https://github.com/vmware-tanzu/velero/pull/5838
but that was expected to be included in Velero 1.11.

Maybe I get it conceptually wrong, and I'm hoping to get some guidance here.
Help is appreciated.  
Thanks and have a nice day.

**Comment by kaovilai** [comment]
There have been recent developments around this. See https://github.com/vmware-tanzu/velero/issues/7492

Please check if that satisfies your requirements.

**Reply by PieterVoet** [reply]
Hi kaovilai,  thanks for responding.

After reading https://github.com/vmware-tanzu/velero/pull/5838 I understand that another way of backing up a namespace
is implemented, which uses only _one_ label, added to the NameSpace resource. This would trigger all resources in that
namespace to be backed up. Like you said last week : 'Which is equivalent to --includedNamespaces right? '.

For now I can see no advantage to my issue.  I do understand that this will enable making thatever is being backed up
is dynamic, if labels are changed runtime.

However, 'blackpiglet' states :
   
   If the namespace I/E filters and the (Or)LabelSelectors selected namespaces are different. The tracker takes the union of them.

that would explain that my assumption on my Backup CR is wrong. So I think, unless the logic to assemble a union is not changed,
even https://github.com/vmware-tanzu/velero/pull/5838 is probably not solving my issue..

thanks !

**Comment by blackpiglet** [comment]
For your scenario, just creating a backup including the namespace should work.
The reason is that Velero can resolve some k8s resource dependency. That includes the ServiceAccount's relationship with ClusterRole, ClusterRoleBinding.
https://github.com/vmware-tanzu/velero/blob/cdd5a4fdba19b14edf1c68b8f71f5e31a4eb45de/pkg/backup/actions/service_account_action.go#L92-L118


```
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: myns-s3backup-try-2024-05-13
  namespace: openshift-adp
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: false
  hooks: {}
  includedNamespaces:
  - myns
  itemOperationTimeout: 4h0m0s
  snapshotMoveData: false
  storageLocation: backup-s3-1
  ttl: 720h0m0s
```
