### DISCUSSION TITLE
Velero Backup Fails with Error Message "0"

### DISCUSSION THREAD

**Discussion by piny940** [vmware-tanzu/velero#7800] [Community support Q&A]
Hello,

I have encountered an issue with Velero while trying to create a backup. The backup failed with an error message "0". Below are the details of the backup and my configuration.

**Backup Details:**
```
$ velero backup describe velero-backup-daily-20240516031123
Name:         velero-backup-daily-20240516031123
Namespace:    velero
Labels:       app.kubernetes.io/instance=velero
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=velero
              helm.sh/chart=velero-6.0.0
              velero.io/schedule-name=velero-backup-daily
              velero.io/storage-location=default
Annotations:  meta.helm.sh/release-name=velero
              meta.helm.sh/release-namespace=velero
              velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.28.9
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=28

Phase:  PartiallyFailed (run `velero backup logs velero-backup-daily-20240516031123` for more information)


Errors:
  Velero:    message: /0
  Cluster:    <none>
  Namespaces: <none>

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true
Snapshot Move Data:          true
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2024-05-16 03:11:23 +0000 UTC
Completed:  2024-05-16 03:11:42 +0000 UTC

Expiration:  2024-06-15 03:11:23 +0000 UTC

Total items to be backed up:  650
Items backed up:              650

Backup Item Operations:  0 of 1 completed successfully, 1 failed (specify --details for more information)
Backup Volumes:
  Velero-Native Snapshots: <none included>

  CSI Snapshots:
    default/nginx-pvc:
      Data Movement: included, specify --details for more information

  Pod Volume Backups: <none included>

HooksAttempted:  0
HooksFailed:     0
```

**Error Log:**
```
$ velero backup logs velero-backup-daily-20240516031123 | grep error
time="2024-05-16T03:11:36Z" level=error msg=0 backup=velero/velero-backup-daily-20240516031123 logSource="pkg/controller/backup_controller.go:678"
```

The error seems to have occured [here](https://github.com/vmware-tanzu/velero/blob/release-1.13/pkg/controller/backup_controller.go#L678). I read the code around it, but I could not find why the error message is just "0".

**Helm values.yaml**
I'm using [CSI Snapshot Data Movement](https://velero.io/docs/v1.13/csi-snapshot-data-movement/).

```
image:
  repository: velero/velero
  tag: v1.13.0
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi
initContainers:
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v0.7.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-gcp
    image: velero/velero-plugin-for-gcp:v1.9.1
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  backupStorageLocation:
    - name: default
      provider: gcp
      bucket: velero-piny940
      credential:
        name: google-credentials
        key: gcp
  volumeSnapshotLocation:
    - name: default
      provider: gcp
      credential:
        name: google-credentials
        key: gcp
  features: EnableCSI
  defaultSnapshotMoveData: true
deployNodeAgent: true
nodeAgent:
  podVolumePath: /var/lib/kubelet/pods
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
schedules:
  backup-daily:
    disabled: false
    schedule: "48 3 * * *"
    template:
      labels:
        app: velero-backup-daily
      snapshotVolumes: true
```

- **CSI Driver**: [longhorn](https://longhorn.io).
- **VolumeSnapshotClass:**

```
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-snapshot-vsc
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: snap
```

When I create a backup without enabling the CSI feature, no errors occur. I suspect the error is related to the volume snapshot. Any insights or guidance on resolving this issue would be greatly appreciated.

Thank you.
