### DISCUSSION TITLE
Velero backup skips PVs

### DISCUSSION THREAD

**Discussion by Veeraraghavans** [vmware-tanzu/velero#7850] [General discussions]
Hi Team,

I have installed Velero Client v1.12.3 and Server v1.13.2, When i trigger backup of my cluster i get some volumes skipped. How to know why it is skipped is there way to may them part of the backup?

```
time="2024-05-31T09:33:58Z" level=info msg="hookTracker: map[], hookAttempted: 0, hookFailed: 0" backup=velero/juputer-dev-backup logSource="pkg/backup/backup.go:436"
time="2024-05-31T09:33:58Z" level=info msg="Summary for skipped PVs: [{\"name\":\"pvc-1b065560-7c32-495a-b04b-c4fbf8aacd99\",\"reasons\":[{\"approach\":\"volumeSnapshot\",\"reason\":\"no applicable volumesnapshotter found\"}]},{\"name\":\"pvc-5711bf65-f081-4dad-99b8-596b1977e063\",\"reasons\":[{\"approach\":\"volumeSnapshot\",\"reason\":\"no applicable volumesnapshotter found\"}]}]" backup=velero/juputer-dev-backup logSource="pkg/backup/backup.go:445"
time="2024-05-31T09:33:58Z" level=info msg="Backed up a total of 200 items" backup=velero/juputer-dev-backup logSource="pkg/backup/backup.go:449" progress=
```

**Comment by sseago** [comment]
It looks like you're using native snapshots for your backups and some of those volumes are of a type that doesn't support native snapshots -- i.e. they're not ebs/gp2, azure, or gcp volumes. If your volumes use CSI storage classes, you can use CSI snapshots or CSI snapshots+data mover, or in any case you can use fs-backup:

https://velero.io/docs/v1.13/csi/
https://velero.io/docs/v1.13/csi-snapshot-data-movement/
https://velero.io/docs/v1.13/file-system-backup/

**Comment by shubham-pampattiwar** [comment]
@sseago It could also be the case that the user has not configured a VolumeSnapshotLocation ? @Veeraraghavans Did you configure a valid VolumeSnapshotLocation ? 
Ref: https://velero.io/docs/v1.13/api-types/volumesnapshotlocation/

**Reply by sseago** [reply]
@shubham-pampattiwar ahh, yes, if the intent was to use native snapshots *and* the volumes in question support them, then there could just be a missing VSL.

It also says above that it's only certain volumes that are failing this way, though -- that's why I thought the most likely scenario was some volumes support native snapshots, and others don't.

**Comment by Veeraraghavans** [comment]
Thank you both @sseago @shubham-pampattiwar I havent configured specific VolumeSnapshotLocation. Below is the snapshot details.  Thank you @sseago for sharing the docs on it. I will try to configure VolumeSnapshot 

values.yaml file:
```
configuration:
  backupStorageLocation:
    - provider: azure 
  volumeSnapshotLocation:
    - provider: azure

features: EnableCSI

# Velero deployment configuration  
image:
  repository: velero/velero

# Azure plugin init container
initContainers:
  - name: velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.9.0 
    volumeMounts:
      - name: plugins
        mountPath: /target

# Service Account and Identity management
podLabels: {azure.workload.identity/use: "true"}
serviceAccount:
  server:
    create: true
    name: velero
```


I have enabled features: EnableCSI for taking snapshot of missed PV. Please find details of file type which is missed during backup process 
```
Provisioner: file.csi.azure.com 
Type: azurefile-premium
```


This is what I see when i describe in warning velero backup describe juputer-dev-backup-2

> Warnings:
>   Velero:     <none>
>   Cluster:   resource: /persistentvolumes name: /pvc-5711bf65-f081-4dad-99b8-596b1977e063 message: /No volume ID returned by volume snapshotter for persistent volume
>              resource: /persistentvolumes name: /pvc-1b065560-7c32-495a-b04b-c4fbf8aacd99 message: /No volume ID returned by volume snapshotter for persistent volume

```
time="2024-06-03T12:51:08Z" level=info msg="Summary for skipped PVs: [{\"name\":\"pvc-1b065560-7c32-495a-b04b-c4fbf8aacd99\",\"reasons\":[{\"approach\":\"volumeSnapshot\",\"reason\":\"no applicable volumesnapshotter found\"}]},{\"name\":\"pvc-5711bf65-f081-4dad-99b8-596b1977e063\",\"reasons\":[{\"approach\":\"volumeSnapshot\",\"reason\":\"no applicable volumesnapshotter found\"}]}]" backup=velero/juputer-dev-backup-2 logSource="pkg/backup/backup.go:445"
time="2024-06-03T12:51:08Z" level=info msg="Backed up a total of 200 items" backup=velero/juputer-dev-backup-2 logSource="pkg/backup/backup.go:449" progress=
```
Do I need to follow https://velero.io/docs/v1.13/file-system-backup/ method to backup for it?
