### DISCUSSION TITLE
How to add --use-restic to helm values file?

### DISCUSSION THREAD

**Discussion by retrogaming457** [vmware-tanzu/velero#7888] [Community support Q&A] [answered]
I'm using velero from helm chart using below command and I wonder where can I add restic integration on velero-values.yaml file?
```
helm upgrade velero vmware-tanzu/velero --install --create-namespace --namespace velero -f velero-values.yaml
```
```
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.7.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  defaultVolumesToFsBackup: true
  backupStorageLocation:
  - name: default
    provider: aws
    bucket: velero
    accessMode: ReadWrite
    default: true
    config:
      region: eu
      s3ForcePathStyle: true
      s3Url: https://example.com
      publicUrl: https://example.com
  volumeSnapshotLocation:
  - name: aws
    provider: aws
    config:
      region: eu
credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = <hash>
      aws_secret_access_key = <hash>
deployNodeAgent: true
```
Please help. Thanks.
