### DISCUSSION TITLE
Velero with Longhorn CSI snapshot support

### DISCUSSION THREAD

**Discussion by ehemmerlin** [vmware-tanzu/velero#7909] [Community support Q&A] [answered]
We are currently using Velero's Container Storage Interface (CSI) snapshot support and it's CSI volume data movement feature. connected to Longhorn storage which supports CSI snapshots.

The issue we face is that the backups use a lot of disk space, as Longhorn replicates the data of each snapshot the same way it does for all of our Kubernetes volumes. Moreover it retains these volumes, as it's the default behaviour of our storage class, so volumes created during backups are never deleted even if the backup has expired and no longer exists.

We are looking for a way to remove the volumes created by the snapshots after the backup is deleted: is there a way to specify a different storage class for Velero's backup (we could create one with a Delete reclaim policy instead of a Retain one) or another way to solve this issue and delete the volumes from expired backups?

**Comment by MartMet** [comment]
You need to provide a VolumeSnapshotClass with a special parameter  so longhorn can decide its a "longhorn-backup" or "longhorn-snapshot" - both can be snapshotted via CSI **but backups will remain**, while snapshots will be deleted. [Detailed explanation](https://github.com/longhorn/longhorn/issues/5802#issuecomment-2255415898)



volumesnapshotclass.yaml
```yaml
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-backup-vsc
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: snap
```
