### DISCUSSION TITLE
Edit all occurences of a pattern on a restore operation

### DISCUSSION THREAD

**Discussion by WRKT** [vmware-tanzu/velero#8001] [Community support Q&A]
Hello there,

Is it possible to modify every occurence of a pattern inside a backup during restore ?
Like I have ingresses hosts, deployment, statefulsets all tagged with a release name like : **foo-production** in their metadata.name and also in some ingresses hosts.

I want to use Velero to backup/restore these resources in a staging cluster, so I want to replace every occurence of **foo-production** in my backup into **bar-staging** as example during the restore.

Thank you.

**Comment by WRKT** [comment]
I created a custom plugin to handle that,
It effectively replace all patterns accordinly, making it easier with editing ingresses and services, but now Velero won't create a podvolumerestore during a backup...

This is the plugin used: https://github.com/WRKT/velero-custom-plugins

I do not understand why my plugin would block the podvolumerestore...

**Reply by sseago** [reply]
@WRKT If you're modifying metadata.name for a pod, this might be the cause of the podvolumerestor problems, since the PodVolumeRestore (created from the PodVolumeBackup) is keyed off pod and volume name -- so there will be no restored pod matching the expected name for the PVR. You may be able test whether this is the cause of your problem by trying an alternate version of the plugin which leaves metadata.name alone for pods. Also, your plugin as-is may work fine for CSI snapshots or datamover.

**Reply by WRKT** [reply]
@sseago alright, i'm going to try these changes, thanks

**Reply by WRKT** [reply]
@sseago hi, i didn't succeed to leave pods metadata.name during the restore, so I would like to test CSI snapshots or the datamover. 

I presume that in this case, I need to disable filesystem backup ? 
What are the options that I need to configure to use CSI snapshots ?

I installed velero with helm charts, those are my currentValue:

```yaml
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.9.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
          - name: velero-custom-plugins
            image: harbor.agc.dpk-agc-cl04.agoracalyce.net/velero/velero-custom-plugins:1.0
            imagePullPolicy: Always
            volumeMounts:
              - mountPath: /target
                name: plugins
        configuration:
          backupStorageLocation:
          - name: default
            provider: aws
            bucket: velero-backup-homol
            prefix: velero-backup-1
            config:
              region: eu-west-2
              s3Url: https://s3.eu-west-2.wasabisys.com
          defaultVolumesToFsBackup: true
          defaultItemOperationTimeout: 24h
          fsBackupTimeout: 24h
        snapshotsEnabled: false
        deployNodeAgent: true
        nodeAgent:
          podVolumePath: /var/lib/kubelet/pods
          resources:
            requests:
              memory: 1024Mi
            limits:
              cpu: '0'
              memory: 2048Mi
        credentials:
          useSecret: true
          existingSecret: cloud-credentials
        resources:
          limits:
            cpu: '0'
            memory: 2048Mi
        metrics:
          serviceMonitor:
            enabled: true
          nodeAgentPodMonitor:
            enabled: true
```
