### DISCUSSION TITLE
Exclude specific PVCs from namespace backup

### DISCUSSION THREAD

**Discussion by 11qu1d** [vmware-tanzu/velero#8080] [Community support Q&A]
Hi,

I am trying to backup all resources in a namespace, but exclude only some PVCs.

I am using the below schedule:

```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: example-schedule
  namespace: velero
spec:
  schedule: 0 1 * * *
  template:
    csiSnapshotTimeout: 60m0s
    defaultVolumesToFsBackup: false
    includeClusterResources: false
    includedNamespaces:
      - example
    includedResources:
      - '*'
    itemOperationTimeout: 4h0m0s
    snapshotMoveData: true
    storageLocation: aws-bucket
    ttl: 168h0m0s
    volumeSnapshotLocations:
      - aws-bucket
```

For the PVCs im trying to exclude i added this annotations in each one:

```yaml
  annotations:
    velero.io/exclude-from-backup: 'true'
```

For PVCs that i want to include i have added this annotation:
```yaml
  annotations:
    velero.io/csi-volumesnapshot-class: ceph-block-ssd
```

That's because i have multiple volumesnapshot classes that cause an error with Velero if not explicitly mentioned.

I would expect the above to skip trying to backup any PVCs that have the first annotation above, but every time the schedule is executed they are all included.

Feels like i'm missing something, any help is appreciated.

Thanks!
