### DISCUSSION TITLE
PVC Missing Selector on Restore

### DISCUSSION THREAD

**Discussion by ndrafahl** [vmware-tanzu/velero#8432] [Community support Q&A] [answered]
Hey!

I don't think this is an issue with Velero, I think it's more of a misunderstanding on my part on how to backup and recover a PV/PVC where I'm not actually restoring the contents of the PV, just the kubernetes resource that is associated to the PV/PVC.

In a helm chart, I have a PV and PVC defined:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv-volume-xyz
  labels:
    type: nfs
    name: shared-pv-volume-xyz
spec:
  storageClassName: nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: the_nfs_server
    path: /
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pv-claim
  namespace: my_namespace
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: shared-pv-volume-xyz
```

I created a velero schedule with the following it, where the PV and PVC are both included:
```
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: myschedulename
  namespace: velero
spec:
  paused: false

  schedule: 0 * * * *

  useOwnerReferencesInBackup: false

  template:
    csiSnapshotTimeout: 10m

    includedNamespaces:
    - 'my_namespace'
    
    includedResources:
    - '*'
    
    excludedResources:
    - storageclasses.storage.k8s.io
    - events
    - pods
    - backups.velero.io
    
    includeClusterResources: null
    
    orLabelSelectors:
      - matchLabels:
          mylabel: mylabelvalue

    snapshotVolumes: false
    
    ttl: 24h0m0s

    defaultVolumesToFsBackup: false

    snapshotMoveData: false

    datamover: velero

    uploaderConfig:
        parallelFilesUpload: 10
```

From here, I created a backup from the snapshot, and confirm both the PV and the PVC both show up within the backup by doing a `velero backup describe <the backup name> --details`.

To test out the recovery process, I then `helm uninstall` the release, and confirm both the PV and the PVC are deleted from the cluster.

Then, I do a recovery via velero and confirm that the PV and the PVCs are both restored and bound properly, and everything comes up OK.  This includes restoring the secrets that helm was maintaining for that release (so I can do my `helm` commands against that release in the cluster again).  Unfortunately though, I can no longer `helm upgrade` that release due to the PVC:
```
$ helm upgrade my-release my-chart -n my-namespace--reuse-values
Error: UPGRADE FAILED: cannot patch "shared-pv-claim" with kind PersistentVolumeClaim: PersistentVolumeClaim "shared-pv-claim" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
        AccessModes: {"ReadWriteMany"},
-       Selector:    nil,
+       Selector:    s"&LabelSelector{MatchLabels:map[string]string{name: shared-pv-volume-xyz,},MatchExpressions:[]LabelSelectorRequirement{},}",
        Resources:   {Requests: {s"storage": {i: {...}, s: "1Gi", Format: "BinarySI"}}},
        VolumeName:  "shared-pv-volume-xyz",
        ... // 4 identical fields
  }
```

The problem I run into is I can no longer do a `helm upgrade` of that release.  The PVC prior to removal/restoration had label selectors on there to select the PV:
```
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: shared-pv-volume-xyz
  storageClassName: nfs
  volumeMode: Filesystem
  volumeName: shared-pv-volume-xyz
```

But the restored PVC no longer has those selectors:
```
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeMode: Filesystem
  volumeName: shared-pv-volume-xyz
```

I'm wondering if I'm missing something super obvious here?  One option I would have is to just not include the pv/pvc in the backup, and just `helm upgrade...` the release to re-create the PV/PVC with the proper selector being applied, but I'm trying to avoid additional steps on restoration.

I tried doing some searching across issues/discussions and couldn't find anything obvious, so apologies if this has been answered already.

Thanks!!
