### DISCUSSION TITLE
vSphere 7.x no applicable volumesnapshotter found

### DISCUSSION THREAD

**Discussion by r0k5t4r** [vmware-tanzu/velero#8481] [Community support Q&A]
Hi all,

I have the following set up:

vSphere 7
VMware ESXi 7.0 Update 3q
Rancher 2.9.2
K8s v1.28.10+rke2r1
Velero 1.15 (Helm)

Helm values:

``` yaml
configuration:
  backupStorageLocation:
  - bucket: velero
    config:
      checksumAlgorithm: ""
      region: default
      s3ForcePathStyle: true
      s3Url: https://cephrgw.local
    name: default
    provider: aws
  defaultVolumesToFsBackup: false
  uploaderType: kopia
  volumeSnapshotLocation:
  - bucket: velero
    config:
      region: default
    name: default
    provider: aws
credentials:
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = asdasdasdasdds
      aws_secret_access_key = asdasdasdasdasdsd
deployNodeAgent: true
features: EnableCSI
initContainers:
- image: velero/velero-plugin-for-aws:latest
  imagePullPolicy: Always
  name: velero-plugin-for-aws
  volumeMounts:
  - mountPath: /target
    name: plugins
snapshotsEnabled: true
```
Storage Class:

``` bash
kubectl get sc
NAME                       PROVISIONER              RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csisnaps-sc (default)      csi.vsphere.vmware.com   Delete          Immediate           true                   14h
vsphere-csi-sc (default)   csi.vsphere.vmware.com   Delete          Immediate           true                   15h
```

Restic / Kopia works fine. But shouldn't PV snapshots also work with this set up?

I followed the steps from this blogpost and I can successfully create and restore volume snapshots:

https://cormachogan.com/2022/03/03/announcing-vsphere-csi-driver-v2-5-support-for-csi-snapshots/

When I try to backup the pod and its pv, the backup finished very quick and I see this error in the logs:

`time="2024-12-04T06:25:38Z" level=info msg="Summary for skipped PVs: [{\"name\":\"pvc-df83e1cd-673c-454d-9943-c48c6b65fbe3\",\"reasons\":[{\"approach\":\"podvolume\",\"reason\":\"opted out due to annotation in pod csisnaps-pod\"},{\"approach\":\"volumeSnapshot\",\"reason\":\"no applicable volumesnapshotter found\"}]}]" backup=velero/rancher-test-default logSource="pkg/backup/backup.go:542"`

I really tried all different sorts of things.

This is my snapotclass. I even added a label.

```
kubectl get volumesnapshotclass -o yaml
apiVersion: v1
items:
- apiVersion: snapshot.storage.k8s.io/v1
  deletionPolicy: Delete
  driver: csi.vsphere.vmware.com
  kind: VolumeSnapshotClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"snapshot.storage.k8s.io/v1","deletionPolicy":"Delete","driver":"csi.vsphere.vmware.com","kind":"VolumeSnapshotClass","metadata":{"annotations":{},"labels":{"velero.io/csi-volumesnapshot-class":"true"},"name":"block-snapshotclass"}}
    creationTimestamp: "2024-12-03T15:49:54Z"
    generation: 1
    labels:
      velero.io/csi-volumesnapshot-class: "true"
    name: block-snapshotclass
    resourceVersion: "20557"
    uid: 2ae336ab-3469-411d-ba05-fe1c81f9f718
kind: List
metadata:
  resourceVersion: ""
```
I also added the OPT-IN for the pvc:

``` yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csisnaps-pvc-vsan-claim
  annotations:
    backup.velero.io/backup-volumes: "true"
spec:
  storageClassName: vsphere-csi-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```
Either I'm missing something or volume snapshots are not supported in my set up.

Please help.
