### DISCUSSION TITLE
Cannot upload backup to alternative S3 provider: "Transfering payloads in multiple chunks using aws-chunked is not supported."

### DISCUSSION THREAD

**Discussion by onigoetz** [vmware-tanzu/velero#8549] [Community support Q&A]
__What steps did you take and what happened:__
In a new install of Velero I could not backup to an S3 provider (Infomaniak Swissbackup).
I get an error about `NotImplemented: Transfering payloads in multiple chunks using aws-chunked is not supported.`

__What did you expect to happen:__

Apparently S3 clients have a way to use either `aws-chunked` or the "classic" multipart upload. I would have expected it to fallback to this or have an option to configure

<details>

<summary>kubectl logs deployment/velero -n velero</summary>

```
time="2024-12-22T22:36:04Z" level=error msg="backup failed" backuprequest=velero/homepage-backup controller=backup error="rpc error: code = Unknown desc = error putting object velero_bsl/backups/homepage-backup/velero-backup.json: operation error S3: PutObject, https response error StatusCode: 501, RequestID: tx005a7ef891d549638010c-0067689454, HostID: tx005a7ef891d549638010c-0067689454, api error NotImplemented: Transfering payloads in multiple chunks using aws-chunked is not supported." logSource="pkg/controller/backup_controller.go:291"
```

</details>

<details>

<summary>velero backup describe <backupname> or kubectl get backup/<backupname> -n velero -o yaml</summary>

```
❯ velero backup describe homepage-backup
Name:         homepage-backup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.28.7
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=28

Phase:  Failed (run `velero backup logs homepage-backup` for more information)


Namespaces:
  Included:  homepage
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true
Snapshot Move Data:          false
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2024-12-22 23:36:03 +0100 CET
Completed:  <n/a>

Expiration:  2025-01-21 23:36:03 +0100 CET

Total items to be backed up:  17
Items backed up:              17

Backup Volumes:
  Velero-Native Snapshots: <none included>

  CSI Snapshots: <none included or not detectable>

  Pod Volume Backups: <none included>

HooksAttempted:  0
HooksFailed:     0
```

</details>

<details>

<summary>velero backup logs <backupname> </summary>

```
An error occurred: file not found
```

</details>

velero restore describe <restorename> or kubectl get restore/<restorename> -n velero -o yaml

N/A

velero restore logs <restorename>

N/A

__Anything else you would like to add:__

<details>

<summary>BackupStorageLocation</summary>

```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-8.1.0
  name: default
  namespace: velero
spec:
  accessMode: ReadWrite
  config:
    region: us-east-1
    s3ForcePathStyle: "true"
    s3Url: https://s3.___.infomaniak.com
  credential:
    key: cloud
    name: velero
  objectStorage:
    bucket: default
    prefix: velero_bsl
  provider: aws
```

</details>

__Environment:__

Velero version (use velero version): v1.15.0
Velero features (use velero client config get features): `features: <NOT SET>`
Kubernetes version (use kubectl version): v1.28.7
Kubernetes installer & version: kubeadm v1.28.15
Cloud provider or hardware configuration: Bare Metal / intel
OS (e.g. from /etc/os-release): Ubuntu 24.04.1 LTS
