### DISCUSSION TITLE
restore with longhorn volumes is marked as completed before volume is actually restored

### DISCUSSION THREAD

**Discussion by KonstantinNosov** [vmware-tanzu/velero#8556] [Community support Q&A] [answered]
I use velero to backup and restore volumes managed with longhorn.
the restore transits to completed less than in a minute:
```
status:
  completionTimestamp: '2024-12-24T16:49:14Z'
  hookStatus: {}
  phase: Completed
  progress:
    itemsRestored: 15
    totalItems: 15
  startTimestamp: '2024-12-24T16:48:20Z'
```
backup schedule spec:
```
spec:
  schedule: 30 0 * * *
  skipImmediately: false
  template:
    csiSnapshotTimeout: 1h0m0s
    hooks: {}
    includedNamespaces:
      - '*'
    includedResources:
      - pv
      - pvc
    metadata: {}
    ttl: 730h0m0s
  useOwnerReferencesInBackup: false
```

At this moment longhorn reports volumes are not ready since actual restore is yet in progress.

Volumes are restored successfully after some time, it is only about status of Restore - it is used by argocd health checks, so workloads start to be created before actual volumes restore is finished and fail with timeouts, report degraded state etc since volumes are quite big and take significant time to restore.

Not sure if it is an issue of velero, longhorn or snapshot controller, so starting discussion rather than creating an issue
