### DISCUSSION TITLE
Error in VolumeSnapshot

### DISCUSSION THREAD

**Discussion by pablofilgueira91** [vmware-tanzu/velero#8633] [Community support Q&A]
Hi, I'm trying to make a snapshot volume of a PVC, and I get the error that it tries to look for the PVC in an incorrect resource group.

I installed Velero with Helmchart, and this is the configuration in my value.yaml
```    
configuration:
      backupStorageLocation:
        - name: default
          provider: azure
          bucket: velero
          config:
            resourceGroup: Velero_Backups
            storageAccount: velerobackupsbrubanklabs
            subscriptionId: fbc238d5-a18f-49fa-b188-09073532a408
            useAAD: "true"
      volumeSnapshotLocation:
        - name: default
          provider: azure
          config:
            resourceGroup: MC_RG-AKS-LABS_BB-AKS-LABS_eastus2
            subscriptionId: fbc238d5-a18f-49fa-b188-09073532a408
            apiTimeout: "10m"
```

This is the error in backup
```
Phase:  PartiallyFailed (run `velero backup logs pvc-backup5` for more information)


Errors:
  Velero:   name: /pablo-pod message: /Error backing up item error: /error getting volume info: rpc error: code = Unknown desc = GET https://management.azure.com/subscriptions/fbc238d5-a18f-49fa-b188-09073532a408/resourceGroups/Velero_Backups/providers/Microsoft.Compute/disks/pvc-7549d79d-c736-426f-b75c-10b0b210c190
--------------------------------------------------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: AuthorizationFailed
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AuthorizationFailed",
    "message": "The client 'b2098050-afb0-4520-ad7f-bd34bfc22332' with object id 'b2098050-afb0-4520-ad7f-bd34bfc22332' does not have authorization to perform action 'Microsoft.Compute/disks/read' over scope '/subscriptions/fbc238d5-a18f-49fa-b188-09073532a408/resourceGroups/Velero_Backups/providers/Microsoft.Compute/disks/pvc-7549d79d-c736-426f-b75c-10b0b210c190' or the scope is invalid. If access was recently granted, please refresh your credentials."
  }
}
--------------------------------------------------------------------------------
```

It is looking for the PVC in the Velero_Backups resource group but it should look for it in MC_RG-AKS-LABS_BB-AKS-LABS_eastus2 as configured in volumeSnapshotLocation

any idea what the problem could be?

velero version
Client:
	Version: v1.15.1
	Git commit: -
Server:
	Version: v1.15.1
