### DISCUSSION TITLE
VolumeSnapshot not deleted

### DISCUSSION THREAD

**Discussion by sylvainmetayer** [vmware-tanzu/velero#8650] [Community support Q&A]
Hello,

It seems that Velero does not delete VolumeSnapshot after the DataUpload phase.

Here is my configuration from a schedule : 

```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  labels:
    velero.io/storage-location: XYZ
  name: scheduled-backup-default
  namespace: velero
spec:
  schedule: 0 0 * * *
  skipImmediately: false
  template:
    csiSnapshotTimeout: 30m0s
    includedNamespaces:
      - default
    snapshotMoveData: true
    storageLocation: XYZ
    ttl: 720h0m0s
```

After the backup, I can see in the logs `backup SnapshotMoveData is set to true, skip VolumeSnapshot resource persistence.`, however, the VolumeSnapshot is not deleted in my cloud provider (OVH)

I am using Velero 1.15.0. Did I missed an option during the configuration of my schedule and/or velero configuration ?

**Comment by sylvainmetayer** [comment]
It seems that by settings the following arguments (and ensuring that `backup.velero.io/backup-volumes` annotation is present on every pod with volumes), the snapshot volumes are not created. 

```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  labels:
    velero.io/storage-location: XYZ
  name: scheduled-backup-default
  namespace: velero
spec:
  schedule: 0 0 * * *
  skipImmediately: false
  template:
    csiSnapshotTimeout: 30m0s
    includedNamespaces:
      - default
    snapshotVolumes: false
    snapshotMoveData: true
    storageLocation: XYZ
    ttl: 720h0m0s
```
