### DISCUSSION TITLE
check if node exists in restore resource modifier

### DISCUSSION THREAD

**Discussion by ericborn42** [vmware-tanzu/velero#8709] [Community support Q&A] [answered]
I am attempting to modify a couple ingress values in all ingresses using the restore-resource-modifier. This is a fairly large application which has many components deployed by third party helm charts so there are some inconsistencies in the yaml of the various ingresses. 

I am running into a situation where some ingress definitions do not include /spec/tls/0/hosts/0 or even the /spec/tls node at all. Most ingresses do though. **Is there a way to check if the node exists and log a warning instead of marking the restore as partially failed?**

I have tried using test operation with a value of `.*` which still results in errors in the restore and a partially failed designation 

```
spec:  
  ingressClassName: nginx  
  tls:  
    - hosts:  
        - example.com  
  rules:
    - host: example.com
      http:
```
vs     
```
spec:
  ingressClassName: nginx
  rules:
    - host: example.com
```
