### ISSUE TITLE
add support for restic rclone backend

### ISSUE THREAD

**Issue by metal3d** [vmware-tanzu/velero#1253]
**What steps did you take and what happened:**
I installed velero + restic on Scaleway kubernetes cluster. After having tried some simple backup, I added persistence volume backup on pods in a namespace.

I create the backup:
```
velero backup create gitea --include-namespaces=git
```

No bucket is created, and the backup sticks on "InProgress":
```
velero backup get
NAME      STATUS       CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
gitea     InProgress   0001-01-01 00:00:00 +0000 UTC   29d       default            <none>
```

Note that others backup, without persistence volume backup, are working well. Buckets are created and backups are stored.

**What did you expect to happen:**
Backup of the namespace + volumes in my bucket.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
https://paste.fedoraproject.org/paste/Kq-K~yDb0JAALDLkTTWBSA
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
Name:         gitea
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  InProgress

Namespaces:
  Included:  git
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    <n/a>
Completed:  <n/a>

Expiration:  2019-04-03 12:15:09 +0200 CEST

Validation errors:  <none>

Persistent Volumes: <none included>
```
* `velero backup logs <backupname>`
```
velero backup logs gitea
An error occurred: request failed: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><RequestId>tx26c87a0b00024765b7a2f-005c7cfe63</RequestId><Key>backups/gitea/gitea-logs.gz</Key></Error>
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v0.11.0
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version: kubespray
- Cloud provider or hardware configuration: Scaleway
- OS (e.g. from `/etc/os-release`): Centos 7.4 on server, Fedora 29 for the client

**Comment by metal3d** [comment]
OK, found the problem and I cannot fix that.
```
 velero restic repo get -o yaml

 message: |-
    error running command=restic init --repo=s3:https://s3.nl-ams.scw.cloud/velero/restic/git --password-file=/tmp/velero-restic-credentials-git393484349 --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: create repository at s3:https://s3.nl-ams.scw.cloud/velero/restic/git failed: client.BucketExists: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'nl-ams'
```

It's the same problem with "mc" command I tried before, I needed to use "s3v2" api version to avoid that problem.

Is there a way to fix ?

**Comment by metal3d** [comment]
To be sure that everything is ok:

- I set region to "nl-ams" in the BackupStorageLocation object
- that works for backup without persistenceVolumes
- that give the above error only when I want to backup volumes

So it seems that "restic" doesn't use the provided region parameter.

Here is my backupstoragelocation:
```yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: velero
  config:
    region: nl-ams
    s3ForcePathStyle: "true"
    s3Url: https://s3.nl-ams.scw.cloud
```

**Comment by skriss** [comment]
Hmm. I'm guessing this is an issue within `restic` itself. Could you try manually creating a restic repo in your object storage? The [restic docs](https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#amazon-s3) should explain how to do that.  Let me know if that does or does not work.

**Comment by metal3d** [comment]
You're right:

```
restic -r s3:https://s3.nl-ams.scw.cloud/restic init
Fatal: create repository at s3:https://s3.nl-ams.scw.cloud/restic failed: client.BucketExists: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'nl-ams'
```

I found this bug report here: https://github.com/restic/restic/issues/2023 where it is explained that we can use restic "rclone" on preexisting bucket. I don't know if it could be usable with velero.

**Comment by Hyrsham** [comment]
Hello there, 

I am currently facing the same issue with scaleway,
@metal3d did you find a workaround about this issue ?

**Comment by vitobotta** [comment]
Same here. @metal3d have you found a workaround in the meantime? And you @Hyrsham ?

**Comment by newtoncorp** [comment]
Hello people,

I've been able to setup velero to use Scaleway's Kubernetes & Object storage the following way.

- Create a Kube cluster in scw interface
- download kubeconfig
- create a bucket in the object storage interface (here `velero-test-newton` in `fr-par` region)
- `brew install velero`
```cat > credentials << EOF
[default]
aws_access_key_id=SCW<KEY>
aws_secret_access_key=<SECRET>
```

```
velero install \                                                                                                                                                                                         
  --provider velero.io/aws \
  --bucket velero-backups \
  --plugins velero/velero-plugin-for-aws:v1.0.0 \
  --backup-location-config s3Url=https://s3.fr-par.scw.cloud,region=fr-par \
  --use-volume-snapshots=false \
  --secret-file=./credentials \
  --kubeconfig ./kubeconfig-k8s-serene-bardeen.yaml \
  --bucket velero-test-newton
```
- create an example app in Kubernetes
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-example
  labels:
    app: nginx

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-logs
  namespace: nginx-example
  labels:
    app: nginx
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: nginx-example
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-logs
          persistentVolumeClaim:
           claimName: nginx-logs
      containers:
      - image: nginx:stable
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-svc
  namespace: nginx-example
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
```
- `kubectl apply -f ./nginx-example --kubeconfig kubeconfig-k8s-serene-bardeen.yaml`
- `velero backup create nginx-backup --selector app=nginx --kubeconfig kubeconfig-k8s-serene-bardeen.yaml`
- `velero backup describe nginx-backup --kubeconfig kubeconfig-k8s-serene-bardeen.yaml`
Gives 
```Name:         nginx-backup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  Completed

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  app=nginx

Storage Location:  default

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-01-16 13:53:37 +0100 CET
Completed:  2020-01-16 13:53:40 +0100 CET

Expiration:  2020-02-15 13:53:37 +0100 CET

Persistent Volumes: <none included>
```
