### ISSUE TITLE
allow service clusterIP to be preserved on restore

### ISSUE THREAD

**Issue by nareshtank** [vmware-tanzu/velero#1255]
**What steps did you take and what happened:**
I created Service with fixed ClusterIP

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"portal","namespace":"portal"},"spec":{"clusterIP":"10.96.0.51","ports":[{"name":"portal-https","port":443},{"name":"portal-ssh","port":2020}],"selector":{"run":"portal"},"type":"ClusterIP"}}
  creationTimestamp: 2019-03-05T06:33:29Z
  labels:
    ark-restore: fbbac0f17e4049bcbea3c0521c31175f-1551767531000
    ark.heptio.com/backup-name: fbbac0f17e4049bcbea3c0521c31175f-1551766587000
    ark.heptio.com/restore-name: fbbac0f17e4049bcbea3c0521c31175f-1551767531000
  name: portal
  namespace: portal
  selfLink: /api/v1/namespaces/portal/services/portal
  uid: 970aab73-3f10-11e9-b30b-aaeeba615cd7
spec:
  clusterIP: 10.96.0.51
  ports:
  - name: portal-https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    run: portal
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

After ark backup JSON looks correct:

```
{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "annotations": {
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"name\":\"portal\",\"namespace\":\"portal\"},\"spec\":{\"clusterIP\":\"10.96.0.51\",\"ports\":[{\"name\":\"portal-https\",\"port\":443},{\"name\":\"portal-ssh\",\"port\":2020}],\"selector\":{\"run\":\"portal\"},\"type\":\"ClusterIP\"}}\n"
    },
    "creationTimestamp": "2019-03-05T06:15:11Z",
    "name": "portal",
    "namespace": "portal",
    "resourceVersion": "483713",
    "selfLink": "/api/v1/namespaces/portal/services/portal",
    "uid": "08942fb5-3f0e-11e9-b30b-aaeeba615cd7"
  },
  "spec": {
    "clusterIP": "10.96.0.51",
    "ports": [
      {
        "name": "portal-https",
        "port": 443,
        "protocol": "TCP",
        "targetPort": 443
      },
      {
        "name": "portal-ssh",
        "port": 2020,
        "protocol": "TCP",
        "targetPort": 2020
      }
    ],
    "selector": {
      "run": "portal"
    },
    "sessionAffinity": "None",
    "type": "ClusterIP"
  },
  "status": {
    "loadBalancer": {}
  }
}
```

I then deleted the service and restore it with ark: the ClusterIP was random
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"portal","namespace":"portal"},"spec":{"clusterIP":"10.96.0.51","ports":[{"name":"portal-https","port":443},{"name":"portal-ssh","port":2020}],"selector":{"run":"portal"},"type":"ClusterIP"}}
  creationTimestamp: 2019-03-05T06:33:29Z
  labels:
    ark-restore: fbbac0f17e4049bcbea3c0521c31175f-1551767531000
    ark.heptio.com/backup-name: fbbac0f17e4049bcbea3c0521c31175f-1551766587000
    ark.heptio.com/restore-name: fbbac0f17e4049bcbea3c0521c31175f-1551767531000
  name: portal
  namespace: portal
  resourceVersion: "485930"
  selfLink: /api/v1/namespaces/portal/services/portal
  uid: 970aab73-3f10-11e9-b30b-aaeeba615cd7
spec:
  clusterIP: 10.110.171.41
  ports:
  - name: portal-https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: portal-ssh
    port: 2020
    protocol: TCP
    targetPort: 2020
  selector:
    run: portal
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**What did you expect to happen:**

clusterIP should remain same when restore.
I restored the service from backup JSON manually, it created the service with same clusterIP.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`

```
time="2019-03-05T06:33:29Z" level=info msg="Restoring resource 'services' into namespace 'portal' from: /tmp/301133352/resources/services/namespaces/portal" backup=fbbac0f17e4049bcbea3c0521c31175f-1551766587000 logSource="pkg/restore/restore.go:592" restore=heptio-ark/fbbac0f17e4049bcbea3c0521c31175f-1551767531000
time="2019-03-05T06:33:29Z" level=info msg="Getting client for /v1, Kind=Service" backup=fbbac0f17e4049bcbea3c0521c31175f-1551766587000 logSource="pkg/restore/restore.go:652" restore=heptio-ark/fbbac0f17e4049bcbea3c0521c31175f-1551767531000
time="2019-03-05T06:33:29Z" level=info msg="Executing item action for services" backup=fbbac0f17e4049bcbea3c0521c31175f-1551766587000 logSource="pkg/restore/restore.go:764" restore=heptio-ark/fbbac0f17e4049bcbea3c0521c31175f-1551767531000
time="2019-03-05T06:33:29Z" level=info msg="Restoring Service: portal" backup=fbbac0f17e4049bcbea3c0521c31175f-1551766587000 logSource="pkg/restore/restore.go:796" restore=heptio-ark/fbbac0f17e4049bcbea3c0521c31175f-1551767531000
```

* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`

```
Phase:  Completed

Validation errors:  <none>

```

No warnings,
No errors

* `velero backup logs <backupname>`

(Whole backup have 3 sets of docker secret, pv, pvc, deployments, service)
https://gist.github.com/nareshtank/97023f9934e186c6249a95f7008a933f

* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml
```
Phase:  Completed

Validation errors:  <none>

Warnings:  <none>
Errors:    <none>`
```

* `velero restore logs <restorename>`

https://gist.github.com/nareshtank/a57529c811d464768c82972656a45bc6

*`Notes`*
I have three services in backup 2 with fixed clusterIP and 1 with Random clusterIp but fixed NodePort.
On restore NodePorts are not changing, get info from [issue 989](https://github.com/heptio/velero/issues/989).

But ClusterIp in all 3 services are changing, but in Issue:989 I saw the logs reported It has the same clusterIP even after restore.

**Environment:**

- Ark version (use `ark version`):
 
Version: v0.10.1
Git commit: 7e4fca428d73899cbbdb00da8d340d44984975d8

- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:

kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:54:02Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
On premises - Fedora 26
