### ISSUE TITLE
Consider making it easier to add fsfreeze or other pre/post hooks to pods

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#1872]
**Describe the problem/challenge you have**
Right now, if a user wants to use an fsfreeze or other pre/post hook for their pod backup, they need to manually add annotations to the pod and possibly add a container to the pod spec as well (i.e. the `gcr.io/heptio-images/fsfreeze` image). This can be burdensome for users.

**Describe the solution you'd like**
Per #1586, one option would be to add a webhook to automatically add this to new pods. Another option would be a CLI command that makes this easier (e.g. `velero hook add`).

**Comment by ThomasSteinbach** [comment]
Having auto-fsfreeze would be absolutely helpful. Currently using restic opt-out seems quite helpful at a first glance, but is really dangerous considering data consistency. To implement a minimum level of data consistency you have to patch your deployments by hand. This is quite cumbersome if you have a Helm charts creating lots of persistent volumes, like Gitlab for example does. You have to check your whole k8s object definitions and "kustomize patch" them like following:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-postgresql
  labels:
    app: postgresql
    release: gitlab
spec:
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: data
        pre.hook.backup.velero.io/command: '["/bin/fsfreeze", "--freeze", "/var/lib/postgresql/data/pgdata"]'
        pre.hook.backup.velero.io/container: fsfreeze
        post.hook.backup.velero.io/command: '["/bin/fsfreeze", "--unfreeze", "/var/lib/postgresql/data/pgdata"]'
        post.hook.backup.velero.io/container: fsfreeze
    spec:
      containers:
        - name: gitlab-postgresql
        - name: metrics
        - name: fsfreeze
          image: busybox
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data/pgdata"
              name: data
              readOnly: false
          command: ["/bin/sh", "-c", "sleep infinity"
```

You have to repeath that patch by hand for every single volume to backup. So it would be really helpful to have an automation within Velero that would add a fsfreeze container to every pod mounting a persistent volume and doing auto freeze/unfreeze the volume on backup.
