### ISSUE TITLE
Restic restores of statically provisioned PVs

### ISSUE THREAD

**Issue by brokencode64** [vmware-tanzu/velero#1927]
**What steps did you take and what happened:**
We have many persistent volumes that are classless nfs disks created vs "persistent volume" yamls.  It seems that after annotating the pods with the correct notations to have them backed up the actual data for the volumes are backed up to s3; however, upon trying to restore them the Persistent volumes are not automatically recreated.  If I create the persistent volume manually the data will be restored.

**What did you expect to happen:**
The volumes should have been backed up along with the rest of the deployments and restored. Upon running a restore the persistent volumes should be automatically restored with the data.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Yamls**
For example, we create most of our persistent volumes for our on-prem environment and some of our aws volumes like this:
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: prometheus-prometheus-alertmanager
 labels:
   type: nfs
   name: prometheus-prometheus-alertmanager
spec:
 capacity:
   storage: 10Gi
 accessModes:
   - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
   path: /system/prometheus-prometheus-alertmanager
   server: x.x.x.x.1.amazonaws.com
```
That persistent volume claim would be used like this:
```
`---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-prometheus-alertmanager
  namespace: monitor
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: nfs
      name: prometheus-prometheus-alertmanager
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus-alertmanager
  name: prometheus-prometheus-alertmanager
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-alertmanager
  template:
    metadata:
      labels:
        app: prometheus-alertmanager
      annotations:
        velero.io/backup-name: monitor
        backup.velero.io/backup-volumes: storage-volume
        prometheus.io/path: /metrics
        prometheus.io/port: "9093"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - args:
        - --config.file=/etc/config/alertmanager.yml
        - --storage.path=/data
        - --web.external-url=http://alertmanager.tools.kube-pet.appdev.io
        image: prom/alertmanager:v0.16.1
        imagePullPolicy: IfNotPresent
        name: prometheus-alertmanager
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
        ports:
        - containerPort: 9093
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /#/status
            port: 9093
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
        - mountPath: /data
          name: storage-volume
      - args:
        - --volume-dir=/etc/config
        - --webhook-url=http://localhost:9093/-/reload
        image: jimmidyson/configmap-reload:v0.1
        imagePullPolicy: IfNotPresent
        name: prometheus-alertmanager-configmap-reload
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-prometheus-alertmanager
        name: config-volume
      - name: storage-volume
        persistentVolumeClaim:
          claimName: prometheus-prometheus-alertmanager
---
```
**Environment:**
- Velero version: V1.1.0 
- Kubernetes version : V1.12.4
- Cloud provider or hardware configuration: Two clusters AWS, Three on-prem (hosted on vmware vms)
- OS (e.g. from `/etc/os-release`): AWS hosts ubuntu based, on-prem RHEL 7.5.
