### ISSUE TITLE
Velero cannot parse valid CPU resource requests....  Restic does not work

### ISSUE THREAD

**Issue by Stolr** [vmware-tanzu/velero#1979]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I am having issue trying to restore a workload with restic volume.

```
Couldn't parse resource requirements: couldn't parse CPU request
```

```
time="2019-10-17T15:54:18Z" level=info msg="Using image \"gcr.io/heptio-images/velero-restic-restore-helper:v1.1.0\"" cmd=/velero logSource="pkg/restore/restic_restore_action.go:105" pluginName=velero pod=ok102-confluence-pr/confluence-server-11-frnw2 restore=ok24-velero/tools-confluence-backup-pr-20191017175119
time="2019-10-17T15:54:18Z" level=error msg="Using default resource values, couldn't parse resource requirements: couldn't parse CPU request \"\": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'." cmd=/velero logSource="pkg/restore/restic_restore_action.go:112" pluginName=velero pod=ok102-confluence-pr/confluence-server-11-frnw2 restore=ok24-velero/tools-confluence-backup-pr-20191017175119
  | time="2019-10-17T15:54:18Z" level=info msg="Done executing ResticRestoreAction" cmd=/velero logSource="pkg/restore/restic_restore_action.go:142" pluginName=velero restore=ok24-velero/tools-confluence-backup-pr-20191017175119

```

When this happens , No init container is created and volume is not restored properly.

The restic stay in "New" phase and the restore never finish 

```
Restic Restores:
  New:
    ok102-confluence-pr/confluence-server-11-frnw2: confluence-server-data, confluence-server-shared
```

Had the same issue with another worload. I adapt the limit / request of the deployment and it was ok after that. Seems that default value is not taken and it crash.

Same issue here : https://github.com/fusor/openshift-velero-plugin/issues/7

** Environment **

velero version
Client:
        Version: v1.1.0
        Git commit: a357f21aec6b39a8244dd23e469cc4519f1fe608
Server:
        Version: v1.1.0

oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
openshift v3.11.0+bdd37ad-314
kubernetes v1.11.0+d4cacc0

Any fix I could apply quickly to make my restore works ?

Thanks

**Comment by Stolr** [comment]
Adding a configmap fix the issue so this is not really an issue

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: restic-restore-action-config
  namespace: ok24-velero
  labels:
    velero.io/plugin-config: ""
    velero.io/restic: RestoreItemAction
data:
  cpuRequest: "1"
  memRequest: "1024Mi"
  cpuLimit: "1"
  memLimit: "1024Mi"
```

The error is not present anymore.

But the restic volume won't restore Anyway.

I'll open another issue
