### ISSUE TITLE
Error listing items if labelSelector to empty object

### ISSUE THREAD

**Issue by kzap** [vmware-tanzu/velero#2083]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
In `1.2.0` the CRDs require strict values, and `labelSelector` can accept an empty object `{}`

Example backup:
```yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup-test
  namespace: velero
spec:
  hooks: {}
  includeClusterResources: true
  includedNamespaces:
  - '*'
  labelSelector: {}
  snapshotVolumes: true
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - default
```

The errors you get if `labelSelector: {}` is set are
```go
time="2019-11-29T01:48:53Z" level=error msg="Error listing items" backup=velero/manualbackup-20191129094851 error="found '<', expected: !, identifier, or 'end of string'" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/resource_backupper.go:230" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*defaultResourceBackupper).backupResource" group=v1 logSource="pkg/backup/resource_backupper.go:230" namespace= resource=persistentvolumes
```

**What did you expect to happen:**
The backup would proceed as if `labelSelector` was empty but the YAML is accepted but the velero container has problems with such input and thus fails to complete the backup properly

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  1.2.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.15
- Kubernetes installer & version: 1.13
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Ubuntu
