### ISSUE TITLE
Using fsfreeze leads to hanging system on XFS

### ISSUE THREAD

**Issue by dns2utf8** [vmware-tanzu/velero#2113]
**What steps did you take and what happened:**
I have a [test application that simulates a DB](https://gitlab.com/dns2utf8/multi_file_writer) by writing to 4 different files at the same time.
Sometimes velero, restic or fsfreeze crash and the whole setup stops.

**What did you expect to happen:**
The unfreeze must happen when
* [x] backup succeeds (about 50% chance)
* [x] backup fails (less than 5% chance)
* [ ] backup worker gets killed/crashes

**The output of the following commands will help us better understand what's going on**:
`velero backup get` lists the broken backups as `InProgress` even after the worker has been restarted.

The backing storage minio does not contain any files of that job.

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>` not available
* velero backup describe snapshot-test-2019-12-10-1409 --details
```
Name:         snapshot-test-2019-12-10-1409
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:  New

Namespaces:
  Included:  snapshot-test
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  

Snapshot PVs:  false

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  0

Started:    <n/a>
Completed:  <n/a>

Expiration:  <nil>

Resource List:  <error getting backup resource list: timed out waiting for download URL>

Persistent Volumes: <none included>
```

**Anything else you would like to add:**
The storage was installed with this file and these commands:
```
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: hpe-csp
  namespace: velero
spec:
  provider: hpe.com/snapshotter
  config: {
       "secret-name": "nimble-secret",
       "secret-namespace": "kube-system"
  }
```
```bash
kubectl apply -f hpe_crd_0-snapshotter.yml
kubectl create -f https://raw.githubusercontent.com/hpe-storage/velero-plugin/master/nimble-csp.yaml
velero plugin add hpestorage/velero-hpe-blockstore:beta --image-pull-policy Always
```

**Environment:**

- Velero version: 1.2.0 (Git commit: 5d008491bbf681658d3e372da1a9d3a21ca4c03c)
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
- Cloud provider or hardware configuration: Intel Xeon on worker, HPE storage
- OS (e.g. from `/etc/os-release`): 18.04.3 LTS (Bionic Beaver)

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: snapshot-test
  labels:
    app: multi-file-writer

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mfw-volume
  namespace: snapshot-test
  labels:
    app: multi-file-writer
spec:
  #storageClassName: <YOUR_STORAGE_CLASS_NAME>
  #storageClassName: generic-nimble
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-file-writer
  namespace: snapshot-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-file-writer
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: multi-file-writer
      annotations:
        pre.hook.backup.velero.io/container: fsfreeze
        pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/generated"]'
        post.hook.backup.velero.io/container: fsfreeze
        post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/generated"]'
    spec:
      volumes:
        - name: mfw-volume
          persistentVolumeClaim:
           claimName: mfw-volume
      containers:
      - name: multi-file-writer
        image: registry.gitlab.com/dns2utf8/multi_file_writer:0.2.1
        imagePullPolicy: Always
        env:
            - name: MFW_RUN_FOREVER
              value: "yes"
            - name: MFW_DELAY
              value: "0.01"
        resources:
          requests:
            cpu: "4"
            memory: 128M
          limits:
            cpu: "8"
            memory: 256M
        volumeMounts:
        - mountPath: "/generated"
          name: mfw-volume
          readOnly: false
      - name: fsfreeze
        image: velero/fsfreeze-pause:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/generated"
            name: mfw-volume
            readOnly: false
```

**Comment by dns2utf8** [comment]
I did some more research and found a possible question:

* Does one need to mount the PV with the `noatime` attribute?

Best regards

**Comment by dns2utf8** [comment]
PS: [one log file came in the end](https://gist.github.com/dns2utf8/577fb666f53b07ec2ba06b5637aa56bd)

**Comment by dns2utf8** [comment]
Today I reached the following conclusion:

1. If the filesystem is mounted with `relatime` a `read(...)` from any program will trigger a `write( fd->atime )` if said file has been in the process of being written to while `fsfreeze --freeze ...` occurred, resulting in a complete dead-lock of restic.
    1. To resolve this one has to `fsfreeze --unlock ...` by hand before the timeout
    2. Or delete all pods inside the velero namespace as well as unfreezing the affected pod and finally delete the backup because it will never loose its `InProgress` state
2. With Ubuntu 18.04.3 LTS one can semi randomly trigger a bug with fsfreeze and reads on xfs:
    1. Write multiple MB to a file (eg. 100MB) while after one or two MB freeze the filesystem from the sidecar pod
    2. From the sidecar pod, issue multiple `strace tail /generated/data/0.txt`
    3. After a couple of tries strace shows that the `read(...)` works but `close(...)` hangs
    4. From now on all `read(...)` operations are blocked until the freeze is lifted

IMHO The first point should be documented since one can prevent that freeze by adding the `mountOption`
```bash
kubectl edit storageclasses.storage.k8s.io
```
```yaml
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    ...
  mountOptions:
  - noatime
  parameters:
    ...
```
