### ISSUE TITLE
An error occurred: DownloadRequest.velero.io

### ISSUE THREAD

**Issue by boxcee** [vmware-tanzu/velero#2135]
**What steps did you take and what happened:**
I created a backup:
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  labels:
    namespace: mip-playground
    bucket: velero-mls-development
  name: mip-playground-kubedb
spec:
  includedNamespaces:
    - mip-playground
  includedResources:
    - dormantdatabases.kubedb.com
    - elasticsearches.kubedb.com
    - elasticsearchversions.catalog.kubedb.com
    - etcds.kubedb.com
    - etcdversions.catalog.kubedb.com
    - memcacheds.kubedb.com
    - memcachedversions.catalog.kubedb.com
    - mongodbs.kubedb.com
    - mongodbversions.catalog.kubedb.com
    - mysqls.kubedb.com
    - mysqlversions.catalog.kubedb.com
    - postgreses.kubedb.com
    - postgresversions.catalog.kubedb.com
    - redises.kubedb.com
    - redisversions.catalog.kubedb.com
    - snapshots.kubedb.com
  snapshotVolumes: false
  storageLocation: mls-development
  volumeSnapshotLocations: []
```
and receive the following error message:
```
An error occurred: DownloadRequest.velero.io "mip-playground-kubedb-20191216122548" is invalid: []: Invalid value: map[string]interface {}{"status":map[string]interface {}{"phase":"", "downloadURL":"", "expiration":interface {}(nil)}, "kind":"DownloadRequest", "apiVersion":"velero.io/v1", "metadata":map[string]interface {}{"name":"mip-playground-kubedb-20191216122548", "namespace":"velero", "creationTimestamp":"2019-12-16T11:25:48Z", "generation":1, "uid":"cee7aeee-1ff6-11ea-a004-14dda9d51862"}, "spec":map[string]interface {}{"target":map[string]interface {}{"kind":"BackupLog", "name":"mip-playground-kubedb"}}}: validation failure list:
status.expiration in body must be of type string: "null"
status.phase in body should be one of [New Processed]
```

**What did you expect to happen:**
I didn't exepct that error message.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
```
time="2019-12-16T11:25:05Z" level=error msg="backup failed" controller=backup error="[rpc error: code = Unknown desc = EOF, rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>]" key=velero/mip-playground-kubedb logSource="pkg/controller/backup_controller.go:233"
```
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
Name:         mip-playground-kubedb
Namespace:    velero
Labels:       bucket=velero-mls-development
              namespace=mip-playground
              velero.io/storage-location=mls-development
Annotations:  <none>

Phase:  Failed (run `velero backup logs mip-playground-kubedb` for more information)

Namespaces:
  Included:  mip-playground
  Excluded:  <none>

Resources:
  Included:        dormantdatabases.kubedb.com, elasticsearches.kubedb.com, elasticsearchversions.catalog.kubedb.com, etcds.kubedb.com, etcdversions.catalog.kubedb.com, memcacheds.kubedb.com, memcachedversions.catalog.kubedb.com, mongodbs.kubedb.com, mongodbversions.catalog.kubedb.com, mysqls.kubedb.com, mysqlversions.catalog.kubedb.com, postgreses.kubedb.com, postgresversions.catalog.kubedb.com, redises.kubedb.com, redisversions.catalog.kubedb.com, snapshots.kubedb.com
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  mls-development

Snapshot PVs:  false

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-12-16 12:24:51 +0100 CET
Completed:  2019-12-16 12:25:01 +0100 CET

Expiration:  2020-01-15 12:24:51 +0100 CET

Persistent Volumes: <none included>
```
* `velero backup logs <backupname>`
```
time="2019-12-16T11:25:05Z" level=error msg="backup failed" controller=backup error="[rpc error: code = Unknown desc = EOF, rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>]" key=velero/mip-playground-kubedb logSource="pkg/controller/backup_controller.go:233"
```

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.1.0
	Git commit: a357f21aec6b39a8244dd23e469cc4519f1fe608
<error getting server version: ServerStatusRequest.velero.io "velero-cli-mrzrj" is invalid: []: Invalid value: map[string]interface {}{"kind":"ServerStatusRequest", "apiVersion":"velero.io/v1", "metadata":map[string]interface {}{"generateName":"velero-cli-", "namespace":"velero", "creationTimestamp":"2019-12-16T11:11:30Z", "generation":1, "uid":"cfe033b1-1ff4-11ea-a004-14dda9d51862", "name":"velero-cli-mrzrj"}, "spec":map[string]interface {}{}, "status":map[string]interface {}{"plugins":interface {}(nil), "phase":"", "processedTimestamp":interface {}(nil), "serverVersion":""}}: validation failure list:
status.plugins in body must be of type array: "null"
status.processedTimestamp in body must be of type string: "null"
status.phase in body should be one of [New Processed]>
```
- Velero features (use `velero client config get features`): 
```
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
```
kubespray v2.8.3
```
- Cloud provider or hardware configuration:
```
bare metal hetzner
```
- OS (e.g. from `/etc/os-release`):
```
Container Linux by CoreOS 2303.3.0 (Rhyolite)   4.19.86-coreos
```
