### ISSUE TITLE
Update backup location (backupSyncPeriod)

### ISSUE THREAD

**Issue by doowb** [vmware-tanzu/velero#2260]
**Describe the problem/challenge you have**

I'd like to be able to update an existing backup location (specifically the `backupSyncPeriod` setting) through the command line. From what I can tell, the only option available is to `create` and `get` a backup location.

**Describe the solution you'd like**

I'd like to see a `velero backup-location update NAME --backup-sync-period=5m` command.

**Anything else you would like to add:**

I'm not familiar with exactly how the code might look for this, but I had seen the initial PR #1936 that adds the `backupSyncPeriod` to the backup location specs and when I saw it described as being able to "toggle" the syncing, I thought I'd be able to do that through the command line. If that is possible, I haven't been able to find an example of how to do that.

If the solution is to edit the kubernetes resource directly, I think I know the steps to do that, but I'm not positive. In that case, an example showing how to do that would be helpful.

**Environment:**

- Velero version (use `velero version`):
```
Client:
	Version: v1.2.0
	Git commit: -
Server:
	Version: v1.2.0
```

- Kubernetes version (use `kubectl version`):
```yaml
clientVersion:
  buildDate: "2020-01-08T18:09:13Z"
  compiler: gc
  gitCommit: 70132b0f130acc0bed193d9ba59dd186f0e634cf
  gitTreeState: clean
  gitVersion: v1.17.0
  goVersion: go1.13.5
  major: "1"
  minor: "17"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-07-08T08:38:54Z"
  compiler: gc
  gitCommit: 0c6d31a99f81476dfc9871ba3cf3f597bec29b58
  gitTreeState: clean
  gitVersion: v1.13.8
  goVersion: go1.11.5
  major: "1"
  minor: "13"
  platform: linux/amd64
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
