### ISSUE TITLE
AWS S3 server side encryption not working

### ISSUE THREAD

**Issue by bhvishal9** [vmware-tanzu/velero#2263]
**What steps did you take and what happened:**
We are running velero:1.2.0 docker image on Kubernetes and even though we added `serverSideEncryption` property to backup storage location as mentioned in velero documents, the backup data is not encrypted on S3. In the logs, it doesn't mention of SSE and says the backup completed successfully.

**What did you expect to happen:**
Expected the backups to be SSE-S3 encrypted.

**The output of the following commands will help us better understand what's going on**:
```
kubectl get backupstoragelocations.velero.io/default -o yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  config:
    region: XXXX
  objectStorage:
    bucket: XXXXX
    prefix: velero/exp/
    serverSideEncryption: AES256
  provider: aws
```

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.2.0
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): 1.15.7
- Kubernetes installer & version: kops 1.15.0
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):
