### ISSUE TITLE
InitContainer (aws and gcp) plugin in error state after pod restarts

### ISSUE THREAD

**Issue by DamianKusz** [vmware-tanzu/velero#2349]
**What steps did you take and what happened:**
We were using velero v1.1.0 installed from chart v2.1.9 and everything was fine. After upgrade and add the plugin that is reqired since velero v1.2.0, container starts with initContainers. Pod can be deleted and set up again without any errors. But after a day pod tries to restart itself and plugin declared in initContainers field is exitting with a code 1 and failing restart of pod.

**What did you expect to happen:**
Could you please help me fix the error during restart the pod that contains initContainer velero-plugin-for-[gcp,aws] ?

**Environment:**

`k get pods -n velero`
```
NAME                     READY   STATUS                  RESTARTS   AGE
restic-4gjg5             1/1     Running                 5          4d22h
restic-96l6r             1/1     Running                 3          4d22h
restic-qthjf             1/1     Running                 2          4d22h
restic-znhft             1/1     Running                 4          4d22h
restic-zwth5             1/1     Running                 3          4d22h
velero-cc7854967-5zh46   0/1     Init:CrashLoopBackOff   112        21h
```

`kubectl describe pod -n velero velero...` when pod is in  CrashLoopBackOff state:
```
...
Init Containers:
  velero-plugin-for-aws:
    Container ID:   docker://242b806c90b3fd45e1ac368ba4ee0a4b2b723ed63e4722fe2724a0e140926486
    Image:          velero/velero-plugin-for-aws:v1.0.1
    Image ID:       docker-pullable://velero/velero-plugin-for-aws@sha256:05a70b8d76b984e00696b55eced325d29c919a5cd62376667ad34a6e9d70167b
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 11 Mar 2020 08:39:04 +0100
      Finished:     Wed, 11 Mar 2020 08:39:04 +0100
    Ready:          False
    Restart Count:  91
    Environment:    <none>
    Mounts:
      /target from plugins (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from velero-token-n8sdb (ro)
Containers:
  velero:
    Container ID:  docker://008f75161cd926fb660bfd47301e17c6e984af2a367f2dca6be5e156e516fdab
    Image:         velero/velero:v1.3.0
    Image ID:      docker-pullable://velero/velero@sha256:db805ba1fb53cc53df9ce37962ef25c983e67cf00f491daf4540cb5b56e8fb0f
    Port:          8085/TCP
    Host Port:     0/TCP
    Command:
      /velero
    Args:
      server
    State:          Running
      Started:      Tue, 10 Mar 2020 12:41:23 +0100
    Ready:          True
    Restart Count:  2
    Environment:
      VELERO_SCRATCH_DIR:           /scratch
      VELERO_NAMESPACE:             velero (v1:metadata.namespace)
      AWS_SHARED_CREDENTIALS_FILE:  /credentials/cloud
    Mounts:
      /credentials from cloud-credentials (rw)
      /plugins from plugins (rw)
      /scratch from scratch (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from velero-token-n8sdb (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  cloud-credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  credentials-velero
    Optional:    false
  plugins:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  scratch:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  velero-token-n8sdb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  velero-token-n8sdb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                     From                  Message
  ----     ------   ----                    ----                  -------
  Warning  BackOff  77s (x2052 over 7h26m)  kubelet, ksa-w2.blue  Back-off restarting failed container
```

kubectl describe pod -n velero velero... when pod is set up (new or deleted and set up again after Init:CrashLoopBackOff state):
```
...
...
Init Containers:
  velero-plugin-for-gcp:
    Container ID:   docker://6a0a05c3c9fba651dad837d527433a798757b0fd30a51d6fbd5e19e0646b86c7
    Image:          velero/velero-plugin-for-gcp:v1.0.1
    Image ID:       docker-pullable://velero/velero-plugin-for-gcp@sha256:f702315fe8b97226e06231315adc68c0459d749bc146702ff8e985302f7bafd7
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 11 Mar 2020 11:20:31 +0100
      Finished:     Wed, 11 Mar 2020 11:20:32 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /target from plugins (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from velero-token-twg7g (ro)
Containers:
  velero:
    Container ID:  docker://f28955adc52c1f24fd8007244379cd8722217183a8ac1c15240155668dd6573f
    Image:         velero/velero:v1.3.0
    Image ID:      docker-pullable://velero/velero@sha256:db805ba1fb53cc53df9ce37962ef25c983e67cf00f491daf4540cb5b56e8fb0f
    Port:          <none>
    Host Port:     <none>
    Command:
      /velero
    Args:
      server
    State:          Running
      Started:      Wed, 11 Mar 2020 11:20:34 +0100
    Ready:          True
    Restart Count:  0
    Environment:
      VELERO_SCRATCH_DIR:              /scratch
      VELERO_NAMESPACE:                velero (v1:metadata.namespace)
      GOOGLE_APPLICATION_CREDENTIALS:  /credentials/cloud
    Mounts:
      /credentials from cloud-credentials (rw)
      /plugins from plugins (rw)
      /scratch from scratch (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from velero-token-twg7g (ro)

```

K8s version: 1.16.7
Declaration of Helm (v2.16.3) release:
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  releaseName: velero
  chart:
    repository: https://vmware-tanzu.github.io/helm-charts/
    name: velero
    version: 2.9.1
  values:
    # Details of the container image to use in the Velero deployment & daemonset (if
    # enabling restic). Required.
    image:
      repository: velero/velero
      tag: v1.3.0
      pullPolicy: IfNotPresent

    initContainers:
    - image: velero/velero-plugin-for-aws:v1.0.1
      imagePullPolicy: IfNotPresent
      name: velero-plugin-for-aws
      volumeMounts:
      - mountPath: /target
        name: plugins

    metrics:
      enabled: true
      scrapeInterval: 30s
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        prometheus.io/path: "/metrics"

      serviceMonitor:
        enabled: false

    configuration:
      provider: aws #(on other cluster we are using gcp - problem is the same)
      backupStorageLocation:
        name: aws
        bucket: velero
        prefix:
        config: #( on other clusters if provider is gcp, we have config field empty.)
          region: minio
          s3ForcePathStyle: "true"
          s3Url: http://ksa-m1.blue:31311
      volumeSnapshotLocation:
        name: aws
        config:
          region: minio
    rbac:
      create: true
    serviceAccount:
      server:
        create: true
        name: velero
    credentials:
      useSecret: true
      existingSecret: "secret that exists"
      secretContents: {}
    snapshotsEnabled: true
    deployRestic: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
    schedules:
      some_schedules
```

**Anything else you would like to add:**
Logs from initContainer looks like it is internal problem
```
# k logs -n velero velero-cc7854967-dlj7b -c velero-plugin-for-gcp
cp: cannot create regular file '/target/./velero-plugin-for-gcp': Text file busy
```
