### ISSUE TITLE
Unable to install ca-certificate package on arm builds

### ISSUE THREAD

**Issue by xUnholy** [vmware-tanzu/velero#2466]
I'm deploying velero via helm-operator, I'm using the GCP plugin and during the `/velero server` container command I find the below error occurring. I'm not sure if the error is because of TLS or the backup store location.

I'm using v2.9.15 of the helm chart.

```An error occurred: some backup storage locations are invalid: backup store for location "gcp" is invalid: rpc error: code = Unknown desc = Get "https://storage.googleapis.com/storage/v1/b/raspbernetes-velero-backups/o?alt=json&delimiter=%2F&pageToken=&prefix=&prettyPrint=false&projection=full&versions=false": oauth2: cannot fetch token: Post "https://oauth2.googleapis.com/token": x509: certificate signed by unknown authority```

My helm release config looks as follows:

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: velero
  helmVersion: v3
  chart:
    repository: https://vmware-tanzu.github.io/helm-charts
    name: velero
    version: 2.9.15
  values:
    credentials:
      existingSecret: cloud-credentials
    configuration:
      provider: gcp
      backupStorageLocation:
        name: gcp
        bucket: raspbernetes-velero-backups
      volumeSnapshotLocation:
        name: gcp
    initContainers:
      - name: velero-plugin-for-gcp
        image: raspbernetes/velero-gcp-plugin:v1.0.1
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /target
            name: plugins
    schedules:
      daily-backup:
        schedule: '*/30 * * * *'
        template:
          ttl: '120h'
```
