### ISSUE TITLE
Non cluster-admin role for velero service account.

### ISSUE THREAD

**Issue by fajarbl** [vmware-tanzu/velero#2658]
**Describe the problem/challenge you have**
Hi, is there any way to run velero without cluster-admin role for its service account ? 
We feel it's just too broad to implement a workload with cluster-admin role even though its main purposes are to make manifest / cluster configuration backup. Or is there any way to make sure that there are no destructive operation that could impact existing workload if we're using that role ? 

**Describe the solution you'd like**
A non cluster-admin role for velero service account & docs / guide on how to setup this. 

**Anything else you would like to add:**
Nope. But if that is already possible on v.1.3.2, a docs / guide would be great tho. I don't find it anywhere on https://velero.io/docs/v1.3.2/

**Environment:**

- Velero version (use `velero version`): 1.3.2
- Kubernetes version (use `kubectl version`): 1.15+
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: Google ( GKE )
- OS (e.g. from `/etc/os-release`): Container Optimized OS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
Hi @fajarbl, this is definitely a legitimate concern!

To that end, we have docs at https://velero.io/docs/v1.4/rbac/ (a similar page exists for 1.3.2) for turning the Velero service account's permissions to something more restricted. You should be able to find them with the docs search function, though I don't think it's in the documentation's table of contents.

Do note that if you do so, you may not be able to back up or restore certain resources, based on the permissions that are put in place.

**Comment by ChrHan** [comment]
Hi @nrb , I've looked at the [link](https://velero.io/docs/v1.4/rbac/) you posted and it seems that the list of permission is incomplete:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: YOUR_NAMESPACE_HERE
  name: ROLE_NAME_HERE
  labels:
    component: velero
rules:
  - apiGroups:
      - velero.io
    verbs:
      - "*"
    resources:
      - "*"
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ROLEBINDING_NAME_HERE
subjects:
  - kind: ServiceAccount
    name: YOUR_SERVICEACCOUNT_HERE
roleRef:
  kind: Role
  name: ROLE_NAME_HERE
  apiGroup: rbac.authorization.k8s.io
```

There were only `Role` and `RoleBinding`; do we need `ClusterRole` and `ClusterRoleBinding` too? if yes, what kind of permissions are needed?
