### ISSUE TITLE
Add initContainers to Restore spec

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2729]
Add an `initContainers` field to the `Restore` spec similar to this example taken from the design doc:

```yaml
apiVersion: velero.io/v1
kind: Restore
spec:
  ...
  hooks:
    resources:
      -
        name: my-hook
        includedNamespaces:
        - '*'
        excludedNamespaces:
        - some-namespace
        includedResources:
        - pods
        excludedResources: []
        labelSelector:
          matchLabels:
            app: velero
            component: server
        post:
          -
            exec:
              container: postgres
              command:
                - /bin/bash
                - -c
                - rm /docker-entrypoint-initdb.d/dump.sql
              onError: Fail
              timeout: 10s
              readyTimeout: 60s
        init:
          timeout: 120s
          initContainers:
          - name: restore
            image: postgres:12
            command: ["/bin/bash", "-c", "mv /backup/dump.sql /docker-entrypoint-initdb.d/"]
            volumeMounts:
            - name: backup
              mountPath: /backup
```
