### ISSUE TITLE
restore with override ( e.g: change the replica when restoring )

### ISSUE THREAD

**Issue by panpan0000** [vmware-tanzu/velero#2892]
**Describe the problem/challenge you have**
In a DR/migration scenario , the backup cluster resources are smaller than the main cluster, in most cases.
So, we have to **change the deployment's replica, likely from 10 to 2**.
aka, in original cluster, the replica = 10, but in new cluster , the replica should be 2, because the new cluster is smaller.
it's very practical when jumping  into DR territory.
so far, only the storage-class and pvc-node-selector can be "override" when migrating.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Adding **annotation** to a "restore" resource( maybe we can learn from kasten K10) likely "resource-override: <old-replica>:<new-replica>"

or we can make it more general purpose(not only replica) as below , adding `override` as below example restore yaml.
```
apiVersion: velero.io/v1
kind: Restore
metadata:
....
spec:
  backupName: default-backup
  override:
      spec.replicas:
         old_value: 10
         new_value: 2
      spec.template.dnsPolicy:
         old_value: ClusterFirst
         new_value: default
```
   

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
very looking forward to your reply.
Below are snapshot from K10. maybe we can learn sth. from it.

![image](https://user-images.githubusercontent.com/14049268/91972828-d16bf780-ed4d-11ea-9fa1-634b92bfa21c.png)
![image](https://user-images.githubusercontent.com/14049268/91972857-dc268c80-ed4d-11ea-9e1a-2abcfc4e9350.png)

**Environment:**

- Velero version (use `velero version`):v1.4.2
- Kubernetes version (use `kubectl version`):1.18 
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: bearmetal
- OS (e.g. from `/etc/os-release`): centos

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"
