### ISSUE TITLE
Changing PV/PVC Storage Classes

### ISSUE THREAD

**Issue by svua** [vmware-tanzu/velero#2894]
**What steps did you take and what happened:**
https://velero.io/docs/v1.4/restore-reference/
Changing PV/PVC Storage Classes doesn't work

```
velero install \
     --provider aws \
     --plugins velero/velero-plugin-for-aws:v1.0.0 \
     --bucket velero \
     --secret-file ./credentials-velero \
     --use-volume-snapshots=false \
     --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://10.233.23.101:9000 \
     --use-restic
```

```
k get sc
NAME                        PROVISIONER                                                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-disks                 kubernetes.io/no-provisioner                               Delete          WaitForFirstConsumer   false                  59d
openebs-cstor-r1            openebs.io/provisioner-iscsi                               Delete          Immediate              false                  26d
openebs-cstor-r3            openebs.io/provisioner-iscsi                               Delete          Immediate              false                  28d
openebs-hostpath            openebs.io/local                                           Delete          WaitForFirstConsumer   false                  34d
openebs-snapshot-promoter   volumesnapshot.external-storage.k8s.io/snapshot-promoter   Delete          Immediate              false                  34d
```

```
k -n jenkins-01 get pvc |grep jenkins
jenkins                                                                                                  Bound     local-pv-c455eb27                          15Gi       RWO            local-disks        28m
```

```
cat change-storage-class-config.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  # any name can be used; Velero uses the labels (below)
  # to identify it rather than the name
  name: change-storage-class-config
  # must be in the velero namespace
  namespace: velero
  # the below labels should be used verbatim in your
  # ConfigMap.
  labels:
    # this value-less label identifies the ConfigMap as
    # config for a plugin (i.e. the built-in restore item action plugin)
    velero.io/plugin-config: ""
    # this label identifies the name and kind of plugin
    # that this ConfigMap is for.
    velero.io/change-storage-class: RestoreItemAction
data:
  # add 1+ key-value pairs here, where the key is the old
  # storage class name and the value is the new storage
  # class name.
  local-disks: openebs-cstor-r3
```

```
k -n velero create cm change-storage-class-config --from-file=change-storage-class-config.yaml
configmap/change-storage-class-config created
```

```
velero backup create jenkins-01 --include-namespaces jenkins-01
Backup request "jenkins-01" submitted successfully.
Run `velero backup describe jenkins-01` or `velero backup logs jenkins-01` for more details.
```

```
velero backup get
NAME         STATUS      ERRORS   WARNINGS   CREATED                          EXPIRES   STORAGE LOCATION   SELECTOR
jenkins-01   Completed   0        0          2020-09-02 15:21:42 +0300 EEST   29d       default            <none>
```

**If we have free PV**

```
velero restore create jenkins-02 --from-backup jenkins-01 --namespace-mappings jenkins-01:jenkins-02
Restore request "jenkins-02" submitted successfully.
Run `velero restore describe jenkins-02` or `velero restore logs jenkins-02` for more details.
```

```
velero restore get
NAME         BACKUP       STATUS      ERRORS   WARNINGS   CREATED                          SELECTOR
jenkins-02   jenkins-01   Completed   0        9          2020-09-02 15:27:27 +0300 EEST   <none>
```

```
k get pvc -n jenkins-02 |grep jenkins
jenkins                                                                                                  Bound     local-pv-29fbea2d                          20Gi       RWO          
 local-disks        75s
```

**If we don't have free PV, the process hangs in a InProgress state**

```
velero restore create jenkins-03 --from-backup jenkins-01 --namespace-mappings jenkins-01:jenkins-03

velero restore get
NAME         BACKUP       STATUS       ERRORS   WARNINGS   CREATED                          SELECTOR
jenkins-02   jenkins-01   Completed    0        9          2020-09-02 15:27:27 +0300 EEST   <none>
jenkins-03   jenkins-01   InProgress   0        0          2020-09-02 15:37:21 +0300 EEST   <none>


k get pvc -n jenkins-03 |grep jenkins
jenkins                                                                                                  Pending                                                                        local-disks        3m53s

```

**What did you expect to happen:**
Change STORAGECLASS according to the change-storage-class-config.yaml config

**The output of the following commands will help us better understand what's going on**:
```
velero backup describe jenkins-01
Name:         jenkins-01
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.18.3
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18

Phase:  Completed

Errors:    0
Warnings:  0

Namespaces:
  Included:  jenkins-01
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-09-02 15:21:42 +0300 EEST
Completed:  2020-09-02 15:23:36 +0300 EEST

Expiration:  2020-10-02 15:21:42 +0300 EEST

Total items to be backed up:  463
Items backed up:              463

Velero-Native Snapshots: <none included>

Restic Backups (specify --details for more information):
  Completed:  6
```
**Environment:**

- Velero version (use `velero version`): 
```
Client:
        Version: v1.4.2
        Git commit: 56a08a4d695d893f0863f697c2f926e27d70c0c5
Server:
        Version: v1.4.2
```

- Velero features (use `velero client config get features`): 
`features: <NOT SET>`
- Kubernetes version (use `kubectl version`):
```
k version 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
baremetal nodes
- OS (e.g. from `/etc/os-release`):
```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
