### ISSUE TITLE
Support subPath for volume backups

### ISSUE THREAD

**Issue by beegee1** [vmware-tanzu/velero#2908]
**Describe the problem/challenge you have**
Velero can backup Pod volumes by specifying annotations (backup.velero.io/backup-volumes) in the Pod spec. We're using the same PV/PVC for different services except the subPath is different for each service when mounting the volume.  https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath We cannot simply specify this volume because it holds many other data.
This means, we need to copy the files which were specific to the current service to a separate backup volume (type EmptyDir) first. The backup volume is specified in the annotation. In the restore case we need to copy the data back from the backup volume.

**Describe the solution you'd like**
The possibility to specify the subPath using a Pod annotation what exactly of the volume should be included in the backup.

**Environment:**

- Velero version (use `velero version`): 1.4
- Kubernetes version (use `kubectl version`): 1.16

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by beegee1** [comment]
Can I work on this during the Hacktoberfest event (in October)? Do you think such a feature would be OK from your side? Would be great if someone could give me some hints how it should be implemented?

**Comment by kvzn** [comment]
@eleanor-millman If we attach a PV to a pod, and map subPaths to different paths as below, we can't use velero to backup the volume successfully:

```yaml
          volumeMounts:
            - mountPath: /usr/share/nginx/repo
              name: repo-storage
              subPath: repo
            - mountPath: /usr/share/nginx/beta
              name: repo-storage
              subPath: beta
            - mountPath: /usr/share/nginx/downloads
              name: repo-storage
              subPath: downloads
```
