### ISSUE TITLE
Not able to restore EFS volumes using restic

### ISSUE THREAD

**Issue by vaishali-prophecy** [vmware-tanzu/velero#2958]
Backup is completed successfully as can be seen here - 
```Restic Backups:
  Completed:
    xyz/app-xyz-64b9cdb6cb-tbbn8: app-common-volume, app-log-volume```

But while restore, the PVCs are stuck in pending state - 

`Name:          app-common-volume-pvc
Namespace:     xyz
StorageClass:  efs-sc
Status:        Pending
Volume:
Labels:        prophecy.io/cluster=prophecydev
               prophecy.io/component=app
               prophecy.io/controlplane=xyz
               prophecy.io/logconfmapversion=1659308
               velero.io/backup-name=xyz-backup2
               velero.io/restore-name=xyz-backup2-20200921165054
Annotations:   volume.beta.kubernetes.io/storage-provisioner: efs.csi.aws.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    app-xyz-64b9cdb6cb-tbbn8
Events:
  Type    Reason                Age                  From                         Message
  ----    ------                ----                 ----                         -------
  Normal  ExternalProvisioning  64s (x202 over 51m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "efs.csi.aws.com" or manually created by system administrator`

Not sure why it doesnt get created on its own when PV  resource itself is part of backup

**Comment by nrb** [comment]
@vaishali-prophecy Thanks for the report, that is definitely unusual.

Can you provide the YAML of the PV resource and the PV's storage class?

Also, what version of Velero and Kubernetes are you using?

**Comment by vaishali-prophecy** [comment]
Hi @nrb ,

Yaml for the PV resource - 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    prophecy.io/cluster: prophecydev
    prophecy.io/component: efs
    pvselector: app-common-volume-aaa
    velero.io/backup-name: aaa-backup
  name: app-app-common-volume-aaa
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: app-common-volume-pvc
    namespace: aaa
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-e2900360:/aaa/app/app/common
  persistentVolumeReclaimPolicy: Delete
  storageClassName: efs-sc
  volumeMode: Filesystem
```

Yaml for storage class - 

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: vish
    meta.helm.sh/release-namespace: prophecy
  creationTimestamp: "2020-09-17T15:35:23Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: efs-sc
  resourceVersion: "388862"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/efs-sc
  uid: df3f7a5b-55e0-4e73-ba35-236c6b9d06d2
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

Version of velero - 1.4
K8s version - 1.16

Note that PV resource itself isn't restored on restore action  for the PVCs which are marked in pod annotation.

**Comment by vaishali-prophecy** [comment]
@nrb Hey could you figure out the issue or any other information is needed?

**Comment by vaishali-prophecy** [comment]
@nrb Any updates on this?

**Comment by vaishali-prophecy** [comment]
@nrb Could it be RCA'ed?

**Comment by vaishali-prophecy** [comment]
@nrb @ncdc @carlisia @jwhitcraft ?

**Comment by nrb** [comment]
@vaikas Please realize that we're trying to get to as many requests as we can, but we're not able to get to them all immediately.

Also, I'm not sure what `RCA'd` means in this context.

Are you using restic to back up this volume? If using restic on a volume with a `delete` ReclaimPolicy, Velero will not restore the PV object itself, but rather dynamically provision an empty volume to restore the data into. Then, the pod is restored and Velero uses an initContainer inside of the pod to do the restic restore.

We may be seeing an order of operations issue here if it's restic, and this is probably something we need to look into.

**Comment by vaishali-prophecy** [comment]
@nrb Yes I am using restic. I dont see any dynamically provisioned volume and with ReclaimPolicy as Retain, I see other issues being reported. So what kind of EFS volumes can we actually restore with restic?

**Comment by nrb** [comment]
Based on the message `waiting for a volume to be created, either by external provisioner "efs.csi.aws.com"`, the EFS CSI driver hasn't yet created the volume.

Doing some Googling, as I'm not familiar with the driver, I came across [their documentation](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html) which states

> Only static volume provisioning is supported. This means that an Amazon EFS file system needs to be created outside of Amazon EKS before being used by pods in your cluster.

Docs in https://github.com/kubernetes-sigs/aws-efs-csi-driver state this, too. So it appears AWS has changed how EFS is provisioned and we need to revisit how it's approached in Velero; this is going to require some research on our part.

**Comment by vaishali-prophecy** [comment]
@nrb So to fix problem for now, in case the policy is Retain, how can i go about it?

**Comment by vaishali-prophecy** [comment]
Looks like as per https://github.com/vmware-tanzu/velero/pull/1713, PVs are dynamically reprovisioned irrespective of ReclaimPolicy. Am i right?

**Comment by vaikas** [comment]
@nrb I assume I was mentioned here by accident? If not, is there something that I need to do here?

https://github.com/vmware-tanzu/velero/issues/2958#issuecomment-701496524

**Comment by headyj** [comment]
I'm also facing the same problem. @vaishali-prophecy as a workaround, you can create the PV by hand, just be sure to correctly setup the PV name, PVC namespace and name, as well as volumeHandle parts (for example using aws efs):
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: <pv-name>
spec:
  capacity:
    storage: 1Gi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: 'fs-97aabd66::fsap-093ef92278dedc73c'
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: <claim-namespace>
    name: <claim-name>
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-storage-class
  volumeMode: Filesystem
```

Then you can run the restore process and everything should work fine.
