### ISSUE TITLE
velero backup create ignore --volume-snapshot-locations 

### ISSUE THREAD

**Issue by survivant** [vmware-tanzu/velero#3082]
I'm trying to create a backup wth Velero/Minio/Openebs

````
velero backup create before-disaster5 --include-namespaces rocketchat --storage-location aws --snapshot-volumes --volume-snapshot-locations=minio
````

but I see this in the logs : 

````
time="2020-11-16T15:43:02Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/before-disaster5 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:76" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:449" name=pvc-236ccb00-f35b-4428-9630-3bf577144a59 namespace= persistentVolume=pvc-236ccb00-f35b-4428-9630-3bf577144a59 resource=persistentvolumes volumeSnapshotLocation=default
````

**Environment:**

````
root@test-pcl114:~/openebs-test/velero-plugin/example# velero version
Client:
        Version: v1.5.2
        Git commit: e115e5a191b1fdb5d379b62a35916115e77124a4
Server:
        Version: v1.5.2
root@test-pcl114:~/openebs-test/velero-plugin/example#
````

Here the setup that I used  for Velero: 

````
velero.yaml	
	
configuration:
  provider: aws
  backupStorageLocation:
    name: aws
    bucket: velero
    config:
      region: minio
      s3ForcePathStyle: true
      publicUrl: http://10.1.7.230:9000
      s3Url: http://minio.minio.svc:9000
credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = minion
      aws_secret_access_key = minio123
snapshotsEnabled: false
configMaps:
  restic-restore-action-config:
    labels:
      velero.io/plugin-config: ""
      velero.io/restic: RestoreItemAction
    data:
      image: gcr.io/heptio-images/velero-restic-restore-helper:v1.1.0
deployRestic: true

helm install velero vmware-tanzu/velero --create-namespace --namespace velero -f velero.yaml
helm upgrade velero vmware-tanzu/velero --namespace velero -f velero.yaml --set initContainers[0].name=velero-plugin-for-aws --set initContainers[0].image=velero/velero-plugin-for-aws:v1.1.0 --set initContainers[0].volumeMounts[0].mountPath=/target --set initContainers[0].volumeMounts[0].name=plugins 
````

here the setup for open-ebs plugin

````
velero plugin add openebs/velero-plugin:2.2.0

default-backup-storage-location.yaml 

apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: velero


kubectl create -f default-backup-storage-location.yaml 


minio-VolumeSnapshotLocation.yaml

apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: minio
  namespace: velero
spec:
  provider: openebs.io/cstor-blockstore
  config:
    bucket: velero
    prefix: cstor
    provider: aws
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://minio.minio.svc:9000
    insecureSkipTLSVerify: "true"
	
	
kubectl create -f minio-VolumeSnapshotLocation.yaml	
````

At this point I was expecting Velero to use the VolumeSnapshotLocation minio  and save the pvc information in the bucket velero.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kmova** [comment]
cc: @mynktl @vishnuitta

**Comment by survivant** [comment]
I found that, that I have a default : VolumeSnapshotLocation created by Helm.
````
root@test-pcl114:~/openebs-test/sample/openebs# kubectl get VolumeSnapshotLocation -n velero default -o yaml
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  creationTimestamp: "2020-11-16T15:40:56Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.13.6
  managedFields:
  - apiVersion: velero.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:helm.sh/hook: {}
          f:helm.sh/hook-delete-policy: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:helm.sh/chart: {}
      f:spec:
        .: {}
        f:provider: {}
    manager: Go-http-client
    operation: Update
    time: "2020-11-16T15:40:56Z"
  name: default
  namespace: velero
  resourceVersion: "62566336"
  selfLink: /apis/velero.io/v1/namespaces/velero/volumesnapshotlocations/default
  uid: 13efa455-7760-48c7-9a0c-72ab311d2049
spec:
  provider: aws
root@test-pcl114:~/openebs-test/sample/openebs#
````
Should I replace it by this ?

````
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: openebs.io/cstor-blockstore
  config:
    bucket: velero
    provider: aws
    region: minio
    s3Url: http://minio.minio.svc:9000
````

I'm trying to get you more details.  I'm stuck at create backup, I need to test the restore after that.

**Comment by ashish-amarnath** [comment]
@survivant 
So looks like you are trying to use the AWS volumesnapshotter plugin and wanting to store the snapshots in minio.
Is there an example that you are trying to follow? Can you please share a link to that example?

If you can also share what you are trying to accomplish, I can point you to the correct example or specific instructions.

**Comment by survivant** [comment]
I'll came back to you tomorrow morning with the examples that I try to follow.

basically I'm to backup/restore.  I have Velero + minio + OpenEBS.

- installed OpenEBS
- installed minio
- installed velero with aws plugin
- installed velero-openebs plugin

In my test I'm trying to backup "rocketchat" (my demo application).

I want to create a backup and save it into Minio bucket : velero 

after that I delete the namespace : rocketchat

and I'm trying to restore my backup.  I was told by OpenEbS team that I need the openebs plugin because there are few steps that need to be done for the PV/PVC.  When I try without the OpenEBS plugin.. the PV/PVC weren't created correctly and stuck in pending mode.


That's my usecase.

**Comment by survivant** [comment]
here one demo that I try to follow : https://blah.cloud/automation/using-velero-for-k8s-backup-and-restore-of-csi-volumes/

**Comment by nrb** [comment]
I think you'd need to have the OpenEBS plugin to do a VolumeSnapshotLocation. Minio would be a BackupSnapshotLocation.

The VolumeSnapshotLocation should be set up to use OpenEBS as the `provider`, since that field is used to look up the plugin to run.

**Comment by survivant** [comment]
I found those configuration also
````
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: local-default
  namespace: velero
spec:
  provider: openebs.io/cstor-blockstore
  config:
    # namespace -- namespace in which openebs is installed (default: openebs)
    namespace: openebs
    local: "true"
````
OU
````
minio-VolumeSnapshotLocation.yaml

apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: minio
  namespace: velero
spec:
  provider: openebs.io/cstor-blockstore
  config:
    bucket: velero
    prefix: cstor
    provider: aws
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://minio.minio.svc:9000
    insecureSkipTLSVerify: "true"
````	

not sure if that help..

**Comment by survivant** [comment]
I install Minio with this : 
````
helm install minio minio/minio --create-namespace --namespace minio --set accessKey=minio,secretKey=minio123,persistence.enabled=false,service.type=LoadBalancer
````

Velero
````
velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.0.0 \
    --bucket velero \
    --secret-file ./credentials-velero \
    --use-volume-snapshots=false \
    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://minio.velero.svc:9000 
	

velero.yaml	
	
configuration:
  provider: aws
  backupStorageLocation:
    name: aws
    bucket: velero
    config:
      region: minio
      s3ForcePathStyle: true
      publicUrl: http://10.1.7.230:9000
      s3Url: http://minio.minio.svc:9000
credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = minio
      aws_secret_access_key = minio123
snapshotsEnabled: false
configMaps:
  restic-restore-action-config:
    labels:
      velero.io/plugin-config: ""
      velero.io/restic: RestoreItemAction
    data:
      image: gcr.io/heptio-images/velero-restic-restore-helper:v1.1.0
deployRestic: true

helm install velero vmware-tanzu/velero --create-namespace --namespace velero -f velero.yaml
helm upgrade velero vmware-tanzu/velero --namespace velero -f velero.yaml --set initContainers[0].name=velero-plugin-for-aws --set initContainers[0].image=velero/velero-plugin-for-aws:v1.1.0 --set initContainers[0].volumeMounts[0].mountPath=/target --set initContainers[0].volumeMounts[0].name=plugins 

velero plugin add openebs/velero-plugin:2.2.0
````

**Comment by nrb** [comment]
The `local-default` one looks correct. The `minio` one looks invalid to me - the `openebs.io/cstor-blockstore` plugin doesn't use buckets, and the provider is specified twice (`spec.provider` and `spec.config.provider`)

I think what you want is a setup that looks like this:

The BackupStorageLocation (object storage, which is Minio)
```yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: velero
    prefix: cstor
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://minio.minio.svc:9000
    insecureSkipTLSVerify: "true"
```

The VolumeStorageLocation (where volume snapshots will get made)
```yaml
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  # default so that Velero will use this one by default
  name: default
  namespace: velero
spec:
  provider: openebs.io/cstor-blockstore
  config:
    # namespace -- namespace in which openebs is installed (default: openebs)
    namespace: openebs
    local: "true"
```

**Comment by nrb** [comment]
Looking at the installation values, are you trying to use restic for your volumes? restic is a replacement for a VolumeSnapshotter, and if you're using restic you would not need a VolumeSnapshotLocation, or the OpenEBS snapshot plugin.

**Comment by nrb** [comment]
https://velero.io/docs/v1.5/restic/ is our page on how to use restic with Velero.

**Comment by survivant** [comment]
sorry I had to leave.  Time to make diner.   it's my first time playing with velero and openebs.  

at first, I didn't install OpenEBS plugin, but I got PVC stalled at pending.  Dev team from OpenEBS told me that I have to use the plugin, because the plugin added a initContainer that will do some work before restoring the backup (something like that).

maybe the docs were not up to date on there side.  There is someone in there team that is trying to reproduce the issue.  So far he had issue too.

**Comment by survivant** [comment]
I was trying to follow that tutorial : https://blah.cloud/automation/using-velero-for-k8s-backup-and-restore-of-csi-volumes/

and when I got the pvc at pending, I chatted with OpenEbs team on slack

**Comment by survivant** [comment]
there was a issue with my velero config with openebs.. and bugs in openebs plugins 2.3.0.

**Comment by ToanPV90** [comment]
> I was trying to follow that tutorial : https://blah.cloud/automation/using-velero-for-k8s-backup-and-restore-of-csi-volumes/
> 
> and when I got the pvc at pending, I chatted with OpenEbs team on slack

Hi all, I'm trying to follow that tutorial to backup and restore postgresql release on cluster. I'm using Velero + minio + OpenEBS localpv.
There are no issues with the backup procedure. I verified that the list of resources included all of the necessary resources. But a database was empty when I restored from the backup in a different namespace.

This is the values file for velero.

```
configuration:
  provider: aws
  backupStorageLocation:
    provider: aws
    bucket: tdas-bucket
    config:
      region: minio
      s3ForcePathStyle: true
      publicUrl: http://127.0.0.1:9000
      s3Url: http://minio.velero.svc.cluster.local:9000
credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = minio
      aws_secret_access_key = minio123
configMaps:
  restic-restore-action-config:
    labels:
      velero.io/plugin-config: ""
      velero.io/restic: RestoreItemAction
    data:
      image: velero/velero-restic-restore-helper:latest
snapshotsEnabled: false
deployRestic: true
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.0.0
    volumeMounts:
      - name: plugins
        mountPath: /target
  - name: openebs-velero-plugin
    image: openebs/velero-plugin:latest
    volumeMounts:
      - name:  plugins
        mountPath: /target
```

Additionally, I made sure the volumesnapshot report was empty. Is this reasonable in this circumstance? Thanks
