### ISSUE TITLE
ordered-resources has no effect on schedule

### ISSUE THREAD

**Issue by jemag** [vmware-tanzu/velero#3116]
**What steps did you take and what happened:**
Create backup using command:
```
velero create backup bs --ttl 72h --ordered-resources 'pods=monitoring/kube-prometheus-stack-grafana-6dc6f9ccdf-rth4x,monitoring/kube-prometheus-stack-kube-state-metrics-66789f8885-rd6wv,monitoring/kube-prometheus-stack-operator-6f65f78c4c-4ckcx,monitoring/kube-prometheus-stack-promet
heus-node-exporter-6l2kp,monitoring/prometheus-kube-prometheus-stack-prometheus-0,monitoring/prometheus-msteams-68dffb4b4-zzwtz,monitoring/alertmanager-kube-prometheus-stack-alertmanager-0' --include-namespaces=monitoring
```
Notice backup properly contains orderedResources:
``` yaml
OrderedResources:
  pods: monitoring/kube-prometheus-stack-grafana-6dc6f9ccdf-rth4x,monitoring/kube-prometheus-stack-kube-state-metrics-66789f8885-rd6wv,monitoring/kube-prometheus-stack-operator-6f65f78c4c-4ckcx,monitoring/kube-prometheus-stack-prometheus-node-exporter-6l2kp,monitoring/prometheus-kube-pr
ometheus-stack-prometheus-0,monitoring/prometheus-msteams-68dffb4b4-zzwtz,monitoring/alertmanager-kube-prometheus-stack-alertmanager-0

```

Create schedule with similar command
```
velero create schedule bs --schedule="@every 1h" --ttl 72h --ordered-resources 'pods=monitoring/kube-prometheus-stack-grafana-6dc6f9ccdf-rth4x,monitoring/kube-prometheus-stack-kube-state-metrics-66789f8885-rd6wv,monitoring/kube-prometheus-stack-operator-6f65f78c4c-4ckcx,monitoring/kub
e-prometheus-stack-prometheus-node-exporter-6l2kp,monitoring/prometheus-kube-prometheus-stack-prometheus-0,monitoring/prometheus-msteams-68dffb4b4-zzwtz,monitoring/alertmanager-kube-prometheus-stack-alertmanager-0' --include-namespaces=monitoring
```
Notice schedule has no mention of ordered resources
``` yaml
Name:         bs
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:  Enabled

Schedule:  @every 1h

Backup Template:
  Namespaces:
    Included:  monitoring
    Excluded:  <none>

  Resources:
    Included:        *
    Excluded:        <none>
    Cluster-scoped:  auto

  Label selector:  <none>

  Storage Location:

  Velero-Native Snapshot PVs:  auto

  TTL:  72h0m0s

  Hooks:  <none>

Last Backup:  2020-11-26 12:02:35 -0500 EST
```
and 
``` yaml
Name:         bs
Namespace:    velero
Labels:       <none>
Annotations:  <none>
API Version:  velero.io/v1
Kind:         Schedule
Metadata:
  Creation Timestamp:  2020-11-26T17:02:35Z
  Generation:          3
  Managed Fields:
    API Version:  velero.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:schedule:
        f:template:
          .:
          f:hooks:
          f:includedNamespaces:
          f:ttl:
      f:status:
    Manager:      velero
    Operation:    Update
    Time:         2020-11-26T17:02:35Z
    API Version:  velero.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:lastBackup:
        f:phase:
    Manager:         velero-server
    Operation:       Update
    Time:            2020-11-26T17:02:35Z
  Resource Version:  18170
  Self Link:         /apis/velero.io/v1/namespaces/velero/schedules/bs
  UID:               c0222a4e-b08b-4ed6-af60-cee12c6ce3f7
Spec:
  Schedule:  @every 1h
  Template:
    Hooks:
    Included Namespaces:
      monitoring
    Ttl:  72h0m0s
Status:
  Last Backup:  2020-11-26T17:02:35Z
  Phase:        Enabled
Events:         <none>
```
Backups created from schedule also do not mention ordered-resources
``` yaml
Name:         bs-20201126170235
Namespace:    velero
Labels:       velero.io/schedule-name=bs
              velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.18.10
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18

Phase:  Completed

Errors:    0
Warnings:  0

Namespaces:
  Included:  monitoring
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  72h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2020-11-26 12:02:35 -0500 EST
Completed:  2020-11-26 12:03:13 -0500 EST

Expiration:  2020-11-29 12:02:35 -0500 EST

Total items to be backed up:  167
Items backed up:              167

Velero-Native Snapshots:  3 of 3 snapshots completed successfully (specify --details for more information)

```
**What did you expect to happen:**
Schedule will create backups that consider the ordered-resources provided

**Environment:**

- Velero version (use `velero version`): 1.5.2
- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`): 1.18.10
- Cloud provider or hardware configuration: azure AKS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
