### ISSUE TITLE
Multiple velero deployments in single cluster

### ISSUE THREAD

**Issue by markmasl** [vmware-tanzu/velero#3117]
**What steps did you take and what happened:**
We are running two velero deployments in different namespaces in single GKE cluster. Each of the deployments have different storage provider configured. One of them uses gcp provider with google bucket and volume snapshot feature enabled, another one is using aws provider (s3 bucket) with restic enabled and disabled snapshot feature. The idea behind that is to locally backup all workloads+pv in google with 'velero-gcp' deployment using snapshots, but some of the workloads+pvs to backup with different provider (aws) with 'velero-aws' deployment and send data to AWS S3 with restic.

Velero deployments were installed and configured with helm2 charts 2.13.6.

The velero-gcp deployment which is configured with gcp provider and 'gcp-bucket' for some unknown reason constantly throws such error messages:
`{"backupstoragelocation":"aws-bucket","controller":"backupstoragelocation","error.message":"unable to locate ObjectStore plugin named velero.io/aws","level":"error","logSource":"pkg/controller/backupstoragelocation_controller.go:87","msg":"Error getting a backup store","time":"2020-11-27T15:52:24Z"} `

At the same time, velero-aws deployment, that is configured in different namespace with aws provider and aws-bucket throws similar errors as well:
`{"backupstoragelocation":"gcp-bucket","controller":"backupstoragelocation","error.message":"unable to locate ObjectStore plugin named velero.io/gcp","level":"error","logSource":"pkg/controller/backupstoragelocation_controller.go:87","msg":"Error getting a backup store","time":"2020-11-27T15:52:20Z"}`

However, it seams that both velero deployments are able to successfully backup data as desired, without any errors.

**What did you expect to happen:**
First of all, could you confirm or deny, that such configuration is supported, running multiple velero deployments in single cluster?
We are expecting that velero deployment in velero-gcp namespace should not be searching for backupstoragelocation and plugin that is configured for another velero deployment in different namespace.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero-gcp -n velero-gcp --tail 10`
```
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:58","msg":"Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available","time":"2020-11-30T09:40:50Z"}
{"backupstoragelocation":"aws-bucket","controller":"backupstoragelocation","error.message":"unable to locate ObjectStore plugin named velero.io/aws","level":"error","logSource":"pkg/controller/backupstoragelocation_controller.go:87","msg":"Error getting a backup store","time":"2020-11-30T09:40:50Z"}
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:120","msg":"No backup locations were ready to be verified","time":"2020-11-30T09:40:50Z"}
{"controller":"backupstoragelocation","level":"warning","logSource":"pkg/controller/backupstoragelocation_controller.go:161","msg":"The specified default backup location named \"gcp-bucket\" was not found; for convenience, be sure to create one or make another backup location that is available the default","time":"2020-11-30T09:40:50Z"}
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:58","msg":"Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available","time":"2020-11-30T09:40:50Z"}
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:120","msg":"No backup locations were ready to be verified","time":"2020-11-30T09:40:50Z"}
{"controller":"backupstoragelocation","level":"warning","logSource":"pkg/controller/backupstoragelocation_controller.go:161","msg":"The specified default backup location named \"gcp-bucket\" was not found; for convenience, be sure to create one or make another backup location that is available the default","time":"2020-11-30T09:40:50Z"}
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:58","msg":"Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available","time":"2020-11-30T09:41:28Z"}
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:58","msg":"Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available","time":"2020-11-30T09:41:28Z"}
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:120","msg":"No backup locations were ready to be verified","time":"2020-11-30T09:41:28Z"}
```
- `kubectl logs pod/velero-aws-74b494c779-tn2xh -n velero-aws --tail 10`
```
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:58","msg":"Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available","time":"2020-11-30T10:04:35Z"}
{"backupstoragelocation":"gcp-bucket","controller":"backupstoragelocation","error.message":"unable to locate ObjectStore plugin named velero.io/gcp","level":"error","logSource":"pkg/controller/backupstoragelocation_controller.go:87","msg":"Error getting a backup store","time":"2020-11-30T10:04:35Z"}
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:120","msg":"No backup locations were ready to be verified","time":"2020-11-30T10:04:35Z"}
{"controller":"backupstoragelocation","level":"warning","logSource":"pkg/controller/backupstoragelocation_controller.go:161","msg":"The specified default backup location named \"aws-bucket\" was not found; for convenience, be sure to create one or make another backup location that is available the default","time":"2020-11-30T10:04:35Z"}
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:58","msg":"Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available","time":"2020-11-30T10:04:35Z"}
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:120","msg":"No backup locations were ready to be verified","time":"2020-11-30T10:04:35Z"}
{"controller":"backupstoragelocation","level":"warning","logSource":"pkg/controller/backupstoragelocation_controller.go:161","msg":"The specified default backup location named \"aws-bucket\" was not found; for convenience, be sure to create one or make another backup location that is available the default","time":"2020-11-30T10:04:35Z"}
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:58","msg":"Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available","time":"2020-11-30T10:04:54Z"}
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:58","msg":"Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available","time":"2020-11-30T10:04:54Z"}
{"controller":"backupstoragelocation","level":"info","logSource":"pkg/controller/backupstoragelocation_controller.go:120","msg":"No backup locations were ready to be verified","time":"2020-11-30T10:04:54Z"}
```
- `velero get backup-locations -n velero-gcp -o yaml`
```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  creationTimestamp: "2020-11-27T15:21:08Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: velero-gcp
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.13.6
  name: gcp-bucket
  namespace: velero-gcp
  resourceVersion: "324818252"
  selfLink: /apis/velero.io/v1/namespaces/velero-gcp/backupstoragelocations/gcp-bucket
  uid: 0234a0bb-019a-48fe-af42-bfcb11bfdae2
spec:
  objectStorage:
    bucket: BUCKET_NAME_GCP
  provider: gcp
status:
  lastSyncedTime: "2020-11-30T10:06:35Z"
  lastValidationTime: "2020-11-30T10:06:36Z"
  phase: Available
```
- `velero get backup-locations -n velero-aws -o yaml`
```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  creationTimestamp: "2020-11-27T15:45:19Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: velero-aws
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.13.6
  name: aws-bucket
  namespace: velero-aws
  resourceVersion: "324821699"
  selfLink: /apis/velero.io/v1/namespaces/velero-aws/backupstoragelocations/aws-bucket
  uid: 0dad64ed-2317-4f15-8201-e5515d60592b
spec:
  config:
    region: REGION
  objectStorage:
    bucket: BUCKET_NAME_AWS
  provider: aws
status:
  lastSyncedTime: "2020-11-30T10:09:55Z"
  lastValidationTime: "2020-11-30T10:09:55Z"
  phase: Available
```
- `velero-gcp configuration`
```
initContainers:
   - name: velero-plugin-for-gcp
     image: velero/velero-plugin-for-gcp:v1.1.0
     imagePullPolicy: IfNotPresent
     volumeMounts:
       - mountPath: /target
         name: plugins

# Set provider name and backup storage location bucket name
configuration:
  provider: gcp
  backupStorageLocation:
    name: gcp-bucket
    bucket: BUCKET_NAME_GCP
  volumeSnapshotLocation:
    config:
      snapshotLocation: LOCATION
      project: PROJECT
  logFormat: json
  defaultBackupStorageLocation: gcp-bucket

# Set a service account so that the CRD clean up job has proper permissions to delete CRDs
serviceAccount:
  server:
    name: velero-gcp

snapshotsEnabled: true
deployRestic: false
```
- `velero-aws configuration`
```
initContainers:
   - name: velero-plugin-for-aws
     image: velero/velero-plugin-for-aws:v1.1.0
     imagePullPolicy: IfNotPresent
     volumeMounts:
       - mountPath: /target
         name: plugins

# Set provider name and backup storage location bucket name
configuration:
  provider: aws
  backupStorageLocation:
    name: aws-bucket
    bucket: BUCKET_NAME_AWS
    config:
      region: REGION
  logFormat: json
  defaultBackupStorageLocation: aws-bucket

# Set a service account so that the CRD clean up job has proper permissions to delete CRDs
serviceAccount:
  server:
    name: velero-aws

snapshotsEnabled: false
deployRestic: true
```
- `kubectl get pods -A -l app.kubernetes.io/name=velero­`
```
NAMESPACE    NAME                          READY   STATUS    RESTARTS   AGE
velero-aws   restic-6j4w8                  1/1     Running   0          2d19h
velero-aws   restic-75vhv                  1/1     Running   0          2d19h
velero-aws   restic-c7zx2                  1/1     Running   0          2d19h
velero-aws   restic-vctdx                  1/1     Running   0          2d19h
velero-aws   restic-xnkkc                  1/1     Running   0          2d19h
velero-aws   velero-aws-74b494c779-tn2xh   1/1     Running   0          2d19h
velero-gcp   velero-gcp-694f99bf46-9xxzz   1/1     Running   0          2d20h
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
```
$ velero version -n velero-gcp
Client:
        Version: v1.5.2
        Git commit: 456eb19668f8da603756353d9179b59b5a7bfa04
Server:
        Version: v1.5.2
```
```
$velero version -n velero-aws
Client:
        Version: v1.5.2
        Git commit: 456eb19668f8da603756353d9179b59b5a7bfa04
Server:
        Version: v1.5.2
```
- Velero features (use `velero client config get features`): 
```
$ velero client config get features -n velero-gcp
features: <NOT SET>
```
```
$ velero client config get features -n velero-aws
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.6300", GitCommit:"eb6985a7ebfd53457b0b91ba08fac07597bb87af", GitTreeState:"clean", BuildDate:"2020-09-15T09:20:11Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
`GKE`
- OS (e.g. from `/etc/os-release`):
```
BUILD_ID=12871.1196.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=c46f8a87c479cd2e964513992d3eab92eff5c160
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=81
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=81
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
ID=cos
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by carlisia** [comment]
I'm going to confirm this in a few, but pretty sure Velero installs some non-namespaced resources that would make this not possible/supported.

I do have a question for you: why did you go this route, as opposed to installing only 1 instance of the Velero deployment and configuring different BSL for the different providers you have?

**Comment by nrb** [comment]
@markmasl This is not something we support, though looking at the backupstoragelocation code, it _should_ only be looking within its namespace for BSLs.

One more thing I'd ask - what does `kubectl get deploy/velero -n velero-aws -o yaml` show for the `--default-backup-storage-location` value? Likewise for `kubectl get deploy/velero -n velero-gcp`. I'm wondering if the wires are simply crossed there.

**Comment by markmasl** [comment]
@carlisia We would really would like to go the easiest way. 
The idea was to separate stable and reliable way of backups (using cloud features - snapshots), from not so reliable, due to time, resource, bandwidth consumption (restic). Well, anyway I assume, that separation can be achieved by certain schedule options, without deploying multiple clusters.
But as far as I understand, currently, it is not supported to configure multiple providers with different creds (https://github.com/vmware-tanzu/velero/issues/1064), or please say that I'am wrong :)

**Comment by markmasl** [comment]
@nrb 
`-  kubectl get deploy/velero-gcp -n velero-gcp -o yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-11-12T14:57:21Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: velero-gcp
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.13.6
  name: velero-gcp
  namespace: velero-gcp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: velero-gcp
      app.kubernetes.io/name: velero
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: velero-gcp
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: velero
        helm.sh/chart: velero-2.13.6
        name: velero
    spec:
      containers:
      - args:
        - server
        - --log-format=json
        - --default-backup-storage-location=gcp-bucket
        command:
        - /velero
        env:
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: LD_LIBRARY_PATH
          value: /plugins
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /credentials/cloud
        image: velero/velero:v1.5.2
        imagePullPolicy: IfNotPresent
        name: velero
        ports:
        - containerPort: 8085
          name: monitoring
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /plugins
          name: plugins
        - mountPath: /credentials
          name: cloud-credentials
        - mountPath: /scratch
          name: scratch
      dnsPolicy: ClusterFirst
      initContainers:
      - image: velero/velero-plugin-for-gcp:v1.1.0
        imagePullPolicy: IfNotPresent
        name: velero-plugin-for-gcp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /target
          name: plugins
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: velero-gcp
      serviceAccountName: velero-gcp
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cloud-credentials
        secret:
          defaultMode: 420
          secretName: velero-gcp
      - emptyDir: {}
        name: plugins
      - emptyDir: {}
        name: scratch
```
`- kubectl get deploy/velero-aws -n velero-aws -o yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-11-27T15:45:10Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: velero-aws
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.13.6
  name: velero-aws
  namespace: velero-aws
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: velero-aws
      app.kubernetes.io/name: velero
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: velero-aws
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: velero
        helm.sh/chart: velero-2.13.6
        name: velero
    spec:
      containers:
      - args:
        - server
        - --log-format=json
        - --default-backup-storage-location=aws-bucket
        command:
        - /velero
        env:
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: LD_LIBRARY_PATH
          value: /plugins
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        image: velero/velero:v1.5.2
        imagePullPolicy: IfNotPresent
        name: velero
        ports:
        - containerPort: 8085
          name: monitoring
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /plugins
          name: plugins
        - mountPath: /credentials
          name: cloud-credentials
        - mountPath: /scratch
          name: scratch
      dnsPolicy: ClusterFirst
      initContainers:
      - image: velero/velero-plugin-for-aws:v1.1.0
        imagePullPolicy: IfNotPresent
        name: velero-plugin-for-aws
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /target
          name: plugins
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: velero-aws
      serviceAccountName: velero-aws
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cloud-credentials
        secret:
          defaultMode: 420
          secretName: velero-aws
      - emptyDir: {}
        name: plugins
      - emptyDir: {}
        name: scratch
```
