### ISSUE TITLE
Document how to substitute environment variables in pre/post hook

### ISSUE THREAD

**Issue by d3473r** [vmware-tanzu/velero#3118]
[carlisia] Update on 1/13: this became a task.

----
**What steps did you take and what happened:**
Create a backup of a mysql container with the hooks:
`pre.hook.backup.velero.io/command=["mysql", "--password=$MYSQL_ROOT_PASSWORD", "-e", "FLUSH TABLES WITH READ LOCK"]`
and
`post.hook.backup.velero.io/command=["mysql", "--password=$MYSQL_ROOT_PASSWORD", "-e", "UNLOCK TABLES"]`

velero describe gives me a PartiallyFailed backup and the logs are showing a wrong password:
` msg="stderr: mysql: [Warning] Using a password on the command line interface can be insecure.\nERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)\n"`
`hookCommand="[mysql --password=$MYSQL_ROOT_PASSWORD -e FLUSH TABLES WITH READ LOCK]"`

If I am running the hook with the password directly it works:
`pre.hook.backup.velero.io/command=["mysql", "--password=test123", "-e", "FLUSH TABLES WITH READ LOCK"]`
`msg="stderr: mysql: [Warning] Using a password on the command line interface can be insecure.\n"`
`hookCommand="[mysql --password=test123 -e FLUSH TABLES WITH READ LOCK]"`

**Anything else you would like to add:**

`MYSQL_ROOT_PASSWORD` is a required env in the mysql container (https://hub.docker.com/_/mysql) and is set in the container

```
root@mysql-84f87c85d6-skvfn:/# echo $MYSQL_ROOT_PASSWORD
test123
```

**Environment:**

- Velero version (use `velero version`): 
```
λ velero version
Client:
        Version: v1.5.2
        Git commit: e115e5a191b1fdb5d379b62a35916115e77124a4
Server:
        Version: v1.5.2
```
- Velero features (use `velero client config get features`): 
```
λ velero client config get features
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
λ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by paddy667** [comment]
While this may not be a resolution to the underlying issue of variable expansion. Here is a workaround for the specific issue regarding Mysql if some environment variables already exist in the pod that contain the password (very specfic I know but it might help someone on the right track).
```
    hooks:
      resources:
        <omitted>
        pre:
        - exec:
            command:
            - /bin/bash
            - -c
            - export MYSQL_PWD=${MYSQL_ROOT_PASSWORD} && /opt/rh/rh-mysql57/root/usr/bin/mysqldump
              --single-transaction -hsystem-mysql -uroot system > /var/lib/mysql/data/mysqldump
            container: system-mysql
            onError: Fail
            timeout: 30s
```

Basically: `export MYSQL_PWD=${MYSQL_ROOT_PASSWORD} && <cmd>`

**Comment by marrau** [comment]
Hi, i want to confirm the solution posted by @paddy667. It actually works that way.
I tested it with a mongodump, but instead of exporting the environment variable i just put the ```/bin/bash -c``` in front of it.

Before (substitution not working):
```
<omitted>
         pre:
          - exec:
              container: mongodb
              command:
                - mongodump 
                - -u 
                - root 
                - -p 
                - ${MONGODB_ROOT_PASSWORD} 
                - --gzip 
                - -o 
                - /bitnami/mongodb/backup
              onError: Fail
              timeout: 300s
```

After (substitution works):
```
<omitted>
         pre:
          - exec:
              container: mongodb
              command:
                - /bin/bash
                - -c
                - mongodump -u root -p ${MONGODB_ROOT_PASSWORD} --gzip -o /bitnami/mongodb/backup
              onError: Fail
              timeout: 300s
```

As explanation:
The command is executed as is, the same way kubernetes itself does it. So it does not run a shell but mysqldump (or mongodump in my case) directly. The argument with the environment variable is just an argument and the commands are not able to substitute it.
Instead of the mysqldump a shell must be started. The shell is capable of variable substitution. As the argument for the shell is the command we want to call and that´s what the shell is interpreting, it works.

**Comment by dsu-igeek** [comment]
@a-mccarthy Could you look at adding some info in the doc based on this workaround?  Thanks!

**Comment by blackpiglet** [comment]
@a-mccarthy 
After taking look at the issue, to me, @marrau comments https://github.com/vmware-tanzu/velero/issues/3118#issuecomment-797472702 is comprehensive.

The problem and solution is pretty straightforward, so I put my understand here. If anything is not clear, or other method for communication is needed, please notify me.

#### Problem description
Environment variable is pre-defined in Kubernetes pod already. The pre/post hook want to reference the environment variable in their command. 

For example, MYSQL_ROOT_PASSWORD is an environment variable defined in pod called "mysql". The pre hook want to reference MYSQL_ROOT_PASSWORD in command: 

``` yaml
<omitted>
         pre:
          - exec:
              container: mysql
              command:
                - /bin/sh
                - -c
                - mysql --password=$MYSQL_ROOT_PASSWORD -e "FLUSH TABLES WITH READ LOCK"
              onError: Fail
              timeout: 300s
```

#### Solution
Velero uses a streamer to run command on remote TTY. Because the streamer will not run a shell by default, the environments defined in pod will not be accessible, so specify the shell in command will resolve the issue.
Take the example above, the command is supposed to run in hook is "mysql --password=$MYSQL_ROOT_PASSWORD -e 'FLUSH TABLES WITH READ LOCK'", then add `"/bin/sh -c"` before the command will do the magic.

This solution has some limitations:
* Not all pods have shell integrated. If the pod supposed to run hook has no shell, this command will not work. I suggest not to use environment variable, put value in command instead.
* Even if the pod has shell, there are a lot of variations of shell. Users need to use the shell suits to their situation.
