### ISSUE TITLE
Support for IAM roles for service accounts in EKS

### ISSUE THREAD

**Issue by mihail-sky** [vmware-tanzu/velero#3143]
Hi, I'm wondering if velero supports [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html). In the readme the only two options mentioned are an AWS user and kube2iam.

**Comment by hector-guerrero** [comment]
Hi, I tested this with the latest version of velero (1.6) and the aws-plugin (1.2.0) for velero and it seems to be working

**Comment by jglick** [comment]
Working fine for me in `v1.21.2-eks-0389ca3`. `eksctl` definition snippet

```yaml
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: velero
      namespace: velero
    attachPolicyARNs:
    - arn:aws:iam::…:policy/…
```

pointing to a policy as in the current https://github.com/vmware-tanzu/velero-plugin-for-aws/tree/e8a22b0472eddc72ddb62decede2eae191c6ab59#set-permissions-for-velero. Helm chart snippet:

```yaml
serviceAccount:
  server:
    create: false
    name: velero
credentials:
  useSecret: false
```

**Comment by chivakaa** [comment]
> Working fine for me in `v1.21.2-eks-0389ca3`. `eksctl` definition snippet
> 
> ```yaml
> iam:
>   withOIDC: true
>   serviceAccounts:
>   - metadata:
>       name: velero
>       namespace: velero
>     attachPolicyARNs:
>     - arn:aws:iam::…:policy/…
> ```
> 
> pointing to a policy as in the current https://github.com/vmware-tanzu/velero-plugin-for-aws/tree/e8a22b0472eddc72ddb62decede2eae191c6ab59#set-permissions-for-velero. Helm chart snippet:
> 
> ```yaml
> serviceAccount:
>   server:
>     create: false
>     name: velero
> credentials:
>   useSecret: false
> ```

Thanks, following your notes and using helm chart v4.1.3:
https://artifacthub.io/packages/helm/vmware-tanzu/velero

Taking note of the OIDC arn of the cluster, I created a Role with trusted policy:

- Role: `"arn:aws:iam::<AWS_ACCOUNT>:role/velero-role"`
- Policy: https://github.com/vmware-tanzu/velero-plugin-for-aws/tree/e8a22b0472eddc72ddb62decede2eae191c6ab59#set-permissions-for-velero
- Trusted relationship:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<AWS_ACCOUNT>:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/<ID>"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-1.amazonaws.com/id/<ID>:sub": "system:serviceaccount:velero:velero-sa"
                }
            }
        }
    ]
}
```

Note that: "system:serviceaccount:velero:**velero-sa**" secret created over `velero` namespace should be defined on helm chart config. 

Following I update helm chart section, please remember use the same secret name `velero-sa`

```
serviceAccount:
  server:
    create: true
    name: velero-sa
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::<AWS_ACCOUNT>:role/velero-role"
credentials:
  useSecret: false
```

Deploy chart upgrade in case of existing running chart:
```
helm upgrade [RELEASE] vmware-tanzu/velero \
--namespace velero \
--dependency-update \
--description "YOUR DESCRIPTION" \
-f <chart_file>
```
Or execute new deploy if does not exist previous running chart:

```
helm install vmware-tanzu/velero \
--namespace velero \
--create-namespace \
--description "YOUR DESCRIPTION" \
-f <chart_file> \
--generate-name
```

Validate pod logs. In our deployment, is something similar to: 

```
time="2023-07-25T16:07:15Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:152"
time="2023-07-25T16:07:15Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:137"
```
