### ISSUE TITLE
support azure file snapshot

### ISSUE THREAD

**Issue by andyzhangx** [vmware-tanzu/velero#3151]
Currently azure cloud provide only supports azure disk snapshot, and [azure file plugin](https://kubernetes.io/docs/concepts/storage/volumes/#azurefile) is also a common storage layer which could provide multiple read/write.
Azure file snapshot doc:
https://docs.microsoft.com/en-us/azure/storage/files/storage-snapshots-files

@rosskukulinski 

I could also do the code review work of all azure part since I have been working on k8s on azure storage for a long time.

**Comment by felfa01** [comment]
Do you have an update on this much sought-after feature? Would be great to understand the timeline for when this becomes available.

**Comment by IQNeoXen** [comment]
Any news on this? Would be really nice to have this implemented

**Comment by rajeevpnair** [comment]
Any update on this ? we are really looking for an option to do csi snapshot backups for azure files..

**Comment by reasonerjt** [comment]
@ywk253100 probably this can be handled by CSI plugin?  Could you verify?

**Comment by andyzhangx** [comment]
> @ywk253100 probably this can be handled by CSI plugin? Could you verify?

azure file csi driver only supports snapshot, while does not support restore since current azure file API only supports in-place restore, not CSI spec compliant way, here is the tracking issue: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/136

**Comment by reasonerjt** [comment]
@andyzhangx 
But I believe eventually this has to be resolved in 1.27?   Could you share some insights?

**Comment by davidkarlsen** [comment]
It's been a while - any update @andyzhangx?
And would this work when you use:
```yaml
parameters:
  protocol: nfs
```
in the storage-class?

Is azure-files still a thing or being killed in favour of NetApp given that there is no movement?

**Comment by andyzhangx** [comment]
> It's been a while - any update @andyzhangx? And would this work when you use:
> 
> ```yaml
> parameters:
>   protocol: nfs
> ```
> 
> in the storage-class?
> 
> Is azure-files still a thing or being killed in favour of NetApp given that there is no movement?

@davidkarlsen there is a way to support smb file share restore using azcopy, here is a draft PR: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1466, and for nfs file share, the snapshot feature is only supported on Azure canary region now

**Comment by draghuram** [comment]
Just a quick note to add that at CloudCasa, we implemented a work around where we used Azure APIs to directly read from the snapshot, instead of depending on CSI. This is used in couple of places: For backups, we take CSI snapshot first and then using our work around, we get the data from snapshot and copy to S3. Similar logic is used for restores as well. So for end users, it looks seamless though it would have been much better had CSI "volume from snapshot" is implemented. 

From what I hear, the problem is not with the CSI driver but with the underlying Azure Files functionality itself. If that is the case, I doubt we will have this feature implemented any time soon, though I could be wrong.

**Comment by maulik13** [comment]
> > It's been a while - any update @andyzhangx? And would this work when you use:
> > ```yaml
> > parameters:
> >   protocol: nfs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the storage-class?
> > Is azure-files still a thing or being killed in favour of NetApp given that there is no movement?
> 
> @davidkarlsen there is a way to support smb file share restore using azcopy, here is a draft PR: [kubernetes-sigs/azurefile-csi-driver#1466](https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1466), and for nfs file share, the snapshot feature is only supported on Azure canary region now

Is the mentioned PR going to be merged any time soon?

**Comment by andyzhangx** [comment]
> > > It's been a while - any update @andyzhangx? And would this work when you use:
> > > ```yaml
> > > parameters:
> > >   protocol: nfs
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > in the storage-class?
> > > Is azure-files still a thing or being killed in favour of NetApp given that there is no movement?
> > 
> > 
> > @davidkarlsen there is a way to support smb file share restore using azcopy, here is a draft PR: [kubernetes-sigs/azurefile-csi-driver#1466](https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1466), and for nfs file share, the snapshot feature is only supported on Azure canary region now
> 
> Is the mentioned PR going to be merged any time soon?

@maulik13 we are still reviewing the azcopy design.

**Comment by felfa01** [comment]
Given that AzureFile NFS supports Snapshots, is this something that can be supported from Velero side?

**Comment by draghuram** [comment]
Velero can even today take snapshot of AzureFile PVCs. The problem is that restore cannot be supported because AzureFile CSI driver doesn't support creation of a PVC from snapshot. For the same reason, snapshot data mover backups won't work either. We, at CloudCasa, have added workaround by directly interacting with Azure Portal and thus, supporting both.

**Comment by pablofilgueira91** [comment]
Hi, any news about this?
I would need this function

**Comment by kaovilai** [comment]
You can now create a PVC from azure file snapshot created with azure file CSI driver.

I would consider that velero be able to replicate https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/snapshot#3-create-a-new-pvc-based-on-snapshot here.

If it does, the matter is closed. I believe velero project itself at this current time would not implement an azure file specific functionality if CSI support is sufficient.

Everyone on this thread is encouraged to try following procedures
https://velero.io/docs/v1.15/csi/
and
https://velero.io/docs/v1.15/csi-snapshot-data-movement/

if they can make sure their azure file csi driver is [v1.30.2](https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/snapshot#3-create-a-new-pvc-based-on-snapshot:~:text=From-,v1.30.2,-%2C%20the%20restoration%20of) and above.

Once someone confirms restore works, this issue will close.

**Comment by pablofilgueira91** [comment]
> You can now create a PVC from azure file snapshot created with azure file CSI driver.
> 
> I would consider that velero be able to replicate https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/snapshot#3-create-a-new-pvc-based-on-snapshot here.
> 
> If it does, the matter is closed. I believe velero project itself at this current time would not implement an azure file specific functionality if CSI support is sufficient.
> 
> Everyone on this thread is encouraged to try following procedures https://velero.io/docs/v1.15/csi/ and https://velero.io/docs/v1.15/csi-snapshot-data-movement/
> 
> if they can make sure their azure file csi driver is [v1.30.2](https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/snapshot#3-create-a-new-pvc-based-on-snapshot:~:text=From-,v1.30.2,-%2C%20the%20restoration%20of) and above.
> 
> Once someone confirms restore works, this issue will close.

Hello, I tried to make a backup of a PVC that uses Azure file share with VolumeSnapshot and it works correctly, I attach evidence.

![Image](https://github.com/user-attachments/assets/78a83629-0f3a-47f9-9c38-fa6fe691c632)
![Image](https://github.com/user-attachments/assets/e8d03361-0dc5-42a6-a43c-81460ebe6f0a)

And the backup in Azure
![Image](https://github.com/user-attachments/assets/35581d9f-2fec-4d36-baa7-b2201a3db1e8)

but when I try to do it using Velero, I find the following error
This is the backup that I generate in Velero
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: test-backup
  annotations:
    velero.io/csi-volumesnapshot-class_file.csi.azure.com: "azurefile-bkp"
spec:
    includedNamespaces:
    - pablo
```
and this the error

![Image](https://github.com/user-attachments/assets/86916da9-8dcb-42ea-81e9-f54a4fe979bf)

Is there something I'm doing wrong? Do you have any suggestions?

**Comment by pablofilgueira91** [comment]
Yes of course, here it is

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: velero:apps/Deployment:velero/velero
    deployment.kubernetes.io/revision: "2"
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    app.kubernetes.io/version: 1.15.1
    azure.workload.identity/use: "true"
    component: velero
    helm.sh/chart: velero-8.2.0
  name: velero
  namespace: velero
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/name: velero
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/secret: 5dd8d2188318d750accb371808db58a3ea9d223fbfe97a9ee55d965d162aa62f
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: velero
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: velero
        app.kubernetes.io/version: 1.15.1
        azure.workload.identity/use: "true"
        helm.sh/chart: velero-8.2.0
        name: velero
    spec:
      containers:
      - args:
        - server
        - --uploader-type=kopia
        - --keep-latest-maintenance-jobs=3
        command:
        - /velero
        env:
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: LD_LIBRARY_PATH
          value: /plugins
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /credentials/cloud
        - name: AZURE_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: ALIBABA_CLOUD_CREDENTIALS_FILE
          value: /credentials/cloud
        image: velero/velero:v1.15.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /metrics
            port: http-monitoring
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: velero
        ports:
        - containerPort: 8085
          name: http-monitoring
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /metrics
            port: http-monitoring
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /plugins
          name: plugins
        - mountPath: /credentials
          name: cloud-credentials
        - mountPath: /scratch
          name: scratch
      dnsPolicy: ClusterFirst
      initContainers:
      - image: velero/velero-plugin-for-microsoft-azure:v1.11.0
        imagePullPolicy: IfNotPresent
        name: velero-plugin-for-azure
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /target
          name: plugins
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: velero-server
      serviceAccountName: velero-server
      terminationGracePeriodSeconds: 3600
      volumes:
      - name: cloud-credentials
        secret:
          defaultMode: 420
          secretName: velero
      - name: plugins
      - name: scratch
```

**Comment by pablofilgueira91** [comment]
> Can you paste velero Deployment yaml? `kubectl get deployment velero -n velero -oyaml`

Yes of course, here it is

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: velero:apps/Deployment:velero/velero
    deployment.kubernetes.io/revision: "2"
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    app.kubernetes.io/version: 1.15.1
    azure.workload.identity/use: "true"
    component: velero
    helm.sh/chart: velero-8.2.0
  name: velero
  namespace: velero
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/name: velero
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/secret: 5dd8d2188318d750accb371808db58a3ea9d223fbfe97a9ee55d965d162aa62f
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: velero
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: velero
        app.kubernetes.io/version: 1.15.1
        azure.workload.identity/use: "true"
        helm.sh/chart: velero-8.2.0
        name: velero
    spec:
      containers:
      - args:
        - server
        - --uploader-type=kopia
        - --keep-latest-maintenance-jobs=3
        command:
        - /velero
        env:
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: LD_LIBRARY_PATH
          value: /plugins
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /credentials/cloud
        - name: AZURE_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: ALIBABA_CLOUD_CREDENTIALS_FILE
          value: /credentials/cloud
        image: velero/velero:v1.15.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /metrics
            port: http-monitoring
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: velero
        ports:
        - containerPort: 8085
          name: http-monitoring
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /metrics
            port: http-monitoring
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /plugins
          name: plugins
        - mountPath: /credentials
          name: cloud-credentials
        - mountPath: /scratch
          name: scratch
      dnsPolicy: ClusterFirst
      initContainers:
      - image: velero/velero-plugin-for-microsoft-azure:v1.11.0
        imagePullPolicy: IfNotPresent
        name: velero-plugin-for-azure
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /target
          name: plugins
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: velero-server
      serviceAccountName: velero-server
      terminationGracePeriodSeconds: 3600
      volumes:
      - name: cloud-credentials
        secret:
          defaultMode: 420
          secretName: velero
      - name: plugins
      - name: scratch
```

**Comment by pablofilgueira91** [comment]
From what I see in the logs it is as you say, Velero wants to make the backup with Velero-Native Snapshots
`time="2025-01-29T13:12:52Z" level=info msg="Summary for skipped PVs: [{\"name\":\"pvc-2f70114a-e8d4-47ac-b200-de727d5d4f95\",\"reasons\":[{\"approach\":\"volumeSnapshot\",\"reason\":\"no applicable volumesnapshotter found\"}]}]" backup=velero/test-backup1 logSource="pkg/backup/backup.go:545"`

and not with CSI Snapshots since supposedly the feature is not installed
`time="2025-01-29T13:12:52Z" level=info msg="Skip action velero.io/csi-pvc-backupper for resource persistentvolumeclaims:pablo/pablo-pvc, because the CSI feature is not enabled. Feature setting is ." backup=velero/test-backup1 logSource="pkg/backup/item_backupper.go:369" name=pablo-pvc namespace=pablo resource=persistentvolumeclaims`

but according to this documentation https://velero.io/docs/main/csi/ from version 1.14 it is no longer necessary to install the CSI plugin and if I get the installed plugins I can see that csi is

```
velero plugin get | grep csi
velero.io/csi-pvc-backupper                     BackupItemActionV2
velero.io/csi-volumesnapshot-backupper          BackupItemActionV2
velero.io/csi-volumesnapshotclass-backupper     BackupItemActionV2
velero.io/csi-volumesnapshotcontent-backupper   BackupItemActionV2
velero.io/csi-volumesnapshot-delete             DeleteItemAction
velero.io/csi-volumesnapshotcontent-delete      DeleteItemAction
velero.io/csi-pvc-restorer                      RestoreItemActionV2
velero.io/csi-volumesnapshot-restorer           RestoreItemActionV2
velero.io/csi-volumesnapshotclass-restorer      RestoreItemActionV2
velero.io/csi-volumesnapshotcontent-restorer    RestoreItemActionV2
```

am I missing something else? please I hope for help

**Comment by pablofilgueira91** [comment]
I finally got it working, I didn't have the EnableCSI feature properly activated.

```
Name:         test-backup2
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"velero.io/v1","kind":"Backup","metadata":{"annotations":{"velero.io/csi-volumesnapshot-class_file.csi.azure.com":"azurefile-bkp"},"name":"test-backup2","namespace":"velero"},"spec":{"csiSnapshotTimeout":"10m","includedNamespaces":["pablo"],"includedResources":["persistentvolumeclaims","persistentvolume"]}}

  velero.io/csi-volumesnapshot-class_file.csi.azure.com=azurefile-bkp
  velero.io/resource-timeout=10m0s
  velero.io/source-cluster-k8s-gitversion=v1.30.3
  velero.io/source-cluster-k8s-major-version=1
  velero.io/source-cluster-k8s-minor-version=30

Phase:  Completed


Namespaces:
  Included:  pablo
  Excluded:  <none>

Resources:
  Included:        persistentvolumeclaims, persistentvolume
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto
Snapshot Move Data:          false
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2025-01-29 11:56:48 -0300 -03
Completed:  2025-01-29 11:56:59 -0300 -03

Expiration:  2025-02-28 11:56:48 -0300 -03

Total items to be backed up:  5
Items backed up:              5

Backup Item Operations:
  Operation for volumesnapshots.snapshot.storage.k8s.io pablo/velero-pablo-pvc-zmhqc:
    Backup Item Action Plugin:  velero.io/csi-volumesnapshot-backupper
    Operation ID:               pablo/velero-pablo-pvc-zmhqc/2025-01-29T14:56:55Z
    Items to Update:
              volumesnapshots.snapshot.storage.k8s.io pablo/velero-pablo-pvc-zmhqc
              volumesnapshotcontents.snapshot.storage.k8s.io /snapcontent-a4f5ddc7-d93e-4b09-8a32-7b8ce717518e
    Phase:    Completed
    Created:  2025-01-29 11:56:55 -0300 -03
    Started:  2025-01-29 11:56:55 -0300 -03
    Updated:  2025-01-29 11:56:55 -0300 -03
Resource List:
  snapshot.storage.k8s.io/v1/VolumeSnapshot:
    - pablo/velero-pablo-pvc-zmhqc
  snapshot.storage.k8s.io/v1/VolumeSnapshotClass:
    - azurefile-bkp
  snapshot.storage.k8s.io/v1/VolumeSnapshotContent:
    - snapcontent-a4f5ddc7-d93e-4b09-8a32-7b8ce717518e
  v1/PersistentVolume:
    - pvc-2f70114a-e8d4-47ac-b200-de727d5d4f95
  v1/PersistentVolumeClaim:
    - pablo/pablo-pvc

Backup Volumes:
  Velero-Native Snapshots: <none included>

  CSI Snapshots:
    pablo/pablo-pvc:
      Snapshot:
        Operation ID: pablo/velero-pablo-pvc-zmhqc/2025-01-29T14:56:55Z
        Snapshot Content Name: snapcontent-a4f5ddc7-d93e-4b09-8a32-7b8ce717518e
        Storage Snapshot ID: MC_RG-AKS-LABS_BB-AKS-LABS_eastus2#fdf0c30a8aaf94cf49d3137#pvc-2f70114a-e8d4-47ac-b200-de727d5d4f95###pablo#2025-01-29T14:56:51.0000000Z
        Snapshot Size (bytes): 1073741824
        CSI Driver: file.csi.azure.com
        Result: succeeded

  Pod Volume Backups: <none included>

HooksAttempted:  0
HooksFailed:     0
```

**Comment by kaovilai** [comment]
> I finally got it working, I didn't have the EnableCSI feature properly activated.

Could you share what you did differently? I am not familiar with specifying features in helm charts.

**Comment by kaovilai** [comment]
Also please try restore :)

**Comment by navesimchi** [comment]
@kaovilai I tried to restore and it failed

CSI version:

![Image](https://github.com/user-attachments/assets/e23d0cdf-15ce-4a41-86a0-dd7490b97f4c)

The error:

![Image](https://github.com/user-attachments/assets/3a4fdc64-030c-4d8c-88b5-b59d02c20980)

**Comment by pablofilgueira91** [comment]
The restore does not work correctly because the snapshot of a file share is made within the file share, therefore if the file share is deleted the snapshot is also deleted.
example of a snapshot within a file share
![Image](https://github.com/user-attachments/assets/99c72bf9-6893-4971-ad48-7508926ee883)

from what I could find out the correct way to restore it would be to create a new pvc from the VolumeSnapshot created by velero in the following way

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-pvc-restored
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
  dataSource:
    name: velero-file-pvc-cjqtz
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
```

![Image](https://github.com/user-attachments/assets/014e0d4b-8c37-4439-aa1a-4974b7114b12)

something I don't understand is why the VolumeSnapshot is not created until I do the restore, although the snapshot in the file share was created, the VolumeSnapshot was not created until the backup was restored, as you can see in the image above.
I attach details of the backup
![Image](https://github.com/user-attachments/assets/caa275a9-d036-4358-b018-3ffa8ff99978)

please let me know if I can do any other test.
