### ISSUE TITLE
Velero backup do not restore Deployment volumes [aws-efs]

### ISSUE THREAD

**Issue by fabriziogaliano** [vmware-tanzu/velero#3199]
**velero restic backup**
steps to reproduce:

 - create a POD and a PVC in a specific namespace called `velero-restic-test`:
 
**POD YAML FILE**

```apiVersion: v1
kind: Pod
metadata:
  name: sample
  namespace: velero-restic-test
  annotations:
    backup.velero.io/backup-volumes: sample-volume
spec:
  tolerations:
   - effect: NoSchedule
     operator: Exists
   - effect: NoExecute
     operator: Exists
  containers:
  - image: busybox
    name: test-webserver
    command: ["tail"]
    args: ["-f", "/dev/null"]
    volumeMounts:
    - name: sample-volume
      mountPath: /volume-1
    - name: emptydir-volume
      mountPath: /volume-2
  volumes:
  - name: sample-volume
    persistentVolumeClaim:
      claimName: sample-volume
  - name: emptydir-volume
    emptyDir: {}
```

**POD PVC YAML FILE**

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-volume
  namespace: velero-restic-test
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
```
Apply resources:
`kubectl apply -f pvc-pod.yaml`
`kubectl apply -f pod.yaml`

**DEPLOYMENT YAML FILE**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: velero-restic-test
  annotations:
    backup.velero.io/backup-volumes: sample-volume2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
       - effect: NoSchedule
         operator: Exists
       - effect: NoExecute
         operator: Exists
      containers:
      - image: busybox
        name: test-webserver
        command: ["tail"]
        args: ["-f", "/dev/null"]
        volumeMounts:
        - name: sample-volume2
          mountPath: /volume-1
        - name: emptydir-volume2
          mountPath: /volume-2
      volumes:
      - name: sample-volume2
        persistentVolumeClaim:
          claimName: sample-volume2
      - name: emptydir-volume2
        emptyDir: {}
```

**DEPLOYMENT PVC YAML FILE**

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-volume2
  namespace: velero-restic-test
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
```
Apply resources:
`kubectl apply -f pvc-deployment.yaml`
`kubectl apply -f deployment.yaml`

**at this moment every pods is running with their volumes attached**

just to do not have an empty folder, i've created a file with `cat /dev/urandom > file` in each volumes.

**MAKE A VELERO BACKUP**

`velero backup create test-001 --include-namespaces velero-restic-test`

this is the result of the backup:

```
Name:         test-001
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.11.10
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=11

Phase:  Completed

Errors:    0
Warnings:  0

Namespaces:
  Included:  velero-restic-test
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-12-18 13:30:36 +0000 UTC
Completed:  2020-12-18 13:30:42 +0000 UTC

Expiration:  2021-01-17 13:30:36 +0000 UTC

Total items to be backed up:  41
Items backed up:              41

Velero-Native Snapshots: <none included>

Restic Backups (specify --details for more information):
  Completed:  1
```

**What we see in AWS S3?**

in the Bucket i've 2 folder, like this:

```
 backups/
    ----- <VELERO_BACKUP_NAME>/
 restic/
    ----- <NAMESPACE_NAME>/
           ----- config/
           ----- data/
           ----- etc ...
```

**TRY TO DO A RESTORE**

`kubectl delete -f pod.yaml`
`kubectl delete -f pvc-pod.yaml`
`kubectl delete -f deployment.yaml`
`kubectl delete -f pvc-deployment.yaml`

Launch velero RESTORE:

`velero restore create --from-backup test-001`

everything seems recreated by velero, IF i go inside the **POD**  to check if the data into the pvc volume it was restored i find the file i've created, in the **Deployment** every object was created but the file/s inside the volume NOT.

have you an idea why?

[sample-deployment-pvc-data.log](https:
[restore-sample-deployment-pvc-data-20201218133434.log](https://github.com/vmware-tanzu/velero/files/5716151/restore-sample-deployment-pvc-data-20201218133434.log)
//github.com/vmware-tanzu/velero/files/5716140/sample-deployment-pvc-data.log)

**Environment:**

- Velero version (`1.4.3`): 
- Velero features (`features: <NOT SET>`): 
- Kubernetes version (`1.11.10`):
- Kubernetes installer & version: `Kops on AWS`
- Cloud provider (`AWS`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
