### ISSUE TITLE
Backup stuck on New phase

### ISSUE THREAD

**Issue by pshanoop** [vmware-tanzu/velero#3216]
**What steps did you take and what happened:**

Installed velero using the [helm chart ](https://github.com/vmware-tanzu/helm-charts) version `1.5.2` with these values
```yaml

image:
  repository: velero/velero
  tag: v1.5.2
  pullPolicy: IfNotPresent
  imagePullSecrets: []

podAnnotations:
  iam.amazonaws.com/role: "arn:aws:iam::{{account-id}}:role/kprod-l1-velero-role"

podLabels: {}

resources:
  limits:
    cpu: 1000m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 128Mi

dnsPolicy: ClusterFirst

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.1.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

priorityClassName: ""

affinity: {}

nodeSelector:
  company/node-type: infra

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"

extraVolumes: []

extraVolumeMounts: []

metrics:
  enabled: true
  scrapeInterval: 30s
  serviceMonitor:
    enabled: true
    additionalLabels: {}

installCRDs: true

enableHelmHooks: true

configuration:
  provider: aws
  backupStorageLocation:
    provider: "aws"
    bucket: "bucket-kprod-l1-velero"
    config:
      region: "eu-central-1"
  volumeSnapshotLocation:
    provider: aws
    config:
      region: "eu-central-1"
      bucket: "bucket-kprod-l1-velero"
  backupSyncPeriod:
  resticTimeout:
  restoreResourcePriorities:
  restoreOnlyMode:
  extraEnvVars: {}
  features:
  logLevel: debug
  logFormat:
  defaultVolumesToRestic:

rbac:
  create: true
  clusterAdministrator: true

serviceAccount:
  server:
    create: true
    name:
    annotations:

credentials:
  useSecret: false
  extraEnvVars: {}
  extraSecretRef: ""

backupsEnabled: true
snapshotsEnabled: true
deployRestic: false

restic:
  podVolumePath: /var/lib/kubelet/pods
  privileged: false
  priorityClassName: ""
  resources: {}
  tolerations: []
  extraVolumes: []
  extraVolumeMounts: []
  dnsPolicy: ClusterFirst
  securityContext: {}

schedules: {}
configMaps: {}
```

And I installed `nginx-example` given in velero to validate. 

After install I tried to create backup in same namespace as velero installed. 
`velero backup create nginx-backup-test --include-namespaces nginx-example` 

**What did you expect to happen:**
The backup created and available and possible to download or restore.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
https://gist.github.com/pshanoop/3ae615e16a13bdeb0dad612303e35447
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
Name:         nginx-backup-test
Namespace:    velero
Labels:       <none>
Annotations:  <none>
Phase:  New
Errors:    0
Warnings:  0
Namespaces:
  Included:  nginx-example
  Excluded:  <none>
Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto
Label selector:  <none>
Storage Location:  
Velero-Native Snapshot PVs:  auto
TTL:  720h0m0s
Hooks:  <none>
Backup Format Version:  
Started:    <n/a>
Completed:  <n/a>
Expiration:  <nil>
Velero-Native Snapshots: <none included>
```
- `velero backup logs <backupname>`
```
Logs for backup "nginx-backup-test" are not available until it's finished processing. Please wait until the backup has a phase of Completed or Failed and try again.
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I don't 

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.5.2
	Git commit: e115e5a191b1fdb5d379b62a35916115e77124a4
Server:
	Version: v1.5.2
```
- Velero features (use `velero client config get features`): 
```
❯ velero client config get features
features: <NOT SET>

```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"f3add640dbcd4f3c33a7749f38baaac0b3fe810d", GitTreeState:"clean", BuildDate:"2020-05-20T13:51:56Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
```
kops, 1.16.0
```
- Cloud provider or hardware configuration:
AWS, S3
- OS (e.g. from `/etc/os-release`):
Debian sid. 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
