### ISSUE TITLE
Restic restores failing when using namespace mapping

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/velero#3467]
Restic restores are failing when using a namespace mapping as the check for whether a PVB matches the pod being restored checks the namespace of the PVB against the namespace of the pod: https://github.com/vmware-tanzu/velero/blob/main/pkg/restic/common.go#L98-L100

This check will fail in the case where the pod is being mapped to a new namespace and so a PVR will not be generated for that pod and the restore will not take place.

Instead of checking the new namespace of the pod, we should be checking the original namespace which will match the namespace for the associated PVB.

----

I am getting the same error when trying to restore into a different namespace. The kubernetes resources are still created. It is really strange, since restoring into the same namespace works perfectly fine.

I use a command like 

`velero restore create --from-backup test-backup3 --namespace-mappings mlflow-feature-hotfix:something-else`

Note that mlflow-feature-hotfix ist just a sample application with a postgres that I use to have some state while verifying the backups.

I have velero `1.5.3` installed via helm with the following values.

```yaml
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.1.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  provider: aws
  backupStorageLocation:
    bucket: ${bucket}
    prefix: velero
  volumeSnapshotLocation:
    name: aws-default
  defaultVolumesToRestic: true
deployRestic: true
credentials:
  name: velero-aws
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=${aws_access_key_id}
      aws_secret_access_key=${aws_secret_access_key}

```

I am runnning on Rancher on premise. I put the logs files here https://gist.github.com/JarnoRFB/25b6343e45ca63945ebc9eca457774ab , but to me the logs of the successful backup to the same namespace looked almost the same as the logs of the failing backup to the different namespace.

Any help much appreciated!

_Originally posted by @JarnoRFB in https://github.com/vmware-tanzu/velero/discussions/3385#discussioncomment-357126_
