### ISSUE TITLE
PV is not getting cleaned up for the restored volumes

### ISSUE THREAD

**Issue by pawanpraka1** [vmware-tanzu/velero#3470]
**What steps did you take and what happened:**

Restored the namespace which has 2 pods and corresponding pvcs using openebs/velero-plugin. When I am deleting the restored namespace, pv remains there in the system with the error 

```
  status:
    message: 'Error getting deleter volume plugin for volume "pvc-b4b70408-49d7-4921-a88e-80c1fcd981aa":
      no deletable volume plugin matched'
    phase: Failed

```

**What did you expect to happen:**

PV to be cleand up. PVC and pods gets cleaned up but not the PV.

**Anything else you would like to add:**

I think this change (https://github.com/vmware-tanzu/velero/pull/3007) caused the issue. k8s checks the annotation `pv.kubernetes.io/provisioned-by` to find the plugin related information which has been cleaned up in this PR. Now k8s assumes that pv is statically provisioned and throws error.

This works fine with 1.5.1 and lower releases. The issue is there with 1.5.2 and 1.5.3.
