### ISSUE TITLE
Velero Restic backup stucks indefinitely

### ISSUE THREAD

**Issue by talha0324** [vmware-tanzu/velero#3521]
**What steps did you take and what happened:**
I deployed Velero 1.5.3 with helm with restic enabled, deployment looks like this

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: velero
  namespace: openshift-velero
spec:
  releaseName: velero
  chart:
    repository: https://vmware-tanzu.github.io/helm-charts
    name: velero
    version: 2.14.12
  values:
    image:
      repository: velero/velero
      tag: v1.5.3
      pullPolicy: Always
    initContainers:
    - name: "velero-plugin-for-aws"
      image: "velero/velero-plugin-for-aws:v1.1.0"
      imagePullPolicy: Always
      volumeMounts:
      - name: "plugins"
        mountPath: "/target"
    snapshotsEnabled: false
    backupsEnabled: true
    cleanUpCRDs: true
    configuration:
      # Cloud provider being used (e.g. aws, azure, gcp).
      provider: aws
      backupStorageLocation:
        name: default
        bucket: "velero_backup"
        config:
          # insecureSkipTLSVerify: "true"
          region: "europe-se-1"
          # s3ForcePathStyle: true
          s3Url: "https://object-eu-se-1a.binero.cloud"
      defaultVolumesToRestic: true
      backupSyncPeriod: 5m
      resticTimeout: 6h
    schedules:
    - default-schedule
      mybackup:
        schedule: "*/5 * * * *"
        template:
          ttl: "1h"
          includedNamespaces:
          - "openshift-stakater-system"
          - "openshift-monitoring"
    credentials:
      secretContents:
        cloud: |
          [default]
          aws_access_key_id = 7049a44a5d5a4c0bb70bd489c6d80924
          aws_secret_access_key = bc5b830f985643c2bb182bb05997ebf1
          
    deployRestic: true
    restic:
      privileged: true
      resources:
        requests:
          memory: "200Mi"
          cpu: "200m"
        limits:
          memory: "200Mi"
          cpu: "200m"
    configMaps:
      restic-restore-action-config:
        labels:
          velero.io/plugin-config: ""
          velero.io/restic: RestoreItemAction
        data:
          image: velero/velero-restic-restore-helper:v1.5.3
```

**What did you expect to happen:**
A smooth backup with Restic enabled

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero` [logs.txt](https://github.com/vmware-tanzu/velero/files/6084160/logs.txt)

- `velero backup describe <backupname>` 
```
Name:         default-schedule-20210304132959
Namespace:    openshift-velero
Labels:       velero.io/schedule-name=default-schedule
              velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.19.0+3b01205
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=19

Phase:  InProgress

Errors:    0
Warnings:  0

Namespaces:
  Included:  openshift-stakater-system, openshift-monitoring
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  included

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  72h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-03-04 18:29:59 +0500 PKT
Completed:  <n/a>

Expiration:  2021-03-07 18:29:59 +0500 PKT

Estimated total items to be backed up:  3565
Items backed up so far:                 7

Velero-Native Snapshots: <none included>

Restic Backups (specify --details for more information):
  Completed:  5
  New:        1
```
- `velero backup logs <backupname>`:not available as backup is stuck
- `velero restore describe <restorename>` : not available as backup is stuck
- `velero restore logs <restorename>`: not available

**Anything else you would like to add:**
Cluster backup without restic works fine

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.5.3
	Git commit: 123109a3bcac11dbb6783d2758207bac0d0817cb
Server:
	Version: v1.5.3
```
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+3b01205", GitCommit:"3b012051f912a6e29337c4087fcfc8161651690b", GitTreeState:"clean", BuildDate:"2021-01-16T09:10:53Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Openshift on Openstack

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
