### ISSUE TITLE
Labels on backup objects

### ISSUE THREAD

**Issue by DavidDarville** [vmware-tanzu/velero#3560]
I see that the labels from schedules.velero.io are copied to backups.velero.io, which is not how things are usually done in Kubernetes.

A schedule object like this:
```
apiVersion: velero.io/v1
kind: Schedule
metadata:
  labels:
    foo: bar
  name: test-schedule
  namespace: velero
spec:
  schedule: '0 * * * *'
  template:
    hooks: {}
    includedNamespaces:
    - '*'
    ttl: 48h0m0s
``` 
Will generate backup objects like this:
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  labels:
    foo: bar
    velero.io/backup: test-schedule-20210311110003
    velero.io/pv: ....
    velero.io/schedule-name: test-schedule
    velero.io/storage-location: default
  name: test-schedule-20210311110003
  namespace: velero
......
```
This is not how things are done in Kubernetes. For instance: The pods created by a deploy objects, gets labeled based on '.spec.metadata.labels', NOT '.metadata.labels'.

My problem with this, is that I would like to deploy everything on my Kubernetes clusters automatically - using Argo-CD. And Argo-CD is adding custom labels to all objects that it is managing, to keep track of them. And since Velero is copying those labels from the schedule object, to all backup objects, this tracking will be messed up.

I have tested this using both v1.2.0 and v1.5.3, without seeing any difference in this behaviour.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
