### ISSUE TITLE
backup from schedule not executing hook on all pods (no such container)

### ISSUE THREAD

**Issue by headyj** [vmware-tanzu/velero#3622]
**What steps did you take and what happened:**

1. create a Schedule definition file with hooks:
```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: my-velero-schedule
  namespace: velero
spec:
  schedule: 0 4 * * *
  template:
    includedNamespaces:
    - '*'
    snapshotVolumes: true
    hooks:
      resources:
      - name: my-pre-hook
        includedNamespaces:
        - '*'
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: name
            app.kubernetes.io/component: core
        pre:
          - exec:
              command:
                - custom_command
              timeout: 150s
```

2. Create at least 2 namespaces with 2 pods that match the labelSelector
3. Create a backup from the Schedule
4. Hook is correctly executed on the first pod, but the second is in error, like if velero still tries to find the container name of the first pod in the second one:
time="2021-03-24T14:58:14Z" level=info msg="running exec hook" backup=velero/velero-backup-schedule-20210324145811 hookCommand="[custom-command]" hookContainer=container1 hookName=my-pre-hook hookOnError=Fail hookPhase=pre hookSource=backupSpec hookTimeout="{2m30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:124" name=pod1 namespace=namespace1 resource=pods
[...]
Error executing hook" backup=velero/velero-backup-schedule-20210324145811 error="no such container: \"**container1**\"" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podexec/pod_command_executor.go:184" error.function=github.com/vmware-tanzu/velero/pkg/podexec.ensureContainerExists hookPhase=pre hookSource=backupSpec hookType=exec logSource="internal/hook/item_hook_handler.go:240" name=**pod2** namespace=namespace2 resource=pods

**What did you expect to happen:**
hook should be executed correctly on both pods

**Environment:**

- Velero version: v1.5.3 
- Velero features: - 
- Kubernetes version: v1.19.7
- Kubernetes installer & version:
- Cloud provider or hardware configuration: AWS (EKS)
- OS:
