### ISSUE TITLE
Partially failed backups when trying to backup empty emptyDir with restic

### ISSUE THREAD

**Issue by bo0ts** [vmware-tanzu/velero#3812]
**What steps did you take and what happened:**

I created a restic backup including only the namespace `foo`. The namespace 

```
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup
  labels:
    velero.io/storage-location: default
spec:
  hooks: {}
  includedNamespaces:
  - foo
  excludedResources:
  - storageclasses.storage.k8s.io
  storageLocation: default
  ttl: 720h0m0s
  defaultVolumesToRestic: true
```

The namespace contains completed pods with `emptyDir` volumes. Some of the pods have never written data to the mountpoint. Consequently the directory on the node is empty:

```
sh-5.0# ls /var/lib/kubelet/pods/<uid-of-affected-pod>/volumes/kubernetes.io~empty-dir
sh-5.0#
```

Unfortunately the backup ended in state PartiallyFailed with the following log entries:

```
time="2021-05-18T07:25:01Z" level=info msg="3 errors encountered backup up item" backup=oadp-operator/backup logSource="pkg/backup/backup.go:451" name=pod-with-empty-emptydir
time="2021-05-18T07:25:01Z" level=error msg="Error backing up item" backup=oadp-operator/backup error="pod volume backup failed: error getting volume path on host: expected one matching path, got 0" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:179" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:455" name=pod-with-empty-emptydir
time="2021-05-18T07:25:01Z" level=error msg="Error backing up item" backup=oadp-operator/backup error="pod volume backup failed: error getting volume path on host: expected one matching path, got 0" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:179" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:455" name=pod-with-empty-emptydir
time="2021-05-18T07:25:01Z" level=error msg="Error backing up item" backup=oadp-operator/backup error="pod volume backup failed: error getting volume path on host: expected one matching path, got 0" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:179" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:455" name=pod-with-empty-emptydir
```

**What did you expect to happen:**

I expected a successful backup.

**The output of the following commands will help us better understand what's going on**:

Excerpt of the logs has been provided above.

**Anything else you would like to add:**

Velero installed in OKD via Konveyor.

**Environment:**

- Velero version (use `velero version`): Version: v1.5.2-konveyor
- Kubernetes installer & version: OKD 4.5

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
@bo0ts I see you saw this error while using konveyor, have you opened an issue to konveyor?  Such that the konveyor developer can help do some initial debug and narrow down the problem?

In addition, have you checked the log of the restic daemonset?

**Comment by bo0ts** [comment]
@reasonerjt Thanks for looking into this. I don't see how konveyor is involved here and I'm sure I can reproduce this is with a vanilla velero/restic installation. I can't remember any errors in the restic pods, but I would have to reproduce this issue to be sure.

**Comment by reasonerjt** [comment]
Thanks @bo0ts that would be helpful

**Comment by mahaupt** [comment]
I get the same error on Openshift + Velero installed via Helm chart.
The restic pod tries 3 times to create the backup, then the backup is stuck in "InProgress". The Backup can not be deleted and no new backups are handled.
The volume it's trying do backup is also an emptyDir volume.
```
time="2021-07-21T12:17:55Z" level=error msg="Error uniquely identifying volume path" backup=velero/velero-backup-20210721121535 controller=pod-volume-backup error="expected one matching path, got 0" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/pod_volume_backup_controller.go:442" error.function=github.com/vmware-tanzu/velero/pkg/controller.singlePathMatch logSource="pkg/controller/pod_volume_backup_controller.go:222" name=velero-backup-20210721121535-hkx8d namespace=velero
```

**Comment by mahaupt** [comment]
This error seems to occur especially on completed jobs / builds with an emptyDir mounted. For reproduction, I created a test job:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  template:
    metadata:
      name: testjob
    spec:
      containers:
      - name: testjob
        image: busybox
        command: ["echo", "Running a job"]
        volumeMounts:
        - name: deleteme
          mountPath: /mnt/deleteme
      volumes:
      - name: deleteme
        emptyDir: {}
    
      restartPolicy: OnFailure
```
Let this job run in a separate namespace and create the backup. The backup finishes in a PartiallyFailed state with the following logs:
```
velero backup logs test4 | grep error
time="2021-07-26T15:54:29Z" level=info msg="1 errors encountered backup up item" backup=velero/test4 logSource="pkg/backup/backup.go:427" name=testjob-pmpvf
time="2021-07-26T15:54:29Z" level=error msg="Error backing up item" backup=velero/test4 error="pod volume backup failed: error getting volume path on host: expected one matching path, got 0" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:179" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:431" name=testjob-pmpvf
```
