### ISSUE TITLE
Backup local volume with restic stuck 'In progress' phase

### ISSUE THREAD

**Issue by dyvol777** [vmware-tanzu/velero#4033]
**What steps did you take and what happened:**
I install velero with restic, and want to make backup of example nginx (local pv). But backup stuck in 'In progress' phase.
Backup without local volumes succesfully created. Also, backup with emptydir succesfully created.

**Environment:**
- Velero version 1.6.2
- Velero installed with command:
> velero install \
>     --provider aws \
>     --plugins velero/velero-plugin-for-aws:v1.2.0 \
>     --bucket velero \
>     --secret-file ./credentials-velero \
>     --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://miniourl:9000 \
>     --snapshot-location-config region=minio,s3ForcePathStyle="true",s3Url=http://miniourl:9000 \
>     --use-restic --default-volumes-to-restic\
>     --wait
- Kubernetes version: 1.21.4
- Hardware configuration: Bare metal ubuntu 20.04
- Nginx file:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/nginx
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - test-kuber-01
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-example
  labels:
    app: nginx
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-logs
  namespace: nginx-example
  labels:
    app: nginx
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        pre.hook.backup.velero.io/container: fsfreeze
        pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/var/log/nginx"]'
        post.hook.backup.velero.io/container: fsfreeze
        post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/var/log/nginx"]'
    spec:
      volumes:
        - name: nginx-logs
          persistentVolumeClaim:
           claimName: nginx-logs
      containers:
      - image: nginx:1.17.6
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false
      - image: ubuntu:bionic
        name: fsfreeze
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false
        command:
          - "/bin/bash"
          - "-c"
          - "sleep infinity"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-nginx
  namespace: nginx-example
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
```
- backup created with command
> velero backup create nginx-backup --include-namespaces nginx-example

**The output of the following commands**:
- `kubectl logs deployment/velero -n velero`
no errors
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
Name:         nginx
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.21.4
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=21

Phase:  InProgress

Errors:    0
Warnings:  0

Namespaces:
  Included:  nginx-example
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-08-12 22:50:03 +0300 MSK
Completed:  <n/a>

Expiration:  2021-09-11 22:50:03 +0300 MSK

Estimated total items to be backed up:  23
Items backed up so far:                 0

Resource List:  <backup resource list not found>

Velero-Native Snapshots: <none included>
```
- `velero backup logs <backupname>`
not finished so no logs

**Comment by dyvol777** [comment]
I debug a bit, and think that the problem in deployment:
```
      annotations:
        pre.hook.backup.velero.io/container: fsfreeze
        pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/var/log/nginx"]'
        post.hook.backup.velero.io/container: fsfreeze
        post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/var/log/nginx"]'
...
      - image: ubuntu:bionic
        name: fsfreeze
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false
        command:
          - "/bin/bash"
          - "-c"
          - "sleep infinity"
```
Without it there are no problem in backup

**Comment by dyvol777** [comment]
Also, when restore, pv doesn't restores. But logs say that it had restored.
```
time="2021-08-13T13:13:05Z" level=info msg="starting restore" logSource="pkg/controller/restore_controller.go:465" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Starting restore of backup velero/nginx-12" logSource="pkg/restore/restore.go:387" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Skipping restore of resource because it cannot be resolved via discovery" logSource="pkg/restore/restore.go:1674" resource=volumesnapshotclass.snapshot.storage.k8s.io restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Skipping restore of resource because it cannot be resolved via discovery" logSource="pkg/restore/restore.go:1674" resource=volumesnapshotcontents.snapshot.storage.k8s.io restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Skipping restore of resource because it cannot be resolved via discovery" logSource="pkg/restore/restore.go:1674" resource=volumesnapshots.snapshot.storage.k8s.io restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Resource 'persistentvolumes' will be restored at cluster scope" logSource="pkg/restore/restore.go:1763" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Resource 'persistentvolumeclaims' will be restored into namespace 'nginx-example'" logSource="pkg/restore/restore.go:1761" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Resource 'secrets' will be restored into namespace 'nginx-example'" logSource="pkg/restore/restore.go:1761" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Resource 'configmaps' will be restored into namespace 'nginx-example'" logSource="pkg/restore/restore.go:1761" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Resource 'serviceaccounts' will be restored into namespace 'nginx-example'" logSource="pkg/restore/restore.go:1761" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Resource 'pods' will be restored into namespace 'nginx-example'" logSource="pkg/restore/restore.go:1761" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Resource 'replicasets.apps' will be restored into namespace 'nginx-example'" logSource="pkg/restore/restore.go:1761" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Skipping restore of resource because it cannot be resolved via discovery" logSource="pkg/restore/restore.go:1674" resource=clusters.cluster.x-k8s.io restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Skipping restore of resource because it cannot be resolved via discovery" logSource="pkg/restore/restore.go:1674" resource=clusterresourcesets.addons.cluster.x-k8s.io restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Resource 'deployments.apps' will be restored into namespace 'nginx-example'" logSource="pkg/restore/restore.go:1761" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Resource 'endpoints' will be restored into namespace 'nginx-example'" logSource="pkg/restore/restore.go:1761" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Resource 'endpointslices.discovery.k8s.io' will be restored into namespace 'nginx-example'" logSource="pkg/restore/restore.go:1761" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Skipping restore of resource because the restore spec excludes it" logSource="pkg/restore/restore.go:1691" resource=events restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Resource 'services' will be restored into namespace 'nginx-example'" logSource="pkg/restore/restore.go:1761" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Getting client for /v1, Kind=PersistentVolume" logSource="pkg/restore/restore.go:883" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Dynamically re-provisioning persistent volume because it has a restic backup to be restored." logSource="pkg/restore/restore.go:1092" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Restored 1 items out of an estimated total of 11 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:664" name=example-pv namespace= progress= resource=persistentvolumes restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Getting client for /v1, Kind=PersistentVolumeClaim" logSource="pkg/restore/restore.go:883" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:1133" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Executing AddPVFromPVCAction" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:44" pluginName=velero restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Adding PV example-pv as an additional item to restore" cmd=/velero logSource="pkg/restore/add_pv_from_pvc_action.go:66" pluginName=velero restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Skipping persistentvolumes/example-pv because it's already been restored." logSource="pkg/restore/restore.go:991" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:1133" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:65" pluginName=velero restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Done executing ChangePVCNodeSelectorAction" cmd=/velero logSource="pkg/restore/change_pvc_node_selector.go:93" pluginName=velero restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:1133" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:65" pluginName=velero restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Done executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:76" pluginName=velero restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Resetting PersistentVolumeClaim nginx-example/nginx-logs for dynamic provisioning" logSource="pkg/restore/restore.go:1212" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Attempting to restore PersistentVolumeClaim: nginx-logs" logSource="pkg/restore/restore.go:1238" restore=velero/nginx-12-20210813161305
time="2021-08-13T13:13:05Z" level=info msg="Restored 3 items out of an estimated total of 12 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:664" name=nginx-logs namespace=nginx-example progress= resource=persistentvolumeclaims restore=velero/nginx-12-20210813161305
```

So pod can not allocate to node, while pv created manually, and restore stucks

**Comment by ywk253100** [comment]
> I debug a bit, and think that the problem in deployment:
> 
> ```
>       annotations:
>         pre.hook.backup.velero.io/container: fsfreeze
>         pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/var/log/nginx"]'
>         post.hook.backup.velero.io/container: fsfreeze
>         post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/var/log/nginx"]'
> ...
>       - image: ubuntu:bionic
>         name: fsfreeze
>         securityContext:
>           privileged: true
>         volumeMounts:
>           - mountPath: "/var/log/nginx"
>             name: nginx-logs
>             readOnly: false
>         command:
>           - "/bin/bash"
>           - "-c"
>           - "sleep infinity"
> ```
> 
> Without it there are no problem in backup

You said `Without it there are no problem in backup`, without what?

**Comment by dyvol777** [comment]
Without annotations and second container in deployment. 
So, this deploy backup successfully: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-logs
          persistentVolumeClaim:
           claimName: nginx-logs
      containers:
      - image: nginx:1.17.6
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false
```
