### ISSUE TITLE
Error while restoring volume 

### ISSUE THREAD

**Issue by kpiyush17** [vmware-tanzu/velero#4039]
**What steps did you take and what happened:**
I am trying to test backup/restore using velero. Created a namespace with one pod and a PVC attached to it. The backup works successfully but while restoring the pod is stuck in the init state.

**Pod describe after restore**
```
kubectl describe pod mypod -n star-wars                                                                                                                                                                   ⎈ aks-tf-34
Name:         mypod
Namespace:    star-wars
Priority:     0
Node:         aks-workerl63l0-96403094-vmss000001/10.240.0.66
Start Time:   Tue, 17 Aug 2021 18:58:04 +0530
Labels:       velero.io/backup-name=star-wars-backup
              velero.io/restore-name=star-wars-backup
Annotations:  <none>
Status:       Pending
IP:           10.240.0.93
IPs:
  IP:  10.240.0.93
Init Containers:
  restic-wait:
    Container ID:  containerd://e2c20c3e0d71d3d83e7f77b3eaefc3ba2ce3243a80be3fb9c2030c4c448a7d2f
    Image:         velero/velero-restic-restore-helper:v1.3.1
    Image ID:      docker.io/velero/velero-restic-restore-helper@sha256:5ba97ac1b3a0eb8b20ee29adc79075c022fd8d93d91bb870901f01e7292e8b92
    Port:          <none>
    Host Port:     <none>
    Command:
      /velero-restic-restore-helper
    Args:
      74928d73-db67-4ba3-a7ad-dd9bad2b63de
    State:          Running
      Started:      Tue, 17 Aug 2021 18:58:22 +0530
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      POD_NAMESPACE:  star-wars (v1:metadata.namespace)
      POD_NAME:       mypod (v1:metadata.name)
    Mounts:
      /restores/kube-api-access-2fq8l from kube-api-access-2fq8l (rw)
      /restores/volume from volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2fq8l (ro)
Containers:
  mypod:
    Container ID:
    Image:          mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     250m
      memory:  256Mi
    Requests:
      cpu:        100m
      memory:     128Mi
    Environment:  <none>
    Mounts:
      /mnt/azure from volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2fq8l (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  azure-managed-disk
    ReadOnly:   false
  kube-api-access-2fq8l:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason                  Age   From                     Message
  ----    ------                  ----  ----                     -------
  Normal  Scheduled               34m   default-scheduler        Successfully assigned star-wars/mypod to aks-workerl63l0-96403094-vmss000001
  Normal  SuccessfulAttachVolume  34m   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-e32b35a8-0d04-4a7c-8b86-eb0841f88c31"
  Normal  Pulled                  34m   kubelet                  Container image "velero/velero-restic-restore-helper:v1.3.1" already present on machine
  Normal  Created                 34m   kubelet                  Created container restic-wait
  Normal  Started                 34m   kubelet                  Started container restic-wait
```

**Backup**
kg backup stars-wars-backup -o yaml
```
status:
  completionTimestamp: "2021-08-17T13:26:25Z"
  expiration: "2021-09-16T23:25:55Z"
  formatVersion: 1.1.0
  phase: Completed
  progress:
    itemsBackedUp: 403
    totalItems: 403
```

**Restore**
kg restore stars-wars-backup -o yaml
```
status:
  completionTimestamp: "2021-08-17T13:28:35Z"
  errors: 4
  phase: PartiallyFailed
  progress:
    itemsRestored: 391
    totalItems: 391
```
As it can be seen 4 items failed to restore.

So, I checked podvolumerestore.

kg podvolumerestore
```
NAME                     AGE
star-wars-backup-6qxt2   20m
star-wars-backup-gwpr9   20m
```

kg podvolumerestore star-wars-backup-6qxt2 -o yaml
```
spec:
  backupStorageLocation: default
  pod:
    kind: Pod
    name: mypod
    namespace: star-wars
    uid: e1275cf9-1870-45ae-9cc1-90cfae13ff2a
  repoIdentifier: s3:s3-us-east-1.amazonaws.com/valero-rishi/6100c6e0705a5aee89887cfb/restic/star-wars
  snapshotID: a9b6353d
  volume: volume
status:
  completionTimestamp: "2021-08-17T13:28:31Z"
  phase: Completed
  progress:
    bytesDone: 524288000
    totalBytes: 524288000
  startTimestamp: "2021-08-17T13:28:22Z"
```

However, I am getting the below error while describing other volume restores:

kg podvolumerestore star-wars-backup-gwpr9 -o yaml
```
  message: |-
    error restoring volume: error running restic restore, cmd=restic restore --repo=s3:s3-us-east-1.amazonaws.com/valero-rishi/6100c6e0705a5aee89887cfb/restic/star-wars --password-file=/tmp/credentials/cluster-6100c6e0705a5aee89887cfb/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic 5283dfa2 --target=., stdout=restoring <Snapshot 5283dfa2 of [/host_pods/c5da3ecf-9315-4c17-b0f0-5e87bb604506/volumes/kubernetes.io~projected/kube-api-access-2fq8l] at 2021-08-17 13:26:20.862000162 +0000 UTC by root@velero> to .
    , stderr=ignoring error for /..data: Symlink: symlink ..2021_08_17_13_23_42.294406962 /host_pods/e1275cf9-1870-45ae-9cc1-90cfae13ff2a/volumes/kubernetes.io~projected/kube-api-access-2fq8l/..data: file exists
    ignoring error for /ca.crt: Symlink: symlink ..data/ca.crt /host_pods/e1275cf9-1870-45ae-9cc1-90cfae13ff2a/volumes/kubernetes.io~projected/kube-api-access-2fq8l/ca.crt: file exists
    ignoring error for /namespace: Symlink: symlink ..data/namespace /host_pods/e1275cf9-1870-45ae-9cc1-90cfae13ff2a/volumes/kubernetes.io~projected/kube-api-access-2fq8l/namespace: file exists
    ignoring error for /token: Symlink: symlink ..data/token /host_pods/e1275cf9-1870-45ae-9cc1-90cfae13ff2a/volumes/kubernetes.io~projected/kube-api-access-2fq8l/token: file exists
    Fatal: There were 4 errors

    : exit status 1
  phase: Failed
 ```

The logs of velero and restic pods showing the same error.

**Environment:**

- Velero version (use `velero version`):  1.6.3
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.21.2
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
