### ISSUE TITLE
CRD backup should have status.conditions

### ISSUE THREAD

**Issue by elwood218** [vmware-tanzu/velero#4069]
**Describe the problem/challenge you have**
Following issue I got:
I am using an Ansible module which can wait for a condition to complete. It is usable for a `job` resource for example because it has this section `status.conditions`:
```
kubectl get job mysqldump-dev -o yaml
...
...
status:
  completionTime: "2021-03-10T10:16:46Z"
  conditions:
  - lastProbeTime: "2021-03-10T10:16:46Z"
    lastTransitionTime: "2021-03-10T10:16:46Z"
    status: "True"
    type: Complete
  startTime: "2021-03-10T10:15:55Z"
  succeeded: 1
```

The velero `backup` resource which is kinda a job doesn't have this section:

```
kubectl get backups.velero.io gke-upgrade-1.18 -o yaml
...
...
status:
  completionTimestamp: "2021-08-26T09:23:38Z"
  expiration: "2021-08-31T09:22:00Z"
  formatVersion: 1.1.0
  phase: Completed
  progress:
    itemsBackedUp: 2456
    totalItems: 2456
  startTimestamp: "2021-08-26T09:22:00Z"
  version: 1
  volumeSnapshotsAttempted: 11
  volumeSnapshotsCompleted: 11
```

**Describe the solution you'd like**
Is it possible to add the section `status.conditions` to the CRD `backup` ?

**Anything else you would like to add:**

**Environment:**

- helm version (use `helm version`): 
```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
```
NAME             	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                       	APP VERSION
velero           	aux      	5       	2021-08-26 11:12:35.847132 +0200 CEST  	deployed	velero-2.23.6               	1.6.3
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-gke.501", GitCommit:"de876a981b936ce528482c45794fb1dfc5005042", GitTreeState:"clean", BuildDate:"2021-06-25T02:54:31Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.18) exceeds the supported minor version skew of +/-1
```
- Kubernetes installer & version:
??
- Cloud provider or hardware configuration: 
GKE
- OS (e.g. from `/etc/os-release`):
