### ISSUE TITLE
restore with exclude pv, pvc from a full backup will hang

### ISSUE THREAD

**Issue by half-life666** [vmware-tanzu/velero#4145]
**What steps did you take and what happened:**
1. Create a backup with no excludes (has 2 PVs)
2. Delete the namespace
3. Create a restore with excludes: "persistentvolumes" and "persistentvolumeclaims"
4. velero restore will hang at podvolumerestore (which shouldn't happen?)

**What did you expect to happen:**
velero restore should not hang 

**The output of the following commands will help us better understand what's going on**:
restore CR:
```
spec:
  backupName: test-7dddm
  excludedResources:
  - persistentvolumes
  - persistentvolumeclaims
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  hooks: {}
  namespaceMapping:
    wordpress: wp-restore1
  restorePVs: false
status:
  phase: InProgress
  progress:
    itemsRestored: 17
    totalItems: 17
  startTimestamp: "2021-09-11T15:09:11Z"
```

podvolumerestore
```
apiVersion: velero.io/v1
kind: PodVolumeRestore
metadata:
  creationTimestamp: "2021-09-11T15:09:12Z"

...


spec:
  backupStorageLocation: test-s3-k67t7
  pod:
    kind: Pod
    name: wordpress-mysql-79884bb86c-2lvzc
    namespace: wp-restore1
    uid: e61ac8cf-50ac-45c3-8815-6ab140d6ae46
  repoIdentifier: xxxxxxx
  snapshotID: fd618e15
  volume: mysql-persistent-storage
status:
  progress: {}

```

**Anything else you would like to add:**
Looks like below condition should consider the fact that the pv & pvcs are excluded:

```go
	if groupResource == kuberesource.Pods && len(restic.GetVolumeBackupsForPod(ctx.podVolumeBackups, obj, originalNamespace)) > 0 {
		restorePodVolumeBackups(ctx, createdObj, originalNamespace)
	}

```

**Environment:**

- Velero version (use `velero version`):  v1.6.3
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:18:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.5", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"clean", BuildDate:"2020-12-09T11:10:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
