### ISSUE TITLE
Azure - Velero not restoring in proper Availability Zone

### ISSUE THREAD

**Issue by jemag** [vmware-tanzu/velero#4154]
**What steps did you take and what happened:**

Created an AKS cluster with availability zones. Here you can see disk being in a specific availability zone:
![image](https://user-images.githubusercontent.com/7985687/133676250-8d8ba854-039a-4ddd-9490-697f1e962f69.png)
And nodes having the zone labels:
![image](https://user-images.githubusercontent.com/7985687/133676346-6be0d3a0-0efc-43c9-9079-801dd6fd996e.png)
 then did a whole cluster backup with: 
`velero backup create cluster`
Deleted namespace and resources using PVs, then restored with 
`velero restore create --from-backup cluster`

After the restore the PVs are restored without being in the proper availability zone as can be seen by : 

![no-availability-zone](https://user-images.githubusercontent.com/7985687/133676439-bcfbec5e-8159-404b-8ab2-9f4373a8e6b3.png)
Therefore pods failing to attach the disks:

![attach-failed](https://user-images.githubusercontent.com/7985687/133676478-e8a9fb5a-ed5b-487c-8adb-b150cf006bf3.png)

Investigating further, I noticed that PVs do not have zone labels before backup:
![image](https://user-images.githubusercontent.com/7985687/133676614-37421ea2-06dc-4244-8b34-b6847fec1999.png)

Also logs seem to show that velero might be looking for such labels:
```
time="2021-09-16T19:12:18Z" level=info msg="label \"topology.kubernetes.io/zone\" is not present on PersistentVolume, checking deprecated label..." backup=velero/cluster logSource="pkg/backup/item_backupper.go:432" name=pvc-d51449db-d1da-4173-a48c-f47baf4aee3f namespace= persistentVolume=pvc-d51449db-d1da-4173-a48c-f47baf4aee3f resource=persistentvolumes
time="2021-09-16T19:12:18Z" level=info msg="label \"failure-domain.beta.kubernetes.io/zone\" is not present on PersistentVolume" backup=velero/cluster logSource="pkg/backup/item_backupper.go:435" name=pvc-d51449db-d1da-4173-a48c-f47baf4aee3f namespace= persistentVolume=pvc-d51449db-d1da-4173-a48c-f47baf4aee3f resource=persistentvolumes
time="2021-09-16T19:12:45Z" level=info msg="label \"topology.kubernetes.io/zone\" is not present on PersistentVolume, checking deprecated label..." backup=velero/cluster logSource="pkg/backup/item_backupper.go:432" name=pvc-9d2f286b-035e-452f-a829-028a60356799 namespace= persistentVolume=pvc-9d2f286b-035e-452f-a829-028a60356799 resource=persistentvolumes
time="2021-09-16T19:12:45Z" level=info msg="label \"failure-domain.beta.kubernetes.io/zone\" is not present on PersistentVolume" backup=velero/cluster logSource="pkg/backup/item_backupper.go:435" name=pvc-9d2f286b-035e-452f-a829-028a60356799 namespace= persistentVolume=pvc-9d2f286b-035e-452f-a829-028a60356799 resource=persistentvolumes
time="2021-09-16T19:12:55Z" level=info msg="label \"topology.kubernetes.io/zone\" is not present on PersistentVolume, checking deprecated label..." backup=velero/cluster logSource="pkg/backup/item_backupper.go:432" name=pvc-275a09f7-af4b-4cc1-a1d2-c729c0b04f57 namespace= persistentVolume=pvc-275a09f7-af4b-4cc1-a1d2-c729c0b04f57 resource=persistentvolumes
time="2021-09-16T19:12:55Z" level=info msg="label \"failure-domain.beta.kubernetes.io/zone\" is not present on PersistentVolume" backup=velero/cluster logSource="pkg/backup/item_backupper.go:435" name=pvc-275a09f7-af4b-4cc1-a1d2-c729c0b04f57 namespace= persistentVolume=pvc-275a09f7-af4b-4cc1-a1d2-c729c0b04f57 resource=persistentvolumes
time="2021-09-16T19:13:06Z" level=info msg="label \"topology.kubernetes.io/zone\" is not present on PersistentVolume, checking deprecated label..." backup=velero/cluster logSource="pkg/backup/item_backupper.go:432" name=pvc-aa802594-67a4-45cd-a62f-437d03227626 namespace= persistentVolume=pvc-aa802594-67a4-45cd-a62f-437d03227626 resource=persistentvolumes
time="2021-09-16T19:13:06Z" level=info msg="label \"failure-domain.beta.kubernetes.io/zone\" is not present on PersistentVolume" backup=velero/cluster logSource="pkg/backup/item_backupper.go:435" name=pvc-aa802594-67a4-45cd-a62f-437d03227626 namespace= persistentVolume=pvc-aa802594-67a4-45cd-a62f-437d03227626 resource=persistentvolumes
time="2021-09-16T19:13:16Z" level=info msg="label \"topology.kubernetes.io/zone\" is not present on PersistentVolume, checking deprecated label..." backup=velero/cluster logSource="pkg/backup/item_backupper.go:432" name=geoserver-storage-pv namespace= persistentVolume=geoserver-storage-pv resource=persistentvolumes
time="2021-09-16T19:13:16Z" level=info msg="label \"failure-domain.beta.kubernetes.io/zone\" is not present on PersistentVolume" backup=velero/cluster logSource="pkg/backup/item_backupper.go:435" name=geoserver-storage-pv namespace= persistentVolume=geoserver-storage-pv resource=persistentvolumes
```

**What did you expect to happen:**

Backup restore PV in proper Availability Zone.

**Anything else you would like to add:**
Not quite sure if Velero has the ability to check the Azure resources themselves to verify their Availability Zone or if it is 100% dependent on labels. If it is dependent on labels, are we supposed to create such labels manually for each PV? 

**Environment:**

- Velero version (use `velero version`): 

> Client:
>         Version: v1.6.3
>         Git commit: 5fe3a50bfddc2becb4c0bd5e2d3d4053a23e95d2
> Server:
>         Version: v1.6.3

Using following velero plugin for azure: 
> velero/velero-plugin-for-microsoft-azure:v1.2.1

- Velero features (use `velero client config get features`): 

> features: <NOT SET>

- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"0b17c6315e806a66d507e77760a5d60ab5cccfd8", GitTreeState:"clean", BuildDate:"2021-08-30T01:42:22Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
AKS
- Cloud provider or hardware configuration:
AKS
- OS (e.g. from `/etc/os-release`):

> NAME="Ubuntu"
> VERSION="18.04.5 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04.5 LTS"
> VERSION_ID="18.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
The support for CSI volumes is added by https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/109, closing this issue

**Comment by jemag** [comment]
@ywk253100 original issue message mentions "managed-premium" storage class which uses "kubernetes.io/azure-disk" and not csi provisioner:
```yaml
allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    creationTimestamp: "2021-10-27T14:52:28Z"
    labels:
      addonmanager.kubernetes.io/mode: EnsureExists
      kubernetes.io/cluster-service: "true"
    name: managed-premium
    resourceVersion: "384"
    uid: b8f74914-7254-4aa0-bdf5-2579b42845dc
  parameters:
    cachingmode: ReadOnly
    kind: Managed
    storageaccounttype: Premium_LRS
  provisioner: kubernetes.io/azure-disk
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
```

I did try to test again using the latest image for the initContainers, but that did not help:
```yaml
 initContainers:
        - image: velero/velero-plugin-for-microsoft-azure:latest
          imagePullPolicy: IfNotPresent
          name: velero-plugin-for-azure
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /target
            name: plugins
        - image: velero/velero-plugin-for-csi:latest
          imagePullPolicy: IfNotPresent
          name: velero-plugin-for-csi
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /target
            name: plugins
```
The persistent volumes are still not restored in proper availability zone:
![image](https://user-images.githubusercontent.com/7985687/145075583-964b153c-f00c-48fc-9feb-d33884d9fa5b.png)
Which will prevent volume being attached properly once again:
![image](https://user-images.githubusercontent.com/7985687/145075762-40223958-722d-4be1-b571-e347124c10e0.png)


Is there some more manipulation that needs to be done other than using the latest image? Otherwise it does not seem to be fixed.

**Comment by ywk253100** [comment]
@jemag Please try `velero/velero-plugin-for-microsoft-azure:main` instead, the image with `latest` tag is the latest released version, but the fix is only included in the dev build at this moment.

The [CSIMigration](https://kubernetes.io/docs/concepts/storage/volumes/#azuredisk-csi-migration) feature is enabled by default for my testing AKS cluster which redirects all plugin operations from the existing in-tree plugin to the disk.csi.azure.com Container Storage Interface (CSI) Driver. You can confirm whether this is your case by checking the PV YAML, there should be some CSI stuff in the PV spec.

**Comment by jemag** [comment]
@ywk253100 Thank you for the clarification. However, after switching to the "main" version of the image the problem still happens. From current velero deployment:
```yaml
initContainers:
        - image: velero/velero-plugin-for-microsoft-azure:main
          imagePullPolicy: IfNotPresent
          name: velero-plugin-for-azure
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /target
            name: plugins
        - image: velero/velero-plugin-for-csi:main
          imagePullPolicy: IfNotPresent
          name: velero-plugin-for-csi
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /target
            name: plugins
```
Restored disk availability zone:
![image](https://user-images.githubusercontent.com/7985687/145256633-7401a0f7-563a-4e3b-91a8-8cab67f5a25b.png)
attach error: 
![image](https://user-images.githubusercontent.com/7985687/145256918-3c74243b-46dd-49dc-b58e-c02a6e5c4bf2.png)
