### ISSUE TITLE
PVC Backup fails for the cluster behind proxy with Restic error: `Restic repository is not ready` - velero failed to get the region automatically

### ISSUE THREAD

**Issue by aayushrangwala** [vmware-tanzu/velero#4178]
**What steps did you take and what happened:**
Have a cluster behind mitmproxy with ssl interception disabled. Installed a few pods with PVC and annotated with the Restic required annotations as needed based on the opt-in approach from the docs

Triggered a backup for the pods with PVC but it fails partially with  below error and also attached the logs

```time="2021-09-22T08:24:12Z" level=info msg="1 errors encountered backup up item" backup=velero/test-bkp-2 logSource="pkg/backup/backup.go:427" name=my-release-mysql-0
time="2021-09-22T08:24:12Z" level=error msg="Error backing up item" backup=velero/test-bkp-2 error="restic repository is not ready: error running command=restic init --repo=s3:s3.amazonaws.com/vmware-tmc-dp-6b5deb3b/01FFSAT8CESNMHZ8CNZA2QJB7W/restic/default --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cacert=/tmp/cacert-test-cred-dp-unstable765229072 --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: create repository at s3:s3.amazonaws.com/vmware-tmc-dp-6b5deb3b/01FFSAT8CESNMHZ8CNZA2QJB7W/restic/default failed: client.BucketExists: Head \"https://vmware-tmc-dp-6b5deb3b.s3.dualstack.us-east-1.amazonaws.com/\": 301 response missing Location header\n\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_ensurer.go:144" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryEnsurer).EnsureRepo" logSource="pkg/backup/backup.go:431" name=my-release-mysql-0
```

Logs here
https://gist.github.com/aayushrangwala/9c219a633608445ffc4c19b8de931a28

**What did you expect to happen:**
Backup Should have completed successfully with Restic

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```Name:         test-bkp-2
Namespace:    velero
Labels:       tmc.cloud.vmware.com/creator=arangwala
              tmc.cloud.vmware.com/managed=true
              velero.io/storage-location=test-cred-dp-unstable
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.20.4+vmware.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=20

Phase:  PartiallyFailed (run `velero backup logs test-bkp-2` for more information)

Errors:    1
Warnings:  2

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  test-cred-dp-unstable

Velero-Native Snapshot PVs:  auto

TTL:  24h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-09-22 13:53:58 +0530 IST
Completed:  2021-09-22 13:54:22 +0530 IST

Expiration:  2021-09-23 13:53:57 +0530 IST

Total items to be backed up:  1399
Items backed up:              1399

Velero-Native Snapshots: <none included>
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Command used for annotation
`kubectl -n default annotate pod/my-release-mysql-0 backup.velero.io/backup-volumes=data`

Pod yaml
```
apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      backup.velero.io/backup-volumes: data
      checksum/configuration: 110ee66c883b1a28896eda2d7af9415f80a10bcab0f1713320fbec73cf0e1dea
    labels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: my-release
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mysql
      controller-revision-hash: my-release-mysql-67846b59b8
      helm.sh/chart: mysql-8.8.7
      statefulset.kubernetes.io/pod-name: my-release-mysql-0
    name: my-release-mysql-0
    namespace: default
  spec:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: primary
                app.kubernetes.io/instance: my-release
                app.kubernetes.io/name: mysql
            namespaces:
            - default
            topologyKey: kubernetes.io/hostname
          weight: 1
    containers:
    - env:
      - name: BITNAMI_DEBUG
        value: "false"
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            key: mysql-root-password
            name: my-release-mysql
      - name: MYSQL_DATABASE
        value: my_database
      image: docker.io/bitnami/mysql:8.0.26-debian-10-r31
      livenessProbe:
        exec:
          command:
          - /bin/bash
          - -ec
          - |
            password_aux="${MYSQL_ROOT_PASSWORD:-}"
            if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
            fi
            mysqladmin status -uroot -p"${password_aux}"
        initialDelaySeconds: 5
      name: mysql
      ports:
      - containerPort: 3306
        name: mysql
      readinessProbe:
        exec:
          command:
          - /bin/bash
          - -ec
          - |
            password_aux="${MYSQL_ROOT_PASSWORD:-}"
            if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
            fi
            mysqladmin status -uroot -p"${password_aux}"
        initialDelaySeconds: 5
      securityContext:
        runAsUser: 1001
      startupProbe:
        exec:
          command:
          - /bin/bash
          - -ec
          - |
            password_aux="${MYSQL_ROOT_PASSWORD:-}"
            if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
            fi
            mysqladmin status -uroot -p"${password_aux}"
        failureThreshold: 10
        initialDelaySeconds: 15
      volumeMounts:
      - mountPath: /bitnami/mysql
        name: data
      - mountPath: /opt/bitnami/mysql/conf/my.cnf
        name: config
        subPath: my.cnf
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: my-release-mysql-token-ptdkb
        readOnly: true
    hostname: my-release-mysql-0
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    securityContext:
      fsGroup: 1001
    serviceAccountName: my-release-mysql
    subdomain: my-release-mysql
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-my-release-mysql-0
    - configMap:
        name: my-release-mysql
      name: config
    - name: my-release-mysql-token-ptdkb
      secret:
        secretName: my-release-mysql-token-ptdkb
```

Proxy Information: Mitmproxy with custom CA cert. Certificate is base64 encoded and added to the velero BackupStorageLocation in its spec

BSL below:

```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  labels:
    tmc.cloud.vmware.com/creator: vmware-tmc-dp
    tmc.cloud.vmware.com/managed: "true"
    tmc.cloud.vmware.com/uid: 01FG1JD22YCKA03X8EGMR6F17S
  name: test-cred-dp-unstable
  namespace: velero
spec:
  config:
    bucket: vmware-tmc-dp-6b5deb3b
    profile: test-cred-dp-unstable
    region: us-east-2
    s3ForcePathStyle: "false"
  objectStorage:
    bucket: vmware-tmc-dp-6b5deb3b
    caCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROVENDQWgyZ0F3SUJBZ0lVU2pVeWtZZy92aE14NkZEZHlHUGV3dGh
...
...
<base64 encoded cacert>
    prefix: 01FFSAT8CESNMHZ8CNZA2QJB7W/
  provider: aws
```

Restic Repository CR

```
apiVersion: velero.io/v1
  kind: ResticRepository
  metadata:
    labels:
      velero.io/storage-location: test-cred-dp-unstable
      velero.io/volume-namespace: default
    name: default-test-cred-dp-unstable-c7g8n
    namespace: velero
  spec:
    backupStorageLocation: test-cred-dp-unstable
    maintenanceFrequency: 168h0m0s
    resticIdentifier: s3:s3.amazonaws.com/vmware-tmc-dp-6b5deb3b/01FFSAT8CESNMHZ8CNZA2QJB7W/restic/default
    volumeNamespace: default
```

**Environment:**

- Velero version (use `velero version`):  v1.6.3
- Velero features (use `velero client config get features`):  features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.20.2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
