### ISSUE TITLE
aws-plugin Region is not optional when s3url is defined.

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#4305]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Defining BSL with AWS provider plugin with s3url defined (ie. minio etc) without specifying any aws region

Region should become irrelevant when custom endpoint is defined.
**What did you expect to happen:**
BSL has status Available

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

```
time="2021-11-01T19:35:04Z" level=warning msg="Unavailable backup storage locations detected: available/unavailable/unknown: 1/1/0, Backup storage location \"example-no-region\" is unavailable: rpc error: code = Unknown desc = MissingRegion: could not find region configuration)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:169"
time="2021-11-01T19:35:04Z" level=warning msg="Unavailable backup storage locations detected: available/unavailable/unknown: 1/1/0, )" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:169"
time="2021-11-01T19:35:04Z" level=warning msg="Unavailable backup storage locations detected: available/unavailable/unknown: 1/1/0, )" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:169"
time="2021-11-01T19:35:12Z" level=error msg="Error listing backups in backup store" backupLocation=example-no-region controller=backup-sync error="rpc error: code = Unknown desc = MissingRegion: could not find region configuration" error.file="/opt/app-root/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:377" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:182"
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
BSL Yaml
```yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  generation: 3
  labels:
    openshift.io/oadp: 'True'
  name: example-no-region
  namespace: openshift-adp
spec:
  backupSyncPeriod: 2m0s
  config:
    profile: default
    s3ForcePathStyle: 'true'
    s3Url: 'http://s3.openshift-storage.svc/'
  credential:
    key: cloud
    name: cloud-credentials
  default: true
  objectStorage:
    bucket: migstorage
    prefix: velero
  provider: aws
status:
  lastSyncedTime: '2021-11-01T19:32:49Z'
  lastValidationTime: '2021-11-01T19:35:04Z'
  phase: Unavailable
```

Contrast this to not specifying region for aws native bucket (no s3url defined) the BSL is valid and available.
```yaml
spec:
  backupSyncPeriod: 2m0s
  config:
    profile: default
  credential:
    key: cloud
    name: cloud-credentials
  default: true
  objectStorage:
    bucket: aws-bucket-name
    prefix: velero
  provider: aws
```
It is counter intuitive for region to be optional for aws native but not for custom endpoint.

**Environment:**

- Velero version (use `velero version`): 1.7
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version: 1.22
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
