### ISSUE TITLE
Memory usage keeps increasing unbounded

### ISSUE THREAD

**Issue by fullpolarfox** [vmware-tanzu/velero#4473]
**What steps did you take and what happened:**
We use helm-chart and update velero version from 1.5.3 to 1.7.0. For now we use helm-chart with tag 2.26.2. After update we observed that the memory usage of the velero pod keeps increasing.
We set memory limit to 60G and see that memory usage increasing unbounded. This is usage for 14d

![v](https://user-images.githubusercontent.com/48081250/147190177-6aad9471-6975-4cd7-ba89-08b05af0a77d.jpg)

**Environment:**

- Velero version (use `velero version`): v1.7.0
- Kubernetes version (use `kubectl version`): v1.19.12

**Comment by fullpolarfox** [comment]
What additional information can i give to you for investigation?

**Comment by qiuming-best** [comment]
@fullpolarfox Cloud you provide your OS info, cloud provider info, and your daily operations related to velero, some useful logs, etc if you have, thank you

**Comment by fullpolarfox** [comment]
We use local minio for pv snapshot
This is values for helm release:
```
  values:
    upgradeCRDs: false       
    resources: 
      limits:
        memory: 10Gi
    configuration:
      provider: aws
      backupStorageLocation:
        bucket: velero
        config:
          region: minio
          s3ForcePathStyle: true
          s3Url: http://***:9000
          publicUrl: http://***:9000
    deployRestic: true
    snapshotsEnabled: false
    credentials:
      existingSecret: cloud-credentials
    configuration:
      resticTimeout: 12h
      provider: aws
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.3.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
```
CRDs upgraded via flux from charts/velero/crds

Total backuped items is about 42000. Backup ttl is 7d and volume about 80G. Schedule plan is '@every 24h'
All logs with no errors
