### ISSUE TITLE
Velero cannot restore secrets-store volume because file already exists

### ISSUE THREAD

**Issue by admincasper** [vmware-tanzu/velero#4621]
**What steps did you take and what happened:**
1. I create a backup of all resources in my namespace with:
```YAML
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ns-monitoring-backup-test
  namespace: velero
spec:
  storageLocation: monitoring-backupstoragelocation
  defaultVolumesToRestic: true
  includedNamespaces:
  - monitoring
  ttl: 720h0m0s
```
Among the backup files is the `secretproviderclass` _monitoring/grafana-enterprise-app-secrets_. 
There are mounted secrets in the Grafana pod, which again will load the secrets into env variables, specifically Grafana client id and secret. 
This backup will also backup the volumes _secrets-store-inline_, _storage_ successfully using Restic.

2. I delete the namespace to test if I can restore successfully. 
`k delete ns monitoring`

3. I restore using:
```YAML
apiVersion: velero.io/v1
kind: Restore
metadata:
  creationTimestamp: null
  name: ns-monitoring-backup-test-restore
  namespace: velero
spec:
  backupName: ns-monitoring-backup-test
  hooks: {}
  includedNamespaces:
  - '*'
status: {}
```

I suspect the secretproviderclass is created before the _secrets-store-inline_ volume. Which mounts the secrets in the volume immediately? But I am not sure.

I get the following error msg when running `velero restore logs ns-monitoring-backup-test-restore`:
```YAML 
time="2022-02-07T11:18:16Z" level=error msg="unable to successfully complete restic restores of pod's volumes" 
error="pod volume restore failed: error restoring volume: error running restic restore, cmd=restic restore 

--repo=azure:velero-backup:/monitoring/restic/monitoring --target=., stdout=restoring 
<Snapshot X of [X/volumes/kubernetes.io~csi/secrets-store-inline/mount] at 2022-02-07 10:52:28.522321841 +0000 UTC by root@velero> to .\n
, stderr=ignoring error for /..data: Symlink: symlink ..2022_02_07_10_43_43.2956431277 
X/volumes/kubernetes.io~csi/secrets-store-inline/mount/..data: file exists\n
ignoring error for /grafana-client-id: Symlink: symlink ..data/grafana-client-id 
X/volumes/kubernetes.io~csi/secrets-store-inline/mount/grafana-client-id: file exists\n
ignoring error for /grafana-client-secret: Symlink: symlink ..data/grafana-client-secret 
X/volumes/kubernetes.io~csi/secrets-store-inline/mount/grafana-client-secret: file exists\n
Fatal: There were 3 errors
: exit status 1" logSource="pkg/restore/restore.go:1433" restore=velero/ns-monitoring-backup-test-restore
```

Logs of the init-container gives me:
```YAML
Not found: /restores/secrets-store-inline/.velero/83b73e35-8b79-49fb-9ccc-a68917acb20d
Not found: /restores/secrets-store-inline/.velero/83b73e35-8b79-49fb-9ccc-a68917acb20d
Not found: /restores/secrets-store-inline/.velero/83b73e35-8b79-49fb-9ccc-a68917acb20d
Not found: /restores/secrets-store-inline/.velero/83b73e35-8b79-49fb-9ccc-a68917acb20d
Not found: /restores/secrets-store-inline/.velero/83b73e35-8b79-49fb-9ccc-a68917acb20d
```

The restic-wait init-container never finishes.

**What did you expect to happen:**
Secrets store volume to restore successfully.

**The following information will help us better understand what's going on**:
[bundle-2022-02-07-12-56-03.tar.gz](https://github.com/vmware-tanzu/velero/files/8015047/bundle-2022-02-07-12-56-03.tar.gz)

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
Client:
        Version: v1.7.0
        Git commit: 9e52260568430ecb77ac38a677ce74267a8c2176
Server:
        Version: v1.7.1
- Velero features (use `velero client config get features`): 
features: <NOT SET>
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", 
GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", 
GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
AKS, 1.21.2
- Cloud provider or hardware configuration:
Azure, Windows 10 (WSL2).
- OS (e.g. from `/etc/os-release`):
 Ubuntu 20.04.2 LTS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
