### ISSUE TITLE
Restore is stuck when there is an unsupported volume

### ISSUE THREAD

**Issue by 27149chen** [vmware-tanzu/velero#4644]
**What steps did you take and what happened:**
try to restore a deployment which has a nfs volume, velero is stuck and time out after 4 hours
```
volumes:
    - name: nfs-client-root
      nfs:
        path: /
        server: 192.168.0.8
```

**What did you expect to happen:**
restore successfully.

**The following information will help us better understand what's going on**:
I can see the podvolumebackup and podvolumerestore are created successfully, the podvolumebackup status looks well, but the podvolumerestore not.

```
status:
  completionTimestamp: "2022-02-09T09:49:12Z"
  path: /host_pods/063cd6e3-c923-4164-936c-ba07844bc8c7/volumes/kubernetes.io~nfs/nfs-client-root
  phase: Completed
  progress:
    bytesDone: 278691015
    totalBytes: 278691015
  snapshotID: 1ff9375a
  startTimestamp: "2022-02-09T09:48:54Z"
```

The podvolumerestore seems never to be procressed:
```
apiVersion: velero.io/v1
kind: PodVolumeRestore
metadata:
  creationTimestamp: "2022-02-15T03:29:18Z"
  labels:
    velero.io/pod-uid: ba264969-fd0a-4100-a3d3-4236df17ddad
    velero.io/restore-name: resume-6kog3-f6sp5
    velero.io/restore-uid: cfc2f8ba-c386-4564-b469-6e315b1283db
  name: resume-6kog3-f6sp5-xmvk4
spec:
  backupStorageLocation: 391884229560008845-kp426
  pod:
    kind: Pod
    name: nfs-client-provisioner-759c778f55-v9hq8
    namespace: default
    uid: ba264969-fd0a-4100-a3d3-4236df17ddad
  repoIdentifier: s3:https://xxx/online-bucket-391723538626674829-tzjko/391901517239582861/restic/default
  snapshotID: 1ff9375a
  volume: nfs-client-root
status:
  progress: {}
```

here is the releated logs:
```
time="2022-02-15T07:29:10Z" level=info msg="Validating backup storage location" backup-storage-location=391884229560008845-xv9hf controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:114"
time="2022-02-15T07:29:11Z" level=info msg="Backup storage location valid, marking as available" backup-storage-location=391884229560008845-xv9hf controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:121"
time="2022-02-15T07:29:11Z" level=info msg="Validating backup storage location" backup-storage-location=391884229560008845-hqvpd controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:114"
time="2022-02-15T07:29:11Z" level=info msg="Backup storage location valid, marking as available" backup-storage-location=391884229560008845-hqvpd controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:121"
time="2022-02-15T07:29:16Z" level=error msg="unable to successfully complete restic restores of pod's volumes" error="timed out waiting for all PodVolumeRestores to complete" logSource="pkg/restore/restore.go:1433" restore=qiming-backend/resume-6kog3-f6sp5
time="2022-02-15T07:29:16Z" level=info msg="Done waiting for all restic restores to complete" logSource="pkg/restore/restore.go:562" restore=qiming-backend/resume-6kog3-f6sp5
time="2022-02-15T07:29:16Z" level=info msg="Waiting for all post-restore-exec hooks to complete" logSource="pkg/restore/restore.go:566" restore=qiming-backend/resume-6kog3-f6sp5
time="2022-02-15T07:29:16Z" level=info msg="Done waiting for all post-restore exec hooks to complete" logSource="pkg/restore/restore.go:574" restore=qiming-backend/resume-6kog3-f6sp5
time="2022-02-15T07:29:16Z" level=info msg="restore completed" logSource="pkg/controller/restore_controller.go:480" restore=qiming-backend/resume-6kog3-f6sp5
```

**Environment:**

- Velero version (use `velero version`): 1.7.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.19
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
