### ISSUE TITLE
Restic RAM usage goes through the roof

### ISSUE THREAD

**Issue by brovoca** [vmware-tanzu/velero#4648]
**What steps did you take and what happened:**

Upon running Restic backups of our Jenkins instances, the memory usage goes through the roof effectively making Restic useless for us. Unfortunately this severely affects the usability of Velero too.

```sh
velero backup create --from-schedule jenkins
```

Result:
![2022-02-15_14-39](https://user-images.githubusercontent.com/95472556/154073424-afe90ff1-bb1f-4c81-809e-1347d02b6df9.png)

The biggest Jenkins instance which is seen in the metrics below has 97k total amount of directories and 2,315,795 (2.3 million) files. The biggest directory in terms of file count contains 2484 files (non-recursive). The total volume size is 14G and we're backing it up to Azure Files.

**What did you expect to happen:**

To have reasonable memory usage for backup operations.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

[bundle-2022-02-15-14-27-27.tar.gz](https://github.com/vmware-tanzu/velero/files/8069433/bundle-2022-02-15-14-27-27.tar.gz)

**Anything else you would like to add:**

Using GOGC=1 (or 10) doesn't help at all.

[`helmrelease.yaml`](https://github.com/vmware-tanzu/velero/files/8069484/helmrelease.txt)

`schedule.yaml`:

```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: jenkins
  namespace: velero
spec:
  schedule: "30 0 * * *"
  template:
    includedNamespaces:
      - jenkins
    includedResources:
      - "*"
    snapshotVolumes: false
    storageLocation: default
    ttl: 720h
```

**Environment:**

- Velero version (use `velero version`): v1.7.1 (server)
- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`): v1.22.4
- Kubernetes installer & version: AKS
- Cloud provider or hardware configuration: AKS
- OS (e.g. from `/etc/os-release`): AKS managed

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
