### ISSUE TITLE
velero-plugin-for-gcp v1.4.0 regional storage class: Error attempting to get volume ID for persistent volume

### ISSUE THREAD

**Issue by Bhanukiran117** [vmware-tanzu/velero#4663]
I am getting following error while backup up the regional storage pvc on velero-plugin-for-gcp v1.4.0 where as its working fine in v1.2.0

Error attempting to get volume ID for persistent volume" backup=velero/backup-4 error="rpc error: code = Unknown desc = invalid volumeHandle for CSI driver:pd.csi.storage.gke.io, expected projects/{project}/zones/{zone}/disks/{name}, got projects/sw-gcp/regions/us-west1/disks/pvc-3a5edee8-6e5b-4d3c-8c97-529efc5e101c" logSource="pkg/backup/item_backupper.go:449" name=pvc-3a5edee8-6e5b-4d3c-8c97-529efc5e101c namespace= persistentVolume=pvc-3a5edee8-6e5b-4d3c-8c97-529efc5e101c resource=persistentvolumes volumeSnapshotLocation=default

How ever its taking pvc snapshots.

kubectl describe sc standard-rwo-dup
Name:                  standard-rwo
IsDefaultClass:        Yes
Annotations:           storageclass.kubernetes.io/is-default-class=true
Provisioner:           pd.csi.storage.gke.io
Parameters:            replication-type=regional-pd,type=pd-balanced
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Retain
VolumeBindingMode:     WaitForFirstConsumer
AllowedTopologies:
  Term 0:              topology.gke.io/zone in [us-west1-b, us-west1-a]
Events:                <none>

**Comment by blackpiglet** [comment]
This issue is fixed by two PR:
https://github.com/vmware-tanzu/velero/pull/4680
https://github.com/vmware-tanzu/velero-plugin-for-gcp/pull/84

**Comment by blackpiglet** [comment]
yaml used to reproduce this issue. Need to set replication-type: regional-pd in StorageClass to create regional PV.
``` yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: regional-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    components.gke.io/layer: addon
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    k8s-app: gcp-compute-persistent-disk-csi-driver
  name: regional-standard
parameters:
  type: pd-balanced
  replication-type: regional-pd
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
