### ISSUE TITLE
restore with object metadata.ownerreference and metadata.finalizer

### ISSUE THREAD

**Issue by polym** [vmware-tanzu/velero#4707]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]

In my scene, every deployment or statefulset will have a releated service if it is defined ports in podTemplate. When the deployment or statefulset is deleted, then the service related will be deleted by k8s gc as it has a owner reference to the deployemnt or statefulset.

I use velero to backup and restore for coping namespace from cluster a to cluster b, but I find the service in cluster b doesn't have ownerreference. After searching code, I find that may be releated to `resetMetadataAndStatus` https://github.com/vmware-tanzu/velero/blob/1e24d6ce718fc8fee890db34643e5be361fa5c7d/pkg/restore/restore.go#L1576 which delete all metadata other than name/namespace/labels/annotations. 

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

 restore with ownerreference and finalizer.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Issues or PRs may related:

1.  https://github.com/vmware-tanzu/velero/pull/837/files
2. https://github.com/vmware-tanzu/velero/issues/2632

**Environment:**

- Velero version (use `velero version`):  v1.8.0
- Kubernetes version (use `kubectl version`): v1.23.2
- Kubernetes installer & version: kubeadm-v1.23.2
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`): ubuntu-20.04.1 LTS (Focal Fossa)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by polym** [comment]
Service example:

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-nginx
  namespace: nginx-example
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: deployment
    name: nginx-deployment
    uid: 13b53874-028e-4cc0-8a5f-ac413cb4bba9
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer

```
