### ISSUE TITLE
Hooks on restore with namespace mapping not applied depending on namespace label and hook type (exec/init)

### ISSUE THREAD

**Issue by guillaumefenollar** [vmware-tanzu/velero#4720]
Hello devs, first thank you for this brilliant piece of software !

**What steps did you take and what happened:**
I'm testing Velero restore hooks types with namespace mapping and I saw that the "includedNamespaces" is not targeting the same namespace when the hook type is Exec or Init. To understand this problem easily, let's consider a Restore object (no annotation used on pods directly) with : 
```
- namespaceMapping:
    prod-app1: dev-app1
  hooks:
    resources:
    - includedNamespaces:
      - "dev-app1"    # target namespace after mapping
      postHooks:
      - exec:
        command: (...) # This will be executed and I guess it's expected
    - includedNamespaces:
      - "prod-app1"   # source namespace before mapping
      postHooks:
      - exec:
        command: (...) # This will NOT be executed and I guess it's expected
    - includedNamespaces:
      - "dev-app1"    # target namespace after mapping
      postHooks:
      - init:
          initContainers:
          - (...) # This will be NOT executed (no Init container created) and it's the opposite behavior than with Exec
    - includedNamespaces:
      - "prod-app1"    # source namespace before mapping
      postHooks:
      - init:
          initContainers:
          - (...) # This will be executed (Init container created OK) and it's the opposite behavior than with Exec
```
You got the idea ! Configuration have to be used in opposite way and it's really counter intuitive. I guess it's normal because initContainer may be added before the namespace mapping, although Exec is ran after mapping occured but I find it complicated anyway. So, is it a bug or a feature ?

**What did you expect to happen:**
Exec and Init hooks should behave the same way with same configuration to avoid confusion, or this should be written in documentation somehow.

**Environment:**

- Velero version (use `velero version`): v1.8.0
- Velero features (use `velero client config get features`): Not set
- Kubernetes version (use `kubectl version`): v1.19
- Kubernetes installer & version: Vanilla
- Cloud provider or hardware configuration: Baremetal
- OS (e.g. from `/etc/os-release`): Linux 5

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
