### ISSUE TITLE
Azure CSI Snapshots fails azure tag-policy in v1.8

### ISSUE THREAD

**Issue by joachimm** [vmware-tanzu/velero#4744]
**What steps did you take and what happened:**
After update from Velero 1.7 to 1.8 CSI Snapshots failed due to azure-tags not being applied, causing azure policy to trigger.
As part of the 1.7 to 1.8 I removed the EnableCSI feature flag and removed the CSI plugin and bumped azure plugin to 1.4.

After update I ran:
    velero backup create --from-schedule velero-hourly-pv

This fails with:

time="2022-03-15T12:46:38Z" level=error msg="Error backing up item" backup=velero/velero-hourly-pv-20220315134636 error="error taking snapshot of volume: rpc error: code = Unknown desc = compute.SnapshotsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code=\"RequestDisallowedByPolicy\" Message=\"Resource 'pvc-<cut checksum>' was disallowed by policy. Reasons: 'Tag \\\"created-by\\\" is missing. Please fill it in with your name as value.', ...<Cut but all other tag validations also fail>

**What did you expect to happen:**

Since our VolumeSnapshotClass works fine with 1.7 (and 1.6) and sets the correct azure-tags I expected this to work as previously

```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-azuredisk-vsc
  labels:
    velero.io/csi-volumesnapshot-class: "true"
deletionPolicy: Retain
driver: disk.csi.azure.com
parameters:
  incremental: 'true'
  resourceGroup: rg-experimentation-test-euwest-001
  tags: >-
    created-by="velero.backup",environment="test",owner="team.name",department="Our department"
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
@joachimm in v1.8 we enable the azure plugin to backup volumes provisioned by CSI, could you clarify which plugin caused this error?

**Comment by joachimm** [comment]
The only plugin used is the azure one.

mån 21 mars 2022 kl. 07:14 skrev Daniel Jiang ***@***.***>:

**Comment by reasonerjt** [comment]
@joachimm 
```
The only plugin used is the azure one.
```
You mean you did NOT set the feature flag ` --features=EnableCSI ` in the installation?

**Comment by joachimm** [comment]
Yes I removed that as part of the upgrade.

mån 21 mars 2022 kl. 07:19 skrev Daniel Jiang ***@***.***>:

**Comment by joachimm** [comment]
I read this instructions. Versions 1.4 of the Velero plugins for AWS, Azure and GCP now support snapshotting and restoring the persistent volumes provisioned by CSI driver via the APIs of the cloud providers. With this enhancement, users can backup and restore the persistent volumes on these cloud providers without using the Velero CSI plugin. The CSI plugin will remain beta and the feature flag EnableCSI will be disabled by default.

Specifically the last sentence. Should it be enabled despite the CSI plugin not being used?

**Comment by reasonerjt** [comment]
It should not, it seems an issue within the azure plugin, we'll investigate, thanks.

**Comment by theadzik** [comment]
I have the same problem. Tags are not created on snapshots:

```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  labels:
    velero.io/csi-volumesnapshot-class: "true"
  name: test-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: hostpath.csi.k8s.io
deletionPolicy: Delete
parameters:
```

I added [an annotation](https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/#:~:text=by%20adding%20the-,snapshot.storage.kubernetes.io/is%2Ddefault%2Dclass%3A%20%22true%22,-annotation%3A) but it didn't help.
