### ISSUE TITLE
volume-snapshots not work 

### ISSUE THREAD

**Issue by 631068264** [vmware-tanzu/velero#4852]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

install cmd
```sh
velero install \
   --plugins velero/velero-plugin-for-aws:v1.4.0 \
   --provider aws \
   --bucket velero \
   --namespace velero \
   --secret-file ./credentials-velero \
   --velero-pod-cpu-request 200m \
   --velero-pod-mem-request 200Mi \
   --velero-pod-cpu-limit 1000m \
   --velero-pod-mem-limit 1000Mi \
   --restic-pod-cpu-request 200m \
   --restic-pod-mem-request 200Mi \
   --restic-pod-cpu-limit 1000m \
   --restic-pod-mem-limit 1000Mi \
   --use-restic \
   --use-volume-snapshots=true \
   --snapshot-location-config region=minio \
   --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://xxxx:9000 \
   --wait
```

Use example from `kubectl apply -f examples/nginx-app/with-pv.yaml`
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/8144089/164405038-03e4870f-e41e-4c51-baf0-968c79cb7683.png">

Backup yaml
```yaml
{
   "apiVersion": "velero.io/v1",
   "kind": "Backup",
   "metadata": {
      "name": "nginx-backup-volume-test1",
      "namespace": "velero"
   },
   "spec": {
      "includedNamespaces": [
         "nginx-example"
      ],
      "snapshotVolumes":true
      
      
   }
}
```

restore.yaml
```yaml
{
   "apiVersion": "velero.io/v1",
   "kind": "Restore",
   "metadata": {
      "name": "nginx-backup-volume",
      "namespace": "velero"
   },
   "spec": {
      "backupName": "nginx-backup-volume-test1",
      "includedNamespaces": [
         "nginx-example"
      ],
      "restorePVs": true
   }
}
```

**After restore I can't find  any old log or old file under** `/var/log/nginx`.

All task is Completed without any error or warning.

**Environment:**

- Velero version (use `velero version`):  1.8
- Velero features (use `velero client config get features`):  features: <NOT SET>

- Kubernetes version (use `kubectl version`):   
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version: rke 
- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`): centos 7

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
