### ISSUE TITLE
Azure plugin attempts to list storage account keys when using key-based authentication

### ISSUE THREAD

**Issue by vzabawski** [vmware-tanzu/velero#4930]
**What steps did you take and what happened:**

I've deployed Velero using Helm chart. Configured backup location using the guide for Azure (Option 3: Use storage account access key). As far as I understand, option 3 assumes I retrieve access key myself and give it to Velero, so there's no need to list access keys and since I didn't create identity for Velero, there will be no permissions to list keys.

**What did you expect to happen:**

Velero backups work

**The following information will help us better understand what's going on**:

Helm chart values:
```
velero:
  deployRestic: true
  configuration:
    provider: azure  
    backupStorageLocation:
      bucket: "my-backups"    
        config:
          resourceGroup: "myapp-test"
          storageAccount: "myapptest"
          subscriptionId: "<redacted>"
  metrics:
    enabled: false
  snapshotsEnabled: false
  credentials:
    secretContents:
      cloud: |
        AZURE_STORAGE_ACCOUNT_ACCESS_KEY=<key>
        AZURE_CLOUD_NAME=AzurePublicCloud
```

Velero logs:
```
time="2022-05-20T14:28:09Z" level=error msg="Error in syncHandler, re-adding item to queue" controller=backup-deletion error="error getting the backup store: rpc error: code = Unknown desc = storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" Message=\"The client '<redacted>' with object id '<redacted>' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/<redacted>/resourceGroups/myapp-test/providers/Microsoft.Storage/storageAccounts/myapptest' or the scope is invalid. If access was recently granted, please refresh your credentials.\"" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_deletion_controller.go:294" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*backupDeletionController).processRequest" key=myapp-extras/myapp-backup-8b69r logSource="pkg/controller/generic_controller.go:140"
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
```
Client:
        Version: v1.8.1
        Git commit: 18ee078dffd9345df610e0ca9f61b31124e93f50
Server:
        Version: v1.8.1
```
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"07959215dd83b4ae6317b33c824f845abd578642", GitTreeState:"clean", BuildDate:"2022-03-30T18:28:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Helm chart version: 2.29.6

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
