### ISSUE TITLE
exclude certain resources from the backup schedule

### ISSUE THREAD

**Issue by dmitry-mightydevops** [vmware-tanzu/velero#4944]
I need to exclude certain resource types from the backup schedule

specifically I need this:
```
--exclude-resources=orders.acme.cert-manager.io,challenges.acme.cert-manager.io,certificaterequests.cert-manager.io
```

this is my schedule:

```yaml
staging:
  labels:
    backup: staging
  schedule: "@every 24h"
  template:
    ttl: "480h"
    includedNamespaces:
    - staging
```

what should be the key/value to achieve this?

will the following work?

```yaml
staging:
  labels:
    backup: staging
  schedule: "@every 24h"
  template:
    ttl: "480h"
    includedNamespaces:
    - staging
    excludeResources:
    - orders.acme.cert-manager.io
    - challenges.acme.cert-manager.io
    - certificaterequests.cert-manager.io
```

os excludedResources? Or excludeResources: "long string" vs array.

**Comment by Lyndon-Li** [comment]
The above is correct:
    excludeResources:
    - orders.acme.cert-manager.io
    - challenges.acme.cert-manager.io
    - certificaterequests.cert-manager.io

**Comment by Lyndon-Li** [comment]
@dmitry-mightydevops Please test this like above, if you have further questions, just let us know.

**Comment by Lyndon-Li** [comment]
Closing this stable issue, if more help is needed, please reopen it. Thanks.

**Comment by dmitry-mightydevops** [comment]
@Lyndon-Li that has not worked, I got the following error:

![image](https://user-images.githubusercontent.com/70822710/182041827-e839e98f-37a4-4b66-8759-cdbe2b3c9fe6.png)

```
schedules:
  system:
    labels:
      backup: system
    schedule: "@every 24h"
    template:
      ttl: "480h"
      includedNamespaces:
        - cert-manager
        - ingress-nginx
        - kube-node-lease
        - kube-public
        - kube-system
        - ops
        {{- if .Values.sla }}
        - opsgenie
        {{- end }}
        - default
      excludeResources:
        - orders.acme.cert-manager.io
        - challenges.acme.cert-manager.io
        - certificaterequests.cert-manager.io

  argo-cd:
    labels:
      backup: argo-cd
    schedule: "@every 24h"
    template:
      ttl: "480h"
      includedNamespaces:
        - argo-cd
      excludeResources:
        - orders.acme.cert-manager.io
        - challenges.acme.cert-manager.io
        - certificaterequests.cert-manager.io
```

What can be done?
