### ISSUE TITLE
[velero-plugin-for-csi] Waiting for volumesnapshotcontents (longhorn)

### ISSUE THREAD

**Issue by R-Studio** [vmware-tanzu/velero#4973]
**What steps did you take and what happened:**
I deployed the [nginx-example with PV](https://github.com/vmware-tanzu/velero/blob/main/examples/nginx-app/with-pv.yaml) and 
I want to run a backup for all resources in that namespace "nginx-example" and to achieve this i run following command:
`velero backup create before-nginx10 --include-namespaces nginx-example --storage-location minio --snapshot-volumes --volume-snapshot-locations=minio`
But the backup takes a long time on `Waiting for volumesnapshotcontents snapcontent-xxx to have snapshot handle. Retrying in 5s` and fail with `Timed out awaiting reconciliation of volumesnapshot` and `Error backing up item\" backup=velero/before-nginx10 error=\"error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=nginx-example, name=velero-nginx-logs-v9545): rpc error: code = Unknown desc = timed out waiting for the condition.` 
-> _Without VolumeSnapshots Velero Backups works._

**What did you expect to happen:**
A backup of all K8s resources in that namespace "nginx-example".

**The following information will help us better understand what's going on**:
_If you are using velero v1.7.0+:_  Please use `velero debug  --backup <backupname>`:
[bundle-2022-06-08-17-24-52.tar.gz](https://github.com/vmware-tanzu/velero/files/8863031/bundle-2022-06-08-17-24-52.tar.gz)

**Anything else you would like to add:**
- I use the [Helm Chart of Velero](https://artifacthub.io/packages/helm/vmware-tanzu/velero) with following values:
```
configuration:
  features: EnableCSI
  provider: aws
  backupStorageLocation:
    name: minio
    bucket: velero
    default: true
    config:
      region: minio
      s3ForcePathStyle: true
      s3Url: http://minio.minio.svc.cluster.local:9000
      publicUrl: http://localhost:9000
  volumeSnapshotLocation:
    provider: aws
    name: minio
    bucket: velero-snapshot
    config:
      region: minio

credentials:
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=xxx
      aws_secret_access_key=xxx

initContainers:
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v0.2.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.4.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
```
- As storage for PV I use Rancher Longhorn and I followed the guide for [Enable CSI Snapshot Support on a Cluster](https://longhorn.io/docs/1.2.4/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/). After that I deployed the `VolumeSnapshotClass`:
```
# Use v1 as an example
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: driver.longhorn.io
deletionPolicy: Delete
```
- As storage for Backups and Volumesnapshot I use Minio with two buckets `velero` and `velero-snapshot`.

**Environment:**
- Velero version (use `velero version`): v1.8.1
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`):v1.22.9
- OS (e.g. from `/etc/os-release`): Ubuntu VMs on Proxmox

**Vote on this issue!**
This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
