### ISSUE TITLE
Serviceaccount with IAM role stopped working in new cluster

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#5037]
### Discussed in https://github.com/vmware-tanzu/velero/discussions/5011

<div type='discussions-op-text'>

<sup>Originally posted by **mallow111** June 16, 2022</sup>
We are trying to use velero to do cluster recovery on EKS, let's say we have cluster1, we will use velero to backup everything on it, now cluster1 is broken for some reason, we will provision cluster2, when we use velero to restore services from backup, some services stopped working. The service account has IAM role annotation, inside of the IAM role, we have OIDC provider issuer from cluster1, now we are in cluster2, the IAM role stopped working, therefore service account stopped working as well. Can you guys provide some idea about case like this, how can we make sure the restored service account is working. Should we make the IAM role has OIDC provider for both cluster1 and cluster2?

Service account with annotation example:
```
kubectl -n abc get sa testapp-123 -o yaml
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations:
    xxx/iamrole: testapp-123
    xx/iamrolearn: arn:aws:iam::AWS_ACCOUNT:role/testapp-123
  creationTimestamp: "2022-06-15T22:24:14Z"
  labels:
    velero.io/backup-name: testapp-backup-from-cluster1
    velero.io/restore-name: testapp-restore-from-cluster1
  name: testapp-123
  namespace: abc
secrets:
- name: testapp-123-token-ng5tx
```
IAM role example:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::AWS_ACCOUNT:oidc-provider/oidc.eks.some_zone.amazonaws.com/id/cluster_OIDC_ID1"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.some_zone.amazonaws.com/id/cluster_OIDC_ID1:sub": "system:serviceaccount:testapp:testapp-123"
                }
            }
        }
    ]
}
```

As you can see when this service account tesapp-123 is restored into cluster2, all of its IAM role annotation, and the principle inside of the IAM role will still use the backup cluster's info, this will make the service account stopped working in cluster2. How can we improve this part?
</div>
