### ISSUE TITLE
PodVolumeRestores are not created during restore

### ISSUE THREAD

**Issue by VphDreamer** [vmware-tanzu/velero#5039]
Hello, I have an application deployed in Openshift in a microservices mode, and I have some **mongo** databases deployed in the application, **the mongo databases used persistent volumes**. After the restore, I noticed that all **data was lost**, and also **no PodVolumeRestore is created**. However, I have pvc and pv in the restore application. I'm pretty new to Velero, so, I don't have lot of ideas about what's happenning, maybe I missed some parameters or annotations. Please, tell me if you have an idea.

So this is the command I'm doing for the backup:
```
velero backup create --include-namespaces=acmeair \
--default-volumes-to-restic --snapshot-volumes=false acmeair-backup \
```

and for restore:
```
velero restore create --from-backup=acmeair-backup acmeair-restore \
--include-cluster-resources=true

```

**Comment by qiuming-best** [comment]
@VphDreamer I found that the plugin you used is `cpdbr-velero-plugin` which is one plugin for IBM Cloud, for Openshift I think it should be [openshift-velero-plugin](https://github.com/openshift/openshift-velero-plugin)

So cloud you show me the cmd or helm how you install velero?

And also, If for restic, [here](https://velero.io/docs/v1.9/restic/#limitations) is some limitation when backing up volumes. Could you show me how is the volume mount in mongo databases application in yaml (`kubectl get xxx -oyaml`)

**Comment by VphDreamer** [comment]
@qiuming-best, thanks for the answer.
I got the velero installed via OADP operator. This is the yaml file I used for that:
```
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa-sample
  namespace: oadp-operator
spec:
  backupImages: true
  backupLocations:
    - velero:
        config:
          region: minio
          s3ForcePathStyle: 'true'
          s3Url: 'http://10.3.43.104:9000'
        credential:
          key: cloud
          name: credentials-cloud
        default: true
        objectStorage:
          bucket: acmeair-backup
          prefix: velero
        provider: aws
  configuration:
    restic:
      enable: true
      podConfig:
        resourceAllocations:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 256Mi
    velero:
      customPlugins:
        - image: >-
            image-registry.openshift-image-registry.svc:5000/oadp-operator/cpdbr-velero-plugin:4.0.0-beta1-1-x86_64
          name: cpdbr-velero-plugin
      defaultPlugins:
        - aws
        - openshift
        - csi
      podConfig:
        resourceAllocations:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
```
```
spec:
  containers:
  - image: mongo
    imagePullPolicy: Always
    name: acmeair-booking-db
    ports:
    - containerPort: 27017
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000940000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data/configdb
      name: acmeair-booking-db-1
    - mountPath: /data/db
      name: acmeair-booking-db-2
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-n6f7t
      readOnly: true
```
but, I found out through other issues that if I annotate the pods with their volume name like this:
`oc annotate $pod backup.velero.io/backup-volumes:'acmeair-booking-db-1,acmeair-booking-db-2'`
it works. but, I thinks this was supposed to fixed in the current versions of velero, isn't it ?
