### ISSUE TITLE
The "Restic Backups" count in the output of "velero backup describe" is incorrect

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#5088]
Try to back up Harbor without Redis PV by labeling it with:
`kubectl label pv/pvc-7f803502-07ca-49cd-971c-e9a9bb8a27f1 velero.io/exclude-from-backup=true`

Describe the backup after backing up with Restic:
```
velero backup describe harbor-backup-restic
Name:         harbor-backup-restic
...
Restic Backups (specify --details for more information):
  Completed:  8
```

With `--details`:
```
velero backup describe harbor-backup-restic --details
Name:         harbor-backup-restic
...
Resource List:
...
  v1/PersistentVolume:
    - pvc-06e8a7b9-a0e9-4ab6-8c3b-371bae8c8de0
    - pvc-787d0f9a-b515-4e40-bffd-7bf505d3f44b
    - pvc-9e6d59b7-adc4-4cfd-a564-b59099dc496c
    - pvc-9f3f8d59-f88e-40e9-9794-e3663c61634d
    - pvc-f61f7c73-7d52-40e2-aff3-305e8d83c99e
  v1/PersistentVolumeClaim:
    - harbor/data-harbor-redis-0
    - harbor/data-harbor-trivy-0
    - harbor/database-data-harbor-database-0
    - harbor/harbor-chartmuseum
    - harbor/harbor-jobservice
    - harbor/harbor-registry
...
Restic Backups:
  Completed:
    harbor/harbor-chartmuseum-7686c6d699-4ddqj: chartmuseum-data
    harbor/harbor-core-54f84b66dc-vsgst: psc
    harbor/harbor-database-0: database-data, shm-volume
    harbor/harbor-jobservice-585c9bd464-2n25t: job-logs
    harbor/harbor-redis-0: data
    harbor/harbor-registry-67d5d69976-7bhrj: registry-data
    harbor/harbor-trivy-0: data
```

Actually there are only 5 PVs being backed up, but the `Restic Backups` section says it's 8
**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
