### ISSUE TITLE
Update to Velero 1.9.0 breaks restic with custom CA

### ISSUE THREAD

**Issue by timbuchwaldt** [vmware-tanzu/velero#5140]
**What steps did you take and what happened:**
After updating to Velero 1.9.0 via the Helm chart we saw all Restic backups fail. We use a custom CA Cert for the internal S3 compliant backup stoarge.
The following error is reported:

```
stderr=unable to read root certificate: open /tmp/cacert-default3164165714: no such file or directory
github.com/restic/restic/internal/backend.Transport
/restic/internal/backend/http_transport.go:110
main.open
    /restic/cmd/restic/global.go:687
main.OpenRepository
    /restic/cmd/restic/global.go:421
main.runBackup
    /restic/cmd/restic/cmd_backup.go:524
main.glob..func2
    /restic/cmd/restic/cmd_backup.go:61
github.com/spf13/cobra.(*Command).execute
    /home/build/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
    /home/build/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
    /home/build/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main
    /restic/cmd/restic/main.go:98
runtime.main
    /usr/local/go/src/runtime/proc.go:250
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1571
: exit status 1
```
A rollback to the 1.8.1 release works perfectly.

The config looks something like this:

```
          configuration:
              provider: aws
              backupStorageLocation:
                bucket: k8s-backups
                caCert: <base64 crt>
                config:
                  region: us-east-1
                  s3ForcePathStyle: "true"
                  s3Url: https://my-funny-s3.local
              volumeSnapshotLocation:
                config:
                  region: us-east-1
              defaultVolumesToRestic: true
```

**What did you expect to happen:**
Succesful backups with our custom CA.

**Environment:**

```
Client:
	Version: v1.9.0
	Git commit: 6021f148c4d7721285e815a3e1af761262bff029
Server:
	Version: v1.8.1
```

- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`): 1.23.7/1.22

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
