### ISSUE TITLE
Add new field additionalResources in backup spec

### ISSUE THREAD

**Issue by 27149chen** [vmware-tanzu/velero#5152]
**Describe the problem/challenge you have**
The current resource filtering mechanism (IncludedResources/ExcludedResources + IncludeClusterResources flag) is not flexible enough to cover some special scenarios

**Describe the solution you'd like**
Add a new field called additionalResources (or rawResources), these resources are not affected by the filtering rules in the spec

```
additionalResources:
- group: apps
  version: ""
  resource: deployments
  name: default/my-deploy
```

**Anything else you would like to add:**

velero can be used as an internal backup tool, and the upper systems may have their own resource filtering rules. Instead of translating their rules into velero's rules, velero can provide a raw resources field so that they can fill the result directly.

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by sseago** [comment]
I see a couple possible downsides to this -- it doesn't allow exclude by name, and the interaction with the existing include/excludeResources could be confusing. Instead, we could provide a new pair of fields alongside includeResourses/excludeResources with the intent that users will use one or the other, not both. The old fields work just like before. The new fields (perhaps called structuredIncludes/structuredExcludes) would be similar to that proposed above, with two modifications:
1) the names/items field is optional -- if the list is empty, then that means include (or exclude) all items of the type.
2) we have "structuredExcludes" as well, with functionality similar to current includes/excludes. i.e. you can have an "include everything except this list", or "only include this list".

Something like this:
```
stucturedIncludes:
- group: apps
  resource: deployments
  names:
  - default/my-deploy
- group: ""
  resource: pods
```
This would include the named deployment and all pods. Alternatively, using excludes:
```
stucturedExcludes:
- group: apps
  resource: deployments
  names:
  - default/my-deploy
- group: ""
  resource: pods
```
This would exclude the deployment default/my-deploy (including all others), and exclude all pods
