### ISSUE TITLE
Migration of pvc data from one cluster to another

### ISSUE THREAD

**Issue by fberube-psee** [vmware-tanzu/velero#5191]
Migration of pvc data from one cluster to another
, stderr=: signal: killed
Phase: Failed

thank you for your help

**cluster stage > backup
cluster prod  > restore**

**Source Cluster**:
I backup pods with pv

kind: Schedule
```
spec:
  schedule: 45 22 * * *
  template:
    includedNamespaces:
      - devops
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: clearml-fileserver
    metadata: {}
    ttl: 360h
  useOwnerReferencesInBackup: false

```
```
kind: PodVolumeBackup
status:
  completionTimestamp: '2022-08-08T22:50:16Z'
  phase: Completed
  progress:
    bytesDone: 344387671801
    totalBytes: 344387671801
  snapshotID: 99a15f77
  startTimestamp: '2022-08-08T22:45:56Z'
spec:
  backupStorageLocation: velero-stage

```

**Destination Cluster**

- Create the backupStorageLocation: velero-stage on the prod cluster
   and I can see all backups

- Then a try to restore with Namespace mappings:  devops=test

`velero restore create clearml --from-backup=clearml-fileserver-202208xxx --selector app.kubernetes.io/instance=clearml-fileserver --namespace-mappings devops:test --restore-volumes=true `

**What did you expect to happen:**
A pod, with a pvc and data inside the pv

**The following information will help us better understand what's going on**:

```
Errors:
  Velero:  pod volume restore failed: error running restic restore, cmd=restic restore --repo=s3:https://s3.fr-par.xxx --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic 99a15f77 --target=., stdout=restoring <Snapshot 99a15f77 of [/host_pods/c1f9090b-8c8d-4a4e-8563-ee911375bc07/volumes/kubernetes.io~csi/pvc-f48a43d9-9834-4bd1-abd4-aaf7dcba0dcb/mount] at 2022-08-08 22:45:56.575634078 +0000 UTC by root@velero> to .
, stderr=: signal: killed
```

restic daemonset ouput PodVolumeRestore not found

```
kubectl get  PodVolumeRestore              
clearml-frdm6   test        clearml-fileserver-594fc4758d-lhgfw   fileserver-data   Failed   344387671801   344387671801   159m

```
```
kubectl describe  PodVolumeRestore clearml-frdm6
 Message:               error running restic restore, cmd=restic restore --repo=s3:https://s3.fr-par.scw.xxx --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic 99a15f77 --target=., stdout=restoring <Snapshot 99a15f77 of [/host_pods/c1f9090b-8c8d-4a4e-8563-ee911375bc07/volumes/kubernetes.io~csi/pvc-f48a43d9-9834-4bd1-abd4-aaf7dcba0dcb/mount] at 2022-08-08 22:45:56.575634078 +0000 UTC by root@velero> to .
, stderr=: signal: killed
  Phase:  Failed
  Progress:
    Bytes Done:     344387671801
    Total Bytes:    344387671801

```
**Environment:**
- Velero version (use `velero version`): 1.9 
- Velero features (use `velero client config get features`): features: EnableCSI
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
  Client Version: v1.24.0
  Server Version: v1.23.6

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
