### ISSUE TITLE
Problem with restoring data from pvc

### ISSUE THREAD

**Issue by kuhar2007** [vmware-tanzu/velero#5204]
Hello.

I use velero version 1.8.1.
For storage I use rook-ceph with rbd-pool.
Velero creates backups without any error, but I want restore for example postgress with data inside, velero restore only part of them. 
For example, I have postgress which use pvc, I start to import few databases with tables, after that make full backup via velero.
Backup created without any errors, I remove postgress with pvc, and start restoring.

`velero restore create --from-backup postgress-backup --include-namespaces namespace-name`

Velero restore postgress and pvc, but consistence data inside pvc not actual, without new databases and new tables.

Please help me, what and where I must check?

**Comment by kuhar2007** [comment]
Here is my deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress
  labels:
    app: postgress
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: postgress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgress
      annotations:
        pre.hook.backup.velero.io/container: fsfreeze
        pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/var/lib/pgsql/data"]'
        post.hook.backup.velero.io/container: fsfreeze
        post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/var/lib/pgsql/data"]'
    spec:
      imagePullSecrets:
        - name: regcred
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: fixpermission
          image: centos:7
          command:
            - "sh"
            - "-c"
            - "chown -R 26:0 /var/lib/pgsql/data && chmod -R g+rw /var/lib/pgsql/data"
          volumeMounts:
            - name: disk1
              mountPath: /var/lib/pgsql/data
              subPath: data
      containers:
        - name: postgress
          image: postgress:11
          env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: random
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: "300"
          ports:
            - containerPort: 5432
          resources: {requests: {cpu: .1, memory: 512Mi}, limits: {cpu: .5, memory: 512Mi}}
          readinessProbe:
            exec:
              command: ["/bin/sh", "-i", "-c", "pg_isready"]
            initialDelaySeconds: 15
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command: ["/bin/sh", "-i", "-c", "pg_isready"]
            initialDelaySeconds: 300
            timeoutSeconds: 1
          volumeMounts:
            - name: disk1
              mountPath: /var/lib/pgsql/data
              subPath: data
        - image: ubuntu:bionic
          name: fsfreeze
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: "/var/lib/pgsql/data"
              name: disk1
              readOnly: false
          command:
            - "/bin/bash"
            - "-c"
            - "sleep infinity"
      volumes:
        - name: disk1
          persistentVolumeClaim:
           claimName: "postgress-pvc"
```
Before restoring I check space at /var/lib/pgsql/data  and it used ~650M, after backuping, removing and restoring it uses ~240M, disapeared ~400m data.

What’s interesting:
- I create snapshot
- restore pvc from snapshot (pvc doesn’t use anything)
- map and mount rbd image to any server for checking data - it had ~600M
- made backup
- remove restored pvc and remove snapshot
- made restore velero
- check what inside pvc and see - ~200M data
- try to restore again pvc from snapshot and get again ~200Mb
