### ISSUE TITLE
Unable to handle CSI driver: rbd.csi.ceph.com

### ISSUE THREAD

**Issue by angelsantillana94** [vmware-tanzu/velero#5222]
**What steps did you take and what happened:**

- Velero deployed through CLI command

- I try to make a backup with persistent volumes, but it does not end OK.

```
[workspace|pruebas] [asantillana@host:tmp]$ velero backup create pruebas --snapshot-volumes=true --include-namespaces pruebas
Backup request "pruebas" submitted successfully.
Run `velero backup describe pruebas` or `velero backup logs pruebas` for more details.
[workspace|pruebas] [asantillana@host:tmp]$ 
```

- Checking logs:

```
time="2022-08-16T10:01:14Z" level=info msg="Waiting for CSI driver to reconcile volumesnapshot pruebas/velero-mysql-g2cnn. Retrying in 5s" backup=velero/pruebas cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:169" pluginName=velero-plugin-for-csi
time="2022-08-16T10:01:19Z" level=info msg="Waiting for CSI driver to reconcile volumesnapshot pruebas/velero-mysql-g2cnn. Retrying in 5s" backup=velero/pruebas cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:169" pluginName=velero-plugin-for-csi
time="2022-08-16T10:01:24Z" level=info msg="Waiting for CSI driver to reconcile volumesnapshot pruebas/velero-mysql-g2cnn. Retrying in 5s" backup=velero/pruebas cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:169" pluginName=velero-plugin-for-csi
time="2022-08-16T10:01:29Z" level=info msg="Waiting for CSI driver to reconcile volumesnapshot pruebas/velero-mysql-g2cnn. Retrying in 5s" backup=velero/pruebas cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:169" pluginName=velero-plugin-for-csi
time="2022-08-16T10:01:34Z" level=info msg="Waiting for CSI driver to reconcile volumesnapshot pruebas/velero-mysql-g2cnn. Retrying in 5s" backup=velero/pruebas cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:169" pluginName=velero-plugin-for-csi
[...]
time="2022-08-16T10:15:29Z" level=error msg="Error backing up item" backup=velero/pruebas error="error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=pruebas, name=velero-mysql-hw7f9): rpc error: code = Unknown desc = timed out waiting for the condition" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:316" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*itemBackupper).executeActions" logSource="pkg/backup/backup.go:417" name=velero-mysql-hw7f9

```

**What did you expect to happen:**

- Backup with persistent volumes

**The following information will help us better understand what's going on**:

- StorageClass:

```
[workspace|velero] [asantillana@host:tmp]$ k get sc
NAME                           PROVISIONER        RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-rbd-sc-02                  rbd.csi.ceph.com   Retain          Immediate           true                   305d
```

- VolumeSnapshotClass

```
[workspace|velero] [asantillana@host:tmp]$ k get VolumeSnapshotClass csi-rbd-sc-02 -o yaml | k neat
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Delete
driver: rbd.csi.ceph.com
kind: VolumeSnapshotClass
metadata:
  labels:
    velero.io/csi-volumesnapshot-class: "true"
  name: csi-rbd-sc-02
parameters:
  clusterID: 73e23d08-9eff-44d6-a332-xxx
  csi.storage.k8s.io/snapshotter-secret-name: csi-rbd-02-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: csi-rbd-sc
[workspace|velero] [asantillana@host:tmp]$ 
```

- Kubernetes Virtual Machines on VMware Infrastructure

- ApiVersion v1

```
[workspace|velero] [asantillana@host:tmp]$ kubectl api-resources | grep snapshot.storage
volumesnapshotclasses             vsclass,vsclasses   snapshot.storage.k8s.io/v1             false        VolumeSnapshotClass
volumesnapshotcontents            vsc,vscs            snapshot.storage.k8s.io/v1             false        VolumeSnapshotContent
volumesnapshots                   vs                  snapshot.storage.k8s.io/v1             true         VolumeSnapshot
```

- container images

```
[workspace|velero] [asantillana@host:tmp]$ k images
[Summary]: 1 namespaces, 1 pods, 3 containers and 3 different images
+-------------------------+--------------------------------+-------------------------------------+
|         PodName         |         ContainerName          |           ContainerImage            |
+-------------------------+--------------------------------+-------------------------------------+
| velero-6cd5f5b48f-sf9jp | velero                         | velero/velero:v1.9.0                |
+                         +--------------------------------+-------------------------------------+
|                         | (init)                         | velero/velero-plugin-for-aws:v1.5.0 |
|                         | velero-velero-plugin-for-aws   |                                     |
+                         +--------------------------------+-------------------------------------+
|                         | (init)                         | velero/velero-plugin-for-csi:v0.3.0 |
|                         | velero-velero-plugin-for-csi   |                                     |
+-------------------------+--------------------------------+-------------------------------------+
[workspace|velero] [asantillana@host:tmp]$ 

```

- volumesnapshot

```
[workspace|pruebas] [asantillana@host:tmp]$ k get volumesnapshot
NAME                 READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT   CREATIONTIME   AGE
velero-mysql-g2cnn                mysql                                             csi-rbd-sc-02                                    65m
velero-mysql-hw7f9                mysql                                             csi-rbd-sc-02                                    103m
velero-mysql-wfmqr                mysql                                             csi-rbd-sc-02                                    40m
[workspace|pruebas] [asantillana@host:tmp]$
```

```
[workspace|pruebas] [asantillana@host:tmp]$ k describe volumesnapshot velero-mysql-wfmqr
Name:         velero-mysql-wfmqr
Namespace:    pruebas
Labels:       velero.io/backup-name=pruebas
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2022-08-16T09:45:29Z
  Generate Name:       velero-mysql-
  Generation:          1
  Managed Fields:
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName:
        f:labels:
          .:
          f:velero.io/backup-name:
      f:spec:
        .:
        f:source:
          .:
          f:persistentVolumeClaimName:
        f:volumeSnapshotClassName:
    Manager:         velero-plugin-for-csi
    Operation:       Update
    Time:            2022-08-16T09:45:29Z
  Resource Version:  180378511
  UID:               a2224e6d-f5c2-4e2b-8723-a26e5c056d09
Spec:
  Source:
    Persistent Volume Claim Name:  mysql
  Volume Snapshot Class Name:      csi-rbd-sc-02
Events:                            <none>
[workspace|pruebas] [asantillana@host:tmp]$ 

```
- snapshot-location

```
[workspace|pruebas] [asantillana@host:tmp]$ velero snapshot-location get default -o yaml | k neat
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  labels:
    component: velero
  name: default
  namespace: velero
spec:
  config:
    region: ceph
  provider: aws

```
- backup-location

```
[workspace|pruebas] [asantillana@host:tmp]$ velero backup-location get default -o yaml | k neat
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  labels:
    component: velero
  name: default
  namespace: velero
spec:
  config:
    bucket: velero-clustername
    prefix: ""
    region: ceph
    s3ForcePathStyle: "true"
    s3Url: https://endpoints3.domain.com
  default: true
  objectStorage:
    bucket: velero-clustername
  provider: aws
[workspace|pruebas] [asantillana@host:tmp]$ 

```

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `velero backup describe <backupname>`  : https://gist.github.com/angelsantillana94/724787439dd4bfe50a45e588c49528f4

- `velero backup logs <backupname>`: https://gist.github.com/angelsantillana94/6ab695a3d5ecdb41c5a9dff9ead96bbd

**Environment:**

```
[workspace|velero] [asantillana@host:tmp]$ velero version
Client:
	Version: v1.9.0
	Git commit: 6021f148c4d7721285e815a3e1af761262bff029
Server:
	Version: v1.9.0
[workspace|velero] [asantillana@host:tmp]$ 
```

```
[workspace|velero] [asantillana@host:tmp]$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
[workspace|velero] [asantillana@host:tmp]$ 
```
- ceph-csi-rbd

```
[workspace|csi-rbd-sc] [asantillana@host:tmp]$ helm list
NAME      	NAMESPACE 	REVISION	UPDATED                                 	STATUS  	CHART             	APP VERSION
csi-rbd-sc	csi-rbd-sc	14      	2022-08-09 09:21:44.729913698 +0200 CEST	deployed	ceph-csi-rbd-3.6.2	3.6.2      
[workspace|csi-rbd-sc] [asantillana@host:tmp]$ 

```

- Kubernetes installer & version: kubeadm
- Cloud provider or hardware configuration: n/a
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.4 LTS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
