### ISSUE TITLE
restic pods are in crashloopback and continuously restarting

### ISSUE THREAD

**Issue by nsagark** [vmware-tanzu/velero#5238]
**What steps did you take and what happened:**
Installed velero v1.9 along with restic on eks-d 1.21.5 cluster. The velero pod is up however my restic pods are in crashloopback and the pod are restarting continuously. Here is the error from the restic pods. 

An error occurred: could not read pod volumes host path: open /host_pods/: permission denied

**What did you expect to happen:**
Expected restic pods to be up and running. 

**The following information will help us better understand what's going on**:
I want to run restic pods as nonroot so I updated the security context accordingly. Please let me know if restic pods can be run as non root. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  v1.9
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): EKS-D 1.21.5
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Onprem
- OS (e.g. from `/etc/os-release`): Centos
[Uploading velero-aws.txt…]()

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by nsagark** [comment]
Here is my restic YAML file


```
apiVersion: "apps/v1"
kind: "DaemonSet"
metadata:
  namespace: "velero"
  annotations: {}
  name: "restic"
  labels:
    helm.sh/chart: "velero-2.30.1"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "restic"
    app.kubernetes.io/instance: "restic"
    app.kubernetes.io/component: "daemonset.restic"
spec:
  minReadySeconds: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      helm.sh/chart: "velero-2.30.1"
      app.kubernetes.io/managed-by: "Helm"
      app.kubernetes.io/name: "restic"
      name: "restic"
      app.kubernetes.io/instance: "restic"
      app.kubernetes.io/component: "daemonset.restic"
    matchExpressions: []
  template:
    metadata:
      annotations: {}
      labels:
        helm.sh/chart: "velero-2.30.1"
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/name: "restic"
        name: "restic"
        app.kubernetes.io/instance: "restic"
        app.kubernetes.io/component: "daemonset.restic"
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      serviceAccountName: "velero-server"
      dnsPolicy: "ClusterFirst"
      volumes:
      - name: "cloud-credentials"
        secret:
          secretName: "cloud-credentials"
      - name: "host-pods"
        hostPath:
          path: "/var/lib/kubelet/pods"
      - name: "scratch"
        emptyDir: {}
      containers:
      - name: "restic"
        image: "velero/velero:v1.9.0"
        command:
        - "/velero"
        args:
        - "restic"
        - "server"
        - "--features=EnableCSI"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: "VELERO_NAMESPACE"
          valueFrom:
            fieldRef:
              apiVersion: "v1"
              fieldPath: "metadata.namespace"
        - name: "NODE_NAME"
          valueFrom:
            fieldRef:
              apiVersion: "v1"
              fieldPath: "spec.nodeName"
        - name: "VELERO_SCRATCH_DIR"
          value: "/scratch"
        - name: "AWS_SHARED_CREDENTIALS_FILE"
          value: "/credentials/cloud"
        volumeMounts:
        - name: "cloud-credentials"
          mountPath: "/credentials"
        - mountPropagation: "HostToContainer"
          name: "host-pods"
          mountPath: "/host_pods"
        - name: "scratch"
          mountPath: "/scratch"
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false          
          runAsNonRoot: true
          runAsUser: 65532
        resources:
          limits:
            cpu: "1000m"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "512Mi"
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
        privileged: false
  updateStrategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: 1
```

**Comment by blackpiglet** [comment]
I think this part's setting is the reason

``` yaml
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
        privileged: false
```
The default DaemonSet setting is: 
``` yaml
      securityContext:
        runAsUser: 0
```

This is because Restic pods need to read nodes' kubelet pod directory to access pods' volumes data.

**Comment by nsagark** [comment]
Thanks, @blackpiglet Is there a way to deploy restic containers as non root Or by adding some capabilities?

**Comment by blackpiglet** [comment]
@nsagark 
I tried to use `priviledged: true` instead, but it didn't work. I think this is due to the directory `/var/lib/kubelet/pods` on host's owner's GID and UID setting.
I verify this on my docker-desktop k8s cluster. It is `root:root`. If this is also true for your environment, I think running as root user is mandatory.

``` bash
/var/lib/kubelet/pods # ls -al
total 64
drwxr-x---   16 root     root          4096 Aug 14 15:13 .
drwx------    8 root     root          4096 Jul 21 12:35 ..
drwxr-x---    5 root     root          4096 Jul 21 12:35 1fa929fab6e17047f7779b2ab8125174
drwxr-x---    5 root     root          4096 Jul 21 12:35 2449ddc0985e3be8dd23ffc4d12cb53b
drwxr-x---    5 root     root          4096 Jul 21 12:35 2736c4b4-754e-4525-b103-ca15c3327d94
drwxr-x---    5 root     root          4096 Jul 21 12:35 4c50bffc-1195-41a6-85f1-555e56f21776
drwxr-x---    5 root     root          4096 Jul 22 01:48 4de962d6-a53f-4e83-8eb1-34b05ae1b12d
drwxr-x---    5 root     root          4096 Jul 21 12:35 6ded7175-464a-474b-a821-852f9f00037a
drwxr-x---    5 root     root          4096 Aug 14 15:13 8443aa88-c0d7-4bfd-bfd2-a2ee528a19aa
drwxr-x---    5 root     root          4096 Jul 22 11:10 8889e47b-5225-426a-8923-613066582121
drwxr-x---    5 root     root          4096 Jul 22 01:49 9c15e694-74fb-407f-8725-d9dd3bc42597
drwxr-x---    5 root     root          4096 Jul 21 12:35 a6ffda51-f24c-47ee-8b5c-17321237bd54
drwxr-x---    5 root     root          4096 Jul 21 12:35 b3a24aea-7692-4927-945c-dabdb00b2fe4
drwxr-x---    5 root     root          4096 Jul 22 11:28 cf482952-8531-4729-af48-4c9cc6ed78f3
drwxr-x---    5 root     root          4096 Jul 21 12:35 d9c6bbd179b0d64e8d303a659acf3a74
drwxr-x---    5 root     root          4096 Jul 21 12:35 f76ea91a200a6b1cfe31c7a114460aac
```

**Comment by blackpiglet** [comment]
@nsagark 
If you can modify the `/var/lib/kubelet/pods` directory's owner and group on k8s node, and change it from `root` to other user, I think you can make Restic DaemonSet working without running as `root`.
``` yaml
      securityContext:
        runAsNonRoot: true
        runAsUser: <uid>
        privileged: true
```
