### ISSUE TITLE
run preHook before listing items to backup

### ISSUE THREAD

**Issue by rootmout** [vmware-tanzu/velero#5255]
**Describe the problem/challenge you have**
I want to use velero+restic as a standart backup solution for my pod volumes. These volumes are quite large and are in constant use, using restic directly could result in corrupted backups. My wish was to use preHook to replace the containers in the pods with an image mounting the volume without using it. This way, during the backup, the volume remains mounted by the kubelet and is reachable by velero.

I realize that Velero lists the ID of the objects to be backed up before executing the preHooks. As my script changes the deployments and therefore the pods are updated, restic at backup stage tries to access the volumes of pods that no longer exist.

```
pod volume backup failed: building Restic command: identifying unique volume path on host: expected one matching path: /host_pods/ca2a6a04-8276-4086-ac87-1d3b4beae007/volumes/*/my-volume, got 0
```
`ca2a6a04-8276-4086-ac87-1d3b4beae007` is there the pod with original container, before running the script.

**Describe the solution you'd like**
Run preHook before listing objects to backing up.

**Environment:**

- Velero version (use `velero version`): v1.9.1
- Kubernetes version (use `kubectl version`): v1.24.4
- Kubernetes installer & version: CRC (OpenShift)
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by cleverhu** [comment]
This issue seems like https://github.com/vmware-tanzu/velero/issues/5036.

**Comment by blackpiglet** [comment]
@rootmout 
Per my understanding, Hook is used to run some commands to do some setup and restore for backup and restore process. For example, before backing up some database, we can run some command to flush data into disk. 
And another thought about order of listing resources and running hook is that Velero needs to list resource, then decides 
 whether running hook. If reverting the order, it's not easy to know which resoures are configured with hooks.

**Comment by Lyndon-Li** [comment]
This is a typical problem that should be solved by a snapshot based backup. Other than that, some customized approach that is to stop the work of the workload so that no write will happen, may not be in the scope of Velero's consideration since they are either tricky or not generic enough.

Therefore, the question comes down to do the PV to be backed up support CSI snapshot? If so, Velero's future CSI snapshot data movement feature will solve the problem.

@cleverhu Please help to answer below questions:

1. Please help to confirm the above question - does your PV support CSI snapshot?
2. If your PV supports CSI snapshot, what is motivation for you to move the data through Restic? i.e. you want to move the data to a durable storage? your storage is not large/not efficient enough to take lots of snapshot?  
3. If your PV doesn't support CSI snapshot, please share us more details, i.e. what is the storage type? why doesn't support CSI snapshot? This will help us to design & deliver Velero's data movement feature

**Comment by rootmout** [comment]
Thanks for answers

@Lyndon-Li I use two different types of PV: local-path and topolvm. I initially thought I could do snapshots but neither of them supports it (maybe later for topolvm https://github.com/topolvm/topolvm/issues/124).

In doc, there is a [fsfreeze example](https://velero.io/docs/v1.3.2/hooks/#hook-example-with-fsfreeze) but when you use multiple local-path pv with same filsesystem it will freeze all at once :/

What led me to think that changing the state of the cluster before the backup was the solution was this part of the documentation ([velero/restic#limitations](https://velero.io/docs/v1.9/restic/#limitations)):
> Velero’s Restic integration can only backup volumes that are mounted by a pod [...], some Velero users overcame this limitation running a staging pod (i.e. a busybox or alpine container with an infinite sleep) to mount these PVC/PV pairs prior taking a Velero backup.

@blackpiglet you said:
> If reverting the order, it's not easy to know which resoures are configured with hooks.

we maybe misunderstood, mb, when I said "use preHook to replace the containers in the pods" I was talking about the preHooks of the Backup and Shedule object. I had planned to pass by a dedicated pod (with more cluster rights) to change cluster state like this:

```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: my-schedule
  namespace: velero
spec:
  schedule: 0 7 * * *
  template:
    [...]
    hooks:
      resources:
        - name: stop-disk-use
          includedNamespaces:
          - '*'
          includedResources:
          - pods
          labelSelector:
            matchLabels:
              app: replace-container
          pre:
            -  exec:
                 container: stop-disk-use
                 command:
                   - /bin/app
                   - --pre-backup
                   - #additional param to specify which pod should be "freezed" 
               onError: Fail
               timeout: 1m
          post:
            -  exec:
                 container: stop-disk-use
                 command:
                   - /bin/app
                   - --post-backup
                   - #same additional param as pre-backup cmd
               onError: Fail
               timeout: 1m
```
adapted from https://velero.io/docs/v1.9/api-types/schedule/

maybe adding a pre/post-backup job feature?
