### ISSUE TITLE
Implement a GFS rotation scheme

### ISSUE THREAD

**Issue by brovoca** [vmware-tanzu/velero#5317]
**Describe the problem/challenge you have**
I wish to keep 7 daily backups, 4 weekly and 3 monthly.

For this I need to create 3 schedules, each with a different cron definition and TTL. Below is an example from our Helm chart that helps us with this:

```yaml
schedules:
  daily:
    ttl: "168h" # 7 days
    schedule: "30 0 * * Mon-Sat" # Monday through Saturday at 00:30

  weekly:
    ttl: "672h" # 28 days
    schedule: "30 0 * * Sun" # Every Sunday at 00:30

  monthly:
    ttl: "2232h" # 93 days
    schedule: "30 0 1 * *" # At 00:30 on the fist of each month
```

I find cron definitions difficult to read, and TTLs in hours are also hard to read. Additionally, the weekly and monthly schedule may overlap sometimes.

**Describe the solution you'd like**
I quite enjoy the way that borg implements backup retention and I wonder if Velero could mimic this behavior. Borg allows me to take a backup multiple times in a day. However, I may pass a desired retention to the [`borg prune` command](https://borgbackup.readthedocs.io/en/stable/usage/prune.html) which will allow me to keep `n` amount of secondly, minutely, hourly, daily, weekly, monthly and yearly backups. 

The borg retention policy is commonly referred to as [GFS](https://en.wikipedia.org/wiki/Backup_rotation_scheme#Grandfather-father-son) (Grandfather-father-son) backup rotation scheme. The below text is from the Wikipedia link for GFS:

>Grandfather-father-son backup (GFS) is a common rotation scheme for backup media,[[1]](https://en.wikipedia.org/wiki/Backup_rotation_scheme#cite_note-KissellTakeControl2.0-1) in which there are three or more backup cycles, such as daily, weekly and monthly. The daily backups are rotated on a daily basis using a FIFO system as above. The weekly backups are similarly rotated on a weekly basis, and the monthly backup on a monthly basis. In addition, quarterly, half-yearly, and/or annual backups could also be separately retained.

I believe that a GFS rotation scheme would be an awesome **addition** to Velero Schedules. I believe that a good way to implement it would be to create a RotationScheme CRD.

Here's a fictional Schedule:
```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: banana-jenkins-weekly
  namespace: backups
  labels:
    stage: production
    app.kubernetes.io/component: jenkins
    app.kubernetes.io/instance: banana
    app.kubernetes.io/name: custom-jenkins
    app.kubernetes.io/version: 2.346.1
spec:
  schedule: 30 0 * * * Every day at 00:30
  template:
    includedNamespaces:
    - jenkins
    includedResources:
    - '*'
    labelSelector:
      matchLabels:
        stage: production
        app.kubernetes.io/instance: banana
        app.kubernetes.io/name: custom-jenkins

    # The specified TTL should be used as an absolute maximum lifetime
    # for the backups created in case there is no RotationScheme CRD that
    # would purge it. A TTL of 0 should disable the max lifetime and thus fully
    # rely on the RotationScheme CRD, or never delete the backups.
    ttl: 8760h # one year
```

Now imagine that we have 100 schedules like this. It'd be very tedious to manage a roration scheme for each. I thus suggest a RotationScheme CRD that would rotate the Backups of the matching Schedules. Below is an idea...

```yaml
apiVersion: velero.io/v1
kind: RotationScheme
metadata:
  name: jenkins-production-rotation-scheme
  namespace: backups
  labels:
    stage: production
    app.kubernetes.io/component: jenkins
spec:
  selector:
    matchLabels:
      stage: production
      app.kubernetes.io/component: jenkins
      app.kubernetes.io/name: custom-jenkins

  # Retention copied from https://torsion.org/borgmatic/docs/reference/configuration/
  retention:
    # Keep all archives within this time interval.
    keep_within: 3H

    # Number of secondly archives to keep.
    keep_secondly: 60

    # Number of minutely archives to keep.
    keep_minutely: 60

    # Number of hourly archives to keep.
    keep_hourly: 24

    # Number of daily archives to keep.
    keep_daily: 7

    # Number of weekly archives to keep.
    keep_weekly: 4

    # Number of monthly archives to keep.
    keep_monthly: 6

    # Number of yearly archives to keep.
    keep_yearly: 0

```

This would allow us to maintain one RotationSchedule for many different schedules/backups that exist in the same namespace.

**Anything else you would like to add:**
It's important to think of how the RotationSchedule would get executed. Should it be triggered after each backup, or on a cron schedule? Is protection needed when there are two RotationSchedules that match the same Schedule?

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"
