### ISSUE TITLE
nodePort will be auto assigned when restore with preserve-nodeports flag 

### ISSUE THREAD

**Issue by Yelijah** [vmware-tanzu/velero#5373]
**What steps did you take and what happened:**
My service's nodeport is explicitly specified as 31307. 
After I use command like ' velero restore create --from-backup mysql5 --preserve-nodeports=true' , the nodePort was auto assigned to another port. 
By the way, I'm quite sure the port 31307 isn't be used.

**What did you expect to happen:**
My nodeport shouldn't be changed after restore with preserve-nodeports flag.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

velero version: 1.9.1
[backup file:mysql5.zip](https://github.com/vmware-tanzu/velero/files/9616183/mysql5.zip)

my raw service yaml:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: "fanruan-220905111522"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.1.7
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: "Cluster"
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
      nodePort: 31307
  selector: 
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/component: primary

```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
k8s version:  1.24.2
os : Ubuntu 18.04.6 LTS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
