### ISSUE TITLE
Restic restore failing when restoring  backup to different EKS cluster in different AWS region

### ISSUE THREAD

**Issue by rizblie** [vmware-tanzu/velero#5420]
**What steps did you take and what happened:**

Setup
- I am running two Amazon EKS clusters, one in us-east-2 (primary) and one in us-west-1 (secondary)
- Kubernetes version 1.23
- I created an S3 bucket in us-east-2.

Steps
- I installed velero 1.9.2 (using Helm) with Restic on both clusters, using the same bucket, with access mode set to ReadWrite in primary and ReadOnly in secondary
- I installed wordpress on the primary cluster using helm
- I created a backup of the wordpress namespace on the primary cluster
- I deleted the wordpress namespace from the primary cluster
- I successfully restored the wordpress namespace, resources, and volumes from the backup. So far so good.
- I then tried to restore the same backup on the secondary cluster. 
- The Kubernetes resources were restored, but Restic failed to restore the volumes.
- I can see that EBS volumes were in fact created in the secondary region, but Restic failed to restore the data.
- Errors from restore describe as follows:
  ```
  Errors:
    Velero:  restic repository is not ready: error running command=restic init --repo=s3:s3-us-east-2.amazonaws.com/043124067543-velero-primary/restic/wordpress --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: create repository at s3:s3-us-east-2.amazonaws.com/043124067543-velero-primary/restic/wordpress failed: client.BucketExists: Head "https://043124067543-velero-primary.s3.dualstack.us-west-1.amazonaws.com/": 301 response missing Location header
  
  : exit status 1
      restic repository is not ready: error running command=restic init --repo=s3:s3-us-east-2.amazonaws.com/043124067543-velero-primary/restic/wordpress --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: create repository at s3:s3-us-east-2.amazonaws.com/043124067543-velero-primary/restic/wordpress failed: client.BucketExists: Head "https://043124067543-velero-primary.s3.dualstack.us-west-1.amazonaws.com/": 301 response missing Location header
  
  : exit status 1
  ```
I am confused by the fact that the restore action is executing a `restic init`. The repository already exists, so it just needs an integrity check?

See attached debug bundle.

My helm values file for velero on the secondary is as follows: (primary is similar but ReadWrite, and different role with same permissions)
```
image:
  repository: velero/velero
  tag: v1.9.2
  pullPolicy: IfNotPresent
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.5.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  provider: aws
  # features: EnableCSI
  defaultVolumesToRestic: true
  backupStorageLocation:
    name: primary
    bucket: 043124067543-velero-primary
    accessMode: ReadOnly
    default: true
    config:
      region: us-east-2
deployRestic: true
restic:
  podVolumePath: /var/lib/kubelet/pods
  privileged: false
  # Pod priority class name to use for the Restic daemonset. Optional.
  priorityClassName: ""
  # Resource requests/limits to specify for the Restic daemonset deployment. Optional.
  # https://velero.io/docs/v1.6/customize-installation/#customize-resource-requests-and-limits
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
serviceAccount:
  server:
    create: true
    name: veleros3
    annotations: 
      eks.amazonaws.com/role-arn: "arn:aws:iam::043124067543:role/ServiceAccount-Velero-Backup-Secondary"
```

**What did you expect to happen:**

I expected the Restic volume restore to work in the secondary region, just as it did in the primary region.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
I am not sure if this is a bug, or if I am doing something wrong in my config.
It works fine on the same cluster in the same region, so what is different about a different cluster/region that I may have required a different config parameter somewhere?

**Environment:**

- Velero version (use `velero version`):  1.9.2
- Velero features (use `velero client config get features`):  <NOT SET>
- Kubernetes version (use `kubectl version`): v1.23.10-eks-15b7512
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
[bundle-2022-10-05-20-15-10.tar.gz](https://github.com/vmware-tanzu/velero/files/9718791/bundle-2022-10-05-20-15-10.tar.gz)
