### ISSUE TITLE
Cannot create a velero backup multiple times of a persistent volume backed by AWS EFS

### ISSUE THREAD

**Issue by sumz95** [vmware-tanzu/velero#5452]
**What steps did you take and what happened:**
I tried to create a velero backup of a persistent volume but it errored with:

``` 
time="2022-10-14T10:39:14Z" level=info msg="1 errors encountered backup up item" backup=velero/backup-test-5984 logSource="pkg/backup/backup.go:413" name=write-to-file-pod`
time="2022-10-14T10:39:14Z" level=error msg="Error backing up item" backup=velero/backup-test-5984 error="pod volume backup failed: running Restic backup, stderr=Fatal: Fatal: config cannot be loaded: ciphertext verification failed\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:199" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:417" name=write-to-file-pod 
```
I have installed velero with restic integrated into it. I have a efs backed volumes on a AWS cluster.

Steps taken:
1) Create a pod, with a pvc and pv: 
`kubectl apply -n backup-test -f kube-resources.yaml `
2) Save some data into the pv: 
`kubectl -n backup-test exec <pod> -- sh -c "echo -n "Hello world" > hello.txt" `
3) Run a velero backup: 
`velero backup create backup-1 --wait --snapshot-volumes --default-volumes-to-restic --include-namespaces backup-test`
4) Repeat step 3 a few more times and it will fail
`velero backup create backup-2 --wait --snapshot-volumes --default-volumes-to-restic --include-namespaces backup-test`

kube-resources.yaml :

``` 
apiVersion: v1
kind: Namespace
metadata:
  name: backup-test

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-test
spec:
  resources:
    requests:
      storage: 5G 
  accessModes:
    - ReadWriteMany
---

apiVersion: v1
kind: Pod
metadata:
  name: write-to-file-pod
spec:
  restartPolicy: OnFailure 
  volumes:
      - name: data
        persistentVolumeClaim:
            claimName: backup-test
  containers:
  - name: write-to-file-pod
    image: alpine
    command: [ "/bin/sh", "-c", "tail -f /dev/null"]  
    volumeMounts:
    - name: data
      mountPath: "/data"
```

**What did you expect to happen:**

I expected it to create a successful backup, without a "PartiallyFailed" status

**The following information will help us better understand what's going on**:
[bundle-2022-10-17-16-03-42.tar.gz](https://github.com/vmware-tanzu/velero/files/9809167/bundle-2022-10-17-16-03-42.tar.gz)

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

**Anything else you would like to add:**
The first backup is created successfully, with future backups often failing with the error message mentioned above. It works again once the controller restic pod in the velero namespace has been deleted and then recreated.

**Environment:**

- Velero version (use `velero version`):  `Version: v1.9.2`
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): `Client Version: v1.25.2.   Kustomize Version: v4.5.7.  Server Version: v1.21.14-eks-6d3986b`
- Kubernetes installer & version: `AWS EKS`
- Cloud provider or hardware configuration: `AWS and EFS as persistent volume`
- OS (e.g. from `/etc/os-release`): `Amazon Linux 2 `

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
