### ISSUE TITLE
velero restore Unknown desc = Forbidden

### ISSUE THREAD

**Issue by klinch0** [vmware-tanzu/velero#5599]
i cant restore backup

```
apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: velero
      version: '*'
  install:
    createNamespace: true
  targetNamespace: velero
  interval: 1m0s
  values:

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.5.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    metrics:
      serviceMonitor:
        enabled: true 

    credentials:
      useSecret: true
      existingSecret: minio-credentials

    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        provider: aws
        bucket: test-velero
        accessMode: ReadWrite
        config:
          s3ForcePathStyle: "true"
          region: us-east-1
          s3Url: https:/url

---

kind: Secret
metadata:
  name: minio-credentials
  namespace: velero
stringData:
  cloud: |
    [default]
    aws_access_key_id=qw
    aws_secret_access_key=qeqrwer

```
```
root@master-0:/home/k8s/s3-secrets# velero version
Client:
        Version: v1.9.3
        Git commit: 9a617fe5af9c997d69f8f37a5b40d0462edd9b28
Server:
        Version: v1.9.3
        
  
```

```
root@master-0:/home/k8s/s3-secrets# k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

This okey:
```
velero backup create nginx-backup --selector app=nginx
```

This not:
```
velero restore create --from-backup nginx-backup
```

Describe:

```
root@master-0:/home/k8s/s3-secrets# k describe restore nginx-backup-20221116230342
error fetching volume snapshots metadata: rpc error: code = Unknown desc = Forbidden: Forbidden
                         status code: 403, request id: 172833140C3D5363, host id:
```

and i see k8s secret velero-restic-credentials, what is it? default chart value - deployRestic: false
```
root@master-0:/home/k8s/s3-secrets# kgs velero-restic-credentials -oyaml
apiVersion: v1
data:
  repository-password: qwerty (generated default pass)
kind: Secret
metadata:

```
```
root@master-0:/home/k8s/s3-secrets/velero-tests/velero# k get backupstoragelocations
NAME      PHASE       LAST VALIDATED   AGE   DEFAULT
default   Available   16s              94s   true
root@master-0:/home/k8s/s3-secrets/velero-tests/velero# velero backup-location get default
NAME      PROVIDER   BUCKET/PREFIX   PHASE       LAST VALIDATED                  ACCESS MODE   DEFAULT
default   aws        test-velero     Available   2022-11-16 23:01:44 +0000 UTC   ReadWrite     tr
```

![image](https://user-images.githubusercontent.com/68821526/202317826-dbcc966e-4ba9-481c-8c06-70d45b1e2301.png)

[bundle-2022-11-16-23-14-49.tar.gz](https://github.com/vmware-tanzu/velero/files/10026452/bundle-2022-11-16-23-14-49.tar.gz)

thk

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by allenxu404** [comment]
As per error message, it fails to fetch volume snapshot during restore. You could refer to this [doc](https://velero.io/docs/v1.9/csi/#installing-velero-with-csi-support) if you'd like to backup PV with CSI VolumeSnapshots. 
I assume you setup nginx using the yaml at examples/nginx-app/with-pv.yaml  in velero code. If you just want to try backup/restore with velero, you cloud setup nginx using base.yaml.

**Comment by klinch0** [comment]
> 

its base.yaml nginx config, without pv

https://github.com/vmware-tanzu/velero/blob/main/examples/nginx-app/base.yaml

**Comment by allenxu404** [comment]
Got it @klinch0, this error happened when Velero attempted to get volume snapshot file during restore. it seemed that Velero had issue in getting access.  Just wonder how you install minio?

**Comment by klinch0** [comment]
i install minio via helm chart 

```

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: '*'
  install:
    createNamespace: true
  targetNamespace: minio
  interval: 1m0s
  values:
    mode: standalone
    persistence:
      enabled: true
      size: 100Gi
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cloudflare
      ingressClassName: "nginx"
      path: /
      hostname: minio.swncdn.cc
    apiIngress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cloudflare
      ingressClassName: "nginx"
      path: /
      hostname: api-minio....
```
