### ISSUE TITLE
velero can automatically upgrade and downgrade the resource version

### ISSUE THREAD

**Issue by kong62** [vmware-tanzu/velero#5613]
**Describe the problem/challenge you have**
kubernetes cluster  one 1.16   velero backup ingress:
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ APP_ID }}
  namespace: {{ ENV }}
  labels:
    app: {{ APP_ID }}
    env: {{ ENV }}
    version: {{ TAG }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: {{ DOMAIN }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ APP_ID }}
              servicePort: 8080
```

kubernetes cluster  two 1.22   velero restore ingress:
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ APP_ID }}
  namespace: {{ ENV }}
  labels:
    app: {{ APP_ID }}
    env: {{ ENV }}
    version: {{ TAG }}
spec:
  ingressClassName: traefik
  rules:
  - host: {{ DOMAIN }}
    http:
      paths:
      - backend:
          service:
            name: {{ APP_ID }}
            port:
              number: 8080
        path: /
        pathType: Prefix
```

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
velero can automatically upgrade and downgrade the resource version

**Environment:**

- Velero version (use `velero version`): v1.9.3
- Kubernetes version (use `kubectl version`): v1.16.3 and v1.22.3
