### ISSUE TITLE
Velero setup is failing with Azure AKS

### ISSUE THREAD

**Issue by VickyWinner** [vmware-tanzu/velero#5673]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
I am setting up velero on AKS cluster using helm. It fails to complete the setup.  I am using basic functionality and so did not enable volumesnapshot.  Hence, I granted below permissions per plugin requirement.

```
Microsoft.Storage/storageAccounts/listkeys/action
Microsoft.Storage/storageAccounts/regeneratekey/action
```

**What did you expect to happen:**

```
Backup is setup and no errors in BSL or pod log.
```
## kubectl get bsl
```
NAME      PHASE         LAST VALIDATED   AGE   DEFAULT
default   Unavailable   29s              19h   true
```

## Below are the Azure permissions granted
```
Storage Account Access Key Custom Role   /subscriptions/xxxAzure_Subscription_Id/resourceGroups/xxxAzure_Resource_Group/providers/Microsoft.Storage/storageAccounts/velerosa
Storage File Data SMB Share Contributor  /subscriptions/xxxAzure_Subscription_Id/resourceGroups/xxxAzure_Resource_Group/providers/Microsoft.Storage/storageAccounts/velerosa
Storage Queue Data Contributor           /subscriptions/xxxAzure_Subscription_Id/resourceGroups/xxxAzure_Resource_Group/providers/Microsoft.Storage/storageAccounts/velerosa
Storage File Data SMB Share Contributor  /subscriptions/xxxAzure_Subscription_Id/resourceGroups/xxxAzure_Resource_Group/providers/Microsoft.Storage/storageAccounts/velerosa
Storage Queue Data Contributor           /subscriptions/xxxAzure_Subscription_Id/resourceGroups/xxxAzure_Resource_Group/providers/Microsoft.Storage/storageAccounts/velerosa
Storage Blob Data Contributor            /subscriptions/xxxAzure_Subscription_Id/resourceGroups/xxxAzure_Resource_Group/providers/Microsoft.Storage/storageAccounts/velerosa
Reader                                   /subscriptions/xxxAzure_Subscription_Id/resourceGroups/xxxAzure_Resource_Group/providers/Microsoft.Storage/storageAccounts/velerosa
Reader                                   /subscriptions/xxxAzure_Subscription_Id/resourceGroups/xxxAzure_Resource_Group/providers/Microsoft.Storage/storageAccounts/velerosa
Storage Blob Data Contributor            /subscriptions/xxxAzure_Subscription_Id/resourceGroups/xxxAzure_Resource_Group/providers/Microsoft.Storage/storageAccounts/velerosa
```

## Helm values.yaml
```
image:
  repository: velero/velero
  tag: v1.10.0
  pullPolicy: Always
  imagePullSecrets: []
annotations: {}
labels: {}
podAnnotations: 
podLabels: {}
resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi
dnsPolicy: ClusterFirst
initContainers:
  - name: velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.6.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
podSecurityContext: {}
containerSecurityContext: {}
lifecycle: {}
priorityClassName: ""
terminationGracePeriodSeconds: 3600
tolerations: []
affinity: {}
nodeSelector: {}
dnsConfig: {}
extraVolumes: []
extraVolumeMounts: []
extraObjects: []
metrics:
  enabled: true
  scrapeInterval: 30s
  scrapeTimeout: 10s
  service:
    annotations: {}
    labels: {}
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"
  serviceMonitor:
    enabled: false
    additionalLabels: {}
  prometheusRule:
    enabled: false
    additionalLabels: {}
    spec: []
kubectl:
  image:
    repository: docker.io/bitnami/kubectl
  containerSecurityContext: {}
  resources: {}
  annotations: {}
  labels: {}
upgradeCRDs: true
cleanUpCRDs: false
configuration:
  provider: azure
  backupStorageLocation:
    name: 
    provider: azure
    bucket: velero-backups
    caCert: |
      LS0tLS1CRUdJTiBDRV(OneLineCACert base64 Encoded)
    prefix:
    default: true
    accessMode: ReadWrite
    config:
      resourceGroup: xxxAzure_Resource_Group
      subscriptionId: xxxAzure_Subscription_Id
      storageAccount: velerosa
  volumeSnapshotLocation:
    name:
    provider:
    config: {}
  backupSyncPeriod:
  resticTimeout:
  restoreResourcePriorities:
  restoreOnlyMode:
  clientQPS:
  clientBurst:
  clientPageSize:
  disableControllers:
  storeValidationFrequency:
  garbageCollectionFrequency:
  namespace: velero
  extraEnvVars: {}
  features:
  logLevel: debug
  logFormat:
  defaultVolumesToRestic:
  defaultResticPruneFrequency:
rbac:
  create: true
  clusterAdministrator: true
  clusterAdministratorName: cluster-admin
serviceAccount:
  server:
    create: true
    name:
    annotations:
    labels:
credentials:
  useSecret: true
  name: cloud-credentials
  existingSecret: 
  secretContents:
   cloud: |
     AZURE_CLIENT_ID=xxxxxxxxxxxxxxxxxx
     AZURE_CLIENT_SECRET=xxxxxxxxxxxxxxxxxx
     AZURE_SUBSCRIPTION_ID=xxxxxxxxxxxxxxxxxx
     AZURE_TENANT_ID=xxxxxxxxxxxxxxxxxx
     AZURE_CLOUD_NAME=AzurePublicCloud
     AZURE_RESOURCE_GROUP=xxxAzure_Resource_Group
  extraEnvVars: {}
  extraSecretRef: ""
backupsEnabled: true
snapshotsEnabled: false
deployRestic: false
configMaps: {}
```

## kubectl describe bsl
```
Name:         default
Namespace:    velero
Labels:       app.kubernetes.io/instance=velero
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=velero
              helm.sh/chart=velero-2.32.4
Annotations:  helm.sh/hook: post-install,post-upgrade,post-rollback
              helm.sh/hook-delete-policy: before-hook-creation
API Version:  velero.io/v1
Kind:         BackupStorageLocation
Metadata:
  Creation Timestamp:  2022-12-08T19:14:51Z
  Generation:          1088
  Managed Fields:
    API Version:  velero.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:helm.sh/hook:
          f:helm.sh/hook-delete-policy:
        f:labels:
          .:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/name:
          f:helm.sh/chart:
      f:spec:
        .:
        f:accessMode:
        f:config:
          .:
          f:resourceGroup:
          f:storageAccount:
          f:subscriptionId:
        f:default:
        f:objectStorage:
          .:
          f:bucket:
          f:caCert:
    Manager:      helm
    Operation:    Update
    Time:         2022-12-08T19:14:51Z
    API Version:  velero.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:lastValidationTime:
        f:message:
        f:phase:
    Manager:      velero-server
    Operation:    Update
    Time:         2022-12-08T19:14:59Z
    API Version:  velero.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:config:
          f:blockSizeInBytes:
        f:provider:
    Manager:         kubectl-edit
    Operation:       Update
    Time:            2022-12-08T20:59:25Z
  Resource Version:  36520891
  UID:               aa7cab7f-ddf5-4f23-bd5c-2a9a2c8bxxxx
Spec:
  Access Mode:  ReadWrite
  Config:
    Block Size In Bytes:  104857600
    Resource Group:       xxxAzure_Resource_Group
    Storage Account:      veleroea
    Subscription Id:      xxxAzure_Subscription_Id
  Default:                true
  Object Storage:
    Bucket:   velero-backups
    Ca Cert:   LS0tLS1CRUdJTiBDRV(OneLineCACert base64 Encoded)
  Provider:   velero.io/azure
Status:
  Last Validation Time:  2022-12-09T14:09:14Z
  Message:               BackupStorageLocation "default" is unavailable: rpc error: code = Unknown desc = storage: service returned error: StatusCode=403, ErrorCode=AuthorizationFailure, ErrorMessage=This request is not authorized to perform this operation.
RequestId:99cc452b-901e-0016-69d7-0b9a28000000
Time:2022-12-09T14:09:14.8856904Z, RequestInitiated=Fri, 09 Dec 2022 14:09:14 GMT, RequestId=99cc452b-901e-0016-69d7-0b9a28000000, API Version=, QueryParameterName=, QueryParameterValue=
  Phase:  Unavailable
Events:   <none>
```

## kubectl logs pod/velero-65cff6874c-bsfwr 
```
time="2022-12-09T13:42:00Z" level=debug msg="creating new restartable plugin process" backupLocation=velero/default command=/plugins/velero-plugin-for-microsoft-azure controller=backup-sync kind=ObjectStore logSource="pkg/plugin/clientmgmt/manager.go:139" name=velero.io/azure
time="2022-12-09T13:42:00Z" level=debug msg="Schedule is not due, skipping" logSource="pkg/controller/schedule_controller.go:217" nextRunTime="2022-12-10 00:00:00 +0000 UTC" schedule=velero/velero-astro-daily
time="2022-12-09T13:42:00Z" level=debug msg="starting plugin" args="[/plugins/velero-plugin-for-microsoft-azure --log-level debug]" backupLocation=velero/default cmd=/plugins/velero-plugin-for-microsoft-azure controller=backup-sync logSource="pkg/plugin/clientmgmt/process/logrus_adapter.go:75" path=/plugins/velero-plugin-for-microsoft-azure
time="2022-12-09T13:42:00Z" level=debug msg="plugin started" backupLocation=velero/default cmd=/plugins/velero-plugin-for-microsoft-azure controller=backup-sync logSource="pkg/plugin/clientmgmt/process/logrus_adapter.go:75" path=/plugins/velero-plugin-for-microsoft-azure pid=27523
time="2022-12-09T13:42:00Z" level=debug msg="waiting for RPC address" backupLocation=velero/default cmd=/plugins/velero-plugin-for-microsoft-azure controller=backup-sync logSource="pkg/plugin/clientmgmt/process/logrus_adapter.go:75" path=/plugins/velero-plugin-for-microsoft-azure
time="2022-12-09T13:42:00Z" level=debug msg="Setting log level to DEBUG" backupLocation=velero/default cmd=/plugins/velero-plugin-for-microsoft-azure controller=backup-sync logSource="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.7.1/pkg/plugin/framework/server.go:199" pluginName=velero-plugin-for-microsoft-azure
time="2022-12-09T13:42:00Z" level=debug msg="using plugin" backupLocation=velero/default cmd=/plugins/velero-plugin-for-microsoft-azure controller=backup-sync logSource="pkg/plugin/clientmgmt/process/logrus_adapter.go:75" version=2
time="2022-12-09T13:42:00Z" level=debug msg="plugin address" address=/tmp/plugin2705794768 backupLocation=velero/default cmd=/plugins/velero-plugin-for-microsoft-azure controller=backup-sync logSource="pkg/plugin/clientmgmt/process/logrus_adapter.go:75" network=unix pluginName=velero-plugin-for-microsoft-azure
time="2022-12-09T13:42:00Z" level=debug msg="waiting for stdio data" backupLocation=velero/default cmd=/plugins/velero-plugin-for-microsoft-azure controller=backup-sync logSource="pkg/plugin/clientmgmt/process/logrus_adapter.go:75" pluginName=stdio
time="2022-12-09T13:42:00Z" level=error msg="Error listing backups in backup store" backupLocation=velero/default controller=backup-sync error="rpc error: code = Unknown desc = storage: service returned error: StatusCode=403, ErrorCode=AuthorizationFailure, ErrorMessage=This request is not authorized to perform this operation.\nRequestId:35982459-801e-0035-45d4-0b00eb000000\nTime:2022-12-09T13:42:00.7293794Z, RequestInitiated=Fri, 09 Dec 2022 13:42:00 GMT, RequestId=35982459-801e-0035-45d4-0b00eb000000, API Version=, QueryParameterName=, QueryParameterValue=" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:402" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:107"
time="2022-12-09T13:42:00Z" level=debug msg="received EOF, stopping recv loop" backupLocation=velero/default cmd=/plugins/velero-plugin-for-microsoft-azure controller=backup-sync err="rpc error: code = Unavailable desc = error reading from server: EOF" logSource="pkg/plugin/clientmgmt/process/logrus_adapter.go:75" pluginName=stdio
time="2022-12-09T13:42:00Z" level=debug msg="plugin process exited" backupLocation=velero/default cmd=/plugins/velero-plugin-for-microsoft-azure controller=backup-sync logSource="pkg/plugin/clientmgmt/process/logrus_adapter.go:75" path=/plugins/velero-plugin-for-microsoft-azure pid=27523
time="2022-12-09T13:42:00Z" level=debug msg="plugin exited" backupLocation=velero/default cmd=/plugins/velero-plugin-for-microsoft-azure controller=backup-sync logSource="pkg/plugin/clientmgmt/process/logrus_adapter.go:75"
time="2022-12-09T13:42:04Z" level=debug msg="enqueueing resources ..." logSource="pkg/util/kube/periodical_enqueue_source.go:71" resource="*v1.BackupStorageLocationList"
time="2022-12-09T13:42:04Z" level=debug msg="skip enqueue object velero/default due to the predicate." logSource="pkg/util/kube/periodical_enqueue_source.go:92" resource="*v1.BackupStorageLocationList"
```

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
```
Client:
        Version: v1.10.0
        Git commit: 367f563072659f0bcd809bc33507fd75cd722344
Server:
        Version: v1.10.0
```
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:26:51Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"83d00b7cbf10e530d1d4b2403f22413220c37621", GitTreeState:"clean", BuildDate:"2022-11-09T19:50:11Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
```
Azure
```
- OS (e.g. from `/etc/os-release`):

*I did some troubleshooting and see that there is some traffic found on Azure storage account from activity log*
![image](https://user-images.githubusercontent.com/33285331/206724731-91cc0a35-2651-41fd-a6a7-a3226ef6ee15.png)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
