### ISSUE TITLE
On restore, when multiple selector with same key are declared, only the last is applied

### ISSUE THREAD

**Issue by FedericoAntoniazzi** [vmware-tanzu/velero#5679]
**What steps did you take and what happened:**
We have multiple resources with the following labels:
- `app=web`
- `app=nginx`

When we launch a restore by using `velero restore create --from-backup backup-test-20221212103429 -n kube-system --include-resources sts,pvc --selector app=web,app=nginx --wait`, it will be done only on resources that have `app=nginx`.

Here's the output of the describe command:
```
Name:         backup-test-20221212103429-20221212120204
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Phase:                       Completed
Total items to be restored:  1
Items restored:              1

Started:    2022-12-12 11:02:04 +0000 UTC
Completed:  2022-12-12 11:02:05 +0000 UTC

Backup:  backup-test-20221212103429

Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  <none>

Resources:
  Included:        sts, pvc
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  app=nginx

Restore PVs:  auto

Existing Resource Policy:   <none>

Preserve Service NodePorts:  auto
```

The same behaviour happens when using `--selector app=web --selector app=nginx`.

**What did you expect to happen:**
We expect velero to restore resources considering all the labels specified in the command, i.e. resources that have `app=web` and resources that have `app=nginx`.

**The following information will help us better understand what's going on**:

We think the problem is not releated to a specific backup, but we attach the manifest of the schedule CRD:
```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: backup-test
  namespace: kube-system
spec:
  schedule: "*/15 * * * *"
  template:
    includedNamespaces:
    - 'test'
    excludedNamespaces: null
    includedResources:
    - '*'
    excludedResources: null
    includeClusterResources: true
    labelSelector: null
    snapshotVolumes: false
    storageLocation: default
    volumeSnapshotLocations: []
    ttl: 720h0m0s
    hooks:
      resources: []
```

**Environment:**

- Velero version (use `velero version`):  Client: `v1.10.0`, Server: `v1.9.2`
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): `1.22.17`
- Kubernetes installer & version: `1.22.17`

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
