### ISSUE TITLE
CSI VolumeSnapshot being deleted right after the backup

### ISSUE THREAD

**Issue by headyj** [vmware-tanzu/velero#5702]
**What steps did you take and what happened:**
- configure velero with aws and csi plugins
```
configuration:
  provider: aws
  features: EnableCSI
  volumeSnapshotLocation:
    config:
      region: eu-west-2
  backupStorageLocation:
    bucket: *******
    config:
      region: "eu-central-1"
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.6.0
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v0.4.0
    volumeMounts:
      - mountPath: /target
        name: plugins
```
- create a Schedule and a VolumeSnapshotClass
```
apiVersion: velero.io/v1
kind: Schedule
spec:
[...]
  template:
    snapshotVolumes: true
    ttl: 500h
```
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  [...]
deletionPolicy: Retain
driver: ebs.csi.aws.com
```
- trigger a backup
- At the end, no specific error, but VolumeSnapshot are deleted (even if the VolumeSnapshotClass policy is set to Retain), keeping only the VolumeSnapshotContent which is then unusable, making impossible any restoration using the standard way without manually re-creating a VolumeSnapshot
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
[...]
spec:
  dataSource:
    name: <VolumeSnapshot name>
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: ebs-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

**What did you expect to happen:**
At the end of the backup, both VolumeSnapshot and VolumeSnapshotContent are kept until the expiration of the backup (500 hours in my configuration)

**Environment:**

- Velero version: v1.9.4
- Velero features: -
- Kubernetes version: v1.23
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from `/etc/os-release`): centos rhel fedora (Amazon Linux)
- 
**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
