### ISSUE TITLE
replicas can't restore

### ISSUE THREAD

**Issue by 631068264** [vmware-tanzu/velero#5722]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

 I try a simple example
```
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-example
  labels:
    app: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
```

[bundle-2022-12-29-15-28-06.tar.gz](https://github.com/vmware-tanzu/velero/files/10318113/bundle-2022-12-29-15-28-06.tar.gz)

After backup  ,change  `replicas`  to 3  from 2 , the restore result get   success  but number of `replicas`  is 3 not 2

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.8
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):  v1.18.6
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
