### ISSUE TITLE
Tencent TKE restic restore: restic-wait init container keeps waiting forever 

### ISSUE THREAD

**Issue by quangthe** [vmware-tanzu/velero#5723]
**What steps did you take and what happened:**
Cluster version: Tencent TKE `1.22.5-tke.7`
Velero version: `1.9.5`

Velero installed with
```
velero install  \
--provider aws \
--plugins velero/velero-plugin-for-aws:v1.6.0 \
--bucket velero-backup-poc-xxx \
--secret-file ./credentials-velero \
--use-restic \
--default-volumes-to-restic \
--use-volume-snapshots false \
--backup-location-config \
region=ap-guangzhou,s3ForcePathStyle="true",s3Url=https://cos.ap-guangzhou.myqcloud.com
```

Deploy simple pod with pvc:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: com.tencent.cloud.csi.cbs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-pod
  name: my-pod
spec:
  volumes:
    - name: my-pvc
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - command: ['/bin/sh', '-c', 'trap: TERM INT; sleep infinity & wait']
      image: alpine
      name: my-pod
      resources:
        requests:
          memory: 200Mi
          cpu: 100m
        limits:
          memory: 200Mi
          cpu: 100m
      volumeMounts:
        - name: my-pvc
          mountPath: /test
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
```

Execute to the pod and create some files under `/test/`.

Create backup: `velero backup create mybackup --include-namespaces=default --include-resources=po,pvc,pv` 

Backup created successfully: checked backup logs, restic files created in Tencent COS bucket.

Delete the pod and its pvc.

Restore from backup: `velero restore create --from-backup=mybackup` 

Restore created successfully. `velero restore get` 

However, the pod is in initializing state. The init container `restic-wait` keep output `Not found: /restores/my-pvc/.velero/559e199a-92c6-4210-af3b-5a838c8f2385` in log. Look like it waits forever! 

Trying to kill the pod (keep the pvc). Create the pod again, and check that all files already restore under `/test/`. Look like that the `restic-wait` init container cannot mark the restore task done.

**What did you expect to happen:**
The `restic-wait` init container should be finished.
