### ISSUE TITLE
Velero cannot use two VolumeSnapshotClass 

### ISSUE THREAD

**Issue by slawekww** [vmware-tanzu/velero#5737]
**What steps did you take and what happened:**
Use velero helm chart 3.0.0 using app version 1.10.0 in AKS 1.24.6:
deploy 2 velero instances in two namespaces: test-1 and test-2 using two different StorageAccounts in two different Azure Resource groups.

Define VolumeSnapshotClass:

```yaml
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Retain
driver: disk.csi.azure.com
kind: VolumeSnapshotClass
metadata:
  name: vsc-rg1
parameters:
  # If it is not set, it points to Resource group where AKS is deployed
  resourcegroup: my-rg-1
---
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Retain
driver: disk.csi.azure.com
kind: VolumeSnapshotClass
metadata:
  name: vsc-rg2
parameters:
  # If it is not set, it points to Resource group where AKS is deployed
  resourcegroup: my-rg-2
```

Define VolumeSnapshotLocation:

```yaml
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: vsl1
spec:
  config:
    apiTimeout: 5m
    incremental: "true"
    resourceGroup: my-rg-1
    subscriptionId: my-subscription-id
  provider: azure
---
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: vsl2
spec:
  config:
    apiTimeout: 5m
    incremental: "true"
    resourceGroup: my-rg-2
    subscriptionId: my-subscription-id
  provider: azure
```

**What did you expect to happen:**
I expect that each instance of velero stores Azure Snapshots volumes into different Azure resource group.
Now only  VolumeStorageClass **vsc-rg1** is used and regardless settings in VolumeSnapshotLocation, snapshot volume is always stored on **my-rg-1**.
If it would be possible to define many VolumeSnapshotLocation and use one velero instance, I welcome to use it however helm chart allows to define only one.

**The following information will help us better understand what's going on**:

Collected debug logs and attached however there is no error in backup but snaphots are stored in wrong location.
[bundle-2023-01-04-11-04-47.tar.gz](https://github.com/vmware-tanzu/velero/files/10343777/bundle-2023-01-04-11-04-47.tar.gz)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  1.10.0
- Velero features (use `velero client config get features`): EnableCSI  
- Kubernetes version (use `kubectl version`): AKS 1.24.6
- Kubernetes installer & version:  helm, velero helm chart 3.0.0
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04 LTS (standard AKS node)

**Vote on this issue!**

It should be allowed to store snapshots into two different Resource Groups by velero from one cluster.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
