### ISSUE TITLE
It is not possible to run velero with the newest version in an air-gapped environment

### ISSUE THREAD

**Issue by jlknoch** [vmware-tanzu/velero#5738]
We have a kubernetes cluster with one master & one slave. Both running on Ubuntu 22.04.1 with kubernetes version v1.23.6.

I installed the cli: `velero version`

![image](https://user-images.githubusercontent.com/109718804/210554356-7f7be4b2-6417-4fed-afd1-364d68e462ca.png)

I assume that the server version is empty because we have not deployed yet.

We are in an air-gapped environment with an artifactory.

We tried deploying velero with this command:

```
velero install 
--image artifactory.our-company.com/docker/velero/velero 
--plugins artifactory.our-company.com/docker/velero/velero-plugin-for-aws-arm:main 
--provider aws 
--bucket velero
--secret-file ./credentials-minio 
--use-volume-snapshots=false    
--backup-location-config region=minio,s3ForcePathStyle="true",s3Url=https://cluster1.our-company.com/minio,publicUrl=https://cluster1.our-company.com/minio 
--use-restic
```

Our secret file looks like this:
```
[default]
aws_access_key_id=****************
aws_secret_access_key=*********************************
```

When I try running the velero install command I get this output:
![image](https://user-images.githubusercontent.com/109718804/210556665-c5b438df-fcdf-4a78-a79c-e79dd1cc0851.png)

### The Problem

**However the pod is not starting** `kubectl get all -n velero` :

![image](https://user-images.githubusercontent.com/109718804/210556918-883589ae-6385-45c8-9c8e-e2c78ce66e9f.png)

`kubectl logs deployment/velero -n velero` gives this output:

![image](https://user-images.githubusercontent.com/109718804/210557300-2851496a-d696-4b92-9e36-07baa4d72756.png)

I have assumed that restic is still hanging and therefore the pod does not come up.
Therefore I did `kubectl logs restic-wcwsv -n velero` and I got:

![image](https://user-images.githubusercontent.com/109718804/210557695-ad4d4bd8-be0c-4bcc-b1f1-fde1a8e08199.png)

**I can do absolutely nothing with this error. What should it tell me?**

I then thought that maybe making restic the init container will fix it.
So I added the following `restic-cm.yaml` configmap with `kubectl apply -f restic-cm.yaml -n velero`
```
apiVersion: v1
kind: ConfigMap
metadata:
  # any name can be used; Velero uses the labels (below)
  # to identify it rather than the name
  name: restic-restore-action-config
  # must be in the velero namespace
  namespace: velero
  # the below labels should be used verbatim in your
  # ConfigMap.
  labels:
    # this value-less label identifies the ConfigMap as
    # config for a plugin (i.e. the built-in restic restore
    # item action plugin)
    velero.io/plugin-config: ""
    # this label identifies the name and kind of plugin
    # that this ConfigMap is for.
    velero.io/restic: RestoreItemAction
data:
  # The value for "image" can either include a tag or not;
  # if the tag is *not* included, the tag from the main Velero
  # image will automatically be used.
  image: artifactory.our-company.com/docker/velero/velero-restic-restore-helper

  # "cpuRequest" sets the request.cpu value on the restic init containers during restore.
  # If not set, it will default to "100m". A value of "0" is treated as unbounded.
  cpuRequest: 200m

  # "memRequest" sets the request.memory value on the restic init containers during restore.
  # If not set, it will default to "128Mi". A value of "0" is treated as unbounded.
  memRequest: 128Mi

  # "cpuLimit" sets the request.cpu value on the restic init containers during restore.
  # If not set, it will default to "100m". A value of "0" is treated as unbounded.
  cpuLimit: 200m

  # "memLimit" sets the request.memory value on the restic init containers during restore.
  # If not set, it will default to "128Mi". A value of "0" is treated as unbounded.
  memLimit: 128Mi
```

And I changed `/var/lib/kubelet/pods` in `kubectl edit daemonset.apps/restic -n velero` to `/var/vcap/data/kubelet/pods`

**I would have expected all pods in the velero namespace to be running now**

**But nothing did change. The errors are still the **same.****

Unfortunately, I do not know what else I could do. I am glad about any help.

kindly regards
Jan-Lukas
