### ISSUE TITLE
Velero partially failed backup

### ISSUE THREAD

**Issue by Lakshmi-r21** [vmware-tanzu/velero#5795]
Hi team

Velero back up is partially failing. have attached the logs for the same.Log doesnt have any specific issue
[logs.txt](https://github.com/vmware-tanzu/velero/files/10499349/logs.txt)
Could you please help us on the same

**Comment by Lakshmi-r21** [comment]
below is the configuration

```yaml
##
## Configuration settings that directly affect the Velero deployment YAML.
##

# Resource requests/limits to specify for the Velero deployment.
# https://velero.io/docs/v1.6/customize-installation/#customize-resource-requests-and-limits
resources:
  requests:
    cpu: 250m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# Init containers to add to the Velero deployment's pod spec. At least one plugin provider image is required.
# If the value is a string then it is evaluated as a template.
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.5.2
    volumeMounts:
      - mountPath: /target
        name: plugins

# Settings for Velero's prometheus metrics. Enabled by default.
metrics:
  enabled: true

  serviceMonitor:
    enabled: true

  prometheusRule:
    enabled: true
    # Rules to be deployed
    spec:
    - alert: VeleroBackupPartialFailures
      annotations:
        message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups.
      expr: |-
        velero_backup_partial_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
      for: 15m
      labels:
        severity: warning
    - alert: VeleroBackupFailures
      annotations:
        message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
      expr: |-
        velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
      for: 15m
      labels:
        severity: warning

# This job upgrades the CRDs.
upgradeCRDs: true

# This job is meant primarily for cleaning up CRDs on CI systems.
# Using this on production systems, especially those that have multiple releases of Velero, will be destructive.
cleanUpCRDs: false

##
## Parameters for the `default` BackupStorageLocation and VolumeSnapshotLocation,
## and additional server settings.
##
configuration:
  # Cloud provider being used (e.g. aws, azure, gcp).
  provider: aws

  # Parameters for the `default` BackupStorageLocation. See
  # https://velero.io/docs/v1.6/api-types/backupstoragelocation/
  backupStorageLocation:
    # name is the name of the backup storage location where backups should be stored. If a name is not provided,
    # a backup storage location will be created with the name "default". Optional.
    name: default
    # bucket is the name of the bucket to store backups in. Required.
    bucket: bucketname
    # prefix is the directory under which all Velero data should be stored within the bucket. Optional.
    prefix: prefix
    # Additional provider-specific configuration. See link above
    # for details of required/optional fields for your provider.
    config:
      region: eu-central-1
    
    # Parameters for the `default` VolumeSnapshotLocation. See
    # https://velero.io/docs/v1.6/api-types/volumesnapshotlocation/
    volumeSnapshotLocation:
      # name is the name of the volume snapshot location where snapshots are being taken. Required.
      name: default
      # Additional provider-specific configuration. See link above
      # for details of required/optional fields for your provider.
      config:
        region: eu-central-1

# Information about the Kubernetes service account Velero uses.
serviceAccount:
  server:
    create: true
    name: ref+awsssm://k8sBackup/velero/irsa/serviceAccountName
    annotations:
      eks.amazonaws.com/role-arn: ref+awsssm://k8sBackup/velero/irsa/arn

# Info about the secret to be used by the Velero deployment, which
# should contain credentials for the cloud provider IAM account you've
# set up for Velero.
credentials:
  # Whether a secret should be used. Set to false if, for examples:
  # - using kube2iam or kiam to provide AWS IAM credentials instead of providing the key file. (AWS only)
  # - using workload identity instead of providing the key file. (GCP only)
  useSecret: false

# Backup schedules to create.
schedules:
  backup:
    schedule: "0 7 * * *"
    template:
      includedNamespaces:
        - "*"
      storageLocation: default
      volumeSnapshotLocations:
        - default
      ttl: "120h0m0s"
      metadata:
        labels:
          cluster: ref+awsssm://k8sBackup/velero/eksClusterName
```

**Comment by ywk253100** [comment]
Cannot find any errors in the log file, please provide more context and the complete log

**Comment by Lakshmi-r21** [comment]
when i execute command velero backup logs velero-backup-20230127070038 -n kube-backup |grep -Ev info
below is the logs we get
"
time="2023-01-27T07:01:04Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=kube-backup/velero-backup-20230127070038 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:82" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-da9c3535-18f3-4795-8873-5686c3219857 namespace= persistentVolume=pvc-da9c3535-18f3-4795-8873-5686c3219857 resource=persistentvolumes volumeSnapshotLocation=default
time="2023-01-27T07:01:07Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=kube-backup/velero-backup-20230127070038 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:82" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-8c3af1de-6472-4723-a935-bf9038c7d1fd namespace= persistentVolume=pvc-8c3af1de-6472-4723-a935-bf9038c7d1fd resource=persistentvolumes volumeSnapshotLocation=default
time="2023-01-27T07:01:07Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=kube-backup/velero-backup-20230127070038 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:82" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-47a452e8-1fba-487c-92a4-aa540339f945 namespace= persistentVolume=pvc-47a452e8-1fba-487c-92a4-aa540339f945 resource=persistentvolumes volumeSnapshotLocation=default
time="2023-01-27T07:01:07Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=kube-backup/velero-backup-20230127070038 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:82" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-b0417473-f420-4116-a586-700ece21618f namespace= persistentVolume=pvc-b0417473-f420-4116-a586-700ece21618f resource=persistentvolumes volumeSnapshotLocation=default
time="2023-01-27T07:01:07Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=kube-backup/velero-backup-20230127070038 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:82" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-03b4e1d8-1f51-4c3e-980d-109bad8bcbae namespace= persistentVolume=pvc-03b4e1d8-1f51-4c3e-980d-109bad8bcbae resource=persistentvolumes volumeSnapshotLocation=default
time="2023-01-27T07:01:07Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=kube-backup/velero-backup-20230127070038 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:82" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-404790b0-2f6d-4fdb-8e8e-ca281a14c185 namespace= persistentVolume=pvc-404790b0-2f6d-4fdb-8e8e-ca281a14c185 resource=persistentvolumes volumeSnapshotLocation=default"
Hope this is helpful
In above comment have pasted my configuration.

**Comment by Lakshmi-r21** [comment]
With getting error with volumesnapshot location, went through few links and blogs found out we need to mention region for volume snapshot location. 
As mentioned in above configuration, have mentioned the region even for volume

**Comment by draghuram** [comment]
Hi, Just to be clear, are you saying that you provided region but are still seeing the issue? I don't see region in the VSL "default" posted above. Can you check? Also, please make sure you post the spec of a resource as "code" so that indentation is preserved.

**Comment by Lakshmi-r21** [comment]
Yes you are right, even though region is mentioned.. getting an error with partial back up.. Its taking default region

Below is my configuration, here for volume have given region as eu-central-1
```yaml
##
## Configuration settings that directly affect the Velero deployment YAML.
##

# Resource requests/limits to specify for the Velero deployment.
# https://velero.io/docs/v1.6/customize-installation/#customize-resource-requests-and-limits
resources:
  requests:
    cpu: 250m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# Init containers to add to the Velero deployment's pod spec. At least one plugin provider image is required.
# If the value is a string then it is evaluated as a template.
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.5.2
    volumeMounts:
      - mountPath: /target
        name: plugins

# Settings for Velero's prometheus metrics. Enabled by default.
metrics:
  enabled: true

  serviceMonitor:
    enabled: true

  prometheusRule:
    enabled: true
    # Rules to be deployed
    spec:
    - alert: VeleroBackupPartialFailures
      annotations:
        message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups.
      expr: |-
        velero_backup_partial_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
      for: 15m
      labels:
        severity: warning
    - alert: VeleroBackupFailures
      annotations:
        message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
      expr: |-
        velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
      for: 15m
      labels:
        severity: warning

# This job upgrades the CRDs.
upgradeCRDs: true

# This job is meant primarily for cleaning up CRDs on CI systems.
# Using this on production systems, especially those that have multiple releases of Velero, will be destructive.
cleanUpCRDs: false

##
## Parameters for the `default` BackupStorageLocation and VolumeSnapshotLocation,
## and additional server settings.
##
configuration:
  # Cloud provider being used (e.g. aws, azure, gcp).
  provider: aws

  # Parameters for the `default` BackupStorageLocation. See
  # https://velero.io/docs/v1.6/api-types/backupstoragelocation/
  backupStorageLocation:
    # name is the name of the backup storage location where backups should be stored. If a name is not provided,
    # a backup storage location will be created with the name "default". Optional.
    name: default
    # bucket is the name of the bucket to store backups in. Required.
    bucket: bucketname
    # prefix is the directory under which all Velero data should be stored within the bucket. Optional.
    prefix: prefix
    # Additional provider-specific configuration. See link above
    # for details of required/optional fields for your provider.
    config:
      region: eu-central-1
    
    # Parameters for the `default` VolumeSnapshotLocation. See
    # https://velero.io/docs/v1.6/api-types/volumesnapshotlocation/
    volumeSnapshotLocation:
      # name is the name of the volume snapshot location where snapshots are being taken. Required.
      name: default
      # Additional provider-specific configuration. See link above
      # for details of required/optional fields for your provider.
      config:
        region: eu-central-1

# Information about the Kubernetes service account Velero uses.
serviceAccount:
  server:
    create: true
    name: ref+awsssm://k8sBackup/velero/irsa/serviceAccountName
    annotations:
      eks.amazonaws.com/role-arn: ref+awsssm://k8sBackup/velero/irsa/arn

# Info about the secret to be used by the Velero deployment, which
# should contain credentials for the cloud provider IAM account you've
# set up for Velero.
credentials:
  # Whether a secret should be used. Set to false if, for examples:
  # - using kube2iam or kiam to provide AWS IAM credentials instead of providing the key file. (AWS only)
  # - using workload identity instead of providing the key file. (GCP only)
  useSecret: false

# Backup schedules to create.
schedules:
  backup:
    schedule: "0 7 * * *"
    template:
      includedNamespaces:
        - "*"
      storageLocation: default
      volumeSnapshotLocations:
        - default
      ttl: "120h0m0s"
      metadata:
        labels:
          cluster: ref+awsssm://k8sBackup/velero/eksClusterName
````

When describing logs by using command "velero backup logs velero-backup-20230127070038 -n kube-backup |grep -Ev info"
`time="2023-01-27T07:01:04Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=kube-backup/velero-backup-20230127070038 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:82" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-da9c3535-18f3-4795-8873-5686c3219857 namespace= persistentVolume=pvc-da9c3535-18f3-4795-8873-5686c3219857 resource=persistentvolumes volumeSnapshotLocation=default
time="2023-01-27T07:01:07Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=kube-backup/velero-backup-20230127070038 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:82" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-8c3af1de-6472-4723-a935-bf9038c7d1fd namespace= persistentVolume=pvc-8c3af1de-6472-4723-a935-bf9038c7d1fd resource=persistentvolumes volumeSnapshotLocation=default
time="2023-01-27T07:01:07Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=kube-backup/velero-backup-20230127070038 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:82" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-47a452e8-1fba-487c-92a4-aa540339f945 namespace= persistentVolume=pvc-47a452e8-1fba-487c-92a4-aa540339f945 resource=persistentvolumes volumeSnapshotLocation=default
time="2023-01-27T07:01:07Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=kube-backup/velero-backup-20230127070038 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:82" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-b0417473-f420-4116-a586-700ece21618f namespace= persistentVolume=pvc-b0417473-f420-4116-a586-700ece21618f resource=persistentvolumes volumeSnapshotLocation=default
time="2023-01-27T07:01:07Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=kube-backup/velero-backup-20230127070038 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:82" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-03b4e1d8-1f51-4c3e-980d-109bad8bcbae namespace= persistentVolume=pvc-03b4e1d8-1f51-4c3e-980d-109bad8bcbae resource=persistentvolumes volumeSnapshotLocation=default
time="2023-01-27T07:01:07Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=kube-backup/velero-backup-20230127070038 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:82" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-404790b0-2f6d-4fdb-8e8e-ca281a14c185 namespace= persistentVolume=pvc-404790b0-2f6d-4fdb-8e8e-ca281a14c185 resource=persistentvolumes volumeSnapshotLocation=default`
