### ISSUE TITLE
Kopia volume backup fails on incremential backups

### ISSUE THREAD

**Issue by notz** [vmware-tanzu/velero#5804]
**What steps did you take and what happened:**
We have 3 schedules that are backing up some pvc's (clickhouse, postgres, discourse) on a daily schedule with a 7 day rentention. The backup for postgres and discourse are working every day, but the clickhouse backup is only working if the last working backup was expired and deleted. 

**What did you expect to happen:**
The backup should always succeed. We like to see an option to force a full backup.

**The following information will help us better understand what's going on**:

This my schedule that fails:
```
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: plausible-clickhouse-lt
spec:
  schedule: 35 5 * * *
  template:
    includedNamespaces:
      - plausible
    includedResources:
      - '*'
    excludedResources:
      - storageclasses.storage.k8s.io
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: clickhouse
    ttl: 168h0m0s
    defaultVolumesToFsBackup: true
```

And here are the relevant log file entries:
```
time="2023-01-30T05:37:14Z" level=info msg="Backed up 3 items out of an estimated total of 10 (estimate will change throughout the backup)" backup=backup/plausible-clickhouse-lt-20230130053557 logSource="pkg/backup/backup.go:388" name=clickhouse-data-clickhouse-0 namespace=plausible progress= resource=persistentvolumeclaims |  
  |   | time="2023-01-30T05:37:14Z" level=info msg="Skipping item because it's already been backed up." backup=backup/plausible-clickhouse-lt-20230130053557 logSource="pkg/backup/item_backupper.go:126" name=clickhouse-data-clickhouse-0 namespace=plausible resource=persistentvolumeclaims |  
  |   | time="2023-01-30T05:37:14Z" level=info msg="Processing item" backup=backup/plausible-clickhouse-lt-20230130053557 logSource="pkg/backup/backup.go:348" name=clickhouse-data-clickhouse-0 namespace=plausible progress= resource=persistentvolumeclaims |  
  |   | time="2023-01-30T05:37:14Z" level=info msg="Backed up 3 items out of an estimated total of 11 (estimate will change throughout the backup)" backup=backup/plausible-clickhouse-lt-20230130053557 logSource="pkg/backup/backup.go:388" name=clickhouse-0 namespace=plausible progress= resource=pods |  
  |   | time="2023-01-30T05:37:14Z" level=error msg="Error backing up item" backup=backup/plausible-clickhouse-lt-20230130053557 error="pod volume backup failed: running backup, stderr=Failed to run kopia backup: no such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory: Failed to run kopia backup: no such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory\nno such file or directory" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:223" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:425" name=clickhouse-0 |  
  |   | time="2023-01-30T05:37:14Z" level=info msg="1 errors encountered backup up item" backup=backup/plausible-clickhouse-lt-20230130053557 logSource="pkg/backup/backup.go:421" name=clickhouse-0 |  
  |   | time="2023-01-30T05:37:14Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:37:14Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:37:14Z" level=info msg="Action finished" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/uploader/provider/kopia.go:85" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:37:14Z" level=info msg="Created snapshot with root kabdbdcde943d80693f4689e9af4b7464 and ID 1bc93941c97c130d28cd6a07f86cce62 in 1m10s" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/uploader/kopia/snapshot.go:214" parentSnapshot=69bab2107bbb650cdf8a4202e6d3c2bd path="/host_pods/846a2165-c2a7-4b23-875b-e9d8a48dc9a5/volumes/kubernetes.io~csi/ovh-managed-kubernetes-5kgslm-pvc-fca0b842-8981-4e17-9923-81e839297abe/mount" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:37:07Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:37:07Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:56Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:56Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:46Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:46Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:36Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:36Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:25Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:25Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:19Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=backup/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:136" |  
  |   | time="2023-01-30T05:36:19Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=backup/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:151" |  
  |   | time="2023-01-30T05:36:15Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:15Z" level=info msg="PodVolumeBackup starting" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:91" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:03Z" level=info msg="Start to snapshot..." backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/uploader/kopia/snapshot.go:168" parentSnapshot=69bab2107bbb650cdf8a4202e6d3c2bd path="/host_pods/846a2165-c2a7-4b23-875b-e9d8a48dc9a5/volumes/kubernetes.io~csi/ovh-managed-kubernetes-5kgslm-pvc-fca0b842-8981-4e17-9923-81e839297abe/mount" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:03Z" level=info msg="Starting backup" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/uploader/provider/kopia.go:127" parentSnapshot=69bab2107bbb650cdf8a4202e6d3c2bd path="/host_pods/846a2165-c2a7-4b23-875b-e9d8a48dc9a5/volumes/kubernetes.io~csi/ovh-managed-kubernetes-5kgslm-pvc-fca0b842-8981-4e17-9923-81e839297abe/mount" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:03Z" level=info msg="Based on parent snapshot for this backup" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:175" parentSnapshotID=69bab2107bbb650cdf8a4202e6d3c2bd podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v |  
  |   | time="2023-01-30T05:36:03Z" level=info msg="Found most recent completed PodVolumeBackup for PVC" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:276" parentPodVolumeBackup=plausible-clickhouse-lt-20230126053553-6rd8p parentSnapshotID=69bab2107bbb650cdf8a4202e6d3c2bd podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v pvcUID=fca0b842-8981-4e17-9923-81e839297abe |  
  |   | time="2023-01-30T05:36:03Z" level=info msg="Looking for most recent completed PodVolumeBackup for this PVC" backup=backup/plausible-clickhouse-lt-20230130053557 controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:228" podvolumebackup=backup/plausible-clickhouse-lt-20230130053557-6kj2v pvcUID=fca0b842-8981-4e17-9923-81e839297abe |  
  |   |  
```

**Anything else you would like to add:**
There is also a scheduled csi snapshot backup every day (rentention 1 day) at different time. 

**Environment:**

Im using the latest helm chart - 3.1.2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
```
name=clickhouse-0 namespace=plausible progress= resource=pods |  
```

From provided log, Kopia failed to backup pod `plausible/clickhouse-0`, but the error message seems a little obscure.
Could you also post the pod `plausible/clickhouse-0`'s YAML configuration here to help debug?
Looks like Kopia failed to read the directory from that pod. Need to check the detail volume configuration to find out the reason.

**Comment by blackpiglet** [comment]
```
name=clickhouse-0 namespace=plausible progress= resource=pods |  
```

From provided log, Kopia failed to backup pod `plausible/clickhouse-0`, but the error message seems a little obscure.
Could you also post the pod `plausible/clickhouse-0`'s YAML configuration here to help debug?
Looks like Kopia failed to read the directory from that pod. Need to check the detailed volume configuration to find out the reason.

**Comment by notz** [comment]
@blackpiglet sorry, i have documented the wrong schedule above. I have changed it now, to the failling one. 

Here is the pod yaml (i stripped some unneccesary fields - installed via helm):
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: clickhouse
    meta.helm.sh/release-namespace: plausible
  creationTimestamp: "2022-11-22T16:59:03Z"
  generation: 3
  labels:
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: clickhouse
    helm.toolkit.fluxcd.io/name: clickhouse
    helm.toolkit.fluxcd.io/namespace: plausible
  name: clickhouse
  namespace: plausible
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: clickhouse
      app.kubernetes.io/name: clickhouse
  serviceName: clickhouse-headless
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes-excludes: clickhouse-logs
      labels:
        app.kubernetes.io/instance: clickhouse
        app.kubernetes.io/name: clickhouse
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - export SHARD=${HOSTNAME##*-} && /entrypoint.sh
        image: yandex/clickhouse-server:21.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 5
        name: clickhouse
        ports:
        - containerPort: 8123
          name: http-port
          protocol: TCP
        - containerPort: 9000
          name: tcp-port
          protocol: TCP
        - containerPort: 9009
          name: inter-http-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/clickhouse
          name: clickhouse-data
        - mountPath: /var/log/clickhouse-server
          name: clickhouse-logs
        - mountPath: /etc/clickhouse-server/config.d
          name: clickhouse-config
        - mountPath: /etc/clickhouse-server/metrica.d
          name: clickhouse-metrica
        - mountPath: /etc/clickhouse-server/users.d
          name: clickhouse-users
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - /bin/sh
        - -c
        - |
          mkdir -p /etc/clickhouse-server/metrica.d
        image: busybox:1.31.0
        imagePullPolicy: IfNotPresent
        name: init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: clickhouse-data
        persistentVolumeClaim:
          claimName: clickhouse-data
      - emptyDir: {}
        name: clickhouse-logs
      - configMap:
          defaultMode: 420
          items:
          - key: config.xml
            path: config.xml
          name: clickhouse-config
        name: clickhouse-config
      - configMap:
          defaultMode: 420
          items:
          - key: metrica.xml
            path: metrica.xml
          name: clickhouse-metrica
        name: clickhouse-metrica
      - configMap:
          defaultMode: 420
          items:
          - key: users.xml
            path: users.xml
          name: clickhouse-users
        name: clickhouse-users
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: clickhouse-data
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: clickhouse-data
      name: clickhouse-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: csi-cinder-high-speed
      volumeMode: Filesystem
    status:
      phase: Pending
```

Here is the debug log:
[bundle-2023-01-30-13-44-39.tar.gz](https://github.com/vmware-tanzu/velero/files/10535881/bundle-2023-01-30-13-44-39.tar.gz)
