### ISSUE TITLE
When we add "- --fs-backup-timeout=1000m" in velero deployment, velero pod crashes.

### ISSUE THREAD

**Issue by masifpak** [vmware-tanzu/velero#5810]
Hi Geeks,

I was using velero to take backup including volumes. My volumes are larg in size so there are some timeouts. I went through docs and found to set this parameter in velero deployment to larg values. I set it to 1000m. But then velero pod crashes.

- --fs-backup-timeout=240m

**Comment by draghuram** [comment]
Are you sure you are using 1.10? This flag is not available in previous versions. Find version by checking "velero" container image in velero pod.

**Comment by blackpiglet** [comment]
@masifpak 
Did you set the parameter like this in the Velero deployment?

``` yaml
    spec:
      containers:
      - args:
        - server
        - --features=
        - --uploader-type=restic
        - --fs-backup-timeout=1000m
        command:
        - /velero
```

I added the parameter in my testing environment and created a backup. The backup was completed without error.
Could you follow the issue-creating template to give more detailed information?
And what is the uploader type you are using, Restic or Kopia?
Could you share the trace stack of the Velero crash?
