### ISSUE TITLE
Velero restore fails with restic: permission denied

### ISSUE THREAD

**Issue by Daemonslayer2048** [vmware-tanzu/velero#5820]
**What steps did you take and what happened:**
1. I ran a backup of the namespace in question like so: `velero backup create synapse --include-namespaces synapse-app --default-volumes-to-fs-backup`  
2. After running said backup, I redeployed my cluster (RKE2 on Centos Stream)
3. After getting the base services up (cert-manager, rook, velero, etc) I attempted a restore like so: ```velero restore create synapse --from-backup synapse```

**What did you expect to happen:**
I expected restic to recover my data and pgsql deamonsets

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
[bundle-2023-02-01-21-51-00.tar.gz](https://github.com/vmware-tanzu/velero/files/10564857/bundle-2023-02-01-21-51-00.tar.gz)
GitHub gist](https://gist.github.com) 

**Anything else you would like to add:**
I attempted to add the following ConfigMap in the hopes it would run the restic init container as root:  
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  # any name can be used; Velero uses the labels (below)
  # to identify it rather than the name
  name: restic-restore-action-config
  # must be in the velero namespace
  namespace: velero-service
  # the below labels should be used verbatim in your
  # ConfigMap.
  labels:
    # this value-less label identifies the ConfigMap as
    # config for a plugin (i.e. the built-in restic restore
    # item action plugin)
    velero.io/plugin-config: ""
    # this label identifies the name and kind of plugin
    # that this ConfigMap is for.
    velero.io/restic: RestoreItemAction
data:
  # "cpuRequest" sets the request.cpu value on the restic init containers during restore.
  # If not set, it will default to "100m". A value of "0" is treated as unbounded.
  cpuRequest: "200m"

  # "memRequest" sets the request.memory value on the restic init containers during restore.
  # If not set, it will default to "128Mi". A value of "0" is treated as unbounded.
  memRequest: "128Mi"

  # "cpuLimit" sets the request.cpu value on the restic init containers during restore.
  # If not set, it will default to "100m". A value of "0" is treated as unbounded.
  cpuLimit: "200m"

  # "memLimit" sets the request.memory value on the restic init containers during restore.
  # If not set, it will default to "128Mi". A value of "0" is treated as unbounded.
  memLimit: "128Mi"

  # "secCtxRunAsUser" sets the securityContext.runAsUser value on the restic init containers during restore.
  secCtxRunAsUser: "0"

  # "secCtxRunAsGroup" sets the securityContext.runAsGroup value on the restic init containers during restore.
  secCtxRunAsGroup: "0"

  # "secCtxAllowPrivilegeEscalation" sets the securityContext.allowPrivilegeEscalation value on the restic init containers during restore.
  secCtxAllowPrivilegeEscalation: "false"

  # "secCtx" sets the securityContext object value on the restic init containers during restore.
  # This key override  `secCtxRunAsUser`, `secCtxRunAsGroup`, `secCtxAllowPrivilegeEscalation` if `secCtx.runAsUser`, `secCtx.runAsGroup` or `secCtx.allowPrivilegeEscalation` are set.
  secCtx: |
    capabilities:
      drop:
        - ALL
      add: []
    allowPrivilegeEscalation: true
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
```
Its pretty much exactly what is on the velero site, and still no dice.

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.10.0
	Git commit: 367f563072659f0bcd809bc33507fd75cd722344
Server:
	Version: v1.10.0
```  

- Velero features (use `velero client config get features`):   
```
features: <NOT SET>
```

- Kubernetes version (use `kubectl version`):  
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"9710807c82740b9799453677c977758becf0acbb", GitTreeState:"archive", BuildDate:"2022-12-10T00:00:00Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1+rke2r1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T21:22:38Z", GoVersion:"go1.19.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version: (Installer?), v1.26.1+rke2r1
- Cloud provider or hardware configuration:  Bare metal
- OS (e.g. from `/etc/os-release`): CentOS Stream

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
What is the original cluster type? Is it also the RKE2 with CoreOS?

**Comment by Daemonslayer2048** [comment]
Neither cluster used/uses CoreOS. The original cluster was RKE2 on RHEL7 (with the CIS 1.6 profile enabled), this cluster is RKE2 on CentOS Stream (without any CIS profile enabled). 
As for the node-agents DaemonSet:  
```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    component: velero
  name: node-agent
  namespace: velero-service
spec:
  selector:
    matchLabels:
      name: node-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: velero
        name: node-agent
    spec:
      containers:
      - args:
        - node-agent
        - server
        - --features=
        command:
        - /velero
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        image: velero/velero:v1.9.0
        imagePullPolicy: IfNotPresent
        name: restic
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: /host_pods
          mountPropagation: HostToContainer
          name: host-pods
        - mountPath: /scratch
          name: scratch
        - mountPath: /credentials
          name: cloud-credentials
      securityContext:
        runAsUser: 0
      serviceAccountName: velero
      volumes:
      - hostPath:
          path: /var/lib/kubelet/pods
        name: host-pods
      - emptyDir: {}
        name: scratch
      - name: cloud-credentials
        secret:
          secretName: cloud-credentials
  updateStrategy: {}
```
