### ISSUE TITLE
Having issues with velero backing up in azure cloud.

### ISSUE THREAD

**Issue by dineshkumar-23** [vmware-tanzu/velero#5825]
### Discussed in https://github.com/vmware-tanzu/velero/discussions/5822

<div type='discussions-op-text'>

<sup>Originally posted by **dineshkumar-23** February  3, 2023</sup>
Hi. I am using velero helm chart deployed in my cluster through argocd manifest with azure backup configurations. I have the following deployment.yaml file.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero 
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: velero
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 2.30.1
    helm:
      releaseName: velero
      values: |
        initContainers:
          - name: velero-plugin-for-microsoft-azure
            image: velero/velero-plugin-for-microsoft-azure:master
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - mountPath: /target
              name: plugins
            env:
              - name: AZURE_CREDENTIALS_FILE
                valueFrom: { secretKeyRef: { name: azure-credentials, key: cloud } }
        resources:
          requests:
            memory: 250Mi
          limits:
            memory: 250Mi
        configuration:
          provider: azure
          backupStorageLocation:
            default: true
            accessMode: ReadWrite
            bucket: <my-bucket-name>
            config:
              resourceGroup: <my-resource-group>
              storageAccount: <my-storage-account>
          volumeSnapshotLocation:
            name: snapshots
        credentials:
          existingSecret: azure-credentials
        deployRestic: true
        restic:
          resources:
            requests:
              memory: 400Mi
            limits:
              memory: 500Mi
```

I created the secret as per the documentation with the following method

```
cat << EOF  > ./credentials-velero
AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
AZURE_TENANT_ID=${AZURE_TENANT_ID}
AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
AZURE_CLOUD_NAME=AzureCloud
EOF
```
`kubectl create secret generic -n velero azure-credentials --from-file=cloud=credentials-velero`

I have the following error showing up in the velero pod logs.

```
level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = unable to parse azure cloud name environment variable: autorest/azure: There is no cloud environment matching the name \"AZURECLOU │
│ D\"" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:171" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:182"
```
My cloud name when running the command `az login` and after logging in gives out a json where it is mentioned as `"cloudName": "AzureCloud"`. 
So I am not making any mistake there. Does velero azure plugin support this cloud name? or Am i making any mistake in the deployment file? I am not sure. 

So it would be really helpful if someone has already experienced this and solved the issue and successfully backed up in azurecloud could suggest me a solution for this.

Thanks.</div>
