### ISSUE TITLE
Add the ability to optionally skip some annotations from being passed from Schedule to backup

### ISSUE THREAD

**Issue by vale21** [vmware-tanzu/velero#5836]
**Describe the problem/challenge you have**

I am creating CRDs for Velero through a Helm Chart installed via ArgoCD. The chart deploys a Schedule object and ArgoCD adds anotation to the object to tell that such object belongs to it.
This is a problem when Velero triggers the scheduled backup. Velero brings the same ArgoCd annotation to the Backup object, but Argo does not expect it because it is not part of its manifes, so it deletes the backup.
Meanwhile, Velero reconciles with s3 and re-creates the backup, and so on.

As you can imagine this behavior is undesirable. I have solved it by installing the Helm chart directly, without ArgoCD but I would like to include it.

**Describe the solution you'd like**

A soultion could be to optionally disable some annotations from being copied from teh schedule to the backup. 

**Anything else you would like to add:**

This integrates issue #3067 where you added the support to copy annotations from schedules

**Environment:**

- Velero version (use `velero version`): 1.10.0
- Kubernetes version (use `kubectl version`): AWS EKS 1.24
- Kubernetes installer & version: 
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
I don't think we want to introduce a function to let user customize the annotations when a backup is created via schedules. 
Is it possible you may create the schedule out of the helm chart so that argoCD will not add annotations?
Another workaround I can think of is to create a mutation webhook to remove the annotation when the backup CR is created.

**Comment by reasonerjt** [comment]
labeling as `Icebox` as we don't consider it a very common use-case in the initial triage

**Comment by mailbox171** [comment]
I think Velero+argocd is becoming a popular combo. This feature would be welcome by many.
Thanks

**Comment by tomikonio** [comment]
Or, add the ability to pass extra annotations from the schedule to the backup, i.e.
```
kind: Schedule:
..........................
spec:
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
```
Adding this annotaion to the all the backups changes the argo-app status to synced, but there is no way to pass over this annotation from the schedule to the backups

**Comment by Freyert** [comment]
Coming to this myself as I am running into this issue on account of ArgoCD. https://github.com/vmware-tanzu/velero/pull/3067 introduces the behavior that copies the `Schedule` labels/annotations to the `Backup` labels/annotations.

This causes issues as most "child" resources (`Jobs`, `CronJobs`, `Deployments`, `StatefulSets`, etc.) require _explicitly_ passing annotations and labels to the `PodTemplate`. Copying labels/annotations is not the expected behavior in the kubernetes ecosystem AFAIK.

---

You can actually define a `template.metadata` field which will prevent the labels/annotations automatically being copied.

```yaml
# https://velero.io/docs/main/api-types/schedule/
# The labels you want on backup objects, created from this schedule (instead of copying the labels you have on schedule object itself).
# When this field is set, the labels from the Schedule resource are not copied to the Backup resource.
  metadata:
    labels:
      labelname: somelabelvalue
```

**Comment by kristoferlundgren** [comment]
This is mentioned as a potential solution, but unfortunately does not solve the issue:

> You can actually define a `template.metadata` field which will prevent the labels/**annotations** automatically being copied.

I tried adding `template.metadata.labels` and to my dismay, it does not prevent the ArgoCD annotations from being copied to the Backup object.
(BTW, I also tried adding `template.metadata.annotations`, but it is not defined in the Schedule CRD.)

The other potential solution suggested above is to use Helm. Helm charts are supported in ArgoCD but, by design, the Helm charts are extracted by ArgoCD and the manifests are still deployed with the ArgoCD annotation. And using plain Helm CLI is frowned upon when using ArgoCD/GitOps.

I.e. this is still an issue and steadily growing as ArgoCD is gaining popularity.

**Comment by remyj38** [comment]
Same issue here.

It's very annoying to see all backup in our argocd app deploying velero with schedule.

@reasonerjt Can you reconsider the "Icebox" label of the issue ? Using Argocd is no longer an uncommon use-case.

Other projets support a workaround for Argo-CD when generating objets, like [Victoria Metrics](https://docs.victoriametrics.com/operator/integrations/prometheus/#using-converter-with-argocd) which added an option to add "argocd.argoproj.io/compare-options=IgnoreExtraneous" and "argocd.argoproj.io/sync-options=Prune=false" to prevent argocd to be outofdate.
But the best solution is to prevent Velero to just copy labels and annotation from schedule.

**Comment by lubronzhan** [comment]
I put together a fix for this: https://github.com/velero-io/velero/pull/10045

  The root cause: BackupSpec.Metadata only ever had a Labels field, so while schedule.spec.template.metadata.labels could
  override the labels copied onto a Backup, there was no equivalent for annotations — schedule.annotations was always copied
  through unconditionally (pkg/builder/backup_builder.go, FromSchedule).

  The PR adds an Annotations field to `BackupSpec.Metadata` and applies the exact same override logic that already exists for
  labels:
```
  apiVersion: velero.io/v1
  kind: Schedule
  spec:
    template:
      metadata:
        annotations:
          # any annotations you set here replace schedule.metadata.annotations
          # on the Backup this schedule creates -- e.g. drop the ArgoCD
          # tracking annotation instead of propagating it
```
  This is additive/backward compatible — if you don't set `template.metadata.annotations`, behavior is unchanged. Would
  appreciate a look from @reasonerjt  when you have a chance. Thanks!
