### ISSUE TITLE
velero backup crd hooks config includeNamesapces and includeResources,but describe did not show?

### ISSUE THREAD

**Issue by 13567436138** [vmware-tanzu/velero#6043]
**What steps did you take and what happened:**

**What did you expect to happen:**
```
root@cluster3-159:~# velero backup describe nginx-backup
Name:         nginx-backup
Namespace:    velero
Labels:       velero.io/storage-location=minio
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"velero.io/v1","kind":"Backup","metadata":{"annotations":{},"labels":{"velero.io/storage-location":"minio"},"name":"nginx-backup","namespace":"velero"},"spec":{"csiSnapshotTimeout":"10m0s","hooks":{"resources":[{"includedNamespaces":["nginx-example"],"includedResources":["Deployment"],"name":"my-hook","pre":[{"exec":{"command":["/sbin/fsfreeze","--freeze","/var/log/nginx"],"container":"fsfreeze"}}]}]},"includedNamespaces":["*"],"labelSelector":{"matchLabels":{"app":"nginx"}},"storageLocation":"minio","volumeSnapshotLocations":["minio"]}}

  velero.io/source-cluster-k8s-gitversion=v1.26.1
  velero.io/source-cluster-k8s-major-version=1
  velero.io/source-cluster-k8s-minor-version=26

Phase:  InProgress

Errors:    0
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  app=nginx

Storage Location:  minio

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

CSISnapshotTimeout:  10m0s

Hooks:
  Resources:
    my-hook:
      Namespaces:
        Included:  *
        Excluded:  <none>

      Resources:
        Included:  *
        Excluded:  <none>

      Label selector:  <none>

      Pre Exec Hook:
        Container:  fsfreeze
        Command:    /sbin/fsfreeze --freeze /var/log/nginx
        On Error:   
        Timeout:    0s

Backup Format Version:  1.1.0

Started:    2023-03-28 14:00:33 +0800 CST
Completed:  <n/a>

Expiration:  2023-04-27 14:00:33 +0800 CST

Estimated total items to be backed up:  28
Items backed up so far:                 0

Velero-Native Snapshots: <none included>

```
the crd is:
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  labels:
    velero.io/storage-location: minio
  name: nginx-backup
  namespace: velero
spec:
  csiSnapshotTimeout: 10m0s
  includedNamespaces:
  - '*'
  hooks:
    resources:
    - name: my-hook
      includedNamespaces:
      - nginx-example
      includedResources: 
      - Deployment
      pre:
      - exec:
          container: fsfreeze
          command: ["/sbin/fsfreeze", "--freeze", "/var/log/nginx"]
  labelSelector:
    matchLabels:
      app: nginx
  storageLocation: minio
  volumeSnapshotLocations:
  - minio
```

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- root@cluster3-159:~# velero version
Client:
	Version: v1.10.2-rc.2
	Git commit: 7416504e3a8fea40f78bbc4cfefc7c642aafc812
Server:
	Version: v1.10.2-rc.2

- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- root@cluster3-159:~# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
root@cluster3-159:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.10"
NAME="Ubuntu"
VERSION_ID="22.10"
VERSION="22.10 (Kinetic Kudu)"
VERSION_CODENAME=kinetic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=kinetic
LOGO=ubuntu-logo

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
