### ISSUE TITLE
Got "wrong format of Capacity" error when setting resource policy during the backup

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#6045]
The resource policy is as follows:
```yaml
version: v1
volumePolicies:
  - conditions:
      capacity: '4Gi,'
      storageClass:
        - default
    action:
      type: skip
  - conditions:
      storageClass:
        - standard
    action:
      type: skip
```
Got error:
```
Validation errors:  resource policies velero/cm1: wrong format of Capacity 4Gi
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
