### ISSUE TITLE
When there's invalid key in the resource policy configmap, the validation error's text should be refined

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#6065]
Create a resource polies configmap:
```cat ./vol-policy-cm-invalid-1.yaml
version: v1
volumePolicies:
- conditions:
    capacity: "0,100Gi"
    unknownkey: "0,100Gi"
    csi: {}
    storageClass:
    - gp2
    - ebs-sc
  action:
    type: skip

k create cm vol-policy --from-file ./vol-policy-cm-invalid-1.yaml -n velero
configmap/vol-policy created
```

Create a backup referencing this configmap as resource policy:
```
./velero backup create bak2 --include-namespaces nginx-example --resource-policies-configmap vol-policy
```

The backup is in `FailedValidation` status, this is working as expected, but the validation error says 
```
resource policies velero/vol-policy: failed to decode volume conditions: yaml: unmarshal errors:
  line 6: field unknownkey not found in type resourcepolicies.volumeConditions
```

Ideally, the error should be something like `invalid key xxxxx` instead of saying the field is not found in a type

Another example:

```
cat ./vol-policy-cm-invalid-2.yaml
version: v1
volumePolicies:
- conditions:
    capacity: "0,100Gi"
    csi: {}
    storageClass: gp2
  action:
    type: skip

k create cm vol-policy --from-file ./vol-policy-cm-invalid-2.yaml -n velero
configmap/vol-policy created
```

And the error says:
```
resource policies velero/vol-policy: failed to decode volume conditions: yaml: unmarshal errors:
  line 3: cannot unmarshal !!str `gp2` into []string
```
