### ISSUE TITLE
Validation restore files before execution

### ISSUE THREAD

**Issue by andreyolv** [vmware-tanzu/velero#6195]
**Describe the problem/challenge you have**

Is it possible to verify which files will be restored before executing the restore? As a form of pre-validation of the restore

This feature would be very useful

**Describe the solution you'd like**

Show the files that will be restored before the restore

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by sseago** [comment]
When you say files, I'm assuming you are referring to files in Persistent Volumes which will be restored (either via restic/kopia, CSI snapshots, or native snapshots?).

For CSI or native snapshots, I'm not sure if there's a good way of examining snapshot content without restoring it (although I haven't looked into it). For restic, you can use the `restic ls` command to get a list of files for a given restic snapshotID -- you just need to get the snapshot ID and repo identifier from the relevant pod volume backup.

**Comment by andreyolv** [comment]
I think that the word 'files' was not a good word, sorry. 
I think the best word would be 'items'. 

Example:
- secret xxx in namespace xyz
- pvc yyy in namespace ijk
- ...

**Comment by ywk253100** [comment]
@andreyolv do you have a concrete use case for this requirement?

**Comment by sseago** [comment]
@andreyolv `velero backup describe --details` lists the items that were backed up. Does that meet your needs here?
Here's a partial listing from a recent backup in an OpenShift cluster of mine:
```
Resource List:
  apps/v1/Deployment:
    - mysql-persistent/mysql
  apps/v1/ReplicaSet:
    - mysql-persistent/mysql-76587f959d
  authorization.openshift.io/v1/RoleBinding:
    - mysql-persistent/system:deployers
    - mysql-persistent/system:image-builders
    - mysql-persistent/system:image-pullers
  discovery.k8s.io/v1/EndpointSlice:
    - mysql-persistent/mysql-n2jsf
  rbac.authorization.k8s.io/v1/RoleBinding:
    - mysql-persistent/system:deployers
    - mysql-persistent/system:image-builders
    - mysql-persistent/system:image-pullers
  v1/ConfigMap:
    - mysql-persistent/kube-root-ca.crt
    - mysql-persistent/openshift-service-ca.crt
  v1/Endpoints:
    - mysql-persistent/mysql
```
