### ISSUE TITLE
Providers for BackupStorageLocation and VolumeSnapshotLoaction are not passed properly during helm upgrade from version 3.1.6 to 4.0.2

### ISSUE THREAD

**Issue by Aabhusan** [vmware-tanzu/velero#6241]
**What steps did you take and what happened:**

I tried to upgrade velero helm chart version from 3.1.6 to 4.0.2.  and it seems like some template refactoring has been done.
.configuration.provider was removed and instead each backupStorageLocation and volumeSnapshotLocation has a provider configured. i got this error message:
```
REMOVED: .configuration.provider has been removed, instead each backupStorageLocation and volumeSnapshotLocation has a provider configured
```
after running dry and helm diff i see that provider value is missing:
```
  spec:
-   provider: gcp
+   provider: 
```
below is the error message while running:
```
Error: UPGRADE FAILED: post-upgrade hooks failed: unable to build kubernetes object for post-upgrade hook velero/templates/backupstoragelocation.yaml: error validating "": error validating data: ValidationError(BackupStorageLocation.spec): missing required field "provider" in io.velero.v1.BackupStorageLocation.spec
```
i checked the template: velero/templates/backupstoragelocation.yaml and looks like value is not passed properly.
```
spec:
   provider: {{.provider}}
```

**What did you expect to happen:**
I expected to it smoothly :smiley:

**Comment by Aabhusan** [comment]
the issue was my configuration for backupstoragelocation and volumesnapshotlocation were divided between 2 value files

values-$env.yaml
```
configuration:
  backupStorageLocation:
  - bucket: xxxxxx
      
  volumeSnapshotLocation:
  - project: xxxxxx
```

values.yaml
```
configuration:

  backupStorageLocation:
  - name: xxxx
    provider: xxx
    config:
      serviceAccount: xxx-default

  volumeSnapshotLocation:
  - name: xxxx
    provider: xxx
```
even though provider value was given it was getting null value.
but when i combined the configuration for backupstoragelocation and volumesnapshotlocation in one values.yaml file
```
configuration:
  backupStorageLocation:
    - name: xxx
      provider: xxx
      bucket: xx-xx-xx
      config:
        serviceAccount: xx-xx
  volumeSnapshotLocation:
    - name: xx
      provider: xxx
      config:
        snapshotLocation: xx-xx
        project: xx-xx-xx
```
the issue was resolved.
