### ISSUE TITLE
[Question] Inconsistent deletion time when using TTL

### ISSUE THREAD

**Issue by Lirt** [vmware-tanzu/velero#6245]
**What steps did you take and what happened:**

In Velero versions newer than 1.9 (1.10, 1.11, ...) [one line from documentation](https://velero.io/docs/v1.9/how-velero-works/) was removed:

> The effects of expiration are not applied immediately, they are applied when the gc-controller runs its reconciliation loop every hour.

If I understand correctly this line was removed because `gc-controller` was [rewritten to kubebuilder implementation](https://github.com/vmware-tanzu/velero/pull/5215/files). Does it mean that expiration would now work consistently (backup is deleted right after TTL expires)?

Right now I'm testing creation of snapshots every hour with TTL 15 minutes (shorter TTL than schedule, but this is just to test how does TTL behave) and I can see that backup lives for around 45 minutes (~30 minutes after expiration time).

```bash
NAME                                                STATUS      ERRORS   WARNINGS   CREATED                          EXPIRES   STORAGE LOCATION         SELECTOR
caas-velero-full-backup-ic-hrvart3-20230509090058   Completed   0        0          2023-05-09 11:01:28 +0200 CEST   26m ago   caas-backup-ic-hrvart3   <none>
caas-velero-full-backup-ic-hubudb3-20230509090058   Completed   0        0          2023-05-09 11:00:58 +0200 CEST   26m ago   caas-backup-ic-hubudb3   <none>

```

**What did you expect to happen:**
That backup is deleted after 15 minutes, not 45 minutes.

You can consider this issue as a question if it's not evaluated as a bug. 

If the TTL times are non completely deterministic, can we update documentation to shortly explain the process how the expiration works with TTL and what are expected times when backup deletion is triggered?

**The following information will help us better understand what's going on**:

Example schedule definition:
```yaml
apiVersion: velero.io/v1
kind: Schedule
...
spec:
  schedule: 0 */1 * * *
  template:
    includedNamespaces:
    - '*'
    snapshotVolumes: true
    storageLocation: my-backup-
    ttl: 0h15m0s
    volumeSnapshotLocations:
    - cinder
```

Example backup definition:
```yaml
apiVersion: velero.io/v1
kind: Backup
...
spec:
  csiSnapshotTimeout: 10m0s
  includedNamespaces:
  - '*'
  snapshotVolumes: true
  storageLocation: my-backup-location
  ttl: 15m0s
  volumeSnapshotLocations:
  - cinder
status:
  completionTimestamp: "2023-05-09T09:01:29Z"
  expiration: "2023-05-09T09:15:58Z"
  formatVersion: 1.1.0
  phase: Completed
  startTimestamp: "2023-05-09T09:00:58Z"
  version: 1
  volumeSnapshotsAttempted: 3
  volumeSnapshotsCompleted: 3
```

Relevant Velero log here --> [scheduled-backup-deletion.log](https://github.com/vmware-tanzu/velero/files/11429688/scheduled-backup-deletion.log)

**Environment:**

- Velero version (use `velero version`): v1.11.0
- Velero features (use `velero client config get features`): None
- Kubernetes version (use `kubectl version`): v1.24.10
- Kubernetes installer & version: CAPI
- Cloud provider or hardware configuration: Openstack
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.5 LTS
