### ISSUE TITLE
Local persistent volume raises warnings during backup (No volume ID returned by volume snapshotter for persistent volume))

### ISSUE THREAD

**Issue by M-Gregoire** [vmware-tanzu/velero#6269]
**What steps did you take and what happened:**

I have a persistent volume defined:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: <size>
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /path/to/folder
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - <node name>
```
and the following associated PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: local-storage
  volumeName: my-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: <size>
```

I then create my backup with the usual command:
`velero backup create my-backup`

Once done, looking at the logs, I see this:
```
time="<time>" level=warning msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/my-backup logSource="pkg/backup/item_backupper.go:533" name=my-pv namespace= persistentVolume=my-pv resource=persistentvolumes volumeSnapshotLocation=default
```

Looking at `kubectl -n velero get backup my-backup -oyaml` I do have a volumeSnapshotLocation properly defined:
```
<snip>
spec:
  volumeSnapshotLocations:
  - default
<snip>
```

And `kubectl -n velero get volumesnapshotlocations -oyaml` does give back a `default` volumeSnapshotLocation.

This seems to occur only with local persistent storage, not with `pvc` in a Ceph blockpool.

**What did you expect to happen:**

I expected this to work without warning as It used to previously.

**Environment:**

- Velero version (use `velero version`): v1.11
- Velero AWS plugin to backup to S3 minio: v1.7.0

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
