### ISSUE TITLE
Only one replacement rule can match when restore change image

### ISSUE THREAD

**Issue by wawa0210** [vmware-tanzu/velero#6344]
**What steps did you take and what happened:**

When I try to restore with the velero change image rule, multiple rules only hit one

**What did you expect to happen:**

It is hoped that the image can be hit by all rules and the replacement is completed

**The following information will help us better understand what's going on**:

velero v1.11.0

this is origin pod yaml 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: container1
    image: docker.m.daocloud.io/abc:test
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
```

Below is my change rule configmap

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  # any name can be used; Velero uses the labels (below)
  # to identify it rather than the name
  name: change-image-name-config
  # must be in the velero namespace
  namespace: velero
  # the below labels should be used verbatim in your
  # ConfigMap.
  labels:
    # this value-less label identifies the ConfigMap as
    # config for a plugin (i.e. the built-in restore item action plugin)
    velero.io/plugin-config: ""
    # this label identifies the name and kind of plugin
    # that this ConfigMap is for.
    velero.io/change-image-name: RestoreItemAction
data:
  "case1": "docker.m.daocloud.io,docker.m1.daocloud.io"
  "case5": ":test,:v1.2.0"
```

I hope the effect after the restore is

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: container1
    image: docker.m1.daocloud.io/abc:v1.2.0
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
```

but actual is 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: container1
    image: docker.m1.daocloud.io/abc:test
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
```

After checking the code, it is found that once a certain rule is matched, it will return directly, ignoring subsequent matches

https://github.com/vmware-tanzu/velero/blob/8427a9fdb35375353de438363305ba331659cd13/pkg/restore/change_image_name_action.go#L196-L206

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
I'm not sure about this proposal.
Could you give some example why merging the two rules into one not work for you?

**Comment by wenterjoy** [comment]
I think it is really a bug that  the rule is only matched with the first one that is found.

**Comment by blackpiglet** [comment]
My understanding of the ConfigMap rules is

1. It can have multiple rules. 
2. Each rule is supposed to replace a specific container.

I'm not sure about allowing multiple rules to apply to the same image. Of course, that can make the rules more flexible, but the rules are less readable to users. Users cannot tell the result until they read through all the existing rules.
@sseago What's your opinion?

**Comment by wawa0210** [comment]
> I think it is really a bug that the rule is only matched with the first one that is found.

I think this is a bug, the rules here should be more flexible

> Each rule is supposed to replace a specific container

This is not realistic in real scenarios. For example, the user's image may come from multiple different registries, different projects, and different tags. It is very difficult to complete accurate matching, and there will also be conflicts in the order of configuration rules. 
If the user wants to add a new matching rule, it can only be placed first in order to ensure that it takes effect, but the matching priority of the previous rule is lowered and becomes unpredictable


such as

```
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: container1
    image: dev-harbor.xx.io/app/abc:v1.2.0
    command: ['']
  - name: container2
    image: dev-harbor.xx.io/app/abc-init:v1.2.0
    command: ['']
  - name: container3
    image: dev1-harbor.xx.io/common/envoy:v1.2.0
    command: ['']
  - name: container4
    image: dev1-harbor.xx.io/common/proxy:v1.2.0
    command: ['']


// some real scenarios 
// buiness registry change
// base common tools change registry and project
// need to change image version because cve policy
dev-harbor.xx.io --> prod-harbor.xx.io
dev1-harbor.xx.io/common/ --> prod-harbor.xx.io/commonv2/
envoy:v1.2.0 --> envoy:v1.3.0

// In the past, I needed to write the rules like this, exactly matching(As cases increase, 
// rules need to be written precisely,However, in many scenarios, the registry address and project 
// replacement rules are consistent, so subsequent maintenance costs increase)

// dev-harbor.xx.io/app, prod-harbor.xx.io/app
// dev-harbor.xx.io/app, prod-harbor.xx.io/app
// dev-harbor.xx.io/app, prod-harbor.xx.io/app
// dev1-harbor.xx.io/common/envoy:v1.2.0, prod-harbor.xx.io/commonv2/envoy:v1.3.0
// dev1-harbor.xx.io/common/proxy:v1.2.0, prod-harbor.xx.io.xx.io/commonv2/envoy:v1.3.0


// new rules(High readability and easy maintenance)
// dev-harbor.xx.io,prod-harbor.xx.io/app
// dev1-harbor.xx.io/common,prod-harbor.xx.io/commonv2
// envoy:v1.2.0,envoy:v1.3.0
```

**Comment by blackpiglet** [comment]
There is a proposed design to add a generic substitution in the Restore workflow.
It can also modify the images but doesn't have the ability that this PR requests.
https://github.com/vmware-tanzu/velero/pull/5880/

Could this requested function be integrated into the design workflow?

**Comment by reasonerjt** [comment]
I think we will support whatever the resource modifier can handle.
If it can't, we'll first see if we can enhance the resource modifier.

@anshulahuja98 
Is it possible for resource modifier to achieve the configmap for `change-image-name-config`?
https://velero.io/docs/v1.12/restore-reference/#changing-poddeploymentstatefulsetdaemonsetreplicasetreplicationcontrollerjobcronjob-image-repositories

In addition, any idea on supporting the use case proposed by op?

**Comment by anshulahuja98** [comment]
Logically just the act of changing images is fully supported by resourcemodifer design.

practically the only issue might be that the user will have to define multiple substitutions whereas in case of "image-change" they could provide prefix.

To enhance the end user experience, we can add regex support to check on the prefix of the image instead of the whole image and then substitute it. This was already called as future scope in design.

It won't be the exact same functionality as "image-change"  / or the request in the issue, since they are focusing on specific rule-based sub, but with explicit substitution it is still be supported.

We can think through other approaches apart from regex match on value to see if we can add more value here using resourcemodifer, or if regex might be enough here.

**Comment by qiuming-best** [comment]
```yaml
version: v1
resourceModifierRules:
- conditions:
    groupKind: deployments.apps
    resourceNameRegex: "resource-modifiers-.*"
  patches:
  - operation: replace
    path: "/spec/template/spec/containers/0"
    value: "{\"name\": \"nginx\", \"image\": \"nginx:1.14.2\"}"
```

@anshulahuja98 Take this YAML for example, it will replace the deployments images with nginx:1.14.2, as it will replace the images directly.

In this issue, @wawa0210 wants to replace container images that contain the keywords `docker.m.daocloud.io` and `: test` with `docker.m1.daocloud.io`, `:v1.2.0`.

Currently, we can replace images with one specific value without further matching and replacing target JSON values.

below is the shell command that replaces the image:
```bash
kubectl get pod my-pod -o json | \
  jq '.spec.containers[0].image |= (sub("docker.m.daocloud.io"; "docker.m1.daocloud.io") | \
  sub("test"; "v1.2.0"))' | \
  kubectl patch pod my-pod -p "$(cat -)"
```

For this image matching and replacement requirement,  what about enhancing the handling for the target replacement JSON values? 

we could support `jq` command expression.

```yaml
version: v1
resourceModifierRules:
- conditions:
    groupKind: deployments.apps
    resourceNameRegex: "resource-modifiers-.*"
  patches:
  - operation: replace
    path: "/spec/template/spec/containers/0"
    valueReplaceRegex: 'sub("docker.m.daocloud.io"; "docker.m1.daocloud.io") | sub("test"; "v1.2.0")'
```
Also `jq` command supports regular expression
below may be one example of replacing the keyword `daocloud` with `abccloud`
```yaml
version: v1
resourceModifierRules:
- conditions:
    groupKind: deployments.apps
    resourceNameRegex: "resource-modifiers-.*"
  patches:
  - operation: replace
    path: "/spec/template/spec/containers/0"
    valueReplaceRegex: 'sub("([^/]+)/daocloud"; "\\1/abccloud")'
```
