### ISSUE TITLE
Velero TopLVM resotre affinity issue

### ISSUE THREAD

**Issue by mkoyan44** [vmware-tanzu/velero#6384]
**What steps did you take and what happened:**
I'm investigating the velero backup/restore procedure for the Disaster Recovery plan on the multi-cluster scenario. Where it is required to restore the whole namespace including PVC. The CSI provider is topolvm among with snapshot-controller. 
I have two identical clusters and I'm running the first backup command on the first cluster and restoring on the other one. 
 
```bash
velero backup create arturmkoyan-backup-41 --include-namespaces arturmkoyan --include-resources '*' --snapshot-volumes=true --include-cluster-resources=true
```

```
velero restore create arturmkoyan-restore-41 --include-namespaces arturmkoyan --from-backup arturmkoyan-backup-41 --include-resources '*' --existing-resource-policy=none
```
**What did you expect to happen:**
It's expected to have a fully working namespace after restoration. The backup command includes PV and PVC resources. After tshooting for a while I've noticed that the restored PV object has the wrong AFFINITY labels. 

```
k -n arturmkoyan get pv pvc-0dc22776-770e-44ba-a01a-b6d4f6decc6a -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: topolvm.io
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
  creationTimestamp: "2023-06-12T08:07:08Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    velero.io/backup-name: arturmkoyan-backup-41
    velero.io/restore-name: arturmkoyan-restore-41
  name: pvc-0dc22776-770e-44ba-a01a-b6d4f6decc6a
  resourceVersion: "35979335"
  uid: d8651efe-f2d5-4aa5-bc4d-bd7d78d82be3
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test-pvc
    namespace: arturmkoyan
    resourceVersion: "35920438"
    uid: ccd6a7e5-b9c1-41dc-8370-f68a78066369
  csi:
    driver: topolvm.io
    fsType: xfs
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1686472127682-8081-topolvm.io
    volumeHandle: e8901405-2519-4348-8272-df0a9ed56efc
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.topolvm.io/node
          operator: In
          values:
          - k8s-clients-mc-data-01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: topolvm-provisioner
  volumeMode: Filesystem
status:
  phase: Released
```

The PV object nodeAffinity attribute is immutable and k8s won't allow me to change it. It's expected that Velero will remove all cluster-specific attributes before performing a backup or mutating it on restore. It hardcodes k8s-clients-mc-data-01 for PV object so after restoration, the PV is malfunctioning. 

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**https://gist.github.com/mkoyan44/80c37eec54ce028e7d4f20266bd1dd20**

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): v1.11.0
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.24.6
- Kubernetes installer & version:
- Cloud provider or hardware configuration: VM
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Helm Chart:**

```
affinity: {}
annotations: {}
backupsEnabled: true
cleanUpCRDs: false
configMaps: {}
configuration:
  backupStorageLocation:
  - accessMode: ReadWrite
    bucket: S3_BUCKET_PLACEHOLDER
    config:
      s3ForcePathStyle: "true"
    credential:
      key: aws
      name: velero-aws-credentials
    name: aws-eu-default
    prefix: S3_PREFIX_PATH
    provider: aws
  backupSyncPeriod: 1m
  clientBurst: 30
  clientPageSize: 500
  clientQPS: 20
  defaultBackupStorageLocation: aws-eu-default
  defaultBackupTTL: 72h
  defaultVolumeSnapshotLocations: provider:aws
  defaultVolumesToFsBackup: false
  extraEnvVars: {}
  features: EnableCSI
  fsBackupTimeout: 4h
  logFormat: json
  logLevel: debug
  uploaderType: restic
  volumeSnapshotLocation:
  - config:
      profile: default
    name: aws-eu-default
    provider: aws
containerSecurityContext: {}
credentials:
  extraEnvVars: {}
  extraSecretRef: ""
  secretContents: {}
  useSecret: false
deployNodeAgent: true
dnsConfig: {}
dnsPolicy: ClusterFirst
extraObjects: []
extraVolumeMounts: []
extraVolumes: []
image:
  imagePullSecrets: []
  pullPolicy: IfNotPresent
  repository: velero/velero
  tag: v1.11.0
initContainers:
- image: velero/velero-plugin-for-aws:v1.7.0
  imagePullPolicy: IfNotPresent
  name: velero-plugin-for-aws
  volumeMounts:
  - mountPath: /target
    name: plugins
- image: velero/velero-plugin-for-csi:v0.5.0
  imagePullPolicy: IfNotPresent
  name: velero-plugin-for-csi
  volumeMounts:
  - mountPath: /target
    name: plugins
kubectl:
  annotations: {}
  containerSecurityContext: {}
  image:
    repository: docker.io/bitnami/kubectl
  labels: {}
  resources: {}
labels: {}
lifecycle: {}
metrics:
  enabled: true
  nodeAgentPodMonitor:
    additionalLabels: {}
    annotations: {}
    autodetect: true
    enabled: false
  podAnnotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8085"
    prometheus.io/scrape: "true"
  prometheusRule:
    additionalLabels: {}
    enabled: false
    spec: []
  scrapeInterval: 30s
  scrapeTimeout: 10s
  service:
    annotations: {}
    labels: {}
  serviceMonitor:
    additionalLabels: {}
    annotations: {}
    autodetect: true
    enabled: true
nodeAgent:
  affinity: {}
  annotations: {}
  containerSecurityContext: {}
  dnsConfig: {}
  dnsPolicy: ClusterFirst
  extraEnvVars: {}
  extraVolumeMounts: []
  extraVolumes: []
  labels: {}
  lifecycle: {}
  nodeSelector:
    topolvm-node: "yes"
  podSecurityContext:
    runAsUser: 0
  podVolumePath: /var/lib/kubelet/pods
  priorityClassName: ""
  privileged: false
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  tolerations: []
  useScratchEmptyDir: true
nodeSelector: {}
podAnnotations: {}
podLabels:
  cluster: dev-duss
  env: dev-duss
  gr8_app: velero
  jira: SRE-34760
  owner: sre
  product: kubernetes
  stream: sre
podSecurityContext: {}
priorityClassName: ""
rbac:
  clusterAdministrator: true
  clusterAdministratorName: cluster-admin
  create: true
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 128Mi
schedules: {}
serviceAccount:
  server:
    create: false
snapshotsEnabled: true
terminationGracePeriodSeconds: 3600
tolerations: []
upgradeCRDs: true
```
**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
