### ISSUE TITLE
velero restic backup timeout

### ISSUE THREAD

**Issue by ugur99** [vmware-tanzu/velero#6450]
**What steps did you take and what happened:**
Velero Restic podVolumeBackups has started to get stuck in the first attempt and it can not proceed for other volumes.

**What did you expect to happen:**
Even though it hangs for some podvolumebackups I believe that after some timeout for per volume it should be able to continue with the next volume.

**The following information will help us better understand what's going on**:
 
```yaml
# backup logs
...
name: /dashboard-oauth-proxy-c64f74f59-b89sm error: /timed out waiting for all PodVolumeBackups to complete

time="2023-07-03T02:00:22Z" level=error msg="Error backing up item" backup=velero/backup-velero-full-backup-daily-20230702220021 error="timed out waiting for all PodVolumeBackups to complete" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:243" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:435" name=dashboard-oauth-proxy-c64f74f59-b89sm

...

# backup describe 
...
restic Backups:
  New:
    argo-rollouts/dashboard-oauth-proxy-c64f74f59-b89sm: some-env
...

#podvolumebackup:
...
Status:
  Progress:
Events:  <none>

```

**Anything else you would like to add:**
I know that it is best practice to ignore some dummy volumes to make Velero Restic Backup work more efficiently, but since we cannot do this by volume type, we are currently looking for an easy way to do this for the entire cluster. I mean, if there is a way to tell Restic to only back up pvc-type volumes, that would be great.

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.11.0
	Git commit: -
Server:
	Version: v1.11.0
```
- Velero features (use `velero client config get features`): 
```
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
Server Version: v1.24.10
```
- Kubernetes installer & version:
```
kubespray 
```
