### ISSUE TITLE
Filters by volume types

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#6482]
See issue #6450, sometimes, users want to filter volumes by volume types(i.e., configMap volumes, emptyDir volumes) from various backup types (i.e., file system backup, volume/CSI snapshot).
Looks like there is no existing way for uses to do this easily, if so, we may need to add this in Velero filter mechanisms.

**Comment by reasonerjt** [comment]
We may consider add a new condition in the volume policy to let user optionally skip `hostPath`, `emptyDir` by checking the keys of entries in `.spec.volumes` of pods.

**Comment by qiuming-best** [comment]
Added one new field `VolumeTypes` string slice in `volumeConditions` struct
```go
type volumeConditions struct {
	Capacity     string           `yaml:"capacity,omitempty"`
	StorageClass []string         `yaml:"storageClass,omitempty"`
	NFS          *nFSVolumeSource `yaml:"nfs,omitempty"`
	CSI          *csiVolumeSource `yaml:"csi,omitempty"`
	VolumeTypes  []string         `yaml:"volumeTypes,omitempty"`
}

```
below is an example showing that pod mounted PV with cinder or awsElasticBlockStore volume type should be selected and skipped to be backed up.
```yaml
version: v1
volumePolicies:
- conditions:
    volumeTypes:
      - cinder
      - awsElasticBlockStore
  action:
    type: skip
  ```
