### ISSUE TITLE
Faced Helm Release issue when velero fluxcd helm release chart version is upgraded from 2.29.4 to 4.1.2

### ISSUE THREAD

**Issue by Anoop-P-Hegde** [vmware-tanzu/velero#6487]
NAME    REVISION        SUSPENDED       READY   MESSAGE

velero  2.29.4          False           False   Helm upgrade failed: execution error at (velero/templates/NOTES.txt:78:4):

                                                #################################################################################

                                                ######   BREAKING: The config values passed contained no longer accepted    #####

                                                ######             options. See the messages below for more details.        #####

                                                ######                                                                      #####

                                                ######             To verify your updated config is accepted, you can use   #####

                                                ######             the `helm template` command.                             #####

                                                #################################################################################

                                                ERROR: Please make .configuration.backupStorageLocation from map to slice

                                                REMOVED: .configuration.provider has been removed, instead each backupStorageLocation and volumeSnapshotLocation has a provider configured

Helm Release:
4.1.2
velero version1.8.1 to 1.11.0 upgrade

Could you please provide a solution for the above issue.

**Comment by Anoop-P-Hegde** [comment]
Hi Team,
Any update. Please treat this as a high priority.

**Comment by qiuming-best** [comment]
@Anoop-P-Hegde 
As from Velero helm chart v4.0.0, it supports multiple BSL and VSL, and the backupStorageLocation and volumeSnapshotLocation have changed from the map into a slice, [Here](https://github.com/vmware-tanzu/helm-charts/pull/413) is the PR.  and this breaking change is not backward compatible. So it would be best if you changed the BSL and VSL configuration into slice before the Upgrade.

```
velero:
  version: 3.1.0
  values:
    configuration:
      backupStorageLocation:
        name: default
        bucket: *veleroBucket
        config:
          region: *awsRegion
        provider: aws
      volumeSnapshotLocation:
        name: default
        provider: aws
        config:
          region: *awsRegion
```
