### ISSUE TITLE
Azure Workload Identity guide incorrect and incomplete

### ISSUE THREAD

**Issue by rdvansloten** [vmware-tanzu/velero#6510]
**What steps did you take and what happened:**
I followed the steps on: 
https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/README.md#option-2-use-azure-ad-workload-identity

And it does not work. The guide is either omitting too much information, or it simply does not work as-is. It leaves a lot of steps to the imagination. I am using the latest Velero and Azure plugin versions.

**What did you expect to happen:**

**The following information will help us better understand what's going on**:

When running the guide as-is:
```
time="2023-07-17T10:31:12Z" level=error msg="Error getting a backup store" backup-storage-location=velero/default controller=backup-storage-location error="rpc error: code = Unknown desc = DefaultAzureCredential: failed to acquire a token.\nAttempted credentials:\n\tEnvironmentCredential: missing environment variable AZURE_TENANT_ID\n\tManagedIdentityCredential: no default identity is assigned to this resource\n\tAzureCLICredential: fork/exec /bin/sh: no such file or directory" logSource="pkg/controller/backup_storage_location_controller.go:148"

time="2023-07-17T10:31:12Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/0/1, BackupStorageLocation \"default\" is unavailable: rpc error: code = Unknown desc = DefaultAzureCredential: failed to acquire a token.\nAttempted credentials:\n\tEnvironmentCredential: missing environment variable AZURE_TENANT_ID\n\tManagedIdentityCredential: no default identity is assigned to this resource\n\tAzureCLICredential: fork/exec /bin/sh: no such file or directory)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:192"
```

When setting the environment variable the error wants to have:
```
time="2023-07-17T10:40:13Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/0/1, BackupStorageLocation \"default\" is unavailable: rpc error: code = Unknown desc = DefaultAzureCredential: failed to acquire a token.\nAttempted credentials:\n\tEnvironmentCredential: missing environment variable AZURE_CLIENT_ID\n\tManagedIdentityCredential: no default identity is assigned to this resource\n\tAzureCLICredential: fork/exec /bin/sh: no such file or directory)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:192"
```

It misses yet another environment variable.

If I then add `azure.workload.identity/use: "true"` to the Pod labels, this error is shown:
```
time="2023-07-17T10:44:20Z" level=error msg="Error getting a backup store" backup-storage-location=velero/default controller=backup-storage-location error="rpc error: code = Unknown desc = DefaultAzureCredential authentication failed\nGET http://169.254.169.254/metadata/identity/oauth2/token\n--------------------------------------------------------------------------------\nRESPONSE 400 Bad Request\n--------------------------------------------------------------------------------\n{\n  \"error\": \"invalid_request\",\n  \"error_description\": \"Identity not found\"\n}\n--------------------------------------------------------------------------------\n" logSource="pkg/controller/backup_storage_location_controller.go:148"

time="2023-07-17T10:44:20Z" level=info msg="BackupStorageLocation is invalid, marking as unavailable" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:131"

time="2023-07-17T10:44:20Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/0/1, BackupStorageLocation \"default\" is unavailable: rpc error: code = Unknown desc = DefaultAzureCredential authentication failed\nGET http://169.254.169.254/metadata/identity/oauth2/token\n--------------------------------------------------------------------------------\nRESPONSE 400 Bad Request\n--------------------------------------------------------------------------------\n{\n  \"error\": \"invalid_request\",\n  \"error_description\": \"Identity not found\"\n}\n--------------------------------------------------------------------------------\n)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:192"
```

Service Account:
```
Name:                velero
Namespace:           velero
Labels:              app.kubernetes.io/instance=velero
                     app.kubernetes.io/managed-by=Helm
                     app.kubernetes.io/name=velero
                     helm.sh/chart=velero-4.1.3
Annotations:         azure.workload.identity/client-id: [CLIENT ID OF MY MANAGED IDENTITY]
                     meta.helm.sh/release-name: velero
                     meta.helm.sh/release-namespace: velero
```

**Environment:**
- Kubernetes version (use `kubectl version`): AKS, Kubernetes 1.25.6

Helm template output:
```yaml
Name:             velero-6564955b74-9wkhq
Namespace:        velero
Priority:         0
Service Account:  velero
Node:             aks-x-x-vmss000000/172.17.94.4
Start Time:       Mon, 17 Jul 2023 12:43:47 +0200
Labels:           app.kubernetes.io/instance=velero
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=velero
                  azure.workload.identity/use=true
                  helm.sh/chart=velero-4.1.3
                  name=velero
                  pod-template-hash=6564955b74
Annotations:      prometheus.io/path: /metrics
                  prometheus.io/port: 8085
                  prometheus.io/scrape: true
Status:           Running
IP:               172.x.x.x
IPs:
  IP:           172.x.x.x
Controlled By:  ReplicaSet/velero-6564955b74
Init Containers:
  velero-plugin-for-azure:
    Container ID:   containerd://729bf7147f2b5f4b93f1486b8d5ed9641f251ec12c73e44c6ff014712463a7ac
    Image:          velero/velero-plugin-for-microsoft-azure:v1.7.0
    Image ID:       docker.io/velero/velero-plugin-for-microsoft-azure@sha256:5e63c2be9dd98d56ff289ad541aede1134f999f110ba733d888d65245fc7bd3a
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 17 Jul 2023 12:43:48 +0200
      Finished:     Mon, 17 Jul 2023 12:43:48 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     300m
      memory:  256Mi
    Requests:
      cpu:     100m
      memory:  64Mi
    Environment:
      AZURE_CLIENT_ID:             [MY CLIENT ID WAS HERE]
      AZURE_TENANT_ID:             [MY TENANT ID WAS HERE]
      AZURE_FEDERATED_TOKEN_FILE:  /var/run/secrets/azure/tokens/azure-identity-token
      AZURE_AUTHORITY_HOST:        https://login.microsoftonline.com/
    Mounts:
      /target from plugins (rw)
      /var/run/secrets/azure/tokens from azure-identity-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8tk4g (ro)
Containers:
  velero:
    Container ID:  containerd://842956352e2d3128b00a159ca89e2982664041d0acb97f79eaf0a2c375be423b
    Image:         velero/velero:v1.11.0
    Image ID:      docker.io/velero/velero@sha256:80fc407e950931bf594d97aee2f4de3b1f41e596fba0af590e1530347554ec1c
    Port:          8085/TCP
    Host Port:     0/TCP
    Command:
      /velero
    Args:
      server
      --uploader-type=restic
    State:          Running
      Started:      Mon, 17 Jul 2023 12:43:49 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  512Mi
    Requests:
      cpu:      500m
      memory:   128Mi
    Liveness:   http-get http://:http-monitoring/metrics delay=10s timeout=5s period=30s #success=1 #failure=5
    Readiness:  http-get http://:http-monitoring/metrics delay=10s timeout=5s period=30s #success=1 #failure=5
    Environment:
      VELERO_SCRATCH_DIR:              /scratch
      VELERO_NAMESPACE:                velero (v1:metadata.namespace)
      LD_LIBRARY_PATH:                 /plugins
      AWS_SHARED_CREDENTIALS_FILE:     /credentials/cloud
      GOOGLE_APPLICATION_CREDENTIALS:  /credentials/cloud
      AZURE_CREDENTIALS_FILE:          /credentials/cloud
      ALIBABA_CLOUD_CREDENTIALS_FILE:  /credentials/cloud
      AZURE_TENANT_ID:                 9664fb57-6ab5-4cf3-8c69-2392f2ac06a3
      AZURE_CLIENT_ID:                 789a678d-1418-4b1e-a80b-5d795f9f57ca
      AZURE_FEDERATED_TOKEN_FILE:      /var/run/secrets/azure/tokens/azure-identity-token
      AZURE_AUTHORITY_HOST:            https://login.microsoftonline.com/
    Mounts:
      /credentials from cloud-credentials (rw)
      /plugins from plugins (rw)
      /scratch from scratch (rw)
      /tmp from tmp (rw)
      /var/run/secrets/azure/tokens from azure-identity-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8tk4g (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  cloud-credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  velero
    Optional:    false
  plugins:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  scratch:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  1Gi
  kube-api-access-8tk4g:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
  azure-identity-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3600
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
```
**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
