### ISSUE TITLE
NoCredentialProviders: no valid providers in chain.

### ISSUE THREAD

**Issue by Rohmilchkaese** [vmware-tanzu/velero#6601]
**What steps did you take and what happened:**
No matter how I pass my S3 Creds to Velero - it keeps failing. 

**What did you expect to happen:**
Being able to backup.

**The following information will help us better understand what's going on**:
I'm installing via HELM via ArgoCD: 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
spec:
  destination:
    namespace: velero
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://vmware-tanzu.github.io/helm-charts'
    targetRevision: 4.1.4
    chart: velero
    helm:
      values: |-
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.7.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
        configuration:
          logLevel: warning
          logFormat: json
          backupStorageLocation:
          - name: exoscale
            provider: aws
            bucket: BUCKET_NAME
            prefix: velero
            default: true
            accessMode: ReadWrite
            profile: "exoscale"
            credential:
              name: velero-s3
              key: exoscale
            config:
              region: 'at-vie-1'
              s3ForcePathStyle: true
              publicUrl: 'https://sos-at-vie-1.exo.io'
          volumeSnapshotLocation:
          - name: exoscale
            provider: aws
            config:
              region: 'at-vie-1'
              profile: 'exoscale'
  project: base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

This is my secret (velero-s3) in the velero namespace of course:
```
Name:         velero-s3
Namespace:    velero
Labels:       <none>
Annotations:  reflector.v1.k8s.emberstack.com/auto-reflects: True
              reflector.v1.k8s.emberstack.com/reflected-at: "2023-08-03T14:55:20.5517199+00:00"
              reflector.v1.k8s.emberstack.com/reflected-version: 557401
              reflector.v1.k8s.emberstack.com/reflects: default/velero-s3

Type:  StringData

Data
====
exoscale:  112 bytes
```

Decoded Secret: 
```
exoscale: |
  aws_access_key_id=XXX
  aws_secret_access_key=XXX
```

Logs from Pod:
```
velero-plugin-for-aws Copying /plugins/velero-plugin-for-aws to /target/velero-plugin-for-aws ...  done.
velero I0803 15:13:54.801772       1 request.go:690] Waited for 1.046668283s due to client-side throttling, not priority and fairness, request: GET:https://172.30.136.1:443/apis/longhorn.i
o/v1beta1?timeout=32s
velero {"level":"warning","logSource":"pkg/cmd/server/server.go:562","msg":"Velero node agent not found; pod volume backups/restores will not work until it's created","time":"2023-08-03T15
:13:55Z"}
velero {"level":"warning","logSource":"pkg/cmd/server/server.go:571","msg":"Velero node agent not found; pod volume backups/restores will not work until it's created","time":"2023-08-03T15
:13:55Z"}
velero {"backup-storage-location":"velero/exoscale","controller":"backup-storage-location","error.file":"/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:62","erro
r.function":"main.getSession","error.message":"rpc error: code = Unknown desc = NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.Cred
entialsChainVerboseErrors","level":"error","logSource":"pkg/controller/backup_storage_location_controller.go:148","msg":"Error getting a backup store","time":"2023-08-03T15:14:22Z"}
velero {"controller":"backup-storage-location","level":"error","logSource":"pkg/controller/backup_storage_location_controller.go:192","msg":"Current BackupStorageLocations available/unavai
lable/unknown: 0/0/1, BackupStorageLocation \"exoscale\" is unavailable: rpc error: code = Unknown desc = NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose mes
saging see aws.Config.CredentialsChainVerboseErrors)","time":"2023-08-03T15:14:22Z"}
velero {"backupLocation":"velero/exoscale","controller":"backup-sync","error.file":"/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:62","error.function":"main.get
Session","error.message":"rpc error: code = Unknown desc = NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseEr
rors","level":"error","logSource":"pkg/controller/backup_sync_controller.go:100","msg":"Error getting backup store for this location","time":"2023-08-03T15:14:56Z"}
```
**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.11.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.26.6
- Kubernetes installer & version:
- Cloud provider or hardware configuration: -> 8 Cores / 16 GB Ram for each Worker
- OS (e.g. from `/etc/os-release`): Debian 12 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
