### ISSUE TITLE
"Completed" pod is not restored although is was backed up 

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#6605]
**Describe the problem/challenge you have**
We had an fixed issue #6182 which fixed a wrong backup result issue, so currently non-running pods existance won't effect the backup result, and this kind of pods will be backed up, but the pod was not restored, as we can see it was skipped accroding to velero log.

```
velero backup describe backup-job-1 --details --insecure-skip-tls-verify

  v1/Namespace:
    - default
  v1/PersistentVolume:
    - pvc-54c9e1b6-bb21-42e8-897a-f270e337ab91
    - pvc-6189f570-9ac0-4fe2-9be6-fc0243480162
  v1/PersistentVolumeClaim:
    - default/kibishii-data-kibishii-deployment-0
    - default/kibishii-data-kibishii-deployment-1
  v1/Pod:
    - default/etcd0
    - default/etcd1
    - default/etcd2
    - default/jump-pad
    - default/kibishii-deployment-0
    - default/kibishii-deployment-1
    - default/test11-bhrhc
```

`time="2023-08-04T07:34:58Z" level=info msg="default/test11-bhrhc is complete - skipping" logSource="pkg/restore/restore.go:1040" restore=velero/backup-job-1-20230804073455`

**Describe the solution you'd like**

If there is no need  for Job type of pod, then we can skip backing up them. or restore them.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"
