### ISSUE TITLE
Restic doesn't work with schedule

### ISSUE THREAD

**Issue by AlwaySummit** [vmware-tanzu/velero#6613]
**What steps did you take and what happened:**

Create a schedule with defaultVolumesToFsBackup enabled and manually trigger a backup from the schedule. 
`/velero backup create --from-schedule velero-backup-metering`
It turns out no restic backup triggered but only velero-native snapshots:
`Velero-Native Snapshots:  1 of 1 snapshots completed successfully (specify --details for more information)`

**What did you expect to happen:**

This is the output with `/velero backup create test807-2  --default-volumes-to-fs-backup`
```
restic Backups (specify --details for more information):
  Completed:  20
```
And everything looks fine. I would expect the same result when creating backup from schedule.

**The following information will help us better understand what's going on**:

This is the description of the backup from schedule:
```
Phase:  Completed


Namespaces:
  Included:  *
  Excluded:  kube-system, kube-public, kube-node-lease, velero-restore-test, velero

Resources:
  Included:        pv, pvc
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  k8s-app in (metering)

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  48h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  1h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2023-08-07 08:08:18 +0000 UTC
Completed:  2023-08-07 08:09:04 +0000 UTC

Expiration:  2023-08-09 08:08:18 +0000 UTC

Velero-Native Snapshots:  1 of 1 snapshots completed successfully (specify --details for more information)
```

**Anything else you would like to add:**

The schedule is:
```
spec:
  schedule: 0 0 * * *
  template:
    defaultVolumesToFsBackup: true
    excludedNamespaces:
    - kube-system
    - kube-public
    - kube-node-lease
    - velero-restore-test
    - velero
    hooks: {}
    includedNamespaces:
    - '*'
    includedResources:
    - pv
    - pvc
    labelSelector:
      matchExpressions:
      - key: k8s-app
        operator: In
        values:
        - metering
    ttl: 48h0m0s
```

**Environment:**

- Velero version (use `velero version`): v1.11.0
- Velero features (use `velero client config get features`): 'features: NOT SET'
- Kubernetes version (use `kubectl version`): 12.5.10
- Kubernetes installer & version: gardener 1.69.1
- Cloud provider or hardware configuration: openstack
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 11 (bullseye)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
