### ISSUE TITLE
Datauploader returns failure until timeout when CSI plugin failed to take snapshot due to maximum count of snapshots 

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#6620]
**What steps did you take and what happened:**

1. Backup workloads with PVs by CSI data mover;
2. volumesnapshot can not be taken due to error of `reaches the configured maximum (3)`;
3. Backup returns `PartiallyFailed` until 10m timeout.

```
 k get volumesnapshot -n dm-test-2 velero-nginx-logs-e2e-3-xxxxx -o yaml

status:
  boundVolumeSnapshotContentName: snapcontent-2892fa48-2134-4726-be61-036a5978fdab
  error:
    message: 'Failed to check and update snapshot content: failed to take snapshot
      of the volume 819cb579-ac22-4ac1-80ef-37c5d5729847: "rpc error: code = FailedPrecondition
      desc = the number of snapshots on the source volume 819cb579-ac22-4ac1-80ef-37c5d5729847
      reaches the configured maximum (3)"'
    time: "2023-08-07T13:06:31Z"
  readyToUse: false
```

```
 ⚡  ~  k get dataupload -n velero backup-test-dm-xxxx -o yaml

status:
  completionTimestamp: "2023-08-07T13:27:11Z"
  message: 'error to expose snapshot: error wait volume snapshot ready: timed out
    waiting for the condition'
  phase: Failed
  progress: {}
  startTimestamp: "2023-08-07T13:27:11Z"
```

**What did you expect to happen:**

Velero should fail early when hitting this kind of error instead of waiting for nothing.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
