### ISSUE TITLE
Verify the usage that data mover and fs backup are included in one backup/restore

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#6658]
There are use cases that for one workload, some of its volumes need to be  backed up by data mover and some others to be backed up by fs backup. Though architecturally and technically this usage is supported, we need to verify it since fs backup and data mover are working in different workflows.

**Comment by Lyndon-Li** [comment]
FYI, one issue #6668 is found in this scenario.

**Comment by shawn-hurley** [comment]
I can verify that this works:

```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: quay.io/shawn_hurley/ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
    volumeMounts:
    - mountPath: /etc/config
      name: podpvc
  restartPolicy: Always
  volumes:
  - name: podpvc
    persistentVolumeClaim:
      claimName: kubepvc-1
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-2
  labels:
    app: ubuntu
  annotations:
    "backup.velero.io/backup-volumes-excludes": "podpvc"
spec:
  containers:
  - image: quay.io/shawn_hurley/ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
    volumeMounts:
    - mountPath: /etc/config
      name: podpvc
  restartPolicy: Always
  volumes:
  - name: podpvc
    persistentVolumeClaim:
      claimName: kubepvc-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubepvc-1
spec:
  storageClassName: lvms-vg1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubepvc-2
spec:
  storageClassName: lvms-vg1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

Create those resources in a namespace (use your own storage class but you get the point)

then use: 
```
velero backup create --include-namespaces test-multiple --data-mover velero --snapshot-move-data --default-volumes-to-fs-backup shawn-multi-1
```

Once you run that you should see:
```
kubectl get podvolumebackup,dataupload -n velero
NAME                                            STATUS   CREATED   NAMESPACE       POD        VOLUME   REPOSITORY ID                                                             UPLOADER TYPE   STORAGE LOCATION   AGE
podvolumebackup.velero.io/shawn-multi-1-phkdw   Failed   85m       test-multiple   ubuntu     podpvc   s3:s3-us-east-1.amazonaws.com/shawn-velero-testing/restic/test-multiple   kopia           default            85m


NAME                                       STATUS      STARTED   BYTES DONE   TOTAL BYTES   STORAGE LOCATION   AGE   NODE
dataupload.velero.io/shawn-multi-1-dfcl2   Completed   85m                                  default            85m   dhcp129-86.rdu.redhat.com
```


That failure you see is some node agent diff between pvb and dataupload code, and I will be filing a different bug.
