### ISSUE TITLE
bug? how to restic restore only one pvc

### ISSUE THREAD

**Issue by Heiko-san** [vmware-tanzu/velero#6690]
**What steps did you take and what happened:**

We make a full velero backup of a specific namespace and also restic backup the pvcs/pvs in that namespace (no snapshot backups).

Then we restore the lastest backup for a subset of resources selected by label.

``` sh
velero restore create --from-schedule my-schedule --selector "mylabel=myvalue"
```

The set consists of a pvc/pv and an sts with 1 pod.
As long as we delete the sts and the pvc, the restore succeeds, including the restic restore of the data within the pvc.

However if we just scale down the sts to 0 and only delete the pvc, then both of the following approaches fail:

``` sh
velero restore create --from-schedule my-schedule --selector "mylabel=myvalue"
velero restore create --from-schedule my-schedule --selector "mylabel=myvalue" --include-resources persistentvolumeclaims,persistentvolumes
```

The first will never end because of an error, that the sts's pod can't be queried.
The second actually succeeds, but without doing the restic restore, the pvc is restored empty.

We use velero v1.11.1

**What did you expect to happen:**

At least with the latter approach, I would have expected the data to be restored.

``` sh
velero restore create --from-schedule my-schedule --selector "mylabel=myvalue" --include-resources persistentvolumeclaims,persistentvolumes
```

Is this a bug? Or how would one do a restic restore of only the pvc/pv without touching the related resources (sts in our case)?

**Environment:**

- Velero version (use `velero version`):  

```
Client:
	Version: v1.11.0
	Git commit: 0da2baa908c88ec3c45da15001f6a4b0bda64ae2
Server:
	Version: v1.11.1
```

- Velero features (use `velero client config get features`): 

```
features: <NOT SET>
```

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"archive", BuildDate:"2023-07-20T07:37:53Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.11", GitCommit:"8cfcba0b15c343a8dc48567a74c29ec4844e0b9e", GitTreeState:"clean", BuildDate:"2023-06-14T09:49:38Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

The Schedule

``` yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: my-schedule
  namespace: velero
spec:
  schedule: 0 3 * * *
  template:
    csiSnapshotTimeout: 0s
    defaultVolumesToFsBackup: true
    hooks: {}
    includedNamespaces:
    - my-namespace
    itemOperationTimeout: 0s
    metadata: {}
    snapshotVolumes: false
  useOwnerReferencesInBackup: true
```
