### ISSUE TITLE
post.hook.restore.velero.io/timeout value ignored, 30s default applied (1.12-rc1)

### ISSUE THREAD

**Issue by funkypenguin** [vmware-tanzu/velero#6764]
**What steps did you take and what happened:**

I upgraded Velero from v1.10 to v1.12-rc1, and set about testing all my backup / restores. One of my post-restore hooks takes at least a minute to run, and so I've got a `post.hook.restore.velero.io/timeout` set to 5m. The 5m value is ignored, the default of 30s applied, and the post-restore hook command fails.

This is the pod in question:

```
        podAnnotations:
          backup.velero.io/backup-volumes: backup
          pre.hook.backup.velero.io/command: '["/bin/bash", "-c", "PGPASSWORD=$POSTGRES_PASSWORD pg_dump -U $POSTGRES_USER -d $POSTGRES_DB -F c -f /scratch/backup.psql"]'
          pre.hook.backup.velero.io/timeout: 300s
          post.hook.restore.velero.io/timeout: 300s
          post.hook.restore.velero.io/command: '["/bin/bash", "-c", "[ -f \"/scratch/backup.psql\" ] && sleep 1m && PGPASSWORD=$POSTGRES_PASSWORD pg_restore -U $POSTGRES_USER -d $POSTGRES_DB --clean < /scratch/backup.psql && rm -f /scratch/backup.psql;"]'
```

And this is the error logged by Velero:

```
time="2023-09-05T10:50:18Z" level=info msg="running exec hook" hookCommand="[/bin/bash -c [ -f \"/scratch/backup.psql\" ] && sleep 1m && PGPASSWORD=$POSTGRES_PASSWORD pg_restore -U $POSTGRES_USER -d $POSTGRES_DB --clean < /scratch/backup.psql && rm -f /scratch/backup.psql;]" hookContainer=postgresql hookName="<from-annotation>" hookOnError=Fail hookPhase=post hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:126" pod=labelstudio/labelstudio-postgresql-0 restore=velero/velero-kube-cluster-20230905104959
error: http2: client connection lost
```

Note that the output above indicates a hookTimeout of 30s. I've tried setting the value to both `300s` and `5m`, to no effect.

**What did you expect to happen:**

I expected the timeout value to be honored, and even if the command failed for another reason, I expected to see my specified timeout value in the log.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

I'm fairly confident that this timeout worked as expected on v1.10, since I've performed this restore test successfully at least once before.

**Environment:**

- Velero version (use `velero version`): v1.12.0-rc.1
- Velero features (use `velero client config get features`): `features: <NOT [SET>`]([url](url))
- Kubernetes version (use `kubectl version`): 1.27.5
- Kubernetes installer & version: kubeadm 1.27.5
- Cloud provider or hardware configuration: bare-metal
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
