### ISSUE TITLE
resource-modifier-configmap not applied

### ISSUE THREAD

**Issue by mailbox171** [vmware-tanzu/velero#6801]
I am applying a restore from a backup, mapping a ns onto a different ns.
Everything works but the label I want to remove is not removed.

No mention of it in the logs.
Some syntax problems were solved, I am on 1.12 rc1 so the syntax is still "groupKind" (not groupResource).

version: v1
resourceModifierRules:
- conditions:
    groupKind: secrets
    resourceNameRegex: ".*"
    namespaces:
    - dev-composer-artifactory
  patches:
  - operation: remove
    path: "/metadata/labels/argocd.argoproj.io~1instance"

Now I don't get any error, but the label I want to remove is always there: "argocd.argoproj.io/instance=artifactory-dev".
The restored resource is the following

$ kubectl describe secret artifactory-postgresql-cggh4d6k25 -n af03

Name:         artifactory-postgresql-cggh4d6k25
Namespace:    af03
Labels:   app.kubernetes.io/component=artifactory
              app.kubernetes.io/instance=artifactory-001
              app.kubernetes.io/name=artifactory
              app.kubernetes.io/part-of=artifactory
              app.kubernetes.io/version=1.0.0
              argocd.argoproj.io/instance=artifactory-dev
              environment=development
              tier=artifactory
              velero.io/backup-name=daily-at11-ret84-20230909110058
              velero.io/restore-name=restore-artifactory-22
              
              
[bundle-2023-09-11-17-29-53.tar.gz](https://github.com/vmware-tanzu/velero/files/12578009/bundle-2023-09-11-17-29-53.tar.gz)

 Thanks a lot.

**Comment by Lyndon-Li** [comment]
@anshulahuja98 Please help to check this issue for resource modifier. Thanks!

**Comment by anshulahuja98** [comment]
@mailbox171 can you perhaps put the configmap in a `code block`  so that it's clear ?
For example i am not sure if this part is correct `oproj.io~1insta`

**Comment by mailbox171** [comment]
Sure, you are right.
The "~1" is equivalent to "/" escaped.
Since the label I am deleting is "argocd.argoproj.io/instance"

```
version: v1
resourceModifierRules:
- conditions:
    groupKind: secrets
    resourceNameRegex: ".*"
    namespaces:
    - dev-composer-artifactory
  patches:
  - operation: remove
    path: "/metadata/labels/argocd.argoproj.io~1instance"
```

One more thing.
I had previously installed 1.11 (plugin 1.17) but I guess I uninstalled/reinstalled everything included crd.
Would be nice to have a command to check the version of ALL components.

**Comment by anshulahuja98** [comment]
1st - The issue why the substitution didn't work is that you are on rc1 build currently. In that build resource modifier's namespace filter works on the "new" namespace of the resource.

you had specified following namespace mapping: "dev-composer-artifactory": "af03"

Hence the resource modifier didn't get applied as expected. 
This fix is now checked in https://github.com/vmware-tanzu/velero/pull/6724 Post which in rc2 your current configmap should work as expected.

To test with current build in the configmap you can mention the namespace as "af03"


2nd - `I had previously installed 1.11 (azure plugin 1.7.1) but I guess I uninstalled/reinstalled everything included crd.
Now I am on 1.12 rc1 and 1.8.x.
Would be nice to have a command to check the version of ALL components.`
As of today `velero version` command gives the version of the CLI client and the velero core image in the cluster. If I understand you ask correctly you also want this command to display the versions of the plugins installed. And also potentially CRDs?
Would recommend you to create an issue for the same and we can take it up.

3rd - This is a usecase not currently addressed in the code - we `require` groupResource to be provided.  But your use case is valid. The worry however I have is that users might accidently miss adding the groupresource field in the configmap.
The approach to add this functionality I see is to support "*" as a value and skip checking if provided. 
Would request you again to create an issue for the same and we can take it up.

Thank you for trying out this feature and providing feedback / testing.

**Comment by mailbox171** [comment]
I really appreciate your prompt replies and through explanations. Thanks a lot.
I will follow your suggestions.

**Comment by mailbox171** [comment]
Hello,
I moved to version 12.1

My objective is to remove annotation "argocd.argoproj.io/instance=myapp" label from all resources on restore (otherwise they get wiped from argocd).

I have the configmap below, but it doesn't work.
Would be nice to have an example of a resource modifier that works (12.1), and deletes a label with a "/" in it (there is the issue of escaping the slash).

I have DEBUG logs, but the modifier in not mentioned during the restore. Not even finding and parsing/approving the config map.. nothing.

Please help.

Thanks a lot.

```


velero restore create restore-artifactory-07 --from-backup daily-at09-ret72-20231107090007   --include-namespaces dev-composer-artifactory --namespace-mappings dev-composer-artifactory:af01 --exclude-resources ingresses.networking.k8s.io --resource-modifier-configmap remove-argocd-label



kubectl describe cm remove-argocd-label -n velero
Name:         remove-argocd-label
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Data
====
remove-argocd-label.yml:
----
version: v1
resourceModifierRules:
- conditions:
    groupResource: "*.*"
    resourceNameRegex: ".*"
    namespaces:
    - dev-composer-artifactory 
    - af01
  patches:
  - operation: remove
    path: "/metadata/labels/argocd.argoproj.io~1instance"
- conditions:
    groupResource: configmaps
    resourceNameRegex: ".*"
    namespaces:
    - dev-composer-artifactory 
    - af01
  patches:
  - operation: remove
    path: "/metadata/labels/argocd.argoproj.io~1instance"
- conditions:
    groupResource: persistentvolumeclaims
    resourceNameRegex: ".*"
    namespaces:
    - dev-composer-artifactory 
    - af01
  patches:
  - operation: remove
    path: "/metadata/labels/argocd.argoproj.io~1instance"
- conditions:
    groupResource: persistentvolumes
    resourceNameRegex: ".*"
    namespaces:
    - dev-composer-artifactory
    - af01
  patches:
  - operation: remove
    path: "/metadata/labels/argocd.argoproj.io~1instance"
- conditions:
    groupResource: serviceaccounts
    resourceNameRegex: ".*"
    namespaces:
    - dev-composer-artifactory
    - af01
  patches:
  - operation: remove
    path: "/metadata/labels/argocd.argoproj.io~1instance"
- conditions:
    groupResource: secrets
    resourceNameRegex: ".*"
    namespaces:
    - dev-composer-artifactory
    - af01
  patches:
  - operation: remove
    path: "/metadata/labels/argocd.argoproj.io~1instance"
- conditions:
    groupResource: pods
    resourceNameRegex: ".*"
    namespaces:
    - dev-composer-artifactory
    - af01
  patches:
  - operation: remove
    path: "/metadata/labels/argocd.argoproj.io~1instance"
- conditions:
    groupResource: services
    resourceNameRegex: ".*"
    namespaces:
    - dev-composer-artifactory
    - af01
  patches:
  - operation: remove
    path: "/metadata/labels/argocd.argoproj.io~1instance"
- conditions:
    groupResource: statefulsets.apps
    resourceNameRegex: ".*"
    namespaces:
    - dev-composer-artifactory
    - af01
  patches:
  - operation: remove
    path: "/metadata/labels/argocd.argoproj.io~1instance"

BinaryData
====

Events:  <none>
```
