### ISSUE TITLE
Kopia Backup failed on 5k pods on sn , exit on "failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded"

### ISSUE THREAD

**Issue by TzahiAshkenazi** [vmware-tanzu/velero#6825]
**What steps did you take and what happened:**
Running kopia backup .
create SN with 5000 pods & PVC size 32MB storage class = cephrbd
backup CR failed exit on : "PartiallyFailed"

Steps & Commands:
1. Create single namespaces with 5000 Pods&PVs. (Each PV size is32MB without data , created using BusyBox.) sc=cephfs

2. Created Backup CR
 cr_name': 'backup-kopia-busybox-perf-single-5000-pods-cephfs
./velero backup create backup-kopia-busybox-perf-single-5000-pods-cephrbd --include-namespaces busybox-perf-single-ns-5000-pods --default-volumes-to-fs-backup=true --snapshot-volumes=false -n velero-1-12

3. backup CR failed and exit on "PartiallyFailed"

the errors: 
```name: /busybox-perf-single-ns-5000-pods-988 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-989 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-99 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-990 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-991 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-992 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-993 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-994 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-995 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-996 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-997 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-998 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-999 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded

```
Backupstoragelocations
```
[root@f07-h27-000-r640 ~]# oc get Backupstoragelocations -nvelero-1-12 -oyaml
apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    creationTimestamp: "2023-09-13T15:25:14Z"
    generation: 2175
    labels:
      component: velero
    name: default
    namespace: velero-1-12
    resourceVersion: "233186050"
    uid: 4a629817-6bd9-4dd2-b28f-b3a9c12ffa8d
  spec:
    config:
      insecureSkipTLSVerify: "true"
      profile: default
      region: minio=minio
      s3ForcePathStyle: "true"
      s3Url: http://minio-minio-bucket.apps.vlan608.rdu2.scalelab.redhat.com
    default: true
    objectStorage:
      bucket: minio-oadp-bucket
      prefix: velero
    provider: aws
  status:
    lastSyncedTime: "2023-09-14T09:42:47Z"
    lastValidationTime: "2023-09-14T09:42:31Z"
    phase: Available
kind: List
metadata:
  resourceVersion: ""
```

Backuprepositories
```
[root@f07-h27-000-r640 ~]# oc get Backuprepositories -nvelero-1-12 -oyaml
apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: BackupRepository
  metadata:
    creationTimestamp: "2023-09-13T16:35:14Z"
    generateName: busybox-perf-single-ns-5000-pods-default-kopia-
    generation: 20
    labels:
      velero.io/repository-type: kopia
      velero.io/storage-location: default
      velero.io/volume-namespace: busybox-perf-single-ns-5000-pods
    name: busybox-perf-single-ns-5000-pods-default-kopia-wkktw
    namespace: velero-1-12
    resourceVersion: "233180827"
    uid: adc9406a-5e25-4086-a789-bb3284eb62d6
  spec:
    backupStorageLocation: default
    maintenanceFrequency: 1h0m0s
    repositoryType: kopia
    resticIdentifier: s3:http://minio-minio-bucket.apps.vlan608.rdu2.scalelab.redhat.com/minio-oadp-bucket/velero/restic/busybox-perf-single-ns-5000-pods
    volumeNamespace: busybox-perf-single-ns-5000-pods
  status:
    lastMaintenanceTime: "2023-09-14T09:35:46Z"
    phase: Ready
kind: List
metadata:
  resourceVersion: ""

```

**What did you expect to happen:**
backup CR will complete successfully

**The following information will help us better understand what's going on**:

**Environment:**
Version: release-1.12-dev

features:

Kubernetes version : Kustomize Version: v4.5.4

Kubernetes installer & version:

Cloud provider or hardware configuration:
OCP running over BM servers
3 masters & 12 workers nodes

OS (e.g. from /etc/os-release):

NAME="Red Hat Enterprise Linux CoreOS"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION="411.86.202306021408-0"
VERSION_ID="4.11"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 411.86.202306021408-0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.11/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.11"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.11"
OPENSHIFT_VERSION="4.11"
RHEL_VERSION="8.6"
OSTREE_VERSION="411.86.202306021408-0"

logs :

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
> client rate limiter Wait returned an error: context deadline exceeded

This means the context used by the fs backup timed out. 
By default, the timeout value is 4 hour, that is, a fs backup is allowed to run for 4 hours. 
This timeout is set to the context used by the fs backup. As a result, when the timeout happened, the context will be cancelled and reports `context deadline exceeded`

**Comment by Lyndon-Li** [comment]
@TzahiAshkenazi 
Looks like 4 hour is not enough for your current case. You can overwrite this default timeout value by specifying a velero server parameter `--fs-backup-timeout`, see the [doc here](https://velero.io/docs/main/customize-installation/#:~:text=Additionally%2C%20you%20may%20want%20to%20update%20the%20the%20default%20File%20System%20Backup%20operation%20timeout)

**Comment by TzahiAshkenazi** [comment]
@Lyndon-Li 
thanks for your comment and suggestion indeed i manage to reproduce this one with the same error  which also mention  in the beginning of the describe command for timeout issue 
```
timed out waiting for all PodVolumeBackups to complete
```

```
Errors:
  Velero:    name: /busybox-perf-single-ns-5000-pods-4862 error: /timed out waiting for all PodVolumeBackups to complete
             name: /busybox-perf-single-ns-5000-pods-4863 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-4864 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-4865 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-4866 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-4867 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-4868 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-4869 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
             name: /busybox-perf-single-ns-5000-pods-487 error: /failed to list daemonset pods: client rate limiter Wait returned an error: context deadline exceeded
```

i will increase  the "--fs-backup-timeout"  on the backup creation command for around 6H
