### ISSUE TITLE
dont fully clean after ttl

### ISSUE THREAD

**Issue by Nello-Angelo** [vmware-tanzu/velero#6866]
**What steps did you take and what happened:**
i set up velero and schedule with ttl, ttl works but delete old files and folders exept files and folders in data folder and index folder in restic. I make backup of postgers in kubernetes. Is this correct behavior?
![Screenshot_5](https://github.com/vmware-tanzu/velero/assets/82488489/21cc9657-14a7-4dd3-a06f-ecb57244818d)
```
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: name
  namespace: velero
spec:
  schedule: '@every 1h'
  template:
    csiSnapshotTimeout: 0s
    hooks: {}
    includedNamespaces:
      - nemaspace
    itemOperationTimeout: 0s
    metadata: {}
    ttl: 3h0m0s
  useOwnerReferencesInBackup: false
```

**What did you expect to happen:**
clean all old backup files and folders exept of config file and keys folder

**Environment:**

- Velero version 1.11.1: 
- node agent
- Kubernetes version 1.25.8:
- OS debian 11:
