### ISSUE TITLE
Velero keeps Failed to pull image Kubectl image from DockerHub 

### ISSUE THREAD

**Issue by smoms** [vmware-tanzu/velero#6869]
I am trying to run Velero on GKE in GCP. I am using Velero in Chart with dependency:

```
dependencies:
   - name: velero
    version: 5.0.2
    repository: "@harbor-my-registry"
```

In my values.yaml file I have - amongst other key:value pairs - also the following values for kubectl:
```
kubectl:
  annotations: {}
  containerSecurityContext: {}
  image:
    repository: my-harbor.my-domain.com/library/kubectl
  labels: {}
  resources: {}
```
My first question is:

does Velero requires kubectl? Why?

If so, I am adding that image into my Harbor repository. However I keep receiving errors when I install the Helm release:

>kubectl describe pods velero-rel-upgrade-xxx-xxxx

`Warning  Failed            25s                kubelet            Failed to pull image "docker.io/bitnami/kubectl:1.27": rpc error: code = DeadlineExceeded desc = failed to pull and unpack image "docker.io/bitnami/kubectl:1.27": failed to resolve reference "docker.io/bitnami/kubectl:1.27": failed to do request: Head "https://registry-1.docker.io/v2/bitnami/kubectl/manifests/1.27": dial tcp 3.216.34.172:443: i/o timeout`

Why is pulling from DockerHub instead of using my Harbor registry?

thanks

**Environment:**

Kubectl:
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3-gke.100
K8s:
GKE with COS with containerd (on GCP) - 1.27.3-gke.100
velero:
5.0.2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
