### ISSUE TITLE
CSI Snapshots fail after velero CSI plugin update

### ISSUE THREAD

**Issue by stocc** [vmware-tanzu/velero#6919]
**What steps did you take and what happened:**

After an upgrade of velero-plugin-for-csi from version 0.5.1 to 0.6.0, all our backups involving CSI volume snapshots started to partially fail.
The relevant log line appears to be
```
time="2023-10-04T15:30:34Z" level=error msg="error getting volumesnapshot webportal/velero-redis-data-test-redis-replicas-2-5q55n: volumesnapshots.snapshot.storage.k8s.io \"velero-redis-data-test-redis-replicas-2-5q55n\" not found" backup=velero/webportal-20231004151837 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/volumesnapshot_action.go:234" pluginName=velero-plugin-for-csi
``` 
This has happened in multiple clusters both hosted on-premise and on AWS EKS with different CSI backends (Longhorn and AWS EBS)
After a downgrade to v0.5.1 of the plugin, our backups are working again.

**What did you expect to happen:**
After the upgrade, the backups continue to run without issues.

**Anything else you would like to add:**

[bundle-2023-10-04-17-35-17.tar.gz](https://github.com/vmware-tanzu/velero/files/12805395/bundle-2023-10-04-17-35-17.tar.gz)

I set the log level to debug if that helps. 
Here's the relevant backup schedule:
```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: webportal
  namespace: velero
spec:
  schedule: 20 2 * * *
  template:
    csiSnapshotTimeout: 30m
    hooks: {}
    includedNamespaces:
    - 'webportal'
    metadata: {}
    snapshotVolumes: true
    ttl: 720h0m0s
  useOwnerReferencesInBackup: true

```

**Environment:**

- Velero version (use `velero version`):  v1.11.1 (Helm Chart v5.0.2)
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): Server Version: v1.27.6
- Kubernetes installer & version: kubeadm (Issue also occurs on AWS EKS)
- Cloud provider or hardware configuration: vSphere VMs (also AWS EKS)
- OS (e.g. from `/etc/os-release`): AlmaLinux 8 (and Amazon Linux)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
