### ISSUE TITLE
No prometheus metrics for DataMover

### ISSUE THREAD

**Issue by ivomarino** [vmware-tanzu/velero#6954]
We see data in Grafana for backups but not for the DataMover part:

![image](https://github.com/vmware-tanzu/velero/assets/4869961/debd01a0-66b6-421a-8804-c6055d29f200)
![image](https://github.com/vmware-tanzu/velero/assets/4869961/59f225e7-7a1f-4a4e-9c68-2cf15a427437)

The DataMover is working fine and copies data to S3 using kopia:

```
kubectl -n velero get datauploads -nvelero 
NAME                                                  STATUS       STARTED   BYTES DONE   TOTAL BYTES   STORAGE LOCATION   AGE     NODE
foo-stage-velero-monitoring-20231013101819-b99wr      InProgress   29m       768883947    13258881662   foo-dc1           29m     worker-641b01f2e8637
foo-stage-velero-bar-dev-20231013103233-9tjhm   InProgress   15m       4022582406   5891101065    foo-dc1           15m     worker-641b01f2e8637
```

It seems this part of the dashboard expects metrics like `round(sum(increase(podVolume_data_upload_success_total{node=~"$fsb_node"}[1h])))` which we don't have in prometheus. This are the helm values so far for velero:

```
        metrics:
          enabled: true
          scrapeInterval: 30s
          scrapeTimeout: 10s

          # podAnnotations:
          #   prometheus.io/scrape: "true"
          #   prometheus.io/port: "8085"
          #   prometheus.io/path: "/metrics"

          extraEnvVars:
            - name: velero.io/csi-volumesnapshot-class
              value: "true" 

          serviceMonitor:
            autodetect: true
            enabled: true
        
          nodeAgentPodMonitor:
            autodetect: true
            enabled: true

          prometheusRule:
            autodetect: true
            enabled: true
```

and this is what we get in prometheus so far:
![image](https://github.com/vmware-tanzu/velero/assets/4869961/110e28e6-fed9-4f1a-9cb8-dc1c2a4ac168)

Thanks for any hints
