### ISSUE TITLE
Minio Demo doesn't work. --use-volume-snapshots=false still tries to use snapshots

### ISSUE THREAD

**Issue by sfxworks** [vmware-tanzu/velero#6977]
**What steps did you take and what happened:**

Followed https://velero.io/docs/v1.12/contributions/minio/
Made an empty directory in my minio s3 cluster and said "backup complete"

time="2023-10-19T04:48:53Z" level=info msg="Summary for skipped PVs: [{\"name\":\"pvc-8cd76f01-a9b8-4ed2-93bb-27baaa51ab37\",\"reasons\":[{\"approach\":\"volumeSnapshot\",\"reason\":\"no applicable volumesnapshotter found\"}]},{\"name\":\"pvc-952b7a5e-ba2f-4e82-abcc-2a71068e6097\",\"reasons\":[{\"approach\":\"volumeSnapshot\",\"reason\":\"no applicable volumesnapshotter found\"}]}]" backup=velero/sam-steam-backup logSource="pkg/backup/backup.go:434"

**What did you expect to happen:**
A backup is made

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
[bundle-2023-10-19-00-53-22.tar.gz](https://github.com/vmware-tanzu/velero/files/13038061/bundle-2023-10-19-00-53-22.tar.gz)

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  v1.12.0
- Velero features (use `velero client config get features`):  features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.26.2
- Kubernetes installer & version: kubeadm v1.26.2
- Cloud provider or hardware configuration: baremetal
- OS (e.g. from `/etc/os-release`): 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

**Comment by sfxworks** [comment]
Was unaware that --default-volumes-to-fs-backup was needed ontop of hostvolume support not working (using rancher local volume driver)

**Comment by gentoorax** [comment]
@sfxworks can you elaborate a bit more, did applying this parameter fix it? I have the same issue with minio. Velero installed via helm with values.yaml (see below).

Is this `--default-volumes-to-fs-backup` mandatory for minio? I mean that changes the behavior doesn't it? So that all volumes will be backed up regardless of pod annotations?

```yaml
configuration:
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: velero-default
          caCert: "<redacted>"
          prefix: promethix-alpha
          credential:
            name: cloud-credentials
            key: cloud
          config:
            region: minio
            s3ForcePathStyle: "true"
            s3Url: https://<redacted>:9000
      volumeSnapshotLocation:
        - name: default
          provider: aws
          config:
            region: minio
    credentials:
      useSecret: true
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.5.0
        volumeMounts:
          - mountPath: /target
            name: plugins
    deployNodeAgent: true
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
```
