### ISSUE TITLE
Velero pods cannot be scheduled on Kubernetes cluster version 1.26.6 installed and hardened using Kubespray

### ISSUE THREAD

**Issue by dmakeroam** [vmware-tanzu/velero#7056]
**What steps did you take and what happened:**

We installed Velero on the hardened Kubernetes cluster version 1.26.6 (The cluster installed and hardened using Kubespray)

The installation of that cluster will be follow the links:
- https://github.com/kubernetes-sigs/kubespray/tree/master
- https://github.com/kubernetes-sigs/kubespray/blob/master/docs/hardening.md

However, the pods of Velero cannot be scheduled got the error "Permission Denied". We tried to add the security context to the Velero pod spec as below:

```yaml
securityContext:
  allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 999
    runAsNonRoot: true
    runAsUser: 1001
```

But, it didn't seem to help, it got the new error

"
An error occurred: Unrecognized remote plugin message:
This usually means that the plugin is either invalid or simply needs to be recompiled to support the latest protocol.
"

Do you have any ideas to solve this?

**Environment:**

- Velero v1.8.1
- Velero aws plugin v1.2.1
- Vanilla Kubernetes version v1.26.6 (On Premise on customer private cloud)
