### ISSUE TITLE
Unable to change disk type with velero-plugin-for-microsoft-azure

### ISSUE THREAD

**Issue by michael1011101** [vmware-tanzu/velero#7083]
**What steps did you take and what happened:**
I tried to backup a PV in Azure disk as Premium SSD, then restore it as Premium SSD v2.
It succeeded to create one PV, but not SSD v2.

**What did you expect to happen:**
I expected to use velero backup from one disk type (Premium SSD) to another disk type( Premium SSD v2 ).

**Anything else you would like to add:**

**Environment:**
- Velero version (use `velero version`):  v1.11.0
- velero-plugin-for-microsoft-azure: v1.8.1

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
Did you backup the PV with `file-system backup`, `Azure snapshot` or `CSI snapshot`? 
How did you change the disk type?

**Comment by michael1011101** [comment]
_Did you backup the PV with file-system backup, Azure snapshot or CSI snapshot?_
I don't understand. The velero server was installed by others, I just use it by velero cli.
How can I check it?


_How did you change the disk type?_

I used the method of dynamically creating PVs. 
I changed the disk type by adding one new storageclass with new disk type. And then use the configmap to define how the storage class can be changed.
```
apiVersion: v1
kind: ConfigMap
metadata:
  # any name can be used; Velero uses the labels (below)
  # to identify it rather than the name
  name: change-storage-class-config-v2
  # must be in the velero namespace
  namespace: velero
  # the below labels should be used verbatim in your
  # ConfigMap.
  labels:
    # this value-less label identifies the ConfigMap as
    # config for a plugin (i.e. the built-in restore item action plugin)
    velero.io/plugin-config: ""
    # this label identifies the name and kind of plugin
    # that this ConfigMap is for.
    velero.io/change-storage-class: RestoreItemAction
data:
  # add 1+ key-value pairs here, where the key is the old
  # storage class name and the value is the new storage
  # class name.
  source-storage-class: target-storage-class-v2
```
