### ISSUE TITLE
Escaping of " in values for restore modified patches doesn't work

### ISSUE THREAD

**Issue by aschleifer** [vmware-tanzu/velero#7104]
I have the following modifier:

```yaml
  - conditions:
      groupResource: configmaps
      resourceNameRegex: "^sample-configmap"
      namespaces:
        - default
    patches:
      - operation: replace
        path: "/data/TEST_ENV_VAR"
        value: "\"true\""
```

The original configmap has this:
```yaml
data:
  TEST_ENV_VAR: "false"
```

When executing this modifier during a restore I get this error:
```
Errors:
  Velero:     <none>
  Cluster:    <none>
  Namespaces:
    exb:  error in decoding json patch invalid character 't' after object key:value pair
```

This is happening with these velero versioons:
```
Client:
        Version: v1.12.0
        Git commit: 7112c62e493b0f7570f0e7cd2088f8cad968db99
Server:
        Version: v1.12.0
```

**Comment by mateusoliveira43** [comment]
I think today its not possible to make this change today, because `false` and `true` strings are converted to boolean, instead of strings. Reference: https://github.com/vmware-tanzu/velero/blob/d42505ddd0a12f8ccc8d49dd127c2d6c9a6ea86f/internal/resourcemodifiers/json_patch.go#L36-L39

I beleive what your operation is doing is changing `"false"` to `""true""`. 

@anshulahuja98 what you think?

**Comment by blackpiglet** [comment]
I think the reason is the `\` is not handled correctly in code. 
The generated patch string is: 
```
{\"op\": \"replace\", \"from\": \"\", \"path\": \"/data/test\", \"value\": \"\"true\"\"}"
```

It should be:
```
{\"op\": \"replace\", \"from\": \"\", \"path\": \"/data/test\", \"value\": \"\\"true\"\\"}"
```

Although the example has `\` character, it is used in a user-organized string.
@anshulahuja98 Please check whether this is a valid use case.

**Comment by Segaja** [comment]
I think I also tried it with multiple `\` but couldn't get it to work.

**Comment by blackpiglet** [comment]
Make it work with this ConfigMap setting.

``` yaml
apiVersion: v1
data:
  modify_deploy.yaml: |
    version: v1
    resourceModifierRules:
    - conditions:
        groupResource: configmaps
        resourceNameRegex: "test"
        namespaces:
        - upgrade
      patches:
      - operation: replace
        path: "/data/test"
        value: "\\\"true\\\""
kind: ConfigMap
metadata:
  name: modify-deploy
  namespace: velero
```

```yaml
apiVersion: v1
data:
  test: '"true"'
kind: ConfigMap
metadata:
  creationTimestamp: "2023-11-17T01:21:32Z"
  labels:
    velero.io/backup-name: test-01
    velero.io/restore-name: test-01-20231117092120
  name: test
  namespace: upgrade
  resourceVersion: "130749607"
  uid: 63ab5b05-041b-4bfc-912e-61315b758e98

```
