### ISSUE TITLE
Expired Backup objects from BackupStorageLocations with accessMode=ReadOnly don't get cleaned up

### ISSUE THREAD

**Issue by phoenix-bjoern** [vmware-tanzu/velero#7106]
When a BackupStorageLocation is defined with *accessMode: ReadOnly* Velero imports Backup objects into the cluster as usual.

```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: my-backups
  namespace: velero
spec:
  accessMode: ReadOnly
```

Once the Backups objects expire, Velero usually would remove the Backup objects in the BackupStorageLocation **and** in the cluster if the *accessMode* is set to *ReadWrite*. However, for *ReadOnly* BackupStorageLocations Velero neither removes the entities in the storage location (which is expected), nor does it remove it in the K8S cluster is it installed. Over the time this behavior could lead to a vast number of Backup objects, which could slow down Velero's operations.

It is expected that Velero cleans up the Backup (and other objects) in the cluster it is installed even of the *accessMode* of the BackupStorageLocation is *ReadOnly*.
