### ISSUE TITLE
Azure Disk Type Change Request by snapshot backup

### ISSUE THREAD

**Issue by michael1011101** [vmware-tanzu/velero#7109]
**Describe the problem/challenge you have**

In our landscape, we use the snapshot backup to backup and restore resources. Now we have a scenario where we need to restore the disk to another Azure disk type (type: Premium SSD v2) with Velero.

**Describe the solution you'd like**

1. Add another storage class with new disk type.
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    name: hana
  name: sc-v2
parameters:
  cachingmode: None
  fsType: xfs
  kind: managed
  storageaccounttype: PremiumV2_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
2. Add velereo restore item action configmap.
```
apiVersion: v1
kind: ConfigMap
metadata:
  # any name can be used; Velero uses the labels (below)
  # to identify it rather than the name
  name: change-storage-class-config-v2
  # must be in the velero namespace
  namespace: velero
  # the below labels should be used verbatim in your
  # ConfigMap.
  labels:
    # this value-less label identifies the ConfigMap as
    # config for a plugin (i.e. the built-in restore item action plugin)
    velero.io/plugin-config: ""
    # this label identifies the name and kind of plugin
    # that this ConfigMap is for.
    velero.io/change-storage-class: RestoreItemAction
data:
  # add 1+ key-value pairs here, where the key is the old
  # storage class name and the value is the new storage
  # class name.
  sc: sc-v2
```
3. Backup resources (PV) with velero.
```
velero backup create testbackup --include-resources=pv,pvc,replicasets
```
4. Delete resources in k8s.
5. Restore from backup.
```
velero restore create --from-backup testbackup
```
6. The disk type of PV is changed.

**Anything else you would like to add:**

**Environment:**

- Velero version (use velero version): v1.11.0
- velero-plugin-for-microsoft-azure: v1.8.1

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"
