### ISSUE TITLE
Can't perform a snapshot move of data to S3 from the ebs.csi.aws.com provisioner

### ISSUE THREAD

**Issue by ametdoohan** [vmware-tanzu/velero#7157]
**What steps did you take and what happened:**

When doing snapshot move data using this command `velero backup create default-ns --include-namespaces default --snapshot-move-data` is not successful. Im deploying velero using helm `helm install velero vmware-tanzu/velero  --namespace velero -f values.yaml  --version 5.1.4` . And here is values.yaml

```
configuration:
  uploaderType: kopia
  backupStorageLocation:
  - bucket: [redacted]
    defaultVolumesToFsBackup: True
    provider: aws
  volumeSnapshotLocation:
  - config:
      region: ap-southeast-3
    provider: aws
  features: EnableCSI
initContainers:
- name: velero-plugin-for-csi
  image: velero/velero-plugin-for-csi:v0.6.0
  volumeMounts:
    - mountPath: /target
      name: plugins
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v1.8.2
  volumeMounts:
  - mountPath: /target
    name: plugins
credentials:
  useSecret: false
serviceAccount:
  name: velero-server
  server:
    annotations:
      eks.amazonaws.com/role-arn: "[redacted]"
deployNodeAgent: true
```

Here is policy.json 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeVolumes",
                "ec2:DescribeSnapshots",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:CreateSnapshot",
                "ec2:DeleteSnapshot"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObject",
                "s3:AbortMultipartUpload",
                "s3:ListMultipartUploadParts"
            ],
            "Resource": [
                "arn:aws:s3:::[redacted s3]/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::[redacted s3]"
            ]
        },
        {
            "Resource": [
                "[redacted kms]"
            ],
            "Action": [
                "kms:GenerateDataKey",
                "kms:Decrypt"
            ],
            "Effect": "Allow"
        }
    ]
}
```

**What did you expect to happen:**
I am expecting backup data from the PVC provisioner ebs.csi.aws.com to S3 instead of a snapshot.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

[bundle-2023-11-29-10-32-40.tar.gz](https://github.com/vmware-tanzu/velero/files/13495810/bundle-2023-11-29-10-32-40.tar.gz)

**Environment:**

- Velero version (use `velero version`):  v1.12.1
- Velero features (use `velero client config get features`):  <NOT SET>
- Kubernetes version (use `kubectl version`): Client Version: v1.28.3, Server Version: v1.26.10-eks-4f4795d
- Kubernetes installer & version: EKS 1.26.10
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
