### ISSUE TITLE
storageAccountURI for Velero plugins for Microsoft Azure must include 'https://'

### ISSUE THREAD

**Issue by carlosbustillordguez** [vmware-tanzu/velero#7168]
After following https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/tree/main#:~:text=For%20users%20facing%20Storage%20Account%20Throttling%20issues and inspecting the available options to configure a [backup storage location](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/backupstoragelocation.md), I realized that the `storageAccountURI` must include `https://` as part of the URI, e.g.:
```yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: development
  namespace: velero
[...]
spec:
  accessMode: ReadWrite
  config:
    resourceGroup: my-rg
    storageAccount: my-sa
    storageAccountURI: https://my-sa.blob.core.windows.net
    useAAD: "true"
[...]
```

Otherwise, we will get the following error:

```
time="2023-11-30T11:28:50Z" level=error msg="fail to validate backup store" backup-storage-location=velero/development controller=backup-storage-location error="rpc error: code = Unknown desc = no Host in request URL" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/persistence/object_store.go:198" error.function="github.com/vmware-tanzu/velero/pkg/persistence.(*objectBackupStore).IsValid" logSource="pkg/controller/backup_storage_location_controller.go:155"
```

**What did you expect to happen:**

Update the main [README.md](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/README.md) file and  [backupstoragelocation.md](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/backupstoragelocation.md) properly or fix the code to consume `storageAccountURI` as described in the examples.

**Environment:**

- Velero version (use `velero version`): v1.12.2
-  Velero plugins for Microsoft Azure: v1.8.2
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): v1.27.3
- Kubernetes installer & version: v1.27.3
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): N/A

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
