### ISSUE TITLE
With DataMover restored PV is Empty

### ISSUE THREAD

**Issue by hofq** [vmware-tanzu/velero#7189]
**What steps did you take and what happened:**
- I made a Backup for Testing of an Application using this Schedule:
<details>
<summary>schedule.yaml</summary>

```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: prod-30d-eu-central-1
  namespace: velero
  annotations:
spec: 
  paused: false
  schedule: "0 3 * * *" # 1x pro Tag um 3 Uhr
  useOwnerReferencesInBackup: false
  template:
    ttl: 730h # 30 Tage
    datamover: velero
    snapshotMoveData: true
    volumeSnapshotLocations:
    - csi-gp3
    storageLocation: default
```

</details>

- i tried restoring it using the follwoing command:
`velero create restore --from-backup <name of backup> --include-namespaces <namespace name>`

**What did you expect to happen:**
- After everything finished Successfully, i expected the Data to be in the Volume, that was not the case. The Volume was just Empty

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

[bundle-2023-12-07-18-18-49.tar.gz](https://github.com/vmware-tanzu/velero/files/13603067/bundle-2023-12-07-18-18-49.tar.gz)

**Anything else you would like to add:**
- The DataUpload and DataDownload looked Good. The File size was realistic and both showed no errors 

**Environment:**

- Velero version (use `velero version`): v1.12.2 (also Tried v1.12.1 and 1.12.2-rc2)
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): Client: v1.28.4
- Kubernetes installer & version: v1.27.7-eks-4f4795d
- Cloud provider or hardware configuration: EKS with CSI Plugin
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by hofq** [comment]
```out
/var/lib/kubelet/pods/afe222fb-aad9-4d28-9e79-7be40b5504ff
[root@node afe222fb-aad9-4d28-9e79-7be40b5504ff]# tree ./
./
├── containers
│   └── nginx
│       └── b46faa53
├── etc-hosts
├── plugins
│   └── kubernetes.io~empty-dir
│       └── wrapped_kube-api-access-lwl8s
│           └── ready
└── volumes
    ├── kubernetes.io~csi
    │   └── pvc-ab225afb-ac33-4399-bd8d-22c42fdc4126
    │       ├── mount
    │       │   └── lost+found
    │       └── vol_data.json
    └── kubernetes.io~projected
        └── kube-api-access-lwl8s
            ├── ca.crt -> ..data/ca.crt
            ├── namespace -> ..data/namespace
            └── token -> ..data/token
```
I cannot see a mount Directory on the Node the Pod runs on, so it does not look like it.

**Comment by Lyndon-Li** [comment]
@hofq Please do the check after the restore and when you see the problem. Don't remove the restored pod.

**Comment by hofq** [comment]
The Pod was not removed, but I will re-trigger the restore.

**Comment by Lyndon-Li** [comment]
If the pod was not removed, you should be able to see `/var/lib/kubelet/pods/<restored pod's UID>/volumes/kubernetes.io~csi`, if so, please share the dir tree you see from there.

**Comment by hofq** [comment]
```
./
└── pvc-8630c694-199e-4a53-aa13-e10530b8cdf9
    ├── mount
    │   └── lost+found
    └── vol_data.json
```
This is the Tree directly after the restore

**Comment by Lyndon-Li** [comment]
What files are in the volume? Did you create them manually or are they owned by any application?

**Comment by Lyndon-Li** [comment]
I see you were backing up the default namespace, can you move the workload to a dedicate namespace and test the backup/restore.
This is not a general problem, so let's first make the case simple, and see what happened in your env step by step.

**Comment by hofq** [comment]
Okay, so i will backup the namespace prod-backup-test using my schedule "prod-30d-eu-central-1", which backs up the Namespace in question and a few others. After that i will restore the Namespace  prod-backup-test into prod-backup-test2.

here are the commands i've ran:
```bash
velero create backup --from-schedule prod-30d-eu-central-1
velero create restore --from-backup prod-30d-eu-central-1-20231207135032 --include-namespaces prod-backup-test --namespace-mappings prod-backup-test:prod-backup-test2
```
After Checking the Volume it was empty again.

The Schedule in Question is this one:
```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  annotations:
  labels:
    app: prod-backup-schedules
    app.kubernetes.io/instance: prod-backup-schedules
    type: backup
  name: prod-30d-eu-central-1
  namespace: velero
spec:
  paused: false
  schedule: 0 3 * * *
  template:
    datamover: velero
    includedNamespaces:
    - kube-system
    - monitoring
    - grafana
    - logging
    - prod-backup-test
    snapshotMoveData: true
    storageLocation: default
    ttl: 730h
    volumeSnapshotLocations:
    - csi-gp3
  useOwnerReferencesInBackup: false
~
```
