### ISSUE TITLE
PVR with Velero image from gcr.io hang because of velero-restore-helper image pullbackoff

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#7212]
In an env that docker hub is not accessible
Install Velero by setting `--image gcr.io/velero-gcp/velero:xxx`
Run a PVB
Restore from the PVB
PVR hangs forever because the restored workload pod cannot start due to velero-restore-helper initcontainer not able to pull its image from `velero/velero-restore-helper:xxx`

Looks like the `buildinfo.Registry` is not correctly set for image in gcr.io

**Comment by qiuming-best** [comment]
we may consider add one parameter in Velero install later

**Comment by whzghb** [comment]
You can create such a comfigmap in advance to set the image

```yaml
apiVersion: v1
data:
  image: xxx/xxx/velero-restore-helper:v1.12.2
kind: ConfigMap
metadata:
  labels:
    velero.io/plugin-config: ""
    velero.io/pod-volume-restore: RestoreItemAction
  name: fs-restore-action-config
  namespace: velero-system
```
