### ISSUE TITLE
DataUpload isn't canceled even the Backup is marked as "Failed" when Velero pod restarts

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#7230]
Restart the Velero pod when the `Backup` CR is in `InProgress` status (the `DataUpload` CR is in `Accept` status), the `Backup` CR is marked as `Failed` when the Velero pod starts up again, but the `DataUpload` CR isn't canceled and after a while the `Backup` CR is marked as `WaitingForPluginOperations` then `Completed`.

And here is the final status of the backup with status as `Completed` but  failureReason as `found a backup with status "InProgress" during the server starting,
    mark it as "Failed"`:

```
status:
  backupItemOperationsAttempted: 1
  backupItemOperationsCompleted: 1
  completionTimestamp: "2023-12-19T07:50:44Z"
  expiration: "2024-01-18T07:49:14Z"
  failureReason: found a backup with status "InProgress" during the server starting,
    mark it as "Failed"
  formatVersion: 1.1.0
  hookStatus:
    hooksAttempted: 1
  phase: Completed
  progress:
    itemsBackedUp: 32
    totalItems: 32
  startTimestamp: "2023-12-19T07:49:15Z"
  version: 1
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
