### ISSUE TITLE
BSL.spec.config["credentialsFile"] overrides AWS Web Identity Token credentials from pod environment

### ISSUE THREAD

**Issue by RobKenis** [vmware-tanzu/velero#7302]
**Describe the problem/challenge you have**
We have Velero deployed on AWS EKS with IRSA. This allows the pod to assume a role with permissions on bucket A. We have another bucket (B) in another AWS account to which we want to grant permissions using an IAM User. We have the credentials configured on the BackupStorageLocation like so:

```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: cross-account-aws-bucket
  namespace: velero
spec:
  provider: velero.io/aws
  objectStorage:
    bucket: cross-account-aws-bucket
  credential:
    key: cloud
    name: aws-credentials
  config:
    region: eu-central-1
```

The issue is that Velero authenticates to the bucket using the IAM Role which is assumed through IRSA and does not take the static credentials into account. This could be because the default credentials chain gives priority to web identity credentials over the shared credentials file: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html

**Describe the solution you'd like**
When explicit credentials are defined on a BackupStorageLocation, these always take first priority.

**Environment:**

- Velero version (use `velero version`): 5.2.0
- Kubernetes version (use `kubectl version`): 1.28.4
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): N/A

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"
