### ISSUE TITLE
Support only restore volume data of a backup

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#7345]
**Describe the problem/challenge you have**

Sometimes, it's possible to only restore data into volume without modifying the k8s resources.
Some issues required a similar function, #504 and #2598.
Suggest, at least, provide a workaround for this scenario.

**Describe the solution you'd like**

If a PodVolumeRestore is created based on the PodVolumeBackup information manually, the PodVolumeRestore is not processed by the Velero PVR controller. This is due to the PVR controller checking the PVR-requested pod whether has a restore-helper InitContainer. If not, the PVR is neglected.

Suggest adding a new field in the PVR to make the PVR controller skip the restore-helper InitContainer check logic. 
`AllowOnlyRestoreData` is the proposed parameter name. Its type is bool. The default value is false. This is an example:
``` yaml
apiVersion: velero.io/v1
kind: PodVolumeRestore
metadata:
  name: test-01-xxxxxxxxxxxxx-xxxxxx
  namespace: velero
spec:
  backupStorageLocation: default
  pod:
    kind: Pod
    name: hello-app-xxxxxxxxx-xxxxx
    namespace: restore
    uid: xxxxxxxx
  repoIdentifier: gs:jxun:/restic/test
  snapshotID: xxxxxxxx
  sourceNamespace: test
  uploaderSettings:
    WriteSparseFiles: "false"
  uploaderType: kopia
  volume: sdk-volume
  allowOnlyRestoreData: true
```

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"
