### ISSUE TITLE
Velero CSI volume snapshots deleted just before consumption

### ISSUE THREAD

**Issue by DreamingRaven** [vmware-tanzu/velero#7382]
**What steps did you take and what happened:**

I use [Velero (helm)](https://gitlab.com/deepcypher/dc-kc/-/tree/master/charts/velero?ref_type=heads) to back up [rook-ceph CSI ](https://gitlab.com/deepcypher/dc-kc/-/tree/master/charts/rook?ref_type=heads) storage classes to GCP GCS storage, using a schedule. This uses the CSI and GCP providers.
However, no volumesnapshots make it to GCS, they appear to be created then quickly deleted before they are used in quick succession.

Once I run ``velero backup create 2024-02-04-fs-5 --from-schedule fs`` this is the first volume snapshot you can see from the last few lines, the snapshot is created, then deleted, then an error is thrown as it does not exist anymore. I have verified this volume snapshot can be created manually by declaring a volumesnapshot CR for it, and I see them get created if I watch them quickly enough. Is there any way to stop velero from deleting these volumesnapshots before they are used by velero?:
```
time="2024-02-04T20:31:16Z" level=info msg="Skipping the exclusion checks for this resource" backup=velero/2024-02-04-fs-5 logSource="pkg/backup/item_backupper.go:128" name=velero-foundryvtt-jz482 namespace=foundryvtt resource=volumesnapshots.snapshot.storage.k8s.io
time="2024-02-04T20:31:16Z" level=info msg="Backing up item" backup=velero/2024-02-04-fs-5 logSource="pkg/backup/item_backupper.go:177" name=velero-foundryvtt-jz482 namespace=foundryvtt resource=volumesnapshots.snapshot.storage.k8s.io
time="2024-02-04T20:31:16Z" level=info msg="Executing custom action" backup=velero/2024-02-04-fs-5 logSource="pkg/backup/item_backupper.go:355" name=velero-foundryvtt-jz482 namespace=foundryvtt resource=volumesnapshots.snapshot.storage.k8s.io
time="2024-02-04T20:31:16Z" level=info msg="Executing VolumeSnapshotBackupItemAction" backup=velero/2024-02-04-fs-5 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/volumesnapshot_action.go:63" pluginName=velero-plugin-for-csi
time="2024-02-04T20:31:16Z" level=info msg="Getting VolumesnapshotContent for Volumesnapshot foundryvtt/velero-foundryvtt-jz482" backup=velero/2024-02-04-fs-5 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/volumesnapshot_action.go:96" pluginName=velero-plugin-for-csi
time="2024-02-04T20:31:16Z" level=info msg="Waiting for CSI driver to reconcile volumesnapshot foundryvtt/velero-foundryvtt-jz482. Retrying in 5s" backup=velero/2024-02-04-fs-5 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:246" pluginName=velero-plugin-for-csi
time="2024-02-04T20:31:21Z" level=info msg="Deleting Volumesnapshot foundryvtt/velero-foundryvtt-jz482" backup=velero/2024-02-04-fs-5 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:398" pluginName=velero-plugin-for-csi
time="2024-02-04T20:31:16Z" level=info msg="Executing custom action" backup=velero/2024-02-04-fs-5 logSource="pkg/backup/item_backupper.go:355" name=foundryvtt namespace=foundryvtt resource=persistentvolumeclaims
time="2024-02-04T20:31:16Z" level=info msg="Starting PVCBackupItemAction" backup=velero/2024-02-04-fs-5 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:68" pluginName=velero-plugin-for-csi
time="2024-02-04T20:31:16Z" level=info msg="Fetching storage class for PV ceph-filesystem" backup=velero/2024-02-04-fs-5 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:123" pluginName=velero-plugi
n-for-csi
time="2024-02-04T20:31:16Z" level=info msg="volumesnapshot class=ceph-filesystem" backup=velero/2024-02-04-fs-5 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:133" pluginName=velero-plugin-for-csi
time="2024-02-04T20:31:16Z" level=info msg="Created volumesnapshot foundryvtt/velero-foundryvtt-jz482" backup=velero/2024-02-04-fs-5 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:160" pluginName=
velero-plugin-for-csi
time="2024-02-04T20:31:16Z" level=info msg="Returning from PVCBackupItemAction with 1 additionalItems to backup" backup=velero/2024-02-04-fs-5 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:233" p
luginName=velero-plugin-for-csi
time="2024-02-04T20:31:16Z" level=info msg="Skipping the exclusion checks for this resource" backup=velero/2024-02-04-fs-5 logSource="pkg/backup/item_backupper.go:128" name=velero-foundryvtt-jz482 namespace=foundryvtt resource=volumesnapshots.snapshot.sto
rage.k8s.io
time="2024-02-04T20:31:16Z" level=info msg="Backing up item" backup=velero/2024-02-04-fs-5 logSource="pkg/backup/item_backupper.go:177" name=velero-foundryvtt-jz482 namespace=foundryvtt resource=volumesnapshots.snapshot.storage.k8s.io
time="2024-02-04T20:31:16Z" level=info msg="Executing custom action" backup=velero/2024-02-04-fs-5 logSource="pkg/backup/item_backupper.go:355" name=velero-foundryvtt-jz482 namespace=foundryvtt resource=volumesnapshots.snapshot.storage.k8s.io
time="2024-02-04T20:31:16Z" level=info msg="Executing VolumeSnapshotBackupItemAction" backup=velero/2024-02-04-fs-5 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/volumesnapshot_action.go:63" pluginName=velero-
plugin-for-csi
time="2024-02-04T20:31:16Z" level=info msg="Getting VolumesnapshotContent for Volumesnapshot foundryvtt/velero-foundryvtt-jz482" backup=velero/2024-02-04-fs-5 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/volu
mesnapshot_action.go:96" pluginName=velero-plugin-for-csi
time="2024-02-04T20:31:16Z" level=info msg="Waiting for CSI driver to reconcile volumesnapshot foundryvtt/velero-foundryvtt-jz482. Retrying in 5s" backup=velero/2024-02-04-fs-5 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/in
ternal/util/util.go:246" pluginName=velero-plugin-for-csi
time="2024-02-04T20:31:21Z" level=info msg="Deleting Volumesnapshot foundryvtt/velero-foundryvtt-jz482" backup=velero/2024-02-04-fs-5 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:398" pluginName=velero-
plugin-for-csi
time="2024-02-04T20:31:21Z" level=info msg="1 errors encountered backup up item" backup=velero/2024-02-04-fs-5 logSource="pkg/backup/backup.go:444" name=foundryvtt-5c99967cd4-sp77k
time="2024-02-04T20:31:21Z" level=error msg="Error backing up item" backup=velero/2024-02-04-fs-5 error="error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=foundryvtt, name=velero-foundryvtt-jz482): rpc error: code = Unknown desc = failed to get volumesnapshot foundryvtt/velero-foundryvtt-jz482: volumesnapshots.snapshot.storage.k8s.io \"velero-foundryvtt-jz482\" not found" logSource="pkg/backup/backup.go:448" name=foundryvtt-5c99967cd4-sp77k
time="2024-02-04T20:31:21Z" level=info msg="Backed up 56 items out of an estimated total of 2667 (estimate will change throughout the backup)" backup=velero/2024-02-04-fs-5 logSource="pkg/backup/backup.go:404" name=foundryvtt-5c99967cd4-sp77k namespace=foundryvtt progress= resource=pods
```

**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Using the velero helm chart version 5.2.2 my values are:
```yaml
  backupsEnabled: true
  snapshotsEnabled: true
  deployNodeAgent: true
  kubectl:
    image:
      repository: docker.io/bitnami/kubectl
      # temporary workaround to bitnami failed kubectl container build
      # https://github.com/bitnami/containers/issues/45692#issuecomment-1694498290
      tag: 1.29.1
  cleanUpCRDs: false
  credentials:
    useSecret: true
    existingSecret: cloud-credentials # must match obc.name if using obc
  initContainers:
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v0.7.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-gcp
    image: velero/velero-plugin-for-gcp:v1.9.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /target
      name: plugins

  # https://geek-cookbook.funkypenguin.co.nz/kubernetes/backup/velero/ SEE THIS!!!
  configuration:
    # These are server-level settings passed as CLI flags to the `velero server` command. Velero
    # uses default values if they're not passed in, so they only need to be explicitly specified
    # here if using a non-default value. The `velero server` default values are shown in the
    # comments below.
    # --------------------
    # `velero server` default: restic
    uploaderType:
    # `velero server` default: 1m
    backupSyncPeriod:
    # `velero server` default: 4h
    fsBackupTimeout:
    # `velero server` default: 30
    clientBurst:
    # `velero server` default: 500
    clientPageSize:
    # `velero server` default: 20.0
    clientQPS:
    # Name of the default backup storage location. Default: default
    defaultBackupStorageLocation:
    # How long to wait by default before backups can be garbage collected. Default: 72h
    defaultBackupTTL:
    # Name of the default volume snapshot location.
    defaultVolumeSnapshotLocations: csi:rook-ceph
    # `velero server` default: empty
    disableControllers:
    # `velero server` default: 1h
    garbageCollectionFrequency:
    # Set log-format for Velero pod. Default: text. Other option: json.
    logFormat:
    # Set log-level for Velero pod. Default: info. Other options: debug, warning, error, fatal, panic.
    logLevel:
    # The address to expose prometheus metrics. Default: :8085
    metricsAddress:
    # Directory containing Velero plugins. Default: /plugins
    pluginDir:
    # The address to expose the pprof profiler. Default: localhost:6060
    profilerAddress:
    # `velero server` default: false
    restoreOnlyMode:
    # `velero server` default: customresourcedefinitions,namespaces,storageclasses,volumesnapshotclass.snapshot.storage.k8s.io,volumesnapshotcontents.snapshot.storage.k8s.io,volumesnapshots.snapshot.storage.k8s.io,persistentvolumes,persistentvolumeclaims,secrets,configmaps,serviceaccounts,limitranges,pods,replicasets.apps,clusterclasses.cluster.x-k8s.io,clusters.cluster.x-k8s.io,clusterresourcesets.addons.cluster.x-k8s.io
    restoreResourcePriorities:
    # `velero server` default: 1m
    storeValidationFrequency:
    # How long to wait on persistent volumes and namespaces to terminate during a restore before timing out. Default: 10m
    terminatingResourceTimeout:
    # Comma separated list of velero feature flags. default: empty
    # features: EnableCSI
    features: EnableCSI
    # `velero server` default: velero
    namespace:

    ##########################
    # VELERO SNAPSHOT LOCATION
    ##########################
    volumeSnapshotLocation:
      # name is the name of the volume snapshot location where snapshots are being taken. Required.
    - name: rook-ceph
      # provider is the name for the volume snapshot provider. If omitted
      # `configuration.provider` will be used instead.
      provider: csi
      # Additional provider-specific configuration. See link above
      # for details of required/optional fields for your provider.
      config: {}
        # region:
        # apiTimeout:
        # resourceGroup:
        # The ID of the subscription where volume snapshots should be stored, if different from the cluster’s subscription. If specified, also requires `configuration.volumeSnapshotLocation.config.resourceGroup`to be set. (Azure only)
        # subscriptionId:
        # incremental:
        # snapshotLocation:
        # project:

    ################################
    # VELERO BACKUP STORAGE LOCATION
    ################################
    ## Parameters for the BackupStorageLocation(s). Configure multiple by adding other element(s) to the backupStorageLocation slice.
    ## See https://velero.io/docs/v1.6/api-types/backupstoragelocation/
    backupStorageLocation:
      # name is the name of the backup storage location where backups should be stored. If a name is not provided,
      # a backup storage location will be created with the name "default". Optional.
    - name: gcp-standard
      # provider is the name for the backup storage location provider.
      provider: gcp
      # bucket is the name of the bucket to store backups in. Required.
      bucket:  victor-bucket-a-prod-standard # the name of my specific bucket (2)
      # caCert defines a base64 encoded CA bundle to use when verifying TLS connections to the provider. Optional.
      caCert:
      # prefix is the directory under which all Velero data should be stored within the bucket. Optional.
      #prefix: optional-subdir # a path under the bucket in which the backup data should be stored (3)
      # default indicates this location is the default backup storage location. Optional.
      default: true # prevents annoying warnings in the log
      # validationFrequency defines how frequently Velero should validate the object storage. Optional.
      validationFrequency:
      # accessMode determines if velero can write to this backup storage location. Optional.
      # default to ReadWrite, ReadOnly is used during migrations and restores.
      accessMode: ReadWrite
      credential:
        # name of the secret used by this backupStorageLocation.
        name: cloud-credentials # this is the sealed-secret we created above (3)
        # name of key that contains the secret data to be used.
        key: cloud # this is the key we used in the sealed-secret we created above (3)
      # Additional provider-specific configuration. See link above
      # for details of required/optional fields for your provider.
      config: {}
```
My schedule is:
```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: fs
  namespace: velero
  annotations:
    velero.io/csi-volumesnapshot-class_rook-ceph.cephfs.csi.ceph.com: "ceph-filesystem"
spec:
  # Schedule is a Cron expression defining when to run the Backup
  # 0 3 * * 0 = run weekly at 3:00 AM on Sundays
  schedule: 0 3 * * 2
  template:
    includedNamespaces:
    - '*'
    excludedNamespaces: []
    includedResources:
    - '*'
    excludedResources:
    - storageclasses.storage.k8s.io
    includeClusterResources: null
    snapshotVolumes: true
    storageLocation: gcp-standard
    volumeSnapshotLocations:
    - rook-ceph
    metadata:
      labels:
        backup: velero
```
My volume snapshot class:
```yaml
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Delete
driver: rook-ceph.cephfs.csi.ceph.com
kind: VolumeSnapshotClass
metadata:
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  labels:
    argocd.argoproj.io/instance: rook-ceph
    velero.io/csi-volumesnapshot-class: "true"
  name: ceph-filesystem
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/snapshotter-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph

```
My storage class:
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    argocd.argoproj.io/instance: rook-ceph
  name: ceph-filesystem
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  fsName: ceph-filesystem
  pool: ceph-filesystem-data0
provisioner: rook-ceph.cephfs.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate

```

**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`):  v3.12.0
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): v5.2.2
- Kubernetes version (use `kubectl version`): 1.28.0
- Kubernetes installer & version: Talos v1.6.1
- Cloud provider or hardware configuration: Talos bare-metal
- OS (e.g. from `/etc/os-release`): Talos Linux v1.6.1

**What did you expect to happen:**

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

[bundle-2024-02-04-20-52-06.tar.gz](https://github.com/vmware-tanzu/velero/files/14158443/bundle-2024-02-04-20-52-06.tar.gz)

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

```yaml
Name:         2024-02-04-fs-5
Namespace:    velero
Labels:       backup=velero
              velero.io/schedule-name=fs
              velero.io/storage-location=gcp-standard
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"velero.io/v1","kind":"Schedule","metadata":{"annotations":{"velero.io/csi-volumesnapshot-class_rook-ceph.cephfs.csi.ceph.com":"ceph-filesystem"},"labels":{"argocd.argoproj.io/instance":"velero"},"name":"fs","namespace":"velero"},"spec":{"schedule":"0 3 * * 2","template":{"defaultVolumesToRestic":false,"excludedNamespaces":[],"excludedResources":["storageclasses.storage.k8s.io"],"includeClusterResources":null,"includedNamespaces":["*"],"includedResources":["*"],"metadata":{"labels":{"backup":"velero"}},"snapshotVolumes":true,"storageLocation":"gcp-standard","volumeSnapshotLocations":["rook-ceph"]}}}

  velero.io/csi-volumesnapshot-class_rook-ceph.cephfs.csi.ceph.com=ceph-filesystem
  velero.io/resource-timeout=10m0s
  velero.io/source-cluster-k8s-gitversion=v1.28.0
  velero.io/source-cluster-k8s-major-version=1
  velero.io/source-cluster-k8s-minor-version=28

Phase:  PartiallyFailed (run `velero backup logs 2024-02-04-fs-5` for more information)


Errors:
  Velero:    name: /foundryvtt-5c99967cd4-sp77k error: /error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=foundryvtt, name=velero-foundryvtt-jz482): rpc error: code = Unknown desc = failed to get volumesnapshot foundryvtt/velero-foundryvtt-jz482: volumesnapshots.snapshot.storage.k8s.io "velero-foundryvtt-jz482" not found
             name: /ghost-648464c885-wqdvv error: /error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=ghost, name=velero-ghost-nb5tq): rpc error: code = Unknown desc = failed to get volumesnapshot ghost/velero-ghost-nb5tq: volumesnapshots.snapshot.storage.k8s.io "velero-ghost-nb5tq" not found
             name: /grocy-64c4657b7-7z646 error: /error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=grocy, name=velero-grocy-l9v7s): rpc error: code = Unknown desc = failed to get volumesnapshot grocy/velero-grocy-l9v7s: volumesnapshots.snapshot.storage.k8s.io "velero-grocy-l9v7s" not found
             name: /loki-compactor-d68dfc7d8-86vjj error: /error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=loki, name=velero-loki-compactor-ffd2l): rpc error: code = Unknown desc = failed to get volumesnapshot loki/velero-loki-compactor-ffd2l: volumesnapshots.snapshot.storage.k8s.io "velero-loki-compactor-ffd2l" not found
             name: /nextcloud-app-56986bf44b-sgghg error: /error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=nextcloud, name=velero-nextcloud-app-nextcloud-2pjdc): rpc error: code = Unknown desc = failed to get volumesnapshot nextcloud/velero-nextcloud-app-nextcloud-2pjdc: volumesnapshots.snapshot.storage.k8s.io "velero-nextcloud-app-nextcloud-2pjdc" not found
  Cluster:    <none>
  Namespaces: <none>

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        storageclasses.storage.k8s.io
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  gcp-standard

Velero-Native Snapshot PVs:  true

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2024-02-04 20:30:58 +0000 GMT
Completed:  2024-02-04 20:32:44 +0000 GMT

Expiration:  2024-03-05 20:30:58 +0000 GMT

Total items to be backed up:  2675
Items backed up:              2675

Backup Item Operations:  12 of 12 completed successfully, 0 failed (specify --details for more information)
Velero-Native Snapshots: <none included>

```

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  server v1.12.3, client v1.11.1
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): v1.29.0
- Kubernetes installer & version: Talos Linux 1.6.1
- Cloud provider or hardware configuration: Talos Bare Metal X86_64 and ARM64
- OS (e.g. from `/etc/os-release`): Talos

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
