### ISSUE TITLE
DataDownload fails during restore when `SnapshotMoveData: true` for empty PVC workload

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#7388]
**What steps did you take and what happened:**

Create workload mounting empty CSI volume
Create Backup With SnapshotMoveData: true
Create Restore

**What did you expect to happen:**
Application to become available

**What happened**
`kubectl get restore test-restore479 -o jsonpath='{.status.phase}'
PartiallyFailed`

```
# oc get datadownload test-restore479-9vwfp -n openshift-adp -oyaml
apiVersion: velero.io/v2alpha1
kind: DataDownload
metadata:
  name: test-restore479-9vwfp
status:
  completionTimestamp: "2023-11-21T06:31:45Z"
  message: 'data path restore failed: Failed to run kopia restore: Unable to load
    snapshot : snapshot not found'
  node: worker-2
  phase: Failed
  progress: {}
  startTimestamp: "2023-11-21T06:30:35Z" 
```

**The following information will help us better understand what's going on**:
Velero 1.12

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

This is crosspost for https://issues.redhat.com/browse/OADP-3106

**Environment:**

- Velero version (use `velero version`): 1.12
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
