### ISSUE TITLE
Azure disk snapshot 429 ratelimit with velero-plugin-for-microsoft-azure

### ISSUE THREAD

**Issue by behroozam** [vmware-tanzu/velero#7393]
We have a couple of AKS clusters in Azure and we enabled the CSI feature to snapshot/backup PVCs. 
It's working fine for the clusters with fewer PVCs but for a cluster with 65 PVCs azure starts sending a 429 response code. 

The issue is that whenever the snapshoter tries to take a snapshot or fetch the existing backup it tries to use Azure API to list the storage account keys and It exhausts Azure API. 

This is the error code: 

```
 failed with storage.FileSharesClient#Get: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code=\\\"TooManyRequests\\\" Message=\\\"The request is being throttled as the limit has been reached for operation type - Read_ObservationWindow_00:05:00. For more information, see - https://aka.ms/srpthrottlinglimits\\\", accountName: \\\"<storageaccountname>\\\"\"" backup=<veleronamespace>/<veleroPod>cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:259" pluginName=velero-plugin-for-csi
```

and this is the Azure activity on the storage account which is currently throttled. 
![Screenshot 2024-02-06 105147](https://github.com/vmware-tanzu/velero/assets/5345592/eafe936c-d269-4980-931f-6d9e4c328aaf)

A possible fix for the issue: caching the storage account key instead of listing keys each time for each request 

- Velero version: 1.13.0
- Velero features: EnableCSI 
- Kubernetes version:  v1.27.3
- Cloud provider or hardware configuration: Azure AKS 
- OS : azure linux

**Comment by Lyndon-Li** [comment]
Looks like it was the external-snapshotter called the Azure API, if so, it doesn't make any help even if Velero caches the storage account key. Anything I missed?

**Comment by behroozam** [comment]
> Looks like it was the external-snapshotter called the Azure API, if so, it doesn't make any help even if Velero caches the storage account key. Anything I missed?

We are using velero snapshotclass 

```
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Retain
driver: disk.csi.azure.com
kind: VolumeSnapshotClass
metadata:
  generation: 1
  labels:
    velero.io/csi-volumesnapshot-class: "true"
  name: velero-csi-disk-volume-snapshot-class
```
