### ISSUE TITLE
Failed to read credentials from file when using Azure workload identity

### ISSUE THREAD

**Issue by nomaster** [vmware-tanzu/velero#7395]
**What steps did you take and what happened:**

After **upgrading the Velero plugin for Azure to version 1.9.0**, the following error appears on startup:

> velero-599f68884-clmxv velero time="2024-02-06T09:22:15Z" level=error msg="Error getting a backup store" backup-storage-location=velero/default controller=backup-storage-location error="rpc error: code = Unknown desc = failed to read credentials from file : open : no such file or directory" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.13.0/pkg/util/azure/util.go:68" error.function=github.com/vmware-tanzu/velero/pkg/util/azure.LoadCredentials logSource="pkg/controller/backup_storage_location_controller.go:137"
 

**What did you expect to happen:**

No error, because the configuration didn't change.

**The following information will help us better understand what's going on**:

**Anything else you would like to add:**

It should not be expected that a credential file exists when using Azure workload identity.

With version 1.8.2 of the plugin and the same configuration, the error does not appear.

**Environment:**

- Velero version (use `velero version`): 1.13.0
- Velero features (use `velero client config get features`): EnableCSI
- Kubernetes version (use `kubectl version`): 1.28.3
- Cloud provider or hardware configuration: Azure Kubernetes Services
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.3 LTS 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by nomaster** [comment]
The pod environment seems to be right, no changes since the upgrade:

```
AZURE_CLIENT_ID:             [redacted]
AZURE_RESOURCE_GROUP:        [redacted]
AZURE_SUBSCRIPTION_ID:       [redacted]
AZURE_TENANT_ID:             [redacted]
AZURE_FEDERATED_TOKEN_FILE:  /var/run/secrets/azure/tokens/azure-identity-token
AZURE_AUTHORITY_HOST:        https://login.microsoftonline.com/
```

**Comment by ywk253100** [comment]
Reopen this issue as we also need to bump up the Velero version in plugin side

**Comment by nomaster** [comment]
I have upgraded the plugin to version 1.9.1 and Velero now starts without the mentioned error. But when I order a backup, the following error appears in the log:

> Error getting volume snapshotter for volume snapshot location [...] AZURE_SUBSCRIPTION_ID is required in credential file

An environment variable `AZURE_SUBSCRIPTION_ID` exists and has a value.

**Comment by ywk253100** [comment]
@nomaster As the [Velero Azure plugin doc](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure?tab=readme-ov-file#option-2-use-azure-ad-workload-identity) says, the `AZURE_SUBSCRIPTION_ID` and `AZURE_RESOURCE_GROUP` are required in the credential file, they are not used to do the auth but are used to locate the disks when taking native snapshots.

We do not support setting them via environment variables, they can work with environment variables in previous releases is a coincidence.

**Comment by nomaster** [comment]
This worked. Thank you!

For reference, here's my Helm release values:

```yaml
initContainers:
  - name: velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.9.1
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocation:
    - name: default
      provider: velero.io/azure
      bucket: ${bucket_name}
      config:
        storageAccount: ${storage_account}
        resourceGroup: ${resource_group_name}
  volumeSnapshotLocation:
    - name: default
      provider: velero.io/azure
      config:
        resourceGroup: ${node_resource_group}

podLabels:
  azure.workload.identity/use: "true"

credentials:
  secretContents:
    cloud: |
      AZURE_SUBSCRIPTION_ID=${subscription_id}
      AZURE_RESOURCE_GROUP=${node_resource_group}
      AZURE_CLOUD_NAME=AzurePublicCloud

serviceAccount:
  server:
    annotations:
      azure.workload.identity/client-id: ${client_id}

[...]
```
