### ISSUE TITLE
Aws Pod Identity provider not working 

### ISSUE THREAD

**Issue by cvauvarin** [vmware-tanzu/velero#7421]
**What steps did you take and what happened:**

I configured an IAM Role and bind it to the velero service account using [EKS Pod Identity](https://aws.amazon.com/blogs/containers/amazon-eks-pod-identity-a-new-way-for-applications-on-eks-to-obtain-iam-credentials/).

I deployed the velero server with the helm chart and the following errors happened :

```
time="2024-02-13T09:55:13Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/1/0, BackupStorageLocation \"default\" is unavailable: rpc error: code = Unknown desc = could not load config: invalid endpoint host, \"169.254.170.23\", only loopback hosts are allowed)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:178"
```

**What did you expect to happen:**

The server should be able to retrieve AWS credentials using the pod identity agent.

**Anything else you would like to add:**

This seems to be an SDK version issue, AWS provides the minimum SDK version to use for Pod Identity : https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html.

Command used to deploy the server

```
helm upgrade velero vmware-tanzu/velero \
--namespace claranet-system \
--create-namespace \
--set credentials.useSecret=false \
--set configuration.backupStorageLocation[0].name=default \
--set configuration.backupStorageLocation[0].provider=aws \
--set configuration.backupStorageLocation[0].bucket=<bucket_name> \
--set configuration.backupStorageLocation[0].config.region=eu-west-3 \
--set configuration.volumeSnapshotLocation[0].name=default \
--set configuration.volumeSnapshotLocation[0].provider=aws \
--set configuration.volumeSnapshotLocation[0].config.region=eu-west-3 \
--set initContainers[0].name=velero-plugin-for-aws \
--set initContainers[0].image=velero/velero-plugin-for-aws:v1.9.0 \
--set initContainers[0].volumeMounts[0].mountPath=/target \
--set initContainers[0].volumeMounts[0].name=plugins
```

**Environment:**

- Velero version (use `velero version`): 1.13.0
- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`): v1.29.0-eks-c417bb3
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

Thanks !

Charles

**Comment by mgriffin13** [comment]
Is there an update to this issue? Seems as though just bumping the AWS SDK to a minimum [release-2023-11-14](https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2023-11-14) would solve this issue.

Pod Identities are the AWS recommended approach going forward for providing credentials to your pods for AWS services.

**Comment by kaovilai** [comment]
Most recent bump was to [v1.24.1](https://github.com/vmware-tanzu/velero/pull/7307/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R19) which is newer than 2023-11-14.

**Comment by mgriffin13** [comment]
> Most recent bump was to [v1.24.1](https://github.com/vmware-tanzu/velero/pull/7307/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R19) which is newer than 2023-11-14.

Thank you, but I'm not seeing that released yet, right? The [changelog](https://github.com/vmware-tanzu/velero/blob/main/changelogs/unreleased/7307-guikcd) is still "unreleased" and I didn't see the commit in the latest 1.13.2 tag.

**Comment by cvauvarin** [comment]
I agree on this, the AWS SDK is set to [v1.24.1 on the main branch](https://github.com/vmware-tanzu/velero/blob/main/go.mod#L14) but the change has not been released [in the v1.13.2 version](https://github.com/vmware-tanzu/velero/blob/v1.13.2/go.mod#L19). Any idea when this can be released ?

**Comment by kaovilai** [comment]
If it's not required in 1.13.z, then you can expect it in the next 1.14 https://github.com/vmware-tanzu/velero/wiki/1.14-Roadmap

1.13.z may never get it if there's not a need due to CVEs etc.

IIUC this issue is not a regression of a previously working feature right?

**Comment by cvauvarin** [comment]
No not a regression at all. Just wanted an update on when this can get released on order to fully migrate to AWS pod identity. This can wait the 1.14 for sure.

**Comment by maxrabin** [comment]
Will EKS Pod Identities work with 1.14?

**Comment by blackpiglet** [comment]
@maxrabin 
According to the document https://docs.aws.amazon.com/eks/latest/userguide/pod-id-configure-pods.html, I think it should work, although it was not tested.

**Comment by tropnikovvl** [comment]
I can also confirm that it works.
Tested on EKS 1.30

**Comment by sde-melo** [comment]
Does this still work on EKS 1.32?  I’m encountering the following error:
`BackupStorageLocation "default" is unavailable: rpc error: code = Unknown desc = NoCredentialProviders: no valid providers in chain. Deprecated.`

**Comment by carlos-ffs** [comment]
I confirm it is working on EKS 1.31.
- Verify that you have the pod identity agents running on your EKS.
- Check if your EKS has [OIDC provider](https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html) setup.
- As for the velero helm-chart values I am using this:
    ```yaml
  fullnameOverride: "velero"
  deployNodeAgent: true
  initContainers:
  - name: velero-plugin-for-aws
      # https://hub.docker.com/r/velero/velero-plugin-for-aws/tags
      image: velero/velero-plugin-for-aws:v1.12.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
  credentials:
      useSecret: false # To use pod identity, we need to set this to false
  serviceAccount:
      server:
        create: true
        name: "velero"
  configuration:
      logFormat: json
      logLevel: info
    ```
- I am using a wrapped helm chart with velero as a dependency chart, so we leverage helm templating to create the necessary BSL and VSL:
    ```yaml
    apiVersion: velero.io/v1
    kind: BackupStorageLocation
    metadata:
      name: default
      namespace: {{ .Release.Namespace }}
    spec:
      provider: velero.io/aws
      objectStorage:
        bucket: {{ .Values.aws.veleroBackupBucketName }}
        prefix: {{ .Values.aws.clusterName }}
      accessMode: ReadWrite
    ---
    {{/* https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/volumesnapshotlocation.md */}}
    apiVersion: velero.io/v1
    kind: VolumeSnapshotLocation
    metadata:
      name: default
      namespace: {{ .Release.Namespace }}
    spec:
      provider: velero.io/aws
      config:
        region: {{ .Values.aws.region }}
    ```
- For the S3 bucket and IAM roles creation, we are using terraform:
    ```hcl
    ### S3 SECTION
    resource "aws_s3_bucket" "velero_backup_bucket" {
      bucket        = var.backup_bucket_name
      force_destroy = var.force_destroy_bucket
    
      tags = {
        Name        = "Velero Backup Bucket"
        Team        = "SRE"
      }
    }
    
    resource "aws_s3_bucket_versioning" "velero_backup_bucket_versioning" {
      bucket = aws_s3_bucket.velero_backup_bucket.id
      
      versioning_configuration {
        status = "Enabled"
      }
    }
    
    resource "aws_s3_bucket_public_access_block" "velero_backup_bucket_block" {
      bucket = aws_s3_bucket.velero_backup_bucket.id
    
      block_public_acls       = true
      block_public_policy     = true
      ignore_public_acls      = true
      restrict_public_buckets = true
    }
    
    resource "aws_s3_bucket_server_side_encryption_configuration" "velero_backup_bucket_encryption" {
      bucket = aws_s3_bucket.velero_backup_bucket.id
    
      rule {
        apply_server_side_encryption_by_default {
          sse_algorithm = "AES256"
        }
      }
    }
    
    ### IAM SECTION
    data "aws_iam_policy_document" "eks_pod_identity_assume_role_velero" {
      statement {
        sid    = "AllowEksAuthToAssumeRoleForPodIdentity"
        effect = "Allow"
    
        principals {
          type        = "Service"
          identifiers = ["pods.eks.amazonaws.com"]
        }
    
        actions = [
          "sts:AssumeRole",
          "sts:TagSession",
        ]
      }
    }
    
    resource "aws_iam_role" "velero_s3_access_role" {
      # ************** IMPORTANT ************
      # This role name is used by the crossplane composition to create the pod identity associations. 
      # It must not be changed. Or if you do, you must update the xedgecluster crossplane composition accordingly.
      name               = "velero-s3-access"
      assume_role_policy = data.aws_iam_policy_document.eks_pod_identity_assume_role_velero.json
    }
    
    
    data "aws_iam_policy_document" "velero_s3_access" {
      statement {
        sid     = "VeleroEC2Access"
        effect  = "Allow"
        actions = [
          "ec2:DescribeVolumes",
          "ec2:DescribeSnapshots",
          "ec2:CreateTags",
          "ec2:CreateVolume",
          "ec2:CreateSnapshot",
          "ec2:DeleteSnapshot"
        ]
        resources = ["*"]
      }
      statement {
        sid     = "VeleroS3ObjectAccess"
        effect  = "Allow"
        actions = [
          "s3:GetObject",
          "s3:DeleteObject",
          "s3:PutObject",
          "s3:PutObjectTagging",
          "s3:AbortMultipartUpload",
          "s3:ListMultipartUploadParts"
        ]
        resources = ["arn:aws:s3:::${aws_s3_bucket.velero_backup_bucket.id}/*"]
      }
      statement {
        sid     = "VeleroS3BucketAccess"
        effect  = "Allow"
        actions = ["s3:ListBucket"]
        resources = ["arn:aws:s3:::${aws_s3_bucket.velero_backup_bucket.id}"]
      }
    }
    
    resource "aws_iam_role_policy" "velero_s3_access" {
      name   = "velero-s3-access"
      role   = aws_iam_role.velero_s3_access_role.name
      policy = data.aws_iam_policy_document.velero_s3_access.json
    }
    ```
- Lastly, you need to create the pod identity association. We use crossplane to create our EKSs, so this is one way to do it:
    ```yaml
    - step: create-velero-resources
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $xr := .observed.composite.resource -}}
            {{- $clusterID := $xr.spec.clusterID -}}
            {{- $region := $xr.spec.region -}}
            {{- $accountId := $xr.spec.accountId -}}
            {{- $ns := "velero" -}}
            {{- $sa := "velero" -}}
            ---
            apiVersion: eks.aws.upbound.io/v1beta1
            kind: PodIdentityAssociation
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: {{ $clusterID }}-{{ $sa }}-pod-identity
              name: {{ $clusterID }}-{{ $sa }}-pod-identity
            spec:
              providerConfigRef:
                name: aws-provider-config
              forProvider:
                clusterName: {{ $clusterID }}
                namespace: {{ $ns }}
                region: {{ $region }}
                {{/* This role is created in the ./terraform/modules/velero/main.tf file 
                    If you change the role name there, you must update it here as well. And vice versa.
                */}}
                roleArn: "arn:aws:iam::{{ $xr.spec.accountId }}:role/velero-s3-access"
                serviceAccount: {{ $sa }}
    ```
   - Alternatively, if you want to use terraform, just add the following to the above terraform code I previously mentioned in this comment:
        ```hcl
        resource "aws_eks_pod_identity_association" "example" {
          cluster_name  = var.aws_eks_cluster_name
          namespace  = var.pia_namespace
          service_account  = var.pia_sa_name
          role_arn        = aws_iam_role.velero_s3_access_role.arn
        }
        ```
