### ISSUE TITLE
Getting Warning message "No volume ID returned by volume snapshotter for persistent volume"

### ISSUE THREAD

**Issue by davidmkrtchian** [vmware-tanzu/velero#7422]
**What steps did you take and what happened:**
I want to create backups for my PVC using CSI driver as provided in documentation. 
https://velero.io/docs/v1.13/csi/

I am installing Velero with this configuration and with 2 init container with images velero/velero-plugin-for-aws:v1.9.0 and velero/velero-plugin-for-csi:v0.7.0
```
configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: xxx-backups
      prefix: rax/sandbox/volume-velero-test/
      default: true
      accessMode: ReadWrite
      config:
        region: us-east-1 
  volumeSnapshotLocation:
  - provider: aws
    config:
      region: us-east-1    
defaultSnapshotMoveData:
  features: EnableCSI  

```
Here is how I am creating my PVC 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velero-test
  namespace: velero
  annotations:
    velero.io/csi-volumesnapshot-class: "test-snapclass"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
  storageClassName: netapp-nfs3-aggr01   
``` 
After that by following documentation I am creating an VolumeSnapshotClass using driver csi.trident.netapp.io
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  namespace: velero
  name: test-snapclass
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: csi.trident.netapp.io
deletionPolicy: Delete  
```
After that trying to create an backup with this configuration
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup
  namespace: velero
  annotations:
    velero.io/csi-volumesnapshot-class_disk.csi.cloud.com: "test-snapclass"
spec:
  includedNamespaces:
    - velero
```
The Backup is completing but I am getting this 

` Cluster:   resource: /persistentvolumes name: /pvc-337f3234-a829-49ff-b220-20296ad8d64f message: /No volume ID returned by volume snapshotter for persistent volume`

**What did you expect to happen:**
I understand that by approaching it this way, I am backing up the entire namespace rather than just the PVC or PV. However, my initial priority is to address this issue before moving forward with the backup process.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
[bundle-2024-02-13-16-27-33.tar.gz](https://github.com/vmware-tanzu/velero/files/14265314/bundle-2024-02-13-16-27-33.tar.gz)

**Comment by shubham-pampattiwar** [comment]
Can you also paste the yaml corresponding to the storageclass (`netapp-nfs3-aggr01 `) used for creating the PVC ?

**Comment by davidmkrtchian** [comment]
> Can you also paste the yaml spec corresponding to the storageclass (`netapp-nfs3-aggr01 `) used for creating the PVC ?

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: netapp-nfs3-aggr01
  uid: d3c895fe-7ebf-4cfd-a89e-6f32430a4cca
  resourceVersion: '594498'
  creationTimestamp: '2022-11-03T12:17:09Z'
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
  managedFields:
    - manager: HashiCorp
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2022-11-03T12:17:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:allowVolumeExpansion: {}
        f:metadata:
          f:annotations:
            .: {}
            f:storageclass.kubernetes.io/is-default-class: {}
        f:parameters:
          .: {}
          f:backendType: {}
          f:fsType: {}
          f:media: {}
          f:provisioningType: {}
          f:snapshots: {}
          f:storagePools: {}
        f:provisioner: {}
        f:reclaimPolicy: {}
        f:volumeBindingMode: {}
  selfLink: /apis/storage.k8s.io/v1/storageclasses/netapp-nfs3-aggr01
provisioner: csi.trident.netapp.io
parameters:
  backendType: ontap-nas
  fsType: xfs
  media: ssd
  provisioningType: thin
  snapshots: 'true'
  storagePools: netapp-nfs3-aggr01:aggr01_n01_SSD
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate

```

**Comment by ywk253100** [comment]
Seems you have an incorrect indent for `features: EnableCSI` which caused the CSI isn't enabled so the native snapshot mechanism is used to back up the PVs.

Remove the indent to enable the CSI feature and try it again:
```
defaultSnapshotMoveData:
features: EnableCSI 
```

**Comment by davidmkrtchian** [comment]
> Seems you have an incorrect indent for `features: EnableCSI` which caused the CSI isn't enabled so the native snapshot mechanism is used to back up the PVs.
> 
> Remove the indent to enable the CSI feature and try it again:
> 
> ```
> defaultSnapshotMoveData:
> features: EnableCSI 
> ```
I apologize for my delayed response.

Thank you for your reply. I've corrected the mistake, but there seems to be no change; I'm still receiving "No Volume ID" after creating the backup.
I would be grateful if you could suggest any other solutions.

**Comment by ywk253100** [comment]
Please run the `velero debug` command again and upload the debug bundle

**Comment by davidmkrtchian** [comment]
> Please run the `velero debug` command again and upload the debug bundle

I made some changes in my code and got the next situation. When the configuration is looking in this way 

```
 configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: bostongene-backups
      prefix: rax/sandbox/volume-velero-test/
      default: true
      accessMode: ReadWrite
      config:
        region: us-east-1
  volumeSnapshotLocation:
  - provider: aws
    config:
      region: us-east-1
  features: EnableCSI  (This feature is with indent) 
```
I can see the  features: EnableCSI in the arguments for my deployment. Only in this way it is working.
```
      args:
        - server
        - '--uploader-type=restic'
        - '--features=EnableCSI'
```
But after creating backup, it is failing with timeout
`Waiting for CSI driver to reconcile volumesnapshot velero/velero-velero-test-lfsrd. Retrying in 5s`
 
 Also here is the bundle file
 
[bundle-2024-02-21-22-12-16.tar.gz](https://github.com/vmware-tanzu/velero/files/14363612/bundle-2024-02-21-22-12-16.tar.gz)
