### ISSUE TITLE
volumepolicy to ignore "local-path", but still getting warnings about hostPath volume

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#7441]
### Discussed in https://github.com/vmware-tanzu/velero/discussions/7440

<div type='discussions-op-text'>

<sup>Originally posted by **strowi** February 19, 2024</sup>
Hi,

i am trying to ignore rancher's local-path storageClass, but am still getting warnings in `velero backup describe`:

```yaml
---
# storageClass "local-path"
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: local-path
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
# k get configmap volumepolicy
apiVersion: v1
data:
  velero-policy.yml: |
    version: v1
    volumePolicies:
    - conditions:
        volumeTypes:
          - emptyDir
      action:
        type: skip
    - conditions:
        storageClass:
        - local-path
      action:
        type: skip
kind: ConfigMap
```

```bash
~> velero backup create --resource-policies-configmap volumepolicy --default-volumes-to-fs-backup --include-namespaces harbor,sonarqube backup-test8`

~> velero backup describe backup-test8
...
Warnings:
  Velero:     <none>
  Cluster:    <none>
  Namespaces:
    sonarqube:   resource: /pods name: /sonarqube-694b5fb984-4k28v message: /Volume sonarqube in pod sonarqube/sonarqube-694b5fb984-4k28v is a hostPath volume which is not supported for pod volume backup, skipping
                 resource: /pods name: /sonarqube-postgresql-0 message: /Volume data in pod sonarqube/sonarqube-postgresql-0 is a hostPath volume which is not supported for pod volume backup, skipping
...
```

Although the backup is completed, these warnings make alerting on metrics impossible. Am missing sth about the configuration?

regards,
strowi</div>

**Comment by Lyndon-Li** [comment]
Looks like we need to move the resourcePolicy check ahead of the hostPath check, as the code [around here](https://github.com/vmware-tanzu/velero/blob/b2f1588d2e54c6a9cfd560845394ff94bc1513e4/pkg/podvolume/backupper.go#L292)

**Comment by strowi** [comment]
I think this might also be related:

With the above policy, i am also getting warnings about emptyDirs in Completed Pods (resulting from a completed job) although they shouldn't even be included in the backup.

```yaml
# deployment
....
      volumes:
      - emptyDir:
          medium: Memory
        name: klipper-helm
      - emptyDir:
          medium: Memory
        name: klipper-cache
      - emptyDir:
          medium: Memory
        name: klipper-config
      - emptyDir:
          medium: Memory
        name: tmp
....
```

```bash
resource: /pods name: /helm-install-cilium-wsvzj message: /Skip pod volume tmp error: /pod is not in the expected status, name=helm-install-cilium-wsvzj, namespace=kube-system, phase=Succeeded: pod is not running
resource: /pods name: /helm-install-traefik-ptdr9 message: /Skip pod volume klipper-helm error: /pod is not in the expected status, name=helm-install-traefik-ptdr9, namespace=kube-system, phase=Succeeded: pod is not running
resource: /pods name: /helm-install-traefik-ptdr9 message: /Skip pod volume klipper-cache error: /pod is not in the expected status, name=helm-install-traefik-ptdr9, namespace=kube-system, phase=Succeeded: pod is not running
resource: /pods name: /helm-install-traefik-ptdr9 message: /Skip pod volume klipper-config error: /pod is not in the expected status, name=helm-install-traefik-ptdr9, namespace=kube-system, phase=Succeeded: pod is not running
resource: /pods name: /helm-install-traefik-ptdr9 message: /Skip pod volume tmp error: /pod is not in the expected status, name=helm-install-traefik-ptdr9, namespace=kube-system, phase=Succeeded: pod is not running
```
