### ISSUE TITLE
Restored postgresql tables missing after backup restoration in new cluster

### ISSUE THREAD

**Issue by nknoii** [vmware-tanzu/velero#7496]
**What steps did you take and what happened:**
1. Deployed PostgreSQL in the my local cluster and created tables within the database.
2. Created a Velero backup and it completed successfully.
3. Restored the Velero backup in a new cluster, including all pods, pvc, pv.
4. Attempted to access the database in the new cluster to verify the presence of tables.
But the expected tables were missing from the restored backup.

**What did you expect to happen:**
After restoring the backup into a new cluster, the tables and data should be available for access in the new cluster.

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl exec -it -n postgres postgresql-0 -- psql -U postgres -d postgres `
```
psql (16.2 (Debian 16.2-1.pgdg120+2)) 

Type "help" for help. 
postgres=# \d 
             List of relations 
Schema |    Name     |   Type   |  Owner    
--------+-------------+----------+---------- 
public | t_50000     | table    | postgres 
public | test        | table    | postgres 
public | test_id_seq | sequence | postgres 

(3 rows) 
```

- `velero backup create my-backup --include-namespaces postgres --default-volumes-to-fs-backup --snapshot-volumes --snapshot-move-data  `
```
Backup request "my-backup" submitted successfully. 

Run `velero backup describe my-backup` or `velero backup logs my-backup` for more details. 
```

- `velero backup describe my-backup `
```
Name:         my-backup 
Namespace:    velero 
Labels:       velero.io/storage-location=velero-dev
Annotations:  velero.io/resource-timeout=10m0s 
              velero.io/source-cluster-k8s-gitversion=v1.27.3 
              velero.io/source-cluster-k8s-major-version=1 
              velero.io/source-cluster-k8s-minor-version=27 

Phase:  Completed 

Warnings: 
  Velero:     <none> 
  Cluster:    <none> 
  Namespaces: 
    postgres:   resource: /pods name: /postgresql-0 

Namespaces: 
  Included:  postgres 
  Excluded:  <none> 

Resources: 
  Included:        * 
  Excluded:        <none> 
  Cluster-scoped:  auto 

Label selector:  <none> 
Or label selector:  <none> 
Storage Location:  velero-dev

Velero-Native Snapshot PVs:  true 
Snapshot Move Data:          true 
Data Mover:                  velero 

TTL:  336h0m0s 

CSISnapshotTimeout:    10m0s 
ItemOperationTimeout:  4h0m0s 

Hooks:  <none> 

Backup Format Version:  1.1.0 

Started:    2024-03-05 20:17:33 +0330 +0330 
Completed:  2024-03-05 20:17:42 +0330 +0330 
Expiration:  2024-03-19 20:17:33 +0330 +0330 

Total items to be backed up:  16 
Items backed up:              16 

Velero-Native Snapshots: <none included> 
```

**Anything else you would like to add:**

**Environment:**

- Velero version (use `6.0.0 (Helm chart)`): 
- Cloud provider or hardware configuration: Tested in local kind clusters
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
@nknoii
From the command line you are using, you have specified both `--default-volumes-to-fs-backup` and ` --snapshot-move-data`. `--default-volumes-to-fs-backup` activates the fs-backup method and ` --snapshot-move-data` is for CSI snapshot data movement backup method. If they are both specified, as the current logic, fs-backup method takes preference.

However, fs-backup is not a consistent backup type, so your backup encountered data inconsistency.

Therefore, you need to remove `--default-volumes-to-fs-backup` so that you can get a crash consistent backup with CSI snapshot data movement backup method. For sure, CSI snapshot data movement backup requires your CSI driver supports CSI snapshot.

**Comment by Lyndon-Li** [comment]
Probably, we need to add some checks to prevent these two backup flags coexist.

**Comment by nknoii** [comment]
Hey @Lyndon-Li 

`$ velero backup create my-backup --include-namespaces postgres --snapshot-volumes --snapshot-move-data`

I ran this command. Backup and restore completed successfully. but I'm still facing the same issue where tables are not restored.

ps: I'm  using aws s3 bucket for the backup.

**Comment by Lyndon-Li** [comment]
Please collect velero logs by running `velero debug` and share us the log bundle.

**Comment by nknoii** [comment]
> Please collect velero logs by running `velero debug` and share us the log bundle.

[bundle-2024-03-06-10-48-56.tar.gz](https://github.com/vmware-tanzu/velero/files/14505210/bundle-2024-03-06-10-48-56.tar.gz)

**Comment by Lyndon-Li** [comment]
From the log bundle, there is no logs for data movement backup/restore activities.
From the restore log, a restore was launched for backup `my-backup-20240306101305`. Looks like the backup is a data movement backup, but the DataUpload was not generated. Probably, the data movement backup for the PVC was not completed.

```
time="2024-03-06T04:43:07Z" level=warning msg="Got 0 DataUpload result. Expect one." error="dataupload result number is not expected" logSource="pkg/restore/restore.go:2013" restore=velero/my-backup-20240306101305

time="2024-03-06T04:43:07Z" level=info msg="Start DataMover restore." Action=PVCRestoreItemAction PVC=postgres/postgresql-persistent-storage-postgresql-0 Restore=velero/my-backup-20240306101305 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/restore/pvc_action.go:174" pluginName=velero-plugin-for-csi restore=velero/my-backup-20240306101305
time="2024-03-06T04:43:07Z" level=warning msg="PVC doesn't have a DataUpload for data mover. Return." Action=PVCRestoreItemAction PVC=postgres/postgresql-persistent-storage-postgresql-0 Restore=velero/my-backup-20240306101305 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/restore/pvc_action.go:180" pluginName=velero-plugin-for-csi restore=velero/my-backup-20240306101305
```

@nknoii Please share the log bundle for backup `my-backup-20240306101305` so that we can further troubleshoot (if the restore is to a different cluster, the backup log should be on the source cluster). Or you can run a new backup on the source cluster and make sure there is no warning about PVC skip and then run another restore.

**Comment by nknoii** [comment]
> From the log bundle, there is no logs for data movement backup/restore activities. From the restore log, a restore was launched for backup `my-backup-20240306101305`. Looks like the backup is a data movement backup, but the DataUpload was not generated. Probably, the data movement backup for the PVC was not completed.
> 
> ```
> time="2024-03-06T04:43:07Z" level=warning msg="Got 0 DataUpload result. Expect one." error="dataupload result number is not expected" logSource="pkg/restore/restore.go:2013" restore=velero/my-backup-20240306101305
> 
> time="2024-03-06T04:43:07Z" level=info msg="Start DataMover restore." Action=PVCRestoreItemAction PVC=postgres/postgresql-persistent-storage-postgresql-0 Restore=velero/my-backup-20240306101305 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/restore/pvc_action.go:174" pluginName=velero-plugin-for-csi restore=velero/my-backup-20240306101305
> time="2024-03-06T04:43:07Z" level=warning msg="PVC doesn't have a DataUpload for data mover. Return." Action=PVCRestoreItemAction PVC=postgres/postgresql-persistent-storage-postgresql-0 Restore=velero/my-backup-20240306101305 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/restore/pvc_action.go:180" pluginName=velero-plugin-for-csi restore=velero/my-backup-20240306101305
> ```
> 
> @nknoii Please share the log bundle for backup `my-backup-20240306101305` so that we can further troubleshoot (if the restore is to a different cluster, the backup log should be on the source cluster). Or you can run a new backup on the source cluster and make sure there is no warning about PVC skip and then run another restore.

[postgres-backup.log](https://github.com/vmware-tanzu/velero/files/14518434/postgres-backup.log)
I did a new backup and there were some skipping warnings.

**Comment by Lyndon-Li** [comment]
The volume is built on hostpath, it is not supported by data movement backup or fs-backup:
```
time="2024-03-07T03:28:45Z" level=info msg="Skipping PVC postgres/postgresql-persistent-storage-postgresql-0, associated PV postgresql-pv is not a CSI volume" backup=velero/postgres-backup cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:99" pluginName=velero-plugin-for-csi

time="2024-03-07T03:28:47Z" level=warning msg="Volume postgresql-persistent-storage in pod postgres/postgresql-0 is a hostPath volume which is not supported for pod volume backup, skipping" backup=velero/postgres-backup logSource="pkg/podvolume/backupper.go:267" name=postgresql-0 namespace=postgres resource=pods
```

**Comment by nknoii** [comment]
> The volume is built on hostpath, it is not supported by data movement backup or fs-backup:
> 
> ```
> time="2024-03-07T03:28:45Z" level=info msg="Skipping PVC postgres/postgresql-persistent-storage-postgresql-0, associated PV postgresql-pv is not a CSI volume" backup=velero/postgres-backup cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:99" pluginName=velero-plugin-for-csi
> 
> time="2024-03-07T03:28:47Z" level=warning msg="Volume postgresql-persistent-storage in pod postgres/postgresql-0 is a hostPath volume which is not supported for pod volume backup, skipping" backup=velero/postgres-backup logSource="pkg/podvolume/backupper.go:267" name=postgresql-0 namespace=postgres resource=pods
> ```

I see, velero supports local persistent volumes right? so I changed it to that. but it's still skipping the pvc.


[postgres-backup.log](https://github.com/vmware-tanzu/velero/files/14519452/postgres-backup.log)

```
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: postgres
  labels:
    app: postgresql
spec:
  ports:
    - port: 5432
  selector:
    app: postgresql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/postgresql/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-control-plane
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgresql
  serviceName: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgresql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

```
