### ISSUE TITLE
Skipped "PV summary" in backup log may skip pod volume

### ISSUE THREAD

**Issue by qiuming-best** [vmware-tanzu/velero#7498]
For example, if we have a pod that YAML like below:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: nfs-vol
      mountPath: /var/nfs # The mountpoint inside the container
  volumes:
  - name: nfs-vol
    nfs:
      server: 192.168.200.90 # IP to our NFS server
      path: /nfs # The exported directory

```
If we set skip nfs type of volume source from resources policies
the ` nfs-vol` will be skipped and added into `Skipped` map of `pvcSummary`, but it will not in pvcMap for it is not one PVC which leads to not being added.

so the `nfs-vol`  volume will be skipped without a log.

BackupPodVolumes handles volume not only PVC but also pod volume, but we have only `pvcMap` to record PVC but missed pod volume.
