### ISSUE TITLE
Failed to read credentials from file error

### ISSUE THREAD

**Issue by imarkvisser** [vmware-tanzu/velero#7527]
**What steps did you take and what happened:**
I am using the velero helm chart with the azure plugin and get this error when running a backup:
```
time="2024-03-14T11:07:18Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/nexus-backup error="rpc error: code = Unknown desc = failed to read credentials from file /credentials/cloud: open /credentials/cloud: no such file or directory" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.13.1/pkg/util/azure/util.go:72" error.function=github.com/vmware-tanzu/velero/pkg/util/azure.LoadCredentials logSource="pkg/backup/item_backupper.go:591" name=pvc-844517f3-dad8-45b2-b462-46d1475fe50a namespace= persistentVolume=pvc-844517f3-dad8-45b2-b462-46d1475fe50a resource=persistentvolumes volumeSnapshotLocation=default
time="2024-03-14T11:07:18Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/nexus-backup error="rpc error: code = Unknown desc = failed to read credentials from file /credentials/cloud: open /credentials/cloud: no such file or directory" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.13.1/pkg/util/azure/util.go:72" error.function=github.com/vmware-tanzu/velero/pkg/util/azure.LoadCredentials logSource="pkg/backup/item_backupper.go:591" name=nexus-files namespace= persistentVolume=nexus-files resource=persistentvolumes volumeSnapshotLocation=default
```

`velero backup create nexus-backup --include-namespaces nexus --volume-snapshot-locations default --storage-location default`

These are my helm values:
```
velero:
  image:
    repository: velero/velero
    tag: v1.13.1
    pullPolicy: IfNotPresent

  configuration:
    backupStorageLocation:
    - name: default
      default: true
      provider: velero.io/azure
      bucket: velerobackup
      credential:
        name: velero-dev-credentials
        key: cloud
      config:
        resourceGroup: <resourcegroupname>
        storageAccount: <storageaccountname>
    volumeSnapshotLocation:
    - name: default
      provider: velero.io/azure

  initContainers:
  - name: velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.9.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
```

The secret named `velero-dev-credentials` should be fine;
```
k view-secret velero-dev-credentials 
Choosing key: cloud
AZURE_SUBSCRIPTION_ID=xxx
AZURE_TENANT_ID=xxx
AZURE_CLIENT_ID=xxx
AZURE_CLIENT_SECRET=xxx
AZURE_RESOURCE_GROUP=xxx
```

**Environment:**
- Velero version (use `velero version`):  velero v1.13.1 / azure plugin v1.9.1
- Velero features (use `velero client config get features`): <NOT SET>

My issue seems similar to https://github.com/vmware-tanzu/velero/issues/7395

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
