### ISSUE TITLE
New config option checksumAlgorithm for aws plugin 1.9.1 isn't supported yet

### ISSUE THREAD

**Issue by notz** [vmware-tanzu/velero#7531]
**What steps did you take and what happened:**

I like do disable the checksumAlgorithm, which was introduced in version 1.9.1 of aws plugin.

```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  accessMode: ReadWrite
  config:
    checksumAlgorithm: ''
    region: gra
    s3ForcePathStyle: 'true'
    s3Url: https://s3.gra.io.cloud.ovh.net
  default: true
  objectStorage:
    bucket: velero
  provider: aws
```

Now i get this error message: 

`error getting the backup store: rpc error: code = Unknown desc = config has invalid keys [checksumAlgorithm]; valid keys are [region s3Url publicUrl kmsKeyId customerKeyEncryptionFile s3ForcePathStyle signatureVersion credentialsFile profile serverSideEncryption insecureSkipTLSVerify enableSharedConfig tagging bucket prefix caCert]`

**What did you expect to happen:**

Velero should know about the new config key. I have checked the source code, but i can't find the string `checksumAlgorithm` anywhere.

**The following information will help us better understand what's going on**:

**Environment:**

- Velero version (use `velero version`): 1.13.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.28.3
- Kubernetes installer & version:
- Cloud provider or hardware configuration: OVH
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
