### ISSUE TITLE
insecureSkipTLSVerify not working for client commands

### ISSUE THREAD

**Issue by abh** [vmware-tanzu/velero#7547]
**What steps did you take and what happened:**

I have a backup location defined as

```
    config:
      insecureSkipTLSVerify: "true"
      region: minio
      s3ForcePathStyle: "true"
      s3Url: https://kube-backup-store.tailscale.svc.cluster.local:9000
```

It validates okay according to velero, but when I start a backup it errors out with this error:

```
  <error getting backup volume info: Get "https://kube-backup-store.tailscale.svc.cluster.local:9000/velero/backups/bidaily-20240321004728/bidaily-20240321004728-volumeinfo.json.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=G7sHZ6yEbvG0ZUBLGNAe%2F20240321%2Fminio%2Fs3%2Faws4_request&X-Amz-Date=20240321T005003Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&x-id=GetObject&X-Amz-Signature=f7cf073fd63fffcdf421558e7c2a13fb088838ec477403fb896b739fac3a6e80": tls: failed to verify certificate: x509: certificate is valid for kube-backup-store.ntp.ts.net, not kube-backup-store.tailscale.svc.cluster.local>
```

**What did you expect to happen:**
- Backup proceeding ...

**The following information will help us better understand what's going on**:

Bundle attached: [removed as it was unclear what was shared and maybe it wasn't relevant]
