### ISSUE TITLE
Node Agent: cannot list resource "pods" in API group "" at the cluster scope

### ISSUE THREAD

**Issue by tomosin09** [vmware-tanzu/velero#7562]
**What steps did you take and what happened:**

I deploy velero locally using helm and minikube. In the future, to implement deployment in production, i wont be able to use ClusterRole, so configure velero without it. My conditions are almost the same as [here](https://github.com/vmware-tanzu/velero/issues/5156).
Backup will include the following resources: pv, pvc, pod.
Okay, I'm simulating deployment in a local environment, but i get next error in `node-agent`:

```
time="2024-03-25T17:36:20Z" level=info msg="Setting log-level to INFO"
time="2024-03-25T17:36:20Z" level=info msg="Starting Velero node-agent server v1.13.1 (ea5a89f83b89b2cb7a27f54148683c1ee8d57a37-dirty)" logSource="pkg/cmd/cli/nodeagent/server.go:108"
1.7113881801084177e+09  INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8080"}
An error occurred: pods is forbidden: User "system:serviceaccount:default:velero-service-account" cannot list resource "pods" in API group "" at the cluster scope
```

**What did you expect to happen:**

Velero deployment with node-agent can be isolated in one namespace, without using ClusterRole.

**The following information will help us better understand what's going on**:

**Anything else you would like to add:**

Important from helm values file

```
extraObjects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: velero-role
      namespace: default
      labels:
        component: velero
    rules:
    - apiGroups: [velero.io]
      verbs: ["*"]
      resources: ["*"]
    - apiGroups: [""]
      verbs: ["get", "list", "watch", "create", "update", "patch"]
      resources: ["pods", "persistentvolumes", "persistentvolumeclaims", "secrets", "namespaces"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: velero-role-binding
      labels:
        component: velero
    subjects:
      - kind: ServiceAccount
        name: velero-service-account
        namespace: default
    roleRef:
      kind: Role
      name: velero-role
      apiGroup: rbac.authorization.k8s.io

rbac:
  create: false
  clusterAdministrator: false

serviceAccount:
  server:
    create: true
    name: velero-service-account

deployNodeAgent: true

nodeAgent:
  podVolumePath: /var/lib/kubelet/pods
  priorityClassName: ""
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
  tolerations: []
  annotations: {}
  labels: {}
  useScratchEmptyDir: true
  extraVolumes: []
  extraVolumeMounts: []
  extraEnvVars: {}
  dnsPolicy: ClusterFirst
  podSecurityContext:
    runAsUser: 0
    # fsGroup: 1337
  containerSecurityContext: {}
  lifecycle: {}
  nodeSelector: {}
  affinity: {}
  dnsConfig: {}
```

**Environment:**

- Velero version (use `velero version`): v1.13.1
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): Client Version: v1.29.0, Server Version: v1.28.3
- Kubernetes installer & version: minikube v1.32.0
- Cloud provider or hardware configuration: -
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.3 LTS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
