### ISSUE TITLE
Restore from latest backup with only scheduleName set, does not work (as described in the api spec)

### ISSUE THREAD

**Issue by Elyytscha** [vmware-tanzu/velero#7583]
**What steps did you take and what happened:**
i'm testing the restore process for our vault.

If im in a hurry i wouldn't want to search first manually for the latest backup name from the schedule before i can restore a backup..

tried to restore the latest backup from a schedule as described in the crd spec

![image](https://github.com/vmware-tanzu/velero/assets/10408311/5ffbb811-5a3e-4b4b-8ef7-40fedca56e4f)

```yaml
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: test-vault
  namespace: vault-migration
spec:
  restorePVs: true
  scheduleName: vault
```

**What did you expect to happen:**

successfull creation of the restore cr

**Environment:**

```
velero/velero:v1.13.0
velero/velero-plugin-for-gcp:v1.9.0
GKE 1.27.10
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
