### ISSUE TITLE
While Upgrading to chart version 6.0.0 getting default storage location error

### ISSUE THREAD

**Issue by gravops** [vmware-tanzu/velero#7629]
**What steps did you take and what happened:**
Upgraded chart for velero from 2.26.5 to 6.0.0

**What did you expect to happen:**
Velero upgraded to new version and backup and restore to be working as before.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
Velero pod is in error state with the error:
```
time="2024-04-06T08:55:03Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:552"
An error occurred: backupstoragelocations.velero.io "default" not found
```

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  1.13.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version: 1.26
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Ubuntu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
one related issue is https://github.com/vmware-tanzu/velero/issues/7359 
@gravops please upgrade to velero v1.13.1

**Comment by gravops** [comment]
Hello @qiuming-best thanks for sharing, but my config is as below:
```
              backupStorageLocation:
              - name: aws
                bucket: "eks-{{ metadata.annotations.accountid }}"
                provider: aws
                default: true
                credential:
                  useSecret: false
```
I am using default: true in my BSL definition but still it is checking for some default BSL. I tried cleaning up my old CRDs and reinstall Velero that also didn't work.

**Comment by qiuming-best** [comment]
@gravops what do you mean by `still it is checking for some default BSL`?

**Comment by gravops** [comment]
In logs i can see that container failed to start as it was unable to find the default BSL. And in my case I am having BSL aws with `default: true`.
But as suggested I updated image to 1.13.1 and now it is working. Don't know what was the issue with previous(1.13.0) version was.

**Comment by gravops** [comment]
@qiuming-best Now I am getting this error in velero pod logs:

`time="2024-04-08T05:30:29Z" level=error msg="Error getting a backup store" backup-storage-location=velero/aws controller=backup-storage-location error="rpc error: code = Unknown desc = provided credentialsFile does not exist: stat /credentials/cloud: no such file or directory" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:150" error.function="main.(*ObjectStore).Init" logSource="pkg/controller/backup_storage_location_controller.go:137"`

I followed below doc for upgrade https://velero.io/docs/v1.13/upgrade-to-1.13/.

**Comment by qiuming-best** [comment]
We have some adjustments to the default BSL selection logic which would lead to the error you mentioned above when not creating the default BSL before the velero server install no matter whether you specified the default BSL.

For the Velero helm chart, it will first install the velero server before creating BSL, which would lead to the above problem, and we fixed it in V1.13.1

**Comment by qiuming-best** [comment]
> useSecret: false

please refer to [it](https://velero.io/docs/v1.1.0/debugging-install/#:~:text=open%20credentials%2Fcloud%3A%20no%20such,in%20the%20Velero%20server's%20namespace)

maybe the reason is you configured `useSecret: false`

**Comment by gravops** [comment]
Hello @qiuming-best ,
This is working if I downgrade my aws-plugin version for velero to 1.4.0 or below [v1.8.0](https://github.com/vmware-tanzu/velero-plugin-for-aws/releases/tag/v1.8.0). I think after the changes velero is trying to find Cloud credentials under
`stat /credentials/cloud`.

Previously we were using IAM role and service account only, is there any flag which we can set which will make velero know to use IAM in place of secret?

**Comment by gravops** [comment]
BTW, I used `useSecret: true` and it still didn't work for me.

**Comment by qiuming-best** [comment]
Maybe you can refer to [this](https://github.com/vmware-tanzu/velero-plugin-for-aws?tab=readme-ov-file#option-1-set-permissions-with-an-iam-user)?

**Comment by gravops** [comment]
@qiuming-best ,

Below is my conf for BSL:
```
            configuration:
              backupStorageLocation:
              - name: aws
                bucket: "eks-{{ metadata.annotations.accountid }}"
                provider: aws
                default: true
                credential:
                  useSecret: false
                config:
                  kmsKeyId: "{{ metadata.annotations.kms_arn }}"
                  region: "{{ metadata.annotations.region }}"
                  prefix: "backup"
              volumeSnapshotLocation:
              - name: aws
                provider: aws
                credential:
                  useSecret: false
                config:
                  region: "{{ metadata.annotations.region }}"
```

Also Can you please share about the PR https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/163. This is what I am looking to do. Use IAM role for velero to interact with AWS API.

**Comment by gravops** [comment]
Here is the full config.

```
            image:
              imagePullSecrets:
              - jfrog-auth
              repository: XXXXXX/velero/velero
              tag: v1.13.1
            initContainers:
              - name: velero-plugin-for-aws
                image: XXXXXX/velero/velero-plugin-for-aws:v1.8.0
                imagePullPolicy: IfNotPresent
                volumeMounts:
                  - mountPath: /target
                    name: plugins
            configuration:
              backupStorageLocation:
              - name: aws
                bucket: "eks-{{ metadata.annotations.accountid }}"
                provider: aws
                default: true
                credential:
                  useSecret: false
                config:
                  kmsKeyId: "{{ metadata.annotations.kms_arn }}"
                  region: "{{ metadata.annotations.region }}"
                  prefix: "backup"
              volumeSnapshotLocation:
              - name: aws
                provider: aws
                credential:
                  useSecret: false
                config:
                  region: "{{ metadata.annotations.region }}"
            schedules:
              application-backup:
                schedule: "0 * * * *"
                template:
                  ttl: "720h0m0s"
                  snapshotVolumes: true
                  storageLocation: aws
                  includeClusterResources: true
                  includedNamespaces:
                  - "*"
                  includedResources:
                  - "*"
                  volumeSnapshotLocations:
                  - aws
                  excludedNamespaces:
                  - argocd
                  - aws-ebs-csi-driver
                  - aws-efs-csi-driver
              system-backup:
                schedule: "0 1/12 * * *"
                template:
                  ttl: "720h0m0s"
                  snapshotVolumes: true
                  storageLocation: aws
                  includeClusterResources: true
                  includedResources:
                  - "*"
                  volumeSnapshotLocations:
                  - aws
                  includedNamespaces:
                  - argocd
                  - aws-ebs-csi-driver
                  - aws-efs-csi-driver
            serviceAccount:
              server:
                create: true
            annotations:
              annotation: velero
            labels:
              label: velero
            podAnnotations:
              metrics.dynatrace.com/filter: "{ \"mode\": \"include\", \"names\": [ \"velero_backup_failure_total\", \"velero_backup_partial_failure_total\" ] }"
              metrics.dynatrace.com/path: /metrics
              metrics.dynatrace.com/port: "8085"
              metrics.dynatrace.com/scrape: "true"
            podLabels:
              pod-label: velero
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                cpu: 600m
                memory: 8Gi
            deployNodeAgent: true
            nodeAgent:
              podVolumePath: /var/lib/kubelet/pods
              privileged: false
              annotations:
                annotation: node-agent
              labels:
                label: node-agent
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
            kubectl:
              image:
                repository: docker.io/bitnami/kubectl
                tag: latest
              annotations:
                annotation: kubectl
              labels:
                label: kubectl
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
            cleanUpCRDs: false
            upgradeCRDs: true
```

**Comment by qiuming-best** [comment]
> Hello @qiuming-best , This is working if I downgrade my aws-plugin version for velero to 1.4.0 or below [v1.8.0](https://github.com/vmware-tanzu/velero-plugin-for-aws/releases/tag/v1.8.0). I think after the changes velero is trying to find Cloud credentials under `stat /credentials/cloud`.
> 
> Previously we were using IAM role and service account only, is there any flag which we can set which will make velero know to use IAM in place of secret?

@reasonerjt could you help to take a look at the issue?

**Comment by gravops** [comment]
Now I am completely stuck on this. It working till 1.7.1 but after that in 1.8.0 plugin it is facing issue. I am unable to find if there is any flag which I need to pass to make it use IAM role in place of credentials. With velero:1.13.1 and plugin:1.9.1 it is giving below error:

`time="2024-04-08T08:57:14Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/1/0, BackupStorageLocation \"aws\" is unavailable: rpc error: code = Unknown desc = provided credentialsFile does not exist: stat /credentials/cloud: no such file or directory)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:178"`

**Comment by gravops** [comment]
Hello @qiuming-best @reasonerjt Can you guys suggest on this?

**Comment by gravops** [comment]
@qiuming-best @reasonerjt I tried using "serviceAccountName" as well but it is still check for cloud credentials file. Is there any way we can enable use of IAM/Service Account?
```
            image:
              imagePullSecrets:
              - jfrog-auth
              repository: XXXXXXX/velero/velero
              tag: v1.13.1
              serviceAccountName: velero-service-account
```

**Comment by Da-M1c** [comment]
@gravops i worked the last hours on the same issue, velero helm chart version 5.0.2 with aws plugin 1.7.1 was working fine with service account iam role annotation. I updated to version 5.2.2 with aws plugin 1.8.2 and the iam permission was broken. 

I just looked into the code changes and figured out that the /credentials/cloud is used as long as AWS_SHARED_CREDENTIALS_FILE is configured as env parameter in the deployment. This behavior is configurable via useSecret in block credentials:

![image](https://github.com/vmware-tanzu/velero/assets/32191971/19cf91fc-a6ad-4899-8e87-4bc43c8640ef)

[...]
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:${var.velero_aws_plugin_version}
    volumeMounts:
      - mountPath: /target
        name: plugins
**credentials:
  useSecret: false**
configuration:
  backupStorageLocation:
  - default:
    provider: aws
[...]

This made it working again for me.

**Comment by gravops** [comment]
Hello @Da-M1c ,
As made the changes as you shared in the yaml passed.
```
            image:
              imagePullSecrets:
              - jfrog-auth
              repository: XXXXXXXX/velero/velero
              tag: v1.13.1
              serviceAccountName: velero-service-account
            initContainers:
              - name: velero-plugin-for-aws
                image: XXXXXXXX/velero/velero-plugin-for-aws:v1.8.0
                imagePullPolicy: IfNotPresent
                volumeMounts:
                  - mountPath: /target
                    name: plugins
            credential:
              useSecret: false
            configuration:
              backupStorageLocation:
              - name: aws
                bucket: "eks-{{ metadata.annotations.accountid }}"
                provider: aws
                default: true
                credential:
                  useSecret: false
                config:
                  kmsKeyId: "{{ metadata.annotations.kms_arn }}"
                  region: "{{ metadata.annotations.region }}"
                  prefix: "backup"
              volumeSnapshotLocation:
              - name: aws
                provider: aws
                credential:
                  useSecret: false
                config:
                  region: "{{ metadata.annotations.region }}"
```

Still getting same issue in the velero pod logs.

time="2024-04-09T12:17:44Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/1/0, BackupStorageLocation \"aws\" is unavailable: rpc error: code = Unknown desc = provided credentialsFile does not exist: stat /credentials/cloud: no such file or directory)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:178"
