### ISSUE TITLE
Resource Modifier: Condition matching is incorrect when there are multiple rules

### ISSUE THREAD

**Issue by 27149chen** [vmware-tanzu/velero#7714]
**What steps did you take and what happened:**
1. define a resource modifier to update storageClass name in pvc in this rule: a=>b, b=>c
2. run velero restore
3. result: a=>c, b=>c

```
version: v1
resourceModifierRules:
- conditions:
    groupResource: persistentvolumeclaims
  matches:
    - path: "/spec/storageClassName"
      value: "a"
  patches:
  - operation: replace
    path: "/spec/storageClassName"
    value: "b"
- conditions:
    groupResource: persistentvolumeclaims
  matches:
    - path: "/spec/storageClassName"
      value: "b"
  patches:
  - operation: replace
    path: "/spec/storageClassName"
    value: "c"
```

**What did you expect to happen:**
a=>b, b=>c

**Anything else you would like to add:**
The same problem will occur in other situations if any field that affects the condition matching is changed in patch.

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
