### ISSUE TITLE
Resources that don't match the label selector are backed up

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#7750]
The workload:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd0-pv-claim
spec:
  storageClassName: "default"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
    etcd_node: etcd0
  name: etcd0
  annotations:
    "pre.hook.backup.velero.io/container": "etcd0"
    "pre.hook.backup.velero.io/command": "[\"/usr/local/bin/etcd\", \"-h\"]"
spec:
  volumes:
    - name: etcd0-storage
      persistentVolumeClaim:
        claimName: etcd0-pv-claim
  containers:
    - command:
        - /usr/local/bin/etcd
        - --name
        - etcd0
        - --initial-advertise-peer-urls
        - http://etcd0:2380
        - --listen-peer-urls
        - http://0.0.0.0:2380
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://etcd0:2379
        - --initial-cluster
        - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
        - --initial-cluster-state
        - new
      image: quay.io/coreos/etcd:latest
      volumeMounts:
        - mountPath: "/etcd0.etcd"
          name: etcd0-storage
      name: etcd0
      ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
  restartPolicy: Always
```

The backup command:
```
velero backup create test12 --include-namespaces default --snapshot-volumes --wait --selector app=etcd
```

The backup result:
```
velero backup describe test12 --details
Name:         test12
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.28.7+vmware.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=28

Phase:  Completed


Namespaces:
  Included:  default
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  app=etcd

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true
Snapshot Move Data:          true
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2024-04-28 08:37:32 +0000 UTC
Completed:  2024-04-28 08:38:11 +0000 UTC

Expiration:  2024-05-28 08:37:32 +0000 UTC

Total items to be backed up:  4
Items backed up:              4

Backup Item Operations:
  Operation for persistentvolumeclaims default/etcd0-pv-claim:
    Backup Item Action Plugin:  velero.io/csi-pvc-backupper
    Operation ID:               du-e1522ce3-597d-40b9-96b4-5bbe26061542.480573e7-aa17-4900e451d
    Items to Update:
                           datauploads.velero.io velero/test12-wdxsx
    Phase:                 Completed
    Progress:              128020480 of 128020480 complete (Bytes)
    Progress description:  Completed
    Created:               2024-04-28 08:37:43 +0000 UTC
    Started:               2024-04-28 08:38:02 +0000 UTC
    Updated:               2024-04-28 08:38:03 +0000 UTC
Resource List:
  v1/Namespace:
    - default
  v1/PersistentVolume:
    - pvc-480573e7-aa17-4907-a0ee-b829d03aaebf
  v1/PersistentVolumeClaim:
    - default/etcd0-pv-claim
  v1/Pod:
    - default/etcd0

Backup Volumes:
  Velero-Native Snapshots: <none included>

  CSI Snapshots:
    default/etcd0-pv-claim:
      Data Movement:
        Operation ID: du-e1522ce3-597d-40b9-96b4-5bbe26061542.480573e7-aa17-4900e451d
        Data Mover: velero
        Uploader Type: kopia
        Moved data Size (bytes): 128020480

  Pod Volume Backups: <none included>

HooksAttempted:  1
HooksFailed:     0
```

The PVC/PV isn't labeled with `app=etcd` but is still included in the backup. 
The issue also happens in restore.
