### ISSUE TITLE
Add OWNERS file to allow prow auto merge

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#7783]
[Add OWNERS file like so](https://github.com/jpmcb/prow-github-actions/blob/main/docs/examples.md#review-and-approve-pull-requests) and subsequent
```
# List of usernames who may use /lgtm
reviewers:
- user1
- user2
- user3

# List of usernames who may use /approve
approvers:
- user1
- user2
- admin1
```

Add this github action to allow auto merge when lgtm is applied.
```
name: "Merge on lgtm label"
on:
  schedule:
  - cron: "0 * * * *"

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: jpmcb/prow-github-actions@v1
        with:
          jobs: 'lgtm'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
```
https://github.com/jpmcb/prow-github-actions/blob/main/docs/examples.md#automatic-pr-merger

Follow up from https://github.com/vmware-tanzu/velero/pull/7776
