### ISSUE TITLE
velero-plugin-for-aws v1.9.x no longer works with S3-compatible BackupStorageLocation

### ISSUE THREAD

**Issue by losil** [vmware-tanzu/velero#7828]
**What steps did you take and what happened:**
We have updated our velero deployment with the latest Helm chart `6.4.0` which installs velero `1.13.2`. With this upgrade the version of the `velero-plugin-for-aws` plugin has also been updated to `v1.9.0` respectively `v1.9.2` during troubleshooting. The upgrade itself went through smoothly. Also the BackupStorageLocation which is a S3-compatible NetApp StorageGrid backend was in `Available` state after velero was initialized. 
After that we tested some backup with all were unsuccessful and ended in the state `Failed`. We noticed that that during the backup run the BackupStorageLocation went to `Unavailable` with the corresponding log message:
```
BackupStorageLocation "netapp-s3" is unavailable: rpc error: code = Unknown desc = operation error S3: ListObjectsV2, https response error StatusCode: 403, RequestID: 1716281754869367, HostID: 12783833, api error AccessDenied: V4 authentication signed header not found: accept-encoding
```

The configuration of the BackupStorageLocation looks like this and as said is a S3-compatible NetApp Storagegrid system:
```
configuration:
  backupStorageLocation:
    - name: netapp-s3
      provider: aws
      bucket: mycluster
      prefix: velero
      default: true
      accessMode: ReadWrite
      credential:
        name: velero-s3-credentials
        key: cloud
      config:
        region: myregion
        s3ForcePathStyle: true
        s3Url: https://objectstore.localdomain.local:10443/
        signatureVersion: "4"
```

After the Backup run has ended velero marked the BackupStorageLocation as `Available` again in its regularly validation schedule.

Downgrading the `velcro-plugin-for-aws` to `v1.8.2` solves the issue and the Backups are successful again.

**What did you expect to happen:**

We expect the same behavior when using the current version of the velcro-plugin-for-aws initContainer. Velero should be able to use the S3-compatible backend provided by NetApp Storagegrid.

**The following information will help us better understand what's going on**:

[bundle-2024-05-27-09-20-52.tar.gz](https://github.com/vmware-tanzu/velero/files/15452612/bundle-2024-05-27-09-20-52.tar.gz)

**Environment:**

- Velero version (use `velero version`): v1.13.2
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): v1.26.15+rke2r1
- Kubernetes installer & version: Rancher RKE2 - v1.26.15+rke2r1
- Cloud provider or hardware configuration: VMware ESXi, 7.0.3, 20328353
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.4 LTS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
