### ISSUE TITLE
since 1.13 backup describe does not show FS/Restic backup volumes anymore

### ISSUE THREAD

**Issue by alexfouche** [vmware-tanzu/velero#7894]
**What steps did you take and what happened:**

Since Velero 1.13, the `backup describe --details` does not show Restic / FS volumes backed up anymore. 

I have seen in 1.13.0 releases notes in breaking changes that a mention that Restic volumes details is now moved to the "Backup Volumes:" section, but as you see in my output below, it does not show up, though it has been backed up (I did restore tests to be sure).

-> I believe this is a bug, and if not, this is really confusing. Moreover backup logs wrote that volumes are not backed up because of namespace scoping, so there are all the elements to make you scared and doubt

 ```bash
velero backup describe --details some_backup_name
```

gets me:

```
(...)
  v1/PersistentVolume:
    - pvc-3051eaa6-blabla
    - pvc-5dfc5b49-blabla
    - pvc-628229e4-blabla
  v1/PersistentVolumeClaim:
    - blabla/data-blabla-elasticsearch-master-0
    - blabla/data-blabla-mysql-0
    - blabla/blabla-sugarcrm
(...)

Backup Volumes: <none included>
```

Nevertheless, after some restore tests, the Restic / FS data in indeed backed up

**What did you expect to happen:**

I was expecting something in the `Backup Volumes:` section. Until Velero 1.12, it showed like this:

```
(...)
  v1/PersistentVolume:
    - pvc-3051eaa6-blabla
    - pvc-5dfc5b49-blabla
    - pvc-628229e4-blabla
  v1/PersistentVolumeClaim:
    - blabla/data-blabla-elasticsearch-master-0
    - blabla/data-blabla-mysql-0
    - blabla/blabla-sugarcrm
(...)

restic Backups:
  Completed:
    blabla/blabla-elasticsearch-master-0: data
    blabla/blabla-mysql-0: data
    blabla/blabla-sugarcrm-7cdd49f8ff-wcdq9: app```
```

**The following information will help us better understand what's going on**:

Tested with Velero server 1.13.2

And Velero clients 1.12.2 , 1.13.0, 1.13.2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
