### ISSUE TITLE
“No volume ID returned by volume snapshotter for persistent volume” warning is shown for NFS volumes.

### ISSUE THREAD

**Issue by reitermarkus** [vmware-tanzu/velero#7915]
**What steps did you take and what happened:**

Created a backup. It completed successfully, but shows the following warning for an NFS PV:

```
Warnings:
  Velero:     <none>
  Cluster:   resource: /persistentvolumes name: /my-volume message: /No volume ID returned by volume snapshotter for persistent volume
  Namespaces: <none>
```

All pods which are using this volume also have the corresponding `backup.velero.io/backup-volumes-excludes` annotation.

**What did you expect to happen:**

No warning, since there is no NFS snapshotter and the volume is excluded from backups.

**Anything else you would like to add:**

Related to https://github.com/vmware-tanzu/velero/issues/7672.

Volume definition:

```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvolume
spec:
  capacity:
    storage: 100Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mypath
    server: myserver
```

**Environment:**

- Velero version (use `velero version`): v1.13.2
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): v1.29.6
- Kubernetes installer & version: Talos 1.7.5
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
