### ISSUE TITLE
v1.14.0 Scheduled backup fails if namespace doesn't exist

### ISSUE THREAD

**Issue by phoenix-bjoern** [vmware-tanzu/velero#7928]
**What steps did you take and what happened:**
Create a schedule and include a non-existing namespace:

```
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-application-backup
  namespace: velero
  annotations:
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: velero
spec:
  useOwnerReferencesInBackup: false
  schedule: "0 0 * * *"
  template:
    csiSnapshotTimeout: 14400s
    hooks: {}
    includeClusterResources: false
    includedNamespaces:
    - my-namespace
    - a-non-existing-namespace
    itemOperationTimeout: 0s
    metadata: {}
    ttl: 720h
```

**What did you expect to happen:**

Velero before v1.14.0 executed the backup without complaint. Velero v1.14.0 stops the scheduled backup instantly and sets the status `FailedValidation` instead of executing the backup and e.g. setting the `PartiallyFailed` status. This new behavior is dangerous (or even critical?) as scheduled backups become fragile and stop working as soon as a defined namespace doesn't exist anymore.
