### ISSUE TITLE
failed to restore volume with StorageClass, claim Selector is not supported

### ISSUE THREAD

**Issue by soostdijck** [vmware-tanzu/velero#7946]
**What steps did you take and what happened:**
We have a setup where the NFS CSI driver creates the PV's dynamically once the PVC's are created/restored. This is done by specifying the correct storage classes.

However, when Velero backs up the PVC's, it adds a selector that breaks the PV creation by the NFS driver:

```
  selector:
    matchLabels:
      velero.io/dynamic-pv-restore: <pvc-name>.87z5b
```

**What did you expect to happen:**
We expect the restore to happen without Velero adding extra selectors that break the dynamic PV creation.

The output of the following commands will help us better understand what's going on:

```
velero backup create BACKUP_NAME --include-namespaces NAMESPACE --snapshot-move-data --snapshot-volumes --include-resources pvc

velero restore create --from-backup BACKUP_NAME
```

**Environment:**

Velero helm chart 6.4.x, Velero version 1.13.2
Kubernetes version 1.27

Note, this is a duplicate of [this issue on the helm chart, but I think it belongs here](https://github.com/vmware-tanzu/helm-charts/issues/588#issue-2357291827)

**Comment by kaovilai** [comment]
> it adds a selector that breaks the PV creation by the NFS driver

Sounds like a faulty NFS driver if it can't handle user (or velero) added labelSelector.

**Comment by soostdijck** [comment]
> > it adds a selector that breaks the PV creation by the NFS driver 
> Sounds like a faulty NFS driver if it can't handle user (or velero) added labelSelector.
It seems very unlikely to me that something as large and common as [csi nfs ](https://github.com/kubernetes-csi/csi-driver-nfs) would be "faulty".

**Comment by Lyndon-Li** [comment]
This is done purposefully as/expected by Velero data mover restore workflow.
After Velero data mover restore completes, the restored PV will be bound to this PVC.

If you don't see this happens, it means the data mover restore doesn't complete. 
Then you can get the corresponding DataDownload CR to see the progress by `kubectl get datadownload -n velero`

**Comment by kaovilai** [comment]
@soostdijck can you link docs that indicate label selector cannot be added?

**Comment by StellaV** [comment]
Hi @Lyndon-Li and @kaovilai

Thanks for the quick replies!

 I think there's one confusion about how we use the NFS driver. We do not back up the PV's, as we use a storage class that dynamically creates them when a PVC is added. This is where it goes wrong. The dynamic PV's cannot be created due to the selector added by Velero, resulting in the error "failed to restore volume with StorageClass, claim Selector is not supported".

Here's an example of how we did it:
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  name: sc-example
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs.example.com
  share: /
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nolock
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-example
  labels:
    velero.io/include-in-backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: sc-example
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: vsc-example
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: nfs.csi.k8s.io
parameters:
  server: nfs.example.com
  share: /
deletionPolicy: Delete
```

I hope this makes the issue a bit more clear?

Regards,
Stella
