### ISSUE TITLE
Adding an empty space in the value of `backup.velero.io/backup-volumes` backs up only up to that space

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware-tanzu/velero#7992]
Using the annotation `backup.velero.io/backup-volumes` and passing data like:

```yaml
...
spec:
    template:
        metadata:
            annotations:
                backup.velero.io/backup-volumes: config, data, translations, documents, images, keys
...
```

means that only `config` will be backed up and the rest won't

While if you do:

```yaml
...
spec:
    template:
        metadata:
            annotations:
                backup.velero.io/backup-volumes: config,data,translations,documents,images,keys
...
```
everything works as expected

**What did you expect to happen:**

Everything to be backed up... perhaps remove any empty spaces?

**The following information will help us better understand what's going on**:

This is relevant in the logs

```
{\"name\":\"pvc-d4d6c0a0-1551-4aac-acd2-07e89e0afeb7\",\"reasons\":[{\"approach\":\"podvolume\",\"reason\":\"opted out due to annotation in pod vikunja-5b7677f466-6g7ds\"}
```

**Environment:**

- Velero version (use `velero version`): 
Client:
        Version: v1.13.2
        Git commit: none
Server:
        Version: v1.14.0
# WARNING: the client version does not match the server version. Please update client

- Velero features (use `velero client config get features`): 
features: <NOT SET>

- Kubernetes version (use `kubectl version`):
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2+k3s1

- Cloud provider or hardware configuration:
bare metal

- OS (e.g. from `/etc/os-release`):
Ubuntu 22.04

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
