### ISSUE TITLE
S3 headers are added to bucket files resulting in "error getting backup volume info: gzip: invalid header"

### ISSUE THREAD

**Issue by schferbe** [vmware-tanzu/velero#7995]
**What steps did you take and what happened:**

I installed velero 1.14 and the aws plugin 1.10 as Helm chart via Argo CD

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: default
  sources:
    - chart: velero
      repoURL: https://vmware-tanzu.github.io/helm-charts
      targetRevision: 7.1.0
      helm:
        valuesObject:
          snapshotsEnabled: false
          deployNodeAgent: true
          configuration:
            backupStorageLocation:
              - name: default
                provider: aws
                bucket: my-velero-bucket
                default: true
                credential:
                  name: velero-credentials
                  key: cloud
                config:
                  region: "eu-de"
                  s3ForcePathStyle: "true"
                  s3Url: "https://obs.otc.t-systems.com"

          initContainers:
            - name: velero-plugin-for-aws
              image: velero/velero-plugin-for-aws:v1.10.0
              volumeMounts:
                - mountPath: /target
                  name: plugins

  destination:
    server: https://kubernetes.default.svc
    namespace: velero

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 
    - ServerSideApply=true
```

Then I created a backup with `velero backup create my-app-backup --selector app=my-app`. The backup is stuck in `Phase: Finalizing` and has the following error:

```
Backup Volumes:
  <error getting backup volume info: gzip: invalid header>
```

The `my-app-backup-logs.gz` from the bucket could not be unpacked with `gunzip`. Looking at the file I noticed it looks like this:

```
dbe
(binary content)
0
x-amz-checksum-crc32:kBMAMQ==
```

When removing the lines before and after the binary content it was possible to unpack the file. 

**What did you expect to happen:**

I would expect the `.gz` files in S3 to be valid gzip archives. 

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

[bundle-2024-07-10-14-38-55.tar.gz](https://github.com/user-attachments/files/16162112/bundle-2024-07-10-14-38-55.tar.gz)

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 

```
Client:
        Version: v1.14.0
        Git commit: -
Server:
        Version: v1.14.0
```

- Velero features (use `velero client config get features`): 

```
features: <NOT SET>
```

- Kubernetes version (use `kubectl version`):

```
Client Version: v1.29.2  kubectl.docker  (command link)
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

- Kubernetes installer & version:
- Cloud provider or hardware configuration: Kubernetes from Docker Desktop
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
