### ISSUE TITLE
[velero-plugin-for-aws:v1.9.1]  Brakes  S3 compatible external storage location - oracle cloud issue

### ISSUE THREAD

**Issue by leftyb** [vmware-tanzu/velero#8013]
**Steps followed:**
Upgrade to : 
velero-plugin-for-aws:v1.9.1
Velero chart version :  version: "6.7.0"
Velero version:  appVersion: 1.13.2

**Previous versions:**
velero-plugin-for-aws:v1.8.2
Velero chart version :  version: "5.2.2"
Velero version:  appVersion: 1.12.3

**What did you expect to happen:**
Velero Backups properly stored to external S3 compatible storage location. 
Before upgrade was working properly.

**From velero logs**:
When using `checksumAlgorithm: ""` Following error logs:
` operation error S3: PutObject, https response error StatusCode: 501, RequestID: , HostID: , api error NotImplemented: The s3 command you requested is not implemented."`

When NOT setting `checksumAlgorithm` so by default Velero `BackupStorageLocation ` setting to `CRC32`
Getting following errors from velero logs (tested all available algorithms and got same error) :
`operation error S3: PutObject, https response error StatusCode: 400, RequestID: , HostID: , api error InvalidArgument: x-amz-content-sha256 must be UNSIGNED-PAYLOAD, STREAMING-AWS4-HMAC-SHA256-PAYLOAD or a valid sha256 value."`

**Comment by sseago** [comment]
What s3 provider is this? We've seen issues with IBM Cloud which, in some configurations, won't work with the latest version, but I don't think we got the "not implemented" error message there. It could be that whatever s3 driver is being used needs to be upgraded to a newer version with aws sdk v2 support.

**Comment by kaovilai** [comment]
Please specify your s3 compatible provider that hits this issue.  It's been shown that not all s3 compatible has feature parity with AWS S3, which meant additional configuration may need to be done to disable/enable certain flags to make it work again.

**Comment by reasonerjt** [comment]
@DiouKnox 
Since v1.9.0 we bumped up to `aws-sdk-go-v2` following the suggestion by AWS.
If you set `checksumAlgorithm: ""` and still see the failure, it's probably a compatibility issue on oracle cloud, please check with oracle cloud engineer.

I'll keep this one open but it will likely be closed as a "won't fix" after we hear back from you.

**Comment by DiouKnox** [comment]
oracle has confirmed that it is a compatibility issue, downgrading velero version has solved the issue. thankyou for the replies.

**Comment by reasonerjt** [comment]
Thanks, I'm resovling this one.

**Comment by leftyb** [comment]
Hi all,
I apologise for the late response.
The S3 backend used is `ontap S3` .
https://docs.netapp.com/us-en/ontap/s3-config/ontap-s3-supported-actions-reference.html#bucket-operations

Before the upgrade to `Velero version: appVersion: 1.13.*` Backend was working properly and could store backups. 
After the upgrade, stopped working.
Please provide any info if any.
Thank you.

**Comment by fcecagno** [comment]
Hi, just adding to this closed issue that using the following values, I managed to upload to OCI Object Storage with velero-plugin-for-aws:v1.12.2:
```
configuration:
  backupStorageLocation:
    - provider: aws
      ...
      config:
        checksumAlgorithm: ""
  ...
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.12.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
...
```

**Comment by ebarrere** [comment]
@fcecagno — I've tried that exact version of the plugin along with `checksumAlgorithm: ""` in my config and it's not working for me. Could you share the rest of your `values.yaml` by chance?

**Comment by sseago** [comment]
@ebarrere note that there are a few scenarios where we've been unable to get 1.9.1 and later working, even with `checksumAlgorithm: ""` -- I forget which providers these were, but in at least 2 cases, the only workaround was downgrading to 1.8.z.

**Comment by ebarrere** [comment]
got it, thanks for the quick response!

does this also require a downgrade of the entire velero platform? (given the [compat matrix here](https://github.com/vmware-tanzu/velero-plugin-for-aws?tab=readme-ov-file#compatibility))

**Comment by sseago** [comment]
While the upstream maintainers do not test older plugins with newer core velero, there are no known issues as of today. On the Red Hat side, since we have some customers in this situation, we have tested v1.8 with newer versions of velero, although it's not guaranteed that this approach will work forever. Eventually, newer velero releases may become incompatible. I think the newest Velero release we've tested with this is Velero 1.16 (as part of OADP 1.5).

**Comment by sseago** [comment]
Ultimately the issue is that some s3 providers don't fully support the newer Amazon s3 APIs. Hopefully those platforms will resolve these incompatibilities before Velero gets to the point that the older AWS plugin doesn't work.

**Comment by kaovilai** [comment]
See https://github.com/vmware-tanzu/velero/issues/8265 table for providers we know work and their fixed versions.

**Comment by ebarrere** [comment]
Thanks for everyone's help. I will push Oracle to add support for checksums, as this is not the only place I've run in to it...

**Comment by fcecagno** [comment]
@ebarrere I do not mind sharing my entire values.yaml, since I took a while to get it right.
I'm using the chart https://artifacthub.io/packages/helm/vmware-tanzu/velero version 10.1.2, which means Velero 1.16.2
```
configuration:
  backupStorageLocation:
    - provider: aws
      bucket: <oci_bucket_name>
      default: true
      accessMode: ReadWrite
      credential:
        name: velero-cloud-credentials
        key: cloud
      config:
        checksumAlgorithm: ""
        region: us-east-1
        s3ForcePathStyle: true
        s3Url: https://<oci_objectstorage_namespace>.compat.objectstorage.<oci_objectstorage_region>.oci.customer-oci.com
  features: EnableCSI
  volumeSnapshotLocation:
    - provider: aws
      config:
        region: us-east-1
credentials:
  useSecret: true
  existingSecret: velero-cloud-credentials
fullnameOverride: velero
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.12.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
snapshotsEnabled: true
```

The secret was created using the following format:
```
[default]
aws_access_key_id=
aws_secret_access_key=
```
