### ISSUE TITLE
PVCs empty after velero file system backup and restore

### ISSUE THREAD

**Issue by v1nsai** [vmware-tanzu/velero#8030]
**What steps did you take and what happened:**
* Install velero and configure S3 bucket
`helm upgrade --install velero --namespace velero --values values.yaml`
my values.yaml
```yaml
configuration:
  backupStorageLocation:
  - name: aws-s3
    provider: aws
    bucket: <my bucket name>
    default: true
    accessMode: ReadWrite
    credential:
      name: backuplocation-credentials
      key: cloud
    config:
      region: us-east-1
  volumeSnapshotLocation:
  - name: aws-s3
    provider: aws
    bucket: <my bucket name>
    credential:
      name: backuplocation-credentials
      key: cloud
    config:
      region: us-east-1

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.10.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  useSecret: true
  existingSecret: backuplocation-credentials

snapshotsEnabled: false
deployNodeAgent: true
upgradeCRDs: true
defaultVolumesToFsBackup: true
features: EnableCSI
defaultSnapshotMoveData: true

nodeAgent:
  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0

schedules:
  nightly:
    schedule: 0 3 * * *
    skipImmediately: false
    template:
      csiSnapshotTimeout: 0s
      hooks: {}
      includedNamespaces:
      - '*'
      itemOperationTimeout: 0s
      metadata: {}
      ttl: 168h0m0s
      uploaderConfig:
        parallelFilesUpload: 10
      storageLocation: aws-s3
    useOwnerReferencesInBackup: false

metrics:
  prometheusRule:
    autodetect: true
    enabled: true
    # Additional labels to add to deployed PrometheusRule
    additionalLabels: {}
    # PrometheusRule namespace. Defaults to Velero namespace.
    # namespace: ""
    # Rules to be deployed
    spec:
    - alert: VeleroBackupPartialFailures
      annotations:
        message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups.
      expr: |-
        velero_backup_partial_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
      for: 15m
      labels:
        severity: warning
    - alert: VeleroBackupFailures
      annotations:
        message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
      expr: |-
        velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
      for: 15m
      labels:
        severity: warning
```
* create test deployment and pvc in test namespace
kubectl apply -f -
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: containous/whoami
        ports:
        - containerPort: 80
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'sleep infinity']
        volumeMounts:
        - name: whoami-pvc
          mountPath: /whoami-pvc
      volumes:
      - name: whoami-pvc
        persistentVolumeClaim:
          claimName: whoami-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    app: whoami
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whoami-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
```
* create test file on test pvc
`kubectl exec -it -n test <whoami-deployment-podname> -c busybox -- touch /whoami-pvc/test`
* Backup test namespace
`velero create backup test --include-namespaces test`
* Delete test deployment and pvc
`kubectl delete -f test.yaml -n test`
* Restore test namespace
`velero create restore test --from-backup test`
* Check for test file created on PVC before backup
```
$ kubectl exec -it -n test <whoami-deploy-podname> -c busybox -- ls /whoami-pvc/test
ls: /whoami-pvc/test: No such file or directory
command terminated with exit code 1
```

All other objects restored as expected except for PVCs

**What did you expect to happen:**
I was expecting the restored PVCs to have all the data they contained before being backed up

**The following information will help us better understand what's going on**:
[bundle-2024-07-20-20-19-51.tar.gz](https://github.com/user-attachments/files/16322244/bundle-2024-07-20-20-19-51.tar.gz)

**StorageClass details
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: silverstick-nfs-subdir
    meta.helm.sh/release-namespace: silverstick-provisioner
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2024-07-01T15:46:06Z"
  labels:
    app: nfs-subdir-external-provisioner
    app.kubernetes.io/managed-by: Helm
    chart: nfs-subdir-external-provisioner-4.0.18
    heritage: Helm
    release: silverstick-nfs-subdir
    velero.io/exclude-from-backup: "true"
  name: silverstick
  resourceVersion: "3276075"
  uid: 5aa7b252-ac36-4aff-8f23-587c2cb8106c
parameters:
  archiveOnDelete: "true"
provisioner: k8s-sigs.io/silverstick-nfs-subdir-external-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Environment:**
- Velero version (use `velero version`): 
```
Client:
	Version: v1.13.2
	Git commit: 4d961fb6fec384ed7f3c1b7c65c818106107f5a6
Server:
	Version: v1.13.2
```
- Velero features (use `velero client config get features`): 
`features: <NOT SET>`
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4
```
- Kubernetes installer & version:
`MicroK8s v1.29.4 revision 6809`
- Cloud provider or hardware configuration:
`Bare metal`
- OS (e.g. from `/etc/os-release`):
```
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
