### ISSUE TITLE
PodDisruptionBudget for Velero deployment does not work

### ISSUE THREAD

**Issue by monotek** [vmware-tanzu/velero#8064]
**What steps did you take and what happened:**

Adding a pdb for velero deployment with replica 3 fails:

```
kubectl -n velero get pdb velero -o yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  generation: 1
  labels:
    app: velero
    name: velero-server
  name: velero
  namespace: velero
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: velero
      name: velero-server
status:
  conditions:
  - lastTransitionTime: "2024-07-14T03:11:48Z"
    message: jobs.batch does not implement the scale subresource
    observedGeneration: 1
    reason: SyncFailed
    status: "False"
    type: DisruptionAllowed
  currentHealthy: 0
  desiredHealthy: 0
  disruptionsAllowed: 0
  expectedPods: 1
  observedGeneration: 1

```

**What did you expect to happen:**

PodDisruptionBudget for Velero deployment with replica 3 does work and shows "disruptionsAllowed: 1"

**The following information will help us better understand what's going on**:

**Anything else you would like to add:**

This seemingly happenes because the PodDisruptionBudget selector can't never work, as also all jobs (like repo-maintain and kopia maintain) get the same selectors, as they seem to inherit them from the deployment.

See also status condigtion of pdb above.

Edit: As a workaround you can use a pdb with matchexpressions instead of matchlabels:

```
    matchExpressions:
      - key: app 
        operator: In
        values:
          - velero
      - key: name 
        operator: In
        values:
          - velero-server
      - key: pod-template-hash
        operator: Exists
```

But it's still kinda bad that the pod labels are always the same.

**Environment:**

- Velero version (use `velero version`): 1.14.0
- Velero features (use `velero client config get features`):  <NOT SET>
- Kubernetes version (use `kubectl version`): 1.28.5
- Kubernetes installer & version: aks
- Cloud provider or hardware configuration: aks
- OS (e.g. from `/etc/os-release`): ubuntu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
