### ISSUE TITLE
Restore Resource Modifiers don't work for Ingresses 

### ISSUE THREAD

**Issue by 0x113** [vmware-tanzu/velero#8065]
**What steps did you take and what happened:**
I want to change the annotations and class for all ingresses in a namespace using resource modifiers, but the patch is not applied. The modifier file has two rules - one for ingresses and one for PVCs. The rule for PVCs works fine, but the one for ingresses is not executed at all.

**What did you expect to happen:**
I expect the patch to be applied and the classes and annotations to change.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
Bundle: [bundle-2024-07-31-15-17-36.tar.gz](https://github.com/user-attachments/files/16442333/bundle-2024-07-31-15-17-36.tar.gz)

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
Resource Modifier YAML file I used to create the StorageClass:
```yaml
version: v1
resourceModifierRules:
- conditions:
    groupResource: ingresses
    namespaces:
    - todo-app
  mergePatches:
  - patchData: |
      {
        "metadata": {
          "annotations": {
            "nginx.ingress.kubernetes.io/proxy-connect-timeout": null,
            "nginx.ingress.kubernetes.io/backend-protocol": null,
            "appgw.ingress.kubernetes.io/backend-protocol": "http",
            "appgw.ingress.kubernetes.io/request-timeout": "20"
          }
        },
        "spec": {
          "ingressClassName": "azure-application-gateway"
        }
      }
- conditions:
    groupResource: persistentvolumeclaims
    namespaces:
    - todo-app
    matches:
    - path: "/spec/storageClassName"
      value: "csi-hostpath-sc"
  mergePatches:
  - patchData: |
      {
        "spec": {
          "storageClassName": "managed-csi"
        }
      }
```
I checked the logs for this restore job, and I see only one entry for modifiers:
```
time="2024-07-31T13:16:20Z" level=info msg="Applying resource modifier patch on todo-app/mysql-pv-claim" logSource="internal/resourcemodifiers/resource_modifiers.go:103" restore=velero/restore-modifier-poc
```

**Environment:**

- Velero version (use `velero version`): `v1.14.0`
- Velero features (use `velero client config get features`): `features: EnableCSI`
- Kubernetes version (use `kubectl version`): `v1.29.6`
- Kubernetes installer & version:
- Cloud provider or hardware configuration: `Managed AKS cluster with Azure Application Gateway`
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
