### ISSUE TITLE
unable to locate ObjectStore plugin named velero.io/aws vmware-tanzu/velero:7.1.4 fresh install

### ISSUE THREAD

**Issue by AleksandrSor** [vmware-tanzu/velero#8101]
**What steps did you take and what happened:**

install velero crds
install velero via helm chart
```bash
velero install --crds-only
helm install velero vmware-tanzu/velero --version 7.1.4 -f values.yaml
velero server
```

values.yaml
```yaml
resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 4
    memory: 4Gi

nodeSelector:
  pacman/velero: ""

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.10.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

deployNodeAgent: true
nodeAgent:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 4
      memory: 4Gi
  tolerations:
    - effect: NoSchedule
      operator: Exists

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      default: true
      credential:
        name: velero-creds
        key: minio
      config:
        region: london
        insecureSkipTLSVerify: true
        s3ForcePathStyle: true
        s3Url: https://minio.minio-lon-infra.svc
    - name: bitbucket
      provider: aws
      bucket: bitbucket
      default: false
      credential:
        name: velero-creds
        key: minio
      config:
        region: london
        insecureSkipTLSVerify: true
        s3ForcePathStyle: true
        s3Url: https://minio.minio-lon-infra.svc
  volumeSnapshotLocation:
    - name: default
      provider: aws
      bucket: velero-snapshots
      default: true
      credential:
        name: velero-creds
        key: minio
      config:
        region: london
        insecureSkipTLSVerify: true
        s3ForcePathStyle: true
        s3Url: https://minio.minio-lon-infra.svc

credentials:
  useSecret: true
  name: velero-creds
  secretContents:
    minio: |
        aws_access_key_id=AccessKey
        aws_secret_access_key=SekretKey
```

**What did you expect to happen:**
velero server started up with no errors

**The following information will help us better understand what's going on**:

```log
INFO[0006] Starting workers                              controller=deletebackuprequest controllerGroup=velero.io controllerKind=DeleteBackupRequest logSource="/go/pkg/mod/github.com/bombsimon/logrusr/v3@v3.0.0/logrusr.go:108" worker count=1
ERRO[0006] Error getting backup store for this location  backupLocation=velero/default controller=backup-sync error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/backup_sync_controller.go:101"
ERRO[0006] Error getting a backup store                  backup-storage-location=velero/bitbucket controller=backup-storage-location error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/backup_storage_location_controller.go:137"
INFO[0006] BackupStorageLocation is invalid, marking as unavailable  backup-storage-location=velero/bitbucket controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:120"
ERRO[0006] Error getting backup store for this location  backupLocation=velero/bitbucket controller=backup-sync error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/backup_sync_controller.go:101"
ERRO[0007] Current BackupStorageLocations available/unavailable/unknown: 0/2/0, BackupStorageLocation "bitbucket" is unavailable: unable to locate ObjectStore plugin named velero.io/aws)  controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:178"
ERRO[0007] Error getting a backup store                  backup-storage-location=velero/default controller=backup-storage-location error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/backup_storage_location_controller.go:137"
INFO[0007] BackupStorageLocation is invalid, marking as unavailable  backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:120"
ERRO[0007] Current BackupStorageLocations available/unavailable/unknown: 0/2/0, BackupStorageLocation "default" is unavailable: unable to locate ObjectStore plugin named velero.io/aws)  controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:178"
ERRO[0066] Error getting backup store for this location  backupLocation=velero/default controller=backup-sync error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/backup_sync_controller.go:101"
ERRO[0066] Error getting backup store for this location  backupLocation=velero/bitbucket controller=backup-sync error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/backup_sync_controller.go:101"
ERRO[0076] Error getting a backup store                  backup-storage-location=velero/bitbucket controller=backup-storage-location error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/backup_storage_location_controller.go:137"
INFO[0076] BackupStorageLocation is invalid, marking as unavailable  backup-storage-location=velero/bitbucket controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:120"
```
[velero.server.log.gz](https://github.com/user-attachments/files/16563331/velero.server.log.gz)
[velero.log.gz](https://github.com/user-attachments/files/16563332/velero.log.gz)
[velero.init.log.gz](https://github.com/user-attachments/files/16563333/velero.init.log.gz)

```
kubectl get deployment/velero -n velero -o yaml
```
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    component: velero
    helm.sh/chart: velero-7.1.4
  name: velero
  namespace: velero
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/name: velero
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/secret: 5c9b777b9b522ad0f87f570b64abe645a1fd33b16ac6ad1eeeffbd579321082c
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: velero
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: velero
        helm.sh/chart: velero-7.1.4
        name: velero
    spec:
      containers:
      - args:
        - server
        - --uploader-type=kopia
        - --keep-latest-maintenance-jobs=3
        command:
        - /velero
        env:
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: LD_LIBRARY_PATH
          value: /plugins
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /credentials/cloud
        - name: AZURE_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: ALIBABA_CLOUD_CREDENTIALS_FILE
          value: /credentials/cloud
        image: velero/velero:v1.14.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /metrics
            port: http-monitoring
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: velero
        ports:
        - containerPort: 8085
          name: http-monitoring
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /metrics
            port: http-monitoring
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /plugins
          name: plugins
        - mountPath: /credentials
          name: cloud-credentials
        - mountPath: /scratch
          name: scratch
      dnsPolicy: ClusterFirst
      initContainers:
      - image: velero/velero-plugin-for-aws:v1.10.0
        imagePullPolicy: IfNotPresent
        name: velero-plugin-for-aws
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /target
          name: plugins
      nodeSelector:
        pacman/velero: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: velero-server
      serviceAccountName: velero-server
      terminationGracePeriodSeconds: 3600
      volumes:
      - name: cloud-credentials
        secret:
          defaultMode: 420
          secretName: velero-creds
      - emptyDir: {}
        name: plugins
      - emptyDir: {}
        name: scratch
```

**Environment:**

- Velero version (use `velero version`): 
```
Client:
        Version: v1.14.0
        Git commit: 2fc6300f2239f250b40b0488c35feae59520f2d3
Server:
        Version: v1.14.0
```
- Velero features (use `velero client config get features`): 
```
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.5
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):|
```
# uname -r
5.14.0-452.el9.x86_64
# cat /etc/os-release
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://issues.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
I checked the logs, it seemed you installed velero twice. 
In `velero.log.gz` the aws plugin was registered, because I can see it registered in the log
```
time="2024-08-09T14:14:01Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/aws
time="2024-08-09T14:14:01Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=ObjectStore logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/aws
```
the error seemed due to network issue:
```
time="2024-08-09T14:14:11Z" level=error msg="Error getting backup store for this location" backupLocation=velero/bitbucket controller=backup-sync error="rpc error: code = Unknown desc = failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get \"http://169.254.169.254/latest/meta-data/iam/security-credentials/\": dial tcp 169.254.169.254:80: i/o timeout" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:166" 
```

In `velero.server.log.gz`, there seemed to be some installation issue b/c I cannot find the aws plugin registered, therefore the error `unable to locate ObjectStore plugin named velero.io/aws` is expected. 
Did you modified anything between the installations in `velero.log.gz` and `velero.server.log.gz`?

**Comment by AleksandrSor** [comment]
> 
> the error seemed due to network issue:
> 
> ```
> time="2024-08-09T14:14:11Z" level=error msg="Error getting backup store for this location" backupLocation=velero/bitbucket controller=backup-sync error="rpc error: code = Unknown desc = failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get \"http://169.254.169.254/latest/meta-data/iam/security-credentials/\": dial tcp 169.254.169.254:80: i/o timeout" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:166" 
> ```

I have no idea to where it tried to connect -> http://169.254.169.254

> 
> In `velero.server.log.gz`, there seemed to be some installation issue b/c I cannot find the aws plugin registered, therefore the error `unable to locate ObjectStore plugin named velero.io/aws` is expected. Did you modified anything between the installations in `velero.log.gz` and `velero.server.log.gz`?

velero pod constantly restarting due to this error  so I am not sure

**Comment by AleksandrSor** [comment]
probably I misunderstand a situation
so the error **unable to locate ObjectStore** I am gerring when I execute velero server in shell
Nothere in a velero pod I have not seen this error

**Comment by AleksandrSor** [comment]
> the error seemed due to network issue:
> 
> ```
> time="2024-08-09T14:14:11Z" level=error msg="Error getting backup store for this location" backupLocation=velero/bitbucket controller=backup-sync error="rpc error: code = Unknown desc = failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get \"http://169.254.169.254/latest/meta-data/iam/security-credentials/\": dial tcp 169.254.169.254:80: i/o timeout" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:166" 
> ```

I found out that is was connected to misconfiguration around secret credentials and config
1. I should not change "file" in secret it shoud stay as "cloud" due to environment variables which point to /credentials/cloud
2. content was not ok also, I missed the key
```ini
[default]
```

You can close the issue, thanks for the help

**Comment by AleksandrSor** [comment]
so correct values is
```yaml
resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 4
    memory: 4Gi
nodeSelector:
  pacman/velero: ""
deployNodeAgent: true
initContainers:
  ## https://github.com/topics/velero-plugin
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.10.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
nodeAgent:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 4
      memory: 4Gi
  tolerations:
    - effect: NoSchedule
      operator: Exists
configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      default: true
      config:
        region: london
        insecureSkipTLSVerify: true
        s3ForcePathStyle: true
        s3Url: https://minio.minio-lon-infra.svc
    - name: bitbucket
      provider: aws
      bucket: bitbucket
      default: false
      config:
        region: london
        insecureSkipTLSVerify: true
        s3ForcePathStyle: true
        s3Url: https://minio.minio-lon-infra.svc
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: london
        insecureSkipTLSVerify: true
        s3ForcePathStyle: true
        s3Url: https://minio.minio-lon-infra.svc
credentials:
  useSecret: true
  secretContents:
    cloud: |
        [default]
        aws_access_key_id=access_key
        aws_secret_access_key=secret_access_key
```
