### ISSUE TITLE
"Timeout happened for preparing dataupload" during "CSI Snapshot Data Movement" to MinIO S3

### ISSUE THREAD

**Issue by Zalfsten** [vmware-tanzu/velero#8113]
**What steps did you take and what happened:**

I'm trying to create a backup from a sample nginx deployment (including a PVC) in the namespace `default`.
These are my steps:

```bash
$ velero backup create test5 --include-namespaces=default --snapshot-volumes
Backup request "test5" submitted successfully.
Run `velero backup describe test5` or `velero backup logs test5` for more details.

$ velero backup describe test5
Name:         test5
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.28.6
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=28

Phase:  WaitingForPluginOperations


Namespaces:
  Included:  default
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true
Snapshot Move Data:          true
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2024-08-13 13:10:06 +0000 UTC
Completed:  <n/a>

Expiration:  2024-09-12 13:10:06 +0000 UTC

Total items to be backed up:  17
Items backed up:              17

Backup Item Operations:  0 of 1 completed successfully, 0 failed (specify --details for more information)
Backup Volumes:
  Velero-Native Snapshots: <none included>

  CSI Snapshots:
    default/pvc-test-iscsi:
      Data Movement: included, specify --details for more information

  Pod Volume Backups: <none included>

HooksAttempted:  0
HooksFailed:     0
```

then, after half an hour:

```bash
$ velero backup describe test5
Name:         test5
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.28.6
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=28

Phase:  PartiallyFailed (run `velero backup logs test5` for more information)


Errors:
  Velero:     <none>
  Cluster:    <none>
  Namespaces: <none>

Namespaces:
  Included:  default
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true
Snapshot Move Data:          true
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2024-08-13 13:10:06 +0000 UTC
Completed:  2024-08-13 13:40:35 +0000 UTC

Expiration:  2024-09-12 13:10:06 +0000 UTC

Total items to be backed up:  17
Items backed up:              17

Backup Item Operations:  0 of 1 completed successfully, 1 failed (specify --details for more information)
Backup Volumes:
  Velero-Native Snapshots: <none included>

  CSI Snapshots:
    default/pvc-test-iscsi:
      Data Movement: included, specify --details for more information

  Pod Volume Backups: <none included>

HooksAttempted:  0
HooksFailed:     0
```

In the node agent log, I observe the following error message:

```text
time="2024-08-13T13:40:33Z" level=info msg="Timeout happened for preparing dataupload" Dataupload=test5-8klq9 logSource="pkg/controller/data_upload_controller.go:741"
```

**What did you expect to happen:**

I expected to see a big file in my S3 storage, containing the backup of the persistent volume (though I do not know what exactly to look out for).

**The following information will help us better understand what's going on**:

[bundle-2024-08-13-15-53-39.tar.gz](https://github.com/user-attachments/files/16602317/bundle-2024-08-13-15-53-39.tar.gz)

**Anything else you would like to add:**

I'm unsure if I need to add a VolumeSnapshotLocation (using the provider `csi`). But if I do, I run into another error about velero not finding a matching VolumeSnapshotter.

I've installed the velero server using the [helm chart](https://vmware-tanzu.github.io/helm-charts/) version 7.1.2. This is my value file:

```yaml
velero:
  image:
    repository: velero/velero
    tag: v1.13.2
    pullPolicy: IfNotPresent

  initContainers:
    - name: velero-plugin-for-csi
      image: velero/velero-plugin-for-csi:v0.7.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.10.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins

  cleanUpCRDs: false
  deployNodeAgent: true

  configuration:
    features: EnableCSI
    defaultSnapshotMoveData: true
    uploaderType: kopia
    backupStorageLocation:
      - provider: aws
        bucket: velero
        config:
          region: minio
          s3ForcePathStyle: "true"
          s3Url: <S3 URL>
  credentials:
    useSecret: true
    existingSecret: velero-secret
```

 I suppose the VolumeSnapshotClass is also of interest:

```yaml
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: truenas-snapshot
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: csi.hpe.com
parameters:
  description: "Snapshot created on TrueNAS"
  csi.storage.k8s.io/snapshotter-secret-name: truenas-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: kube-system
deletionPolicy: Delete
```

**Environment:**

- Velero version (use `velero version`):

  ```bash
  Client:
          Version: v1.13.2
          Git commit: 4d961fb6fec384ed7f3c1b7c65c818106107f5a6
  Server:
          Version: v1.13.2
  ```

  (I've tried v1.14.0 before, but also without success)

- Velero features (use `velero client config get features`):

  ```bash
  features: <NOT SET>
  ```

- Kubernetes version (use `kubectl version`):

  ```bash
  Client Version: v1.29.1
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.28.6
  ```
  on-premise
- Kubernetes installer & version: 
  kubespray 2.24.0
- Cloud provider or hardware configuration:
  2-node cluster on VMware, 4 CPUs and 8GB RAM per node.
- OS (e.g. from `/etc/os-release`):

  ```bash
  NAME="AlmaLinux"
  VERSION="9.4 (Seafoam Ocelot)"
  ID="almalinux"
  ID_LIKE="rhel centos fedora"
  VERSION_ID="9.4"
  PLATFORM_ID="platform:el9"
  PRETTY_NAME="AlmaLinux 9.4 (Seafoam Ocelot)"
  ANSI_COLOR="0;34"
  LOGO="fedora-logo-icon"
  CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
  HOME_URL="https://almalinux.org/"
  DOCUMENTATION_URL="https://wiki.almalinux.org/"
  BUG_REPORT_URL="https://bugs.almalinux.org/"

  ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
  ALMALINUX_MANTISBT_PROJECT_VERSION="9.4"
  REDHAT_SUPPORT_PRODUCT="AlmaLinux"
  REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
  SUPPORT_END=2032-06-01
  ```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
