### ISSUE TITLE
resourceModifierRules is not working for me during restore process

### ISSUE THREAD

**Issue by mohapma** [vmware-tanzu/velero#8147]
Below is my rule:-
``` yaml
resourceModifierRules.yml: |
    version: v1
    resourceModifierRules:
    - conditions:
        groupResource: Ingresses
        resourceNameRegex: ".*"
      patches:
      - operation: replace
        path: "/spec/rules/0/host"
        value: "pit-tenant1.test.com"
      - operation: replace
        path: "/spec/tls/0/hosts/0"
        value: "pit-tenant1.test.com"
```

```
velero restore create sso-restore-ingress --include-namespaces sso,cattle-system --include-resources Ingresses --from-backup pit-lab2-full-app --resource-modifier-configmap resource-modifier-config
Restore request "sso-restore-ingress" submitted successfully.
Run `velero restore describe sso-restore-ingress` or `velero restore logs sso-restore-ingress` for more details.
```

Issue:- after successful restoration ingress.yaml file have old hostname, it is not replacing.
