### ISSUE TITLE
Post hook command is executed before the Kopia snapshot is completed

### ISSUE THREAD

**Issue by QuentinBtd** [vmware-tanzu/velero#8159]
**What steps did you take and what happened:**

I am using Velero to back up a PostgreSQL dump created by a pre-hook command, so that Kopia can backup the dump, then delete the file using a post-hook command. However, I noticed that the post-hook was executed before Kopia had the chance to back up the dump.

I conducted several tests:
- The first one involved adding a `sleep 60` at the beginning of my post-hook command-> the dump was successfully included in the Kopia snapshot.

- The second test involved creating a file after the dump was completed, which I used in my post-hook command to wait for the file to be fully generated before deleting the dump -> the dump was not included in the Kopia snapshot.

**What did you expect to happen:**

Dump file should be in Kopia snapshot

**Anything else you would like to add:**

```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: my-app-pg-app
  namespace: velero
spec:
  schedule: "0 4 * * *"
  useOwnerReferencesInBackup: false
  template:
    includedNamespaces:
      - my-app
    labelSelector:
      matchLabels:
        cnpg.io/cluster: pg-app-16
    metadata: {}
    ttl: 720h
    hooks:
      resources:
        - name: dump
          pre:
            - exec:
                container: postgres
                command:
                  - /bin/bash
                  - -c
                  - |
                    set -e
                    echo "/pgdata/*" > /var/lib/postgresql/data/.kopiaignore &&
                    pg_dump -d app -f /var/lib/postgresql/data/dump_app-$(hostname)-$(date '+%Y-%m-%d-%H-%M-%S')
                onError: Fail
                timeout: 5m
          post:
            - exec:
                container: postgres
                command:
                  - /bin/bash
                  - -c
                  - |
                    rm -f /var/lib/postgresql/data/dump_app-$(hostname)-*
                onError: Fail

```

**Environment:**

- Velero version (use `velero version`):  1.14.0
- Velero features (use `velero client config get features`):  None
- Kubernetes version (use `kubectl version`): 1.30
- Kubernetes installer & version: -
- Cloud provider or hardware configuration: AWS - EKS v1.30.2-eks-db838b0
- OS (e.g. from `/etc/os-release`): Amazon Linux 2023

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
