### ISSUE TITLE
Velero doesn't create backups in S3 AWS EKS after v1.14.0 release

### ISSUE THREAD

**Issue by G0g0lush** [vmware-tanzu/velero#8189]
**What steps did you take and what happened:**
Starting from 18 June our Velero backups failed to create backups for our clusters, failing one by one
On 2 July we upgraded from version 1.13(chart 6.0.0) to version 1.14(chart 7.1.0)
velero-plugin-for-aws version is the latest (currently 1.10.1 which should be compatible with our Velero version)
We didin't use CSI plugin

**The following information will help us better understand what's going on**:
Logs:

`time="2024-09-05T11:00:59Z" level=error msg="Error listing backups in backup store" backupLocation=velero/eks-production-us-east-2 controller=backup-sync error="rpc error: code = Unknown desc = operation error S3: ListObjectsV2, https response error StatusCode: 403, RequestID: 4VP5XQYAk9QFDA2BN2E24, HostID: BnUdj+bkpema0z6wcJZ7K3oJ9GqcQ9hZGKm7A1rydo3nw1aoCHKeHzW3ugbu+sd=, api error InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records." error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:351" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:108"`

`time="2024-09-05T11:00:59Z" level=info msg="plugin process exited" backupLocation=velero/eks-production-us-east-2 cmd=/plugins/velero-plugin-for-aws controller=backup-sync id=2541238 logSource="pkg/plugin/clientmgmt/process/logrus_adapter.go:80" plugin=/plugins/velero-plugin-for-aws`

Values.yaml info that I think will be useful:
```
image:
  repository: dockerhub/velero/velero
  pullPolicy: IfNotPresent
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
configuration:
  backupStorageLocation:
  - name: default
    provider: aws
    bucket: ${BUCKET}
    prefix: ${CLUSTER_NAME}
    config:
      region: ${BUCKET_REGION}
  volumeSnapshotLocation:
  - name: default
    provider: aws
    config:
      region: ${REGION}
serviceAccount:
  server:
    create: true
    name: ${VELERO_SERVICE_ACCOUNT}
    annotations:
      eks.amazonaws.com/role-arn: ${VELERO_ROLE_ARN}
credentials:
  useSecret: true
  name: ""
  secretContents:
   cloud: |
    [default]
    aws_access_key_id=iamnotvalid
    aws_secret_access_key=iamnotvalid
```

Of course, the variables are properly configured.

**Anything else you would like to add:**

We are using AWS EKS
We are not using Access key and Secret Access Key since we use a serviceAccount that has a IAM role which has all the necesarry permissions for S3 and EC2 VolumeSnapshots
Policies are correct
Secret exists and has the  **iamnotvalid** value you can see in values.yaml
BSL exists, has the correct region, bucket, prefix, provider, annotations, labels. Has the error **The AWS Access Key Id you provided does not exist in our records** provided in the logs section.
I've recreated secrets and bsl.
I've manually uninstalled and installed the aws-plugin.
I've attached an aws-cli container to our Velero pod and checked if the S3 bucket is reachable and can be interacted with and it was working as expected.

**Environment:**

- Velero version: 
Client:
	Version: v1.14.1
Server:
	Version: v1.14.0

- Velero features:  features: NOT SET

-Kubernetes:
Client Version: v1.30.2
Server Version: v1.30.3-eks-2f46c53

- Cloud provider or hardware configuration: AWS EKS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
