### ISSUE TITLE
Velero deployed by Helm on AWS EKS schedule backup failed

### ISSUE THREAD

**Issue by thanhdanh2020** [vmware-tanzu/velero#8195]
**What steps did you take and what happened:**

I deployed Velero with Helm on AWS EKS cluster with a schedule backup configuration defined in custom `values.yaml`
Then I create a manual backup with `--from-schedule` to check the backup status.
The manual backup `PartiallyFailed` with following error: `"found '<', expected: !, identifier, or 'end of string'"`

**What did you expect to happen:**
The manual backup created from schedule will have `Completed` status with no errors
**The following information will help us better understand what's going on**:
The manual backup errors with all resources, except namespaces.
One of error log while listing `persistentvolumeclaims` on namespace `my-namespace-1`:
`
time="2024-09-09T03:32:14Z" level=info msg="Getting items for resource" backup=velero/velero-daily-backup-20240909033137 group=v1 logSource="pkg/backup/item_collector.go:349" resource=persistentvolumeclaims
time="2024-09-09T03:32:14Z" level=info msg="Listing items" backup=velero/velero-daily-backup-20240909033137 group=v1 logSource="pkg/backup/item_collector.go:522" namespace=my-namespace-1 resource=persistentvolumeclaims
time="2024-09-09T03:32:14Z" level=error msg="Error listing resources" backup=velero/velero-daily-backup-20240909033137 error="found '<', expected: !, identifier, or 'end of string'" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_collector.go:675" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*itemCollector).processPagerClientCalls" logSource="pkg/backup/item_collector.go:675"
time="2024-09-09T03:32:14Z" level=error msg="Error listing items" backup=velero/velero-daily-backup-20240909033137 error="found '<', expected: !, identifier, or 'end of string'" group=v1 logSource="pkg/backup/item_collector.go:553" namespace=my-namespace-1 resource=persistentvolumeclaims
`

My `schedules`config in `values.yaml`:
```yaml
schedules:
  daily-backup:
    disabled: false
    schedule: "0 0 * * *"
    template:
      ttl: "240h"
      storageLocation: default
      volumeSnapshotLocations:
      - default
      includedNamespaces:
      - my-namespace-1
      - my-namespace-2
      # excludedNamespaces:
      # - kube-system
      # - velero
      # includeClusterResources: true
      includedResources:
      - "*"
      excludedResources:
      - events
      - events.events.k8s.io
      - pods
      - replicasets.apps
      - jobs
      labelSelector: {}
      snapshotVolumes: false
      hooks: {}  
```
But when I create a full backup, it works fine.

**Environment:**

- Velero version : 
Client: v1.14.1, Git commit: 8afe3cea8b7058f7baaf447b9fb407312c40d2da
Server: v1.14.1
- Velero features : NOT SET
- Kubernetes version :
Client: v1.29.3
Server: v1.29.7-eks-2f46c53
- Cloud provider or hardware configuration: AWS EKS
