### ISSUE TITLE
`No volume ID returned by volume snapshotter for persistent volume` on specific volume

### ISSUE THREAD

**Issue by hydazz** [vmware-tanzu/velero#8196]
**What steps did you take and what happened:**
Creating a backup of portainer yields `No volume ID returned by volume snapshotter for persistent volume`, but all other volumes backup fine without errors, even though they are configured (to my knowledge) the exact same, I'm a rookie at kubernetes, so don't really know how to diagnose, ive compared the output of the pv, pvc and pods and can't see anything standing out as to why its just portainer failing

**What did you expect to happen:**
Portainers volume to backup without errors

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

here are 2 debug archives, both created with `velero backup create <name> --snapshot-volumes=true --include-namespaces <media-managers/portainer>`, media-mangers backs up without issues, portainer spits out the no volume id error
[portainer.tar.gz](https://github.com/user-attachments/files/16927237/portainer.tar.gz)
[working.tar.gz](https://github.com/user-attachments/files/16927239/working.tar.gz)

**Anything else you would like to add:**

The environment is deployed via flux, so all velero/portainer configurations are here:
https://github.com/hydazz/k3s-homelab

[Velero Helm Config](https://github.com/hydazz/k3s-homelab/blob/main/cluster/homelab/core/velero/helm-release.yaml)

[Portainer Config](https://github.com/hydazz/k3s-homelab/tree/main/cluster/homelab/apps/portainer)

No customisations have been made to the system outside of flux handing it

**Environment:**
- Velero version (use `velero version`): v1.14.1
- Velero features (use `velero client config get features`): features: \<NOT SET\>
- Kubernetes version (use `kubectl version`): v1.31.0
- Kubernetes installer & version: v1.30.4+k3s1
- Cloud provider or hardware configuration: 3x node proxmox vm's
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 12 (bookworm)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
You're trying to backup the volumes with native snapshot which needs the corresponding snapshot plugin for portainer volumes, I'm not sure whether there is one in the community (I'm not familar with portainer).

You could try the file system backup instead: https://velero.io/docs/v1.14/file-system-backup/

**Comment by hydazz** [comment]
Sorry if this is a dumb question, but why is it using native snapshot, it should be using filesytem backup, as the rest of the volume are, following that link, I had already tried annotating the pod, and its still using native snapshotter:
```
kubectl describe pod portainer-55f8868d5b-pc4np -n portainer
Name:             portainer-55f8868d5b-pc4np
Namespace:        portainer
Priority:         0
Service Account:  portainer-sa-clusteradmin
Node:             k3s-discovery/192.168.4.3
Start Time:       Mon, 09 Sep 2024 17:31:19 +1000
Labels:           app.kubernetes.io/instance=portainer
                  app.kubernetes.io/name=portainer
                  pod-template-hash=55f8868d5b
Annotations:      backup.velero.io/backup-volumes: portainer
                  cni.projectcalico.org/containerID: 828a816f1e58d6d10a508e73674032f2362bce77a8317cfd88edc324a45d1c9a
                  cni.projectcalico.org/podIP: 172.16.239.68/32
                  cni.projectcalico.org/podIPs: 172.16.239.68/32
Status:           Running
IP:               172.16.239.68
```

**Comment by ywk253100** [comment]
Use `--default-volumes-to-fs-backup` rather than `--snapshot-volumes` if you want to use file system backup

**Comment by hydazz** [comment]
apologies for the PEBKAC, it was caused by annotating the wrong volume name, it was actually called data 🫤 
`backup.velero.io/backup-volumes: portainer`

```yaml
kubectl describe deployment portainer -n portainer
Name:               portainer
Namespace:          portainer
CreationTimestamp:  Mon, 09 Sep 2024 14:03:18 +1000
Labels:             app.kubernetes.io/instance=portainer
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=portainer
                    app.kubernetes.io/version=ce-latest-ee-2.21.1
                    helm.sh/chart=portainer-1.0.53
                    helm.toolkit.fluxcd.io/name=portainer
                    helm.toolkit.fluxcd.io/namespace=portainer
                    io.portainer.kubernetes.application.stack=portainer
Annotations:        deployment.kubernetes.io/revision: 3
                    meta.helm.sh/release-name: portainer
                    meta.helm.sh/release-namespace: portainer
Selector:           app.kubernetes.io/instance=portainer,app.kubernetes.io/name=portainer
Replicas:           1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:           app.kubernetes.io/instance=portainer
                    app.kubernetes.io/name=portainer
  Annotations:      backup.velero.io/backup-volumes: portainer
  Service Account:  portainer-sa-clusteradmin
  Containers:
   portainer:
    Image:       portainer/portainer-ce:2.21.1
    Ports:       9443/TCP, 8000/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      --http-disabled
    Liveness:     http-get https://:9443/ delay=45s timeout=1s period=30s #success=1 #failure=5
    Readiness:    http-get https://:9443/ delay=45s timeout=1s period=30s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /data from data (rw)
  Volumes:
   data: # < idiot :(
    Type:          PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:     portainer
    ReadOnly:      false
  Node-Selectors:  <none>
  Tolerations:     <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  portainer-577f5554d9 (0/0 replicas created), portainer-55f8868d5b (0/0 replicas created)
NewReplicaSet:   portainer-6684fb8b9f (1/1 replicas created)
Events:          <none>
```
