### ISSUE TITLE
Add possibility to backup resources in namespaces matching a label

### ISSUE THREAD

**Issue by lorenzofelletti** [vmware-tanzu/velero#8340]
**Describe the problem/challenge you have**
On thing I need to do is to backup all resources in namespaces matching a certain label, e.g. all the namespaces having label `backup: true`, or something like that.

**Describe the solution you'd like**
New version of Schedule/Backup spec supporting this option. Something like:
```yaml
apiVersion: velero.io/v2alpha1
kind: Backup
metadata:
  name: a
  namespace: velero
spec:
  namespaceSelector:
    matchLabels:
      backup: "true"
```

Changing the `BackupSpec` type to something like:
```golang
type BackupSpec struct {
    // ...
    NamespaceSelector *metav1.LabelSelector `json:"namespaceSelector,omitempty"`
    // ...
}
```

**Anything else you would like to add:**

**Environment:**

- Velero version (use `v1.14.0`):
- Kubernetes version (use `v1.30.2`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"
