### ISSUE TITLE
Issue with PVC data snapshotting 

### ISSUE THREAD

**Issue by stiliajohny** [vmware-tanzu/velero#8341]
**What steps did you take and what happened:**

Install velero on my Tanzu cluster with: 
```bash 
velero install \
--provider aws \
--plugins velero/velero-plugin-for-aws:v1.8.0 \
--bucket velero-js-test-tanzu-test \
--secret-file ./cloud_credentials \
--use-volume-snapshots=true \
--features=EnableCSI --use-node-agent \
--features=EnableVSphereItemActionPlugin \
--snapshot-location-config region=eu-west-1 \
--backup-location-config region=eu-west-1
```

Then I did 
```bash 
velero backup create backup1 --include-namespaces default  --wait --snapshot-move-data
```

That created a backup on my AWS S3, however the actual PVC data was not backup

I can see that though the log
```bash
velero backup describe backup1
Name:         backup1
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.26.5+vmware.2-fips.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=26

Phase:  Completed


Warnings:
  Velero:     <none>
  Cluster:   resource: /persistentvolumes name: /pvc-8d000c5a-ae2f-4386-b516-16bff360815d message: /VolumeSnapshotter plugin doesn't support data movement.
             resource: /persistentvolumes name: /pvc-8d000c5a-ae2f-4386-b516-16bff360815d message: /No volume ID returned by volume snapshotter for persistent volume
  Namespaces: <none>

Namespaces:
  Included:  default
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto
Snapshot Move Data:          true
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2024-10-23 14:43:10 +0100 BST
Completed:  2024-10-23 14:43:12 +0100 BST

Expiration:  2024-11-22 13:43:10 +0000 GMT

Total items to be backed up:  34
Items backed up:              34

Backup Volumes:
  Velero-Native Snapshots: <none included>

  CSI Snapshots: <none included>

  Pod Volume Backups: <none included>

HooksAttempted:  0
HooksFailed:     0    
```

In my cluster I have installed the volumeStorageClass
```bash
 k get crds | grep -i volumesnapshot                  
volumesnapshotclasses.snapshot.storage.k8s.io           2024-10-17T20:12:50Z
volumesnapshotlocations.velero.io                       2024-10-23T13:42:16Z  
```

My apologies for the ignorance but I am not sure what I am missing and what I need to install 

**What did you expect to happen:**

- No error on backup 
- PVC data backup 

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  1.14.1
- Velero features (use `velero client config get features`): features: <NOT SET>    
- Kubernetes version (use `kubectl version`): Client Version: v1.29.4 S
- Kubernetes installer & version: erver Version: v1.26.5+vmware.2-fips.1
- Cloud provider or hardware configuration: Tanzu and AWS S3 
- OS (e.g. from `/etc/os-release`):MacOS 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
[bundle-2024-10-23-15-20-04.tar.gz](https://github.com/user-attachments/files/17495686/bundle-2024-10-23-15-20-04.tar.gz)

**Comment by msfrucht** [comment]
Feature CSI was not enabled.

`time="2024-10-23T13:43:11Z" level=info msg="Skip action velero.io/csi-pvc-backupper for resource persistentvolumeclaims:default/nginx-pvc, because the CSI feature is not enabled. Feature setting is EnableVSphereItemActionPlugin." backup=velero/backup1 logSource="pkg/backup/item_backupper.go:374" name=nginx-pvc namespace=default resource=persistentvolumeclaims

Adding more than one feature option causes only the last to be consumed. Please change it to a command separated list.

` --features string                            Comma separated list of Velero feature flags to be set on the Velero deployment and the node-agent daemonset, if node-agent is enabled`

`--features=EnableCSI,EnableVSphereItemActionPlugin`

Or edit the Velero Deployment args to:

`- '--features=EnableVSphereItemActionPlugin'`

to

`- '--features=EnableCSI,EnableVSphereItemActionPlugin'`

**Comment by stiliajohny** [comment]
@msfrucht  that was very helpful 

I manage to move it a lot further, but I hit a wall again, I would appreciate any input :) 

Now I get 
```log
Errors:
  Velero:    name: /nginx-deployment-7d764bbb8b-9495p message: /Error backing up item error: /error executing custom action (groupResource=persistentvolumeclaims, namespace=default, name=nginx-pvc): rpc error: code = Unknown desc = failed to get VolumeSnapshotClass for StorageClass tanzu-dev: error getting VolumeSnapshotClass: failed to get VolumeSnapshotClass for provisioner csi.vsphere.vmware.com,
            ensure that the desired VolumeSnapshot class has the velero.io/csi-volumesnapshot-class label

```

Looking on my CRD 
```
 k get crd  | grep volume                             (aws-setup|✔)
podvolumebackups.velero.io                              2024-10-24T06:38:18Z
podvolumerestores.velero.io                             2024-10-24T06:38:18Z
volumesnapshotclasses.snapshot.storage.k8s.io           2024-10-17T20:12:50Z
volumesnapshotlocations.velero.io                       2024-10-24T06:38:18Z 
```


I did previously install the 

```bash 
kubectl apply  -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/refs/tags/v8.1.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
```

To remediate the new error, I installed ( matching my StorageClass details )
```yaml 
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
    name: tanzu-dev-snapshot
    labels:
        velero.io/csi-volumesnapshot-class: "true"  # If using Velero
driver: csi.vsphere.vmware.com
deletionPolicy: Delete
parameters:
    svStorageClass: tanzu-dev
```

Now I get 
```
Errors:
  Velero:    name: /nginx-deployment-7d764bbb8b-9495p message: /Error backing up item error: /error executing custom action (groupResource=persistentvolumeclaims, namespace=default, name=nginx-pvc): rpc error: code = Unknown desc = error creating volume snapshot: no matches for kind "VolumeSnapshot" in version "snapshot.storage.k8s.io/v1"
```

Then I went and installed 
```
k apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/refs/tags/v8.1.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
```

Now the backup is starting but it stays in progress for ever :(

**Comment by stiliajohny** [comment]
[UPDATE]

I install the CRDs (snapshot.storage.k8s.io_*) from 
https://github.com/kubernetes-csi/external-snapshotter/tree/v8.1.0/client/config/crd

Backup was redone and now it was completed 

I am going to verify PVC data was copied

**Comment by stiliajohny** [comment]
that might be related to #7991

**Comment by msfrucht** [comment]
A new bundle from one of the backups would be helpful. Though it is likely the issue is in the CSI stack or driver not the backup.

The error message implies the VolumeSnapshot was never reported successful via the CSI driver and the --csi-snapshot-timeout was triggered. Default 10 minutes. "context deadline exceeded" means a timeout occurred. 

Set during velero backup create and Backup objects. https://velero.io/docs/main/examples/ 

Most storage systems only need a few seconds to do snapshots.

**Comment by msfrucht** [comment]
@stiliajohny The way to test if the issue is Velero backup or CSI stack / CSI driver is to create a VolumeSnapshot manually.

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: vsphere-snapshot-test
  namespace: <namespace of PVC>
spec:
  volumeSnapshotClassName: <volumesnapshotclass name>
  source:
    persistentVolumeClaimName: <pvc name>
```

Then run kubectl apply -f <snapshot-file.yaml\>

If the snapshot resolves to success status.readToUse will become True.

if snapshot resolves to status.error occurs and doesn't change (VolumeSnapshots periodically retry so some CSI drivers unintendedly report transitory issues) it failed. status.error.message should be set, but the usefulness varies by individual issue and driver. I've seen CSI drivers accidently stick entire stack info as the error message.

**Comment by stiliajohny** [comment]
@msfrucht  New bundle 
[bundle-2024-10-24-20-27-18.tar.gz](https://github.com/user-attachments/files/17511842/bundle-2024-10-24-20-27-18.tar.gz)


And I am going to try applying the VolumeSnapshot and retry the backup 
However i have a VolumeSnapshot in the `default` ns 

Here is how it looks 
```yaml 
Name:         velero-nginx-pvc-sm2wm
Namespace:    default
Labels:       velero.io/backup-name=backup2
              velero.io/restore-name=my-backup-nginx2-20241017172815
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2024-10-24T07:12:38Z
  Generate Name:       velero-nginx-pvc-
  Generation:          1
  Resource Version:    198637459
  UID:                 3e62fdce-f8ad-461e-83e5-696f9485baee
Spec:
  Source:
    Persistent Volume Claim Name:  nginx-pvc
  Volume Snapshot Class Name:      ttc-tanzu-dev-snapshot
Events:                            <none>   
```
