### ISSUE TITLE
Allow overriding namespace from values.yaml

### ISSUE THREAD

**Issue by monwolf** [vmware-tanzu/velero#8387]
I have a unique helm chart for managing all the stuff in my eks cluster. We have some sub-charts, such as Prometheus, that allow overriding the namespace. This is a useful feature because, with one chart, you can have multiple applications isolated in different namespaces.

They implemented this using a macro:

```
  namespace: {{ include "prometheus.namespace" . }}
```

```
{{/*
Define the prometheus.namespace template if set with forceNamespace or .Release.Namespace is set
*/}}
{{- define "prometheus.namespace" -}}
  {{- default .Release.Namespace .Values.forceNamespace -}}
{{- end }}
```

Could you add something like this to your chart?

**Comment by blackpiglet** [comment]
@jenting Please help take a look.

**Comment by monwolf** [comment]
Nope, I don't. 

I have this chart definition:
```
apiVersion: v2
name: my-eks-appliers
description: A Helm chart for Kubernetes
type: application
version: 1.28.6
appVersion: "1.28.6"
dependencies:
  - name: my-basic-config
    repository: s3://my-helm3-appliers-repo/charts/
    version: 0.2.1
    condition: my-basic-config.enabled
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts 
    version: 23.0.0 # 25.22.1 (23.0.0 es la compatible con la versión alojada en ECR)
    condition: prometheus.enabled
  - name: velero
    repository: https://vmware-tanzu.github.io/helm-charts
    version: 7.1.0
    condition: velero.enabled
```

And In the values.yaml I would like to do:


```
my-basic-config
  enabled: true
  forceNamespace:  kube-system
  .....
prometheus:
  enabled: true
  forceNamespace:  monitoring
  ....

velero:
  enabled: true
  forceNamespace: velero
  ....
```

And then apply it by using  
```
helm install my-appliers ..... -n whatever  
```

And each subchart stay in its namespace.
