### ISSUE TITLE
Issue with Velero Restore : Azure disk PV Created with Old SKU Despite Updated Storage Class

### ISSUE THREAD

**Issue by ankitsharma1133** [vmware-tanzu/velero#8401]
**What steps did you take and what happened:**

I am trying to change to storage class of azure disk from LRS to ZRS or from storage to another using   name: change-storage-class-config option in velero 

I am trying to change the storage class from the default Storage class i.e SKU StandardSSD_LRS to azuredisk-standard-ssd-zrs i.e SKU StandardSSD_ZRS 

**What did you expect to happen:**

After applying the change-storage-class-config and after restoring the velero backup . The application is UP and new PV, PVC are created and data persist in the new PV. 
The Storage is updated in the PVC based on Velero configmap but the SKU of PV is still same after the OLD PV before restore 

Below is my configmap and PV yaml after Velero restoration 

apiVersion: v1
data:
  default: azuredisk-standard-ssd-zrs
kind: ConfigMap
metadata:
  labels:
    velero.io/change-storage-class: RestoreItemAction
    velero.io/plugin-config: ""
  name: change-storage-class-config
  namespace: velero

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-###############
  labels:
    velero.io/backup-name: test-nginx-12
    velero.io/restore-name: restore12
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
    volume.kubernetes.io/provisioner-deletion-secret-name: ''
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ''
  finalizers:
    - external-provisioner.volume.kubernetes.io/finalizer
    - kubernetes.io/pv-protection
    - external-attacher/disk-csi-azure-com
spec:
  capacity:
    storage: 10Gi
  csi:
    driver: disk.csi.azure.com
    volumeHandle: >-
      /subscriptions/##########/providers/Microsoft.Compute/disks/restore-##################
    volumeAttributes:
      csi.storage.k8s.io/pv/name: pvc-#############
      csi.storage.k8s.io/pvc/name: PVC-nginx
      csi.storage.k8s.io/pvc/namespace: test-nginx-2
      requestedsizegib: '10'
      **skuname: StandardSSD_LRS**
      storage.kubernetes.io/csiProvisionerIdentity: ############-disk.csi.azure.com
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: test-nginx-2
    name: pvc-nginx
  persistentVolumeReclaimPolicy: Delete
  **storageClassName: azuredisk-standard-ssd-zrs**
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.disk.csi.azure.com/zone
              operator: In
              values:
                - westeurope-1

**The following information will help us better understand what's going on**:

**Expected Behavior: **
The restored PV should be created with the SKU specified in the new storage class (StandardSSD_ZRS).

**Actual Behavior: **
The PVC gets restored with the updated storage class, but the new PV is created with the old SKU (StandardSSD_LRS).

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by anshulahuja98** [comment]
Can you share your PVC & StorageClass YAML as well?

Also what type of backup approach do you use? CSI? FSBackup? CSI Datamover? Snapshotting via AzurePlugin?

Can you also share version of Velero used

**Comment by anshulahuja98** [comment]
1. Can you also share the version of AzurePlugin you use.
 
 
 2. `app.kubernetes.io/instance: azuredisk-csi-driver-v2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: azuredisk-csi-driver
    app.kubernetes.io/version: v2.0.0-beta.6
    helm.sh/chart: azuredisk-csi-driver-v2.0.0-beta.6`
    
    
    Is your setup a standard AKS setup?
    
    Do you sideload AKS Disk driver in AKS?
    
    What version of Disk Driver are you on?

**Comment by anshulahuja98** [comment]
I went through the code for AzurePlugin based restore flow
https://github.com/vmware-tanzu/velero/blob/7e80d8f1fdd286a9f7b373289d7a5de12fbf231a/pkg/restore/pv_restorer.go#L80
Seems like velero might not be fetching the StorageClass for the SKU and relying on the original SKU it saved.

This change storage class is probably for dynamic scenarios (CSI)

My suggestion for now would be to try your experiment with CSI plugin for snapshotting instead of AzurePlugin. That should work as expected.

Once we confirm this behaviour, we can callout in the docs.

**Comment by ankitsharma1133** [comment]
Hi @anshulahuja98 

EnableCSI is already true. Is there any other attribute I need to change/Add to use CSI plugin for snapshotting instead of AzurePlugin?

My setup instruction 

helm upgrade -i velero vmware-tanzu/velero -f .\values.yml  -n velero

below are my values.yml for helm 

```
configuration:
  uploaderType: restic 
  backupStorageLocation:
    - name: velerobackupsdev
      bucket: velero 
      defaultVolumesToFsBackup: False
      provider: azure
      default: "true"
      config:
        resourceGroup:#RGNAME#
        storageAccount: #STORAFEACCOUNTNAME#
  volumeSnapshotLocation:
    - name: velerosnapshotsdev
      provider: azure
      config:
        resourceGroup: "#AKS_MC_RG"
initContainers:
  - name: velero-plugin-for-azure   
    image: velero/velero-plugin-for-microsoft-azure:v1.11.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
deployNodeAgent: true
features: EnableCSI
credentials:
  existingSecret: velero-secrets
```
