### ISSUE TITLE
Large PVCs are canceled

### ISSUE THREAD

**Issue by filipe-silva-magalhaes-alb** [vmware-tanzu/velero#8454]
**What steps did you take and what happened:**
The data uploads of the largest pvcs failed.

velero create backup velero-schedule-s3-20241125000006 --resource-policies-configmap velero-efs-resourcepolicy --snapshot-move-data

 kubectl get configmap cm -n velero   velero-efs-resourcepolicy  -o yaml
```
apiVersion: v1
data:
  efs-resourcepolicy.yaml: |
    version: v1
    volumePolicies:
    - conditions:
        csi:
          driver: efs.csi.aws.com
      action:
        type: skip
kind: ConfigMap
metadata:
  name: velero-efs-resourcepolicy
  namespace: velero
```

**What did you expect to happen:**
Backup runs without problems.

**The following information will help us better understand what's going on**:

velero debug --backup velero-schedule-s3-20241125000006
[bundle-2024-11-25-14-30-47.tar.gz](https://github.com/user-attachments/files/17904468/bundle-2024-11-25-14-30-47.tar.gz)

Parameters of backup:
csiSnapshotTimeout: 10m0s
itemOperationTimeout: 6h0m0s
uploaderConfig:
  parallelFilesUpload: 2

Parameters of daemonset (running in privileged mode):
  - --features=EnableCSI 
  - --data-mover-prepare-timeout=190m 

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  v1.14.1
- Velero features (use `velero client config get features`):  <NOT SET>
- Kubernetes version (use `kubectl version`): v1.28.15-eks-7f9249a
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
By default, Velero's data mover backup has a 4 hour timeout for each volume. If that is not enough, you could config `default-item-operation-timeout` from the Velero server parameter.
Meanwhile, if you want to accelerate the backup especially to the large/complex volumes, you could config uploader concurrency through the `parallel-files-upload` backup flag. By default, it is the number of CPU cores of the node where the data mover backup is running

**Comment by filipe-silva-magalhaes-alb** [comment]
Hello @Lyndon-Li , in the schedule I configured the "itemOperationTimeout" to "6h". The instance type of our nodes is "r6a.xlarge" (4 vCPUs and 32GB).

**Schedule configuration:**
```
spec:
  schedule: 0 0 * * *
  skipImmediately: false
  template:
    itemOperationTimeout: 6h0m0s
    resourcePolicy:
      apiGroup: v1
      kind: ConfigMap
      name: velero-efs-resourcepolicy
    snapshotMoveData: true
    ttl: 166h
    uploaderConfig:
      parallelFilesUpload: 2
  useOwnerReferencesInBackup: true
```

**Comment by Lyndon-Li** [comment]
`itemOperationTimeout` should be configured to the Velero server parameters.
`parallelFilesUpload` could also be increased in order to accelerate.

**Comment by filipe-silva-magalhaes-alb** [comment]
I did the chances u suggested but still failed. Only the PVCs with 150Gi and 750Gi are failing.

[Uploading bundle-2024-11-27-09-12-46.tar.gz…]()

**Comment by Lyndon-Li** [comment]
If it still fails, you can further increase `itemOperationTimeout` and tune `parallelFilesUpload`, until you get the largest throughput under your env and your backup could finish.
It is a tuning process to adjust `itemOperationTimeout` and `parallelFilesUpload`, it doesn't guarantee that a fixed number could fix all backups in all env.

**Comment by filipe-silva-magalhaes-alb** [comment]
I downgraded to version 13.2 and the backups work again with the same configuration.

**Comment by Lyndon-Li** [comment]
> I thought that could be the token of the IAM Role that has a timeout of 1 hour, and I increased it to 12 hours, but the data uploads are still failing.

I checked the new log, it indeed failed because of the token timeout:
```
time="2024-12-10T01:28:42-05:00" level=warning msg="async write error: unable to write content chunk 423 of FILE:_22q.fdt: mutable parameters: unable to read format blob: error getting kopia.repository blob: The provided token has expired: mutable parameters: unable to read format blob: error getting kopia.repository blob: The provided token has expired" controller=dataupload dataupload=velero/velero-schedule-s3-20241210000026-vbxqr logModule=kopia/object logSource="pkg/kopia/kopia_log.go:101" sublevel=error
time="2024-12-10T01:28:47-05:00" level=warning msg="Kopia backup is canceled" controller=dataupload dataupload=velero/velero-schedule-s3-20241210000026-vbxqr logSource="pkg/uploader/provider/kopia.go:181" parentSnapshot= path="/host_pods/c1b1eca6-ab75-4590-a142-cbdf694ae9d7/volumes/kubernetes.io~csi/pvc-c0cbd472-56cf-42cf-b957-8ad7bcae0363/mount" realSource=ffwk/elasticsearch-elasticsearch-es-elasticsearch-1
time="2024-12-10T01:28:47-05:00" level=warning msg="Async fs backup data path canceled" dataupload=velero-schedule-s3-20241210000026-vbxqr logSource="pkg/controller/data_upload_controller.go:431"
time="2024-12-10T01:28:47-05:00" level=info msg="Action finished" controller=dataupload dataupload=velero/velero-schedule-s3-20241210000026-vbxqr logSource="pkg/uploader/provider/kopia.go:91"
time="2024-12-10T01:28:51-05:00" level=warning msg="unable to write diagnostics blob: The provided token has expired" controller=dataupload dataupload=velero/velero-schedule-s3-20241210000026-vbxqr logModule=kopia/repodiag logSource="pkg/kopia/kopia_log.go:96"
time="2024-12-10T01:28:51-05:00" level=info msg="FileSystemBR is closed" controller=dataupload dataupload=velero/velero-schedule-s3-20241210000026-vbxqr logSource="pkg/datapath/file_system.go:129" user=velero-schedule-s3-20241210000026-vbxqr
```

We will see what happened to 1.14, and could you also try 1.15 since 1.15 is the latest version?

**Comment by filipe-silva-magalhaes-alb** [comment]
Hello, I upgraded to version 1.15.2, and the problem is the same.

Only these 3 pvcs are being canceled:
```
$ kubectl get pvc -n ffwk
NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
elasticsearch-elasticsearch-0      Bound    pvc-e66f603b-de56-41d9-8e26-531ed3565bce   300Gi      RWO            gp3            <unset>                 640d
elasticsearch-elasticsearch-1      Bound    pvc-8a325aa7-aa4f-4707-8d81-9acbf2d95cb5   300Gi      RWO            gp3            <unset>                 640d
elasticsearch-elasticsearch-2      Bound    pvc-953c04cf-b210-42e6-9f6d-152ab3657bac   300Gi      RWO            gp3            <unset>                 640d
```

Configuration of the schedule:
```
  spec:
    schedule: 0 0 * * *
    skipImmediately: false
    template:
      csiSnapshotTimeout: 50m
      itemOperationTimeout: 10h
      resourcePolicy:
        apiGroup: v1
        kind: ConfigMap
        name: velero-efs-resourcepolicy
      snapshotMoveData: true
      ttl: 166h
    useOwnerReferencesInBackup: true
```

velero debug --backup velero-schedule-s3-20250401000043
[bundle-2025-04-01-09-37-16.tar.gz](https://github.com/user-attachments/files/19547577/bundle-2025-04-01-09-37-16.tar.gz)
