### ISSUE TITLE
Use Velero can not to restore inside pv data

### ISSUE THREAD

**Issue by klllmxx** [vmware-tanzu/velero#8483]
For I try to restore the backup item,all pvs,pvcs can be find,but data not found
something like this
![1733305781965](https://github.com/user-attachments/assets/78247182-2e54-4b2d-936e-a107d6ab8a2e)
command:
deploy:
velero install      --provider aws  --use-node-agent    --privileged-node-agent --plugins velero-plugin-for-aws:v1.4.1,velero-plugin-for-csi:v0.4.2      --bucket prod-backup --secret-file /root/middleware/velero/velero-auth.txt       --namespace velero --image  velero:v1.13.1   --snapshot-location-config  region=minio   --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://192.168.127.131:9000    --uploader-type restic

**Comment by klllmxx** [comment]
backup:

restore:

**Comment by klllmxx** [comment]
How can I do... ....

**Comment by klllmxx** [comment]
> Velero does not restic restore data to volumes when backups do not include pods mounting those volumes.

So....command like this?

**Comment by klllmxx** [comment]
> Velero does not restic restore data to volumes when backups do not include pods mounting those volumes.

About when I try to backup namespaces by prod,the restore schedule not completed
command:
velero backup create cluster-859  --include-namespaces prod
velero restore create redis-result --from-backup cluster-859

[root@k8s-master-prod data]# cd prod-redis-data-redis-cluster-0-pvc-3e40d814-af8b-4c75-b602-1bb28c355d63/
[root@k8s-master-prod prod-redis-data-redis-cluster-0-pvc-3e40d814-af8b-4c75-b602-1bb28c355d63]# ls
[root@k8s-master-prod prod-redis-data-redis-cluster-0-pvc-3e40d814-af8b-4c75-b602-1bb28c355d63]#

**Comment by kaovilai** [comment]
Secondly velero does not override existing volume.

You have to delete for volume to be restored with data.

**Comment by klllmxx** [comment]
> Secondly velero does not override existing volume.
> 
> You have to delete PVC/pv for volume to be restored with data.
Delete PVC/pv already, and delete pv folders from storage backend also, my kubernetes storage is  nfs-client-provisioner.

**Comment by klllmxx** [comment]
And try use v1.15.0 to backup resources like this:
Name:         cluster1
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.28.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=28

Phase:  Failed (run `velero backup logs cluster1` for more information)


Namespaces:
  Included:  prod
  Excluded:  <none>

Resources:
  Included:        persistentvolumeclaims, persistentvolumes.pods, serviceaccounts, secrets
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true
Snapshot Move Data:          false
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  10m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2024-12-05 14:15:25 +0800 CST
Completed:  <n/a>

Expiration:  2025-01-04 14:15:25 +0800 CST

Backup Volumes:
  <error getting backup volume info: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline>

command:
velero install --provider aws --use-node-agent --privileged-node-agent --plugins velero-plugin-for-aws:v1.4.1  --bucket prod-backup --secret-file /root/middleware/velero/velero-auth.txt --namespace velero --image velero:v1.15.0 --use-volume-snapshots  --snapshot-location-config region=minio --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://192.168.127.131:9000 --uploader-type restic

velero backup create cluster1  --include-namespaces prod  --include-resources persistentvolumeclaims,persistentvolumes.pods,serviceaccounts,secrets  --item-operation-timeout 600s --snapshot-volumes=true --default-volumes-to-fs-backup=true

**Comment by klllmxx** [comment]
> Secondly velero does not override existing volume.
> 
> You have to delete PVC/pv for volume to be restored with data.

By the way,one more ask about the how to change this images for restore steps:
![402aa69c1a7d00569778664efbe3199](https://github.com/user-attachments/assets/a93e4509-fd49-4e02-a7f9-0f597b99e44a)

**Comment by kaovilai** [comment]
@klllmxx 
[create this configmap](https://velero.io/docs/v1.15/file-system-backup/#:~:text=image%3A%20myregistry.io/my%2Dcustom%2Dhelper%2Dimage%5B%3AOPTIONAL_TAG%5D)
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  # any name can be used; Velero uses the labels (below)
  # to identify it rather than the name
  name: fs-restore-action-config
  # must be in the velero namespace
  namespace: velero
  # the below labels should be used verbatim in your
  # ConfigMap.
  labels:
    # this value-less label identifies the ConfigMap as
    # config for a plugin (i.e. the built-in restore
    # item action plugin)
    velero.io/plugin-config: ""
    # this label identifies the name and kind of plugin
    # that this ConfigMap is for.
    velero.io/pod-volume-restore: RestoreItemAction
data:
  # The value for "image" can either include a tag or not;
  # if the tag is *not* included, the tag from the main Velero
  # image will automatically be used.
  image: myregistry.io/my-custom-helper-image[:OPTIONAL_TAG]
```
