### ISSUE TITLE
Velero backup but not restore helm charts using deployment name selector

### ISSUE THREAD

**Issue by masalinas** [vmware-tanzu/velero#8560]
**What steps did you take and what happened:**
1)  deploy a helm chart
```
$ helm install poc-k8s-keycloak-angular oci://registry-1.docker.io/ofertoio/poc-k8s-keycloak-angular-chart
```
The chart is deployed ok

2) backup a helm chart using its name:
```
$ velero backup create poc-k8s-keycloak-angular-chart-backup --selector app.kubernetes.io/name=poc-k8s-keycloak-angular-
chart
```
The backup is created ok

3) List your helm installed:
```
$ helm -n default list
```
The helm is showed ok.

4) remove a helm chart:
```
$ helm delete poc-k8s-keycloak-angular-chart
```

The chart is removed ok.

5) restore the helm chart
```
$ velero restore create --from-backup poc-k8s-keycloak-angular-chart-backup
```

All chart resources (deployment, pod and service) are restores ok, **but the helm labels not, so when you execute again**

```
$ helm -n default list
```
**My original helm chart is not showed**

**What did you expect to happen:**
Restore all chart resources and the labels atatched  to helm and continue using these resources as a original helm chart.

**The following information will help us better understand what's going on**:

I noticed that velero not restore the metadata labels attached to helm like these ones:

```
  labels:
    app.kubernetes.io/instance: poc-k8s-keycloak-angular
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: poc-k8s-keycloak-angular-chart
    app.kubernetes.io/version: 1.5.0
    helm.sh/chart: poc-k8s-keycloak-angular-chart-1.5.0
  annotations:
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: poc-k8s-keycloak-angular
    meta.helm.sh/release-namespace: default
```

**Environment:**

- Helm version: v.3.16.4
- Velero version (use `velero version`): 1.15.0
- Velero features (use `velero client config get features`): Plugin AWS 1.11.0 compatible with velero 1.15.0
- Kubernetes version (use `kubectl version`): 1.27.4
- Kubernetes installer & version: minikube 1.31.2
- Cloud provider or hardware configuration: localhost
- OS (e.g. from `/etc/os-release`): ubuntu 24.04 LTS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
