### ISSUE TITLE
Restic restore with resource modifier fails

### ISSUE THREAD

**Issue by nobuaki-fukushima** [vmware-tanzu/velero#8578]
**What steps did you take and what happened:**

When restic restore is performed in conjunction with resource modifier, the pod is restarted and the restic restore destination pod no longer exists, causing the volume restore to fail.

## State at start of restore
`
NAME                                         READY   STATUS              RESTARTS   AGE
growi-mongodb-5dcfb75c59-qvdmt           0/2     Init:0/1            0          20s
`

## State after pod restart
`
NAME                                     READY   STATUS              RESTARTS   AGE
growi-mongodb-65cfdc755b-t2kr6           0/2     ContainerCreating   0          9s
`

## Restore Status
`
restic Restores:
  Failed:
    growi-dev-012579/growi-mongodb-5dcfb75c59-qvdmt: data
`

## Resource modifier definition

The resource modifier definition is as follows
```
- conditions:
    groupResource: deployments.apps
    resourceNameRegex: "^(elasticsearch|growi|gitea-apps-k8s-deployment2|growi-mongodb)$"
    namespaces:
    - gitea-prod
    - growi-prod
  patches:
  - operation: add
    path: "/spec/template/"
    value: "{}"
  - operation: add
    path: "/spec/template/spec/"
    value: "{}"
  - operation: add
    path: "/spec/template/spec/affinity"
    value: "{}"
  - operation: add
    path: "/spec/template/spec/affinity/nodeAffinity"
    value: "{}"
  - operation: add
    path: "/spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution"
    value: "{}"
  - operation: add
    path: "/spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms"
    value: "[{\"matchExpressions\":[{\"key\":\"nodetype\",\"operator\":\"NotIn\",\"values\":[\"devspotnode\"]}]}]"
  - operation: add
    path: "/spec/template/spec/tolerations"
    value: "[{\"key\": \"kubernetes.azure.com/scalesetpriority\", \"operator\": \"Equal\", \"value\": \"spot\", \"effect\": \"NoSchedule\"}]"

```

If the resource modifier is not used, the pod will not be restarted and the volume will be restored successfully.

**What did you expect to happen:**
When performing a restic restore using a resource modifier, identify the pod to be restored by pod label instead of pod name.
Specifically, when the resource modifier is activated, a pod label is added and used for identification during the restore.

**The following information will help us better understand what's going on**:
[debug.zip](https://github.com/user-attachments/files/18313533/debug.zip)

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):v1.15.0 1d4f1475975b5107ec35f4d19ff17f7d1fcb3edf
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.15", GitCommit:"2cb5b4899b34d1d33043a06ae686f5882c7748f2", GitTreeState:"clean", BuildDate:"2023-11-03T12:18:15Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): - RuntimeOS: windows - RuntimeArch: amd64

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
