### ISSUE TITLE
Node-agent high memory usage

### ISSUE THREAD

**Issue by RobKenis** [vmware-tanzu/velero#8582]
**What steps did you take and what happened:**

Velero is installed with nodeAgent enabled. Backup storage location is configured to use Azure Blob Storage.

```yaml
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore-that-uses-a-lot-of-memory
  namespace: velero
spec:
  backupName: external-backup-1
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  - csinodes.storage.k8s.io
  - volumeattachments.storage.k8s.io
  - backuprepositories.velero.io
  - policies.rabbitmq.com
  existingResourcePolicy: update
  hooks: {}
  includedNamespaces:
  - custom-namespace
  itemOperationTimeout: 48h0m0s
  uploaderConfig:
    parallelFilesDownload: 16
```

The memory request for node-agent is set to 5Gi. Normally, the limit is also set to 5Gi. To avoid the Pod getting OOMKilled, I have removed the limit for this restore.

**What did you expect to happen:**

Memory usage stays around, but below, 5Gi.

**Anything else you would like to add:**

![image](https://github.com/user-attachments/assets/c309449f-e8ec-413b-b102-4724838af097)

**Environment:**

- Velero version (use `velero version`): v1.15.0
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): v1.28.2+k3s1
- Kubernetes installer & version: v1.28.2+k3s1
- Cloud provider or hardware configuration: Azure VM
- OS (e.g. from `/etc/os-release`): AlmaLinux 9.5 (Teal Serval)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
