### ISSUE TITLE
Trailing checksum is not supported

### ISSUE THREAD

**Issue by percy78** [vmware-tanzu/velero#8742]
**What steps did you take and what happened:**

Upgraded Velero to v1.15.2 and since then I've encountered the issue that the backups seems to be working fine but throws and error in the end preventing anything to be backed up a the moment. 

In addition I also upgraded the aws plugin to the latest v1.11.1

**What did you expect to happen:**

Successful Backups

**The following information will help us better understand what's going on**:

```
status:
  expiration: "2025-04-02T11:52:33Z"
  failureReason: 'rpc error: code = Unknown desc = error putting object backups/test/velero-backup.json:
    operation error S3: PutObject, https response error StatusCode: 400, RequestID:
    615340fe5149adeb5208, HostID: 615340fe5149adeb5208, api error BadRequest: trailing
    checksum is not supported'
  formatVersion: 1.1.0
  hookStatus: {}
  phase: Failed
  progress:
    itemsBackedUp: 4242
    totalItems: 4242
  startTimestamp: "2025-03-03T11:52:33Z"
  version: 1
  warnings: 38
```

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): **Velero 1.15.2**
- Velero features (use `velero client config get features`): **features: NOT SET**
- Kubernetes version (use `kubectl version`): **Client Version: v1.31.0** 
- Kubernetes installer & version: **Server Version: v1.30.5+rke2r1**
- Cloud provider or hardware configuration: **Scality S3 Version 8.0.0.0**
- OS (e.g. from `/etc/os-release`): **K8s**

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
