### ISSUE TITLE
Declarative schedule fails to run

### ISSUE THREAD

**Issue by darnone** [vmware-tanzu/velero#8769]
**What steps did you take and what happened:**
I am deploying velero using helm chart and ArgoCD. When I deploy velero, create a schedule, and create a backup from the schedule the backup runs fine But if I define that same schedule declartivel using helm chart values, the schedule is create but backups from them do not work. I fact they are not created at all

**What did you expect to happen:**

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
I would add a bundle but the backup does not exist.

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.15.2
- Velero features (use `velero client config get features`): features: <NOT SET> but CSI Enabled is in my config
- Kubernetes version (use `kubectl version`): 1.30.9
- Kubernetes installer & version: 1.30.9 
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by darnone** [comment]
schedule config from helm chart:
```
schedules:
  gts-cicd-dev-schedule-fsb:
    disabled: false
    schedule: " 15 2 * * 1-5"
    template:
      csiSnapshotTimeout: 0s
      defaultVolumesToFsBackup: true
      ttl: "0s"
      excludedNamespaces:
      - velero
      - default
      hooks: {}
      includedNamespaces:
      - "*"
      includedResources:
      - "*"
      itemOperationTimeout: 0s
      metadata: {}
    useOwnerReferencesInBackup: false
```

**Comment by blackpiglet** [comment]
Could you help collect the debug bundle by running CLI `velero debug` and upload the generated tarball here?

**Comment by darnone** [comment]
I see in the log:
time="2025-03-10T15:13:07Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/0/1)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:181"

my configuration section:
```
configuration:
  features: EnableCSI
  uploaderType: kopia
  backupStorageLocation:
  - name: velero-backup-storage-location
    #bucket: {{ .Values.velero_backups_bucket }}
    bucket: gts-argocd-ci-velero-dev
    default: true
    provider: aws
    config:
      region: us-east-1
  volumeSnapshotLocation:
  - name: velero-volume-storage-location
    provider: aws
    config:
      region: us-east-1
  repositoryMaintenanceJob:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      memory: 2048Mi
```
