### ISSUE TITLE
Prometheus monitoring backups are in PartiallyFailed state

### ISSUE THREAD

**Issue by dmrub** [vmware-tanzu/velero#8780]
**What steps did you take and what happened:**

The backup of the prometheus monitoring (https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) sometimes fails. The DataUpload of the prometheus DB volume is canceled. I cannot find out the reason for the error.

**What did you expect to happen:**
Backup is successful.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

[bundle-2025-03-11-17-03-14.tar.gz](https://github.com/user-attachments/files/19208756/bundle-2025-03-11-17-03-14.tar.gz)

[bundle-2025-03-12-12-03-23.tar.gz](https://github.com/user-attachments/files/19208760/bundle-2025-03-12-12-03-23.tar.gz)

**Anything else you would like to add:**

Backups are performed with CSI snapshotting with LINBIT SDS (https://linbit.com/software-defined-storage)

```yaml
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: linstor
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: linstor.csi.linbit.com
deletionPolicy: Delete

---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: monitoring-backup
  namespace: velero
  annotations:
    velero.io/csi-volumesnapshot-class_disk.csi.cloud.com: "linstor"
spec:
  schedule: "10 0,8-20/2 * * 1-6"
  template:
    csiSnapshotTimeout: 20m
    snapshotVolumes: true
    snapshotMoveData: true
    includedNamespaces:
      - 'monitoring'
    includedResources:
      - '*'
    storageLocation: default
    volumeSnapshotLocations:
      - default
    ttl: 168h0m0s
```

**Environment:**

- Velero version (use `velero version`):
Client:
        Version: v1.15.2
        Git commit: 804d73c4f2349f1ca9bd3d6c751956e1d2021c01
Server:
        Version: v1.15.2
- Velero features (use `velero client config get features`): 
features: <NOT SET>
- Kubernetes version (use `kubectl version`): 
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.12
- Kubernetes installer & version: none
- Cloud provider or hardware configuration: 3x Proxmox VMs
- OS (e.g. from `/etc/os-release`):
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
