### ISSUE TITLE
Cannot restore rook-ceph PVC from backup

### ISSUE THREAD

**Issue by raymundovr** [vmware-tanzu/velero#8825]
**What steps did you take and what happened:**
I am trying to restore my cluster on a new cluster for disaster recovery purposes. Both have rook-ceph installed and running. Applications mount PVCs created from `StorageClasses` that uses `rook-ceph.cephfs.csi.ceph.com` provisioner.

Backup is completed and without errors, however, running the `velero restore` on the second cluster reports `PartiallyFailed` and by describing the restore I can observe:
```
Errors:                                                                                                                                                                                       
  Velero:   error from restore item operation: data path restore failed: Failed to run data path service for DataDownload firefly-894f9ef58928-20250327-20250327155830-w5gxr: Data path for data download firefly-894f9ef58928-20250327-20250327155830-w5gxr failed: Failed to run kopia restore: Failed to copy snapshot data to the target: restore error: copy file: error creating file: unable to open snapshot file for /5f76ea11-3d55-45a0-be76-8c40e7e000ee/20241122_101214.txt: unable to open object: a626f78deb6a4bbcc46a517138896dc6: failed to open object with id a626f78deb6a4bbcc46a517138896dc6: error to open object: unexpected content error: error getting cached content from blob "p96c638339039ba612358fe080152853e-s8dc09762761d06d6133": failed to get blob with ID p96c638339039ba612358fe080152853e-s8dc09762761d06d6133: invalid blob offset or length

```
Velero was installed on both clusters using
```
velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.11.1 \
    --bucket k8s-cluster-0 \
    --secret-file ./credentials \
    --use-node-agent \
    --use-volume-snapshots=true \
    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://minio.dom.io \
    --snapshot-location-config region="default" --features=EnableCSI --default-snapshot-move-data=true
```

Backup is generated as:
`
velero backup create firefly-894f9ef58928-20250327 --snapshot-move-data --include-cluster-resources=true --include-namespaces firefly-894f9ef58928
`
Restore created as
`velero restore create --include-cluster-resources=true --from-backup firefly-894f9ef58928-20250327`

Ceph volumesnapshotclasses have been create and labeled as "velero.io/csi-volumesnapshot-class: "true""

**What did you expect to happen:**
The snapshot data would be moved accordingly and the restore operation would succeed.

**The following information will help us better understand what's going on**:
Support bundle attached. [bundle-2025-03-27-16-07-41.tar.gz](https://github.com/user-attachments/files/19489029/bundle-2025-03-27-16-07-41.tar.gz)

**Anything else you would like to add:**
PVC Displays
```
Events:                                                                                                                                                                                    │

│   Warning  ProvisioningFailed    27s (x10 over 3m48s)  rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-d4d7df87-rz4wl_a01c0fd1-e1d2-480e-968d-d21b7e86a487  failed to provision │
│  volume with StorageClass "levv-filesystem-storage": claim Selector is not supported                                                                                                        
```
VolumeSnapshotClass
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-cephfsplugin-snapclass
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: rook-ceph.cephfs.csi.ceph.com # csi-provisioner-name
parameters:
  # Specify a string that identifies your cluster. Ceph CSI supports any
  # unique string. When Ceph CSI is deployed by Rook use the Rook namespace,
  # for example "rook-ceph".
  clusterID: rook-ceph # namespace:cluster
  csi.storage.k8s.io/snapshotter-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph # namespace:cluster
deletionPolicy: Delete
```

**Environment:**

- Velero version (use `velero version`): 
Client:
        Version: v1.15.2
        Git commit: 804d73c4f2349f1ca9bd3d6c751956e1d2021c01
Server:
        Version: v1.15.2
- Velero features (use `velero client config get features`): features: <NOT SET> 
- Kubernetes version (use `kubectl version`): 
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.0
- Kubernetes installer & version: 1.32
- Cloud provider or hardware configuration:
self-hosted
- OS (e.g. from `/etc/os-release`): debian bookworm

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
