### ISSUE TITLE
Data mover pods can’t schedule on tainted nodes

### ISSUE THREAD

**Issue by navesimchi** [vmware-tanzu/velero#8857]
**What steps did you take and what happened:**
I installed Velero using the Helm chart from [ArtifactHub](https://artifacthub.io/packages/helm/vmware-tanzu/velero/8.5.0), version 8.5.0, with the EnableCSI feature enabled.

My goal is to back up Azure Files PVCs on an AKS cluster.

However, the data mover pods fail to schedule because they don’t tolerate the taints on my nodes. Specifically:
	•	Spot nodes have the taint kubernetes.azure.com/scalesetpriority: spot
	•	System nodes have the taint CriticalAddonsOnly=true:NoSchedule

This results in scheduling failures like the following:

> 0/8 nodes are available: 2 node(s) had untolerated taint {CriticalAddonsOnly: true}, 6 node(s) had untolerated taint {kubernetes.azure.com/scalesetpriority: spot}

![Image](https://github.com/user-attachments/assets/436ac8ff-2902-4c2a-86db-63560ab886c1)

**What did you expect to happen:**
I expected the data mover pods to be schedulable on tainted nodes by either:
	•	Being configurable to include custom tolerations.
	•	Or by tolerating common taints like those used on spot and system nodes in AKS.

**What did you try already:**
I used the following Helm values file for the installation:
```
credentials:
  useSecret: true
  existingSecret: "velero-secrets"

backupStorageLocation: [ ]

configuration:
  features: "EnableCSI"
  defaultBackupStorageLocation: ""

backupsEnabled: false
deployNodeAgent: true

initContainers:
  - name: velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.11.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"

nodeAgent:
  tolerations:
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
    - key: "kubernetes.azure.com/scalesetpriority"
      operator: "Equal"
      value: "spot"
      effect: "NoSchedule"
```
Despite specifying these tolerations, the data mover pods still fail to schedule.

I also came across [Issue #2898](https://github.com/vmware-tanzu/velero/issues/2898), but that seems specific to Restic. I’m using the default data mover installed with the EnableCSI flag, not Restic.

Additionally, I cannot manually patch or edit the tolerations every time a backup is created — this is not scalable for a production environment.

**Anything else you would like to add:**
	•	AKS cluster with tainted spot and system node pools
	•	Velero Helm chart version: 8.5.0
	•	Kubernetes version: 1.30.9

**Environment:**

- Velero version (use `velero version`): v1.15.2
- Velero features (use `velero client config get features`): EnableCSI
- Kubernetes version (use `kubectl version`): 1.30.9

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
