### ISSUE TITLE
PostHooks Multiple Exec Hooks are ignored in HooksAttamps calculation

### ISSUE THREAD

**Issue by amastbau** [vmware-tanzu/velero#8910]
**What steps did you take and what happened:**

## Observed Behavior with Multiple Exec Post-Hooks in Velero Restore

**Velero Version:** (Please specify your Velero version here, e.g., v1.12.x, v1.13.0)

**Kubernetes Version:** (Please specify your Kubernetes version here, e.g., v1.27.x, v1.28.x, OpenShift version)

**Problem Description:**

When running a restore (or backup) with multiple `exec` post-hooks defined for a resource (e.g., a Deployment or Pod), the "Hooks Attempted" count in the `Restore` (or `Backup`) status appears to be `1` per resource, regardless of the number of `exec` post-hooks configured. This is unexpected, as it doesn't accurately reflect the individual execution attempts of each hook.

Furthermore, if one of the `exec` hooks fails (exits with a non-zero status), the overall post-hooks phase seems to be considered based on the first attempted hook's outcome, potentially not reflecting the status of subsequent hooks when `onError: Continue` is used.

**Steps to Reproduce:**

1.  **Prerequisites:**
    * A running Kubernetes cluster with Velero installed and configured.

2.  **Deploy a Sample Application:** Deploy a simple application with multiple replicas in a namespace (e.g., `sample-app`). For example, an `nginx` deployment:
    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sample-app
      namespace: sample-app
    spec:
      replicas: 2 # Ensure multiple pods to observe behavior across instances
      selector:
        matchLabels:
          app: sample-app
      template:
        metadata:
          labels:
            app: sample-app
        spec:
          containers:
          - name: nginx
            image: nginx:latest
    ```
    Apply this deployment:
    ```bash
    kubectl apply -f sample-app.yaml
    ```

3.  **Create a Backup with Post-Hooks :**
 ```yaml
 apiVersion: velero.io/v1
    kind: Backup
    metadata:
      name: multiple-post-hooks-backup
      namespace: <your-velero-namespace> # Replace with your Velero namespace
    spec:
      includedNamespaces:
        - sample-app
      hooks:
        resources:
        - includedNamespaces:
            - sample-app
          name: multiple-hooks-example
          postHooks:
          - exec:
              command:
                - /usr/bin/sh
                - -c
                - echo 'This post-hook will fail during backup' && exit 1
              onError: Continue
              timeout: 1m
          - exec:
              command:
                - /usr/bin/sh
                - -c
                - echo 'This post-hook will succeed during backup' && exit 0
              onError: Continue
              timeout: 1m
```   
Apply the backup:
```bash
kubectl apply -f multiple-post-hooks-backup.yaml
```

4.  **Create a Restore with Multiple Post-Hooks:**
    ```yaml
    apiVersion: velero.io/v1
    kind: Restore
    metadata:
      name: multiple-post-hooks-restore
      namespace: <your-velero-namespace> # Replace with your Velero namespace
    spec:
      backupName: multiple-post-hooks-backup # Or a relevant backup name
      hooks:
        resources:
        - includedNamespaces:
            -sample-app
          name: multiple-hooks-example
          postHooks:
          - exec:
              command:
                - /usr/bin/sh
                - -c
                - echo 'This post-hook will fail during restore' && exit 1
              onError: Continue
              timeout: 1m
          - exec:
              command:
                - /usr/bin/sh
                - -c
                - echo 'This post-hook will succeed during restore' && exit 0
              onError: Continue
              timeout: 1m
    ```
    Apply the restore:
    ```bash
    kubectl apply -f multiple-post-hooks-restore.yaml
    ```

5.  **Examine the Restore Status:**
    ```bash
    kubectl describe restore multiple-post-hooks-restore -n <your-velero-namespace>
    Phase:                       PartiallyFailed (run 'velero restore logs multiple-post-hooks-restore' for more information)
    Total items to be restored:  36
    Items restored:              36
    
    Started:    2025-05-06 21:42:05 +0000 UTC
    Completed:  2025-05-06 21:42:19 +0000 UTC
    
    Warnings:
      Velero:     <none>
      Cluster:  could not restore, CustomResourceDefinition:reclaimspacecronjobs.csiaddons.openshift.io already exists. Warning: the in-cluster version is different than the backed-up version
      Namespaces:
        sample-app:  could not restore, RoleBinding:system:deployers already exists. Warning: the in-cluster version is different than the backed-up version
                     could not restore, RoleBinding:system:image-builders already exists. Warning: the in-cluster version is different than the backed-up version
                     could not restore, RoleBinding:system:image-pullers already exists. Warning: the in-cluster version is different than the backed-up version
                     could not restore, ConfigMap:kube-root-ca.crt already exists. Warning: the in-cluster version is different than the backed-up version
                     could not restore, ConfigMap:openshift-service-ca.crt already exists. Warning: the in-cluster version is different than the backed-up version
                     could not restore, RoleBinding:admin already exists. Warning: the in-cluster version is different than the backed-up version
                     could not restore, RoleBinding:system:deployers already exists. Warning: the in-cluster version is different than the backed-up version
                     could not restore, RoleBinding:system:image-builders already exists. Warning: the in-cluster version is different than the backed-up version
                     could not restore, RoleBinding:system:image-pullers already exists. Warning: the in-cluster version is different than the backed-up version
    
    Errors:
      Velero:     <none>
      Cluster:    <none>
      Namespaces:
        sample-app:  hook multiple-hooks-example in container mysql failed to execute, err: command terminated with exit code 1
    
    Backup:  multiple-post-hooks-backup
    
    Namespaces:
      Included:  all namespaces found in the backup
      Excluded:  <none>
    
    Resources:
      Included:        *
      Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io, csinodes.storage.k8s.io, volumeattachments.storage.k8s.io, backuprepositories.velero.io
      Cluster-scoped:  auto
    
    Namespace mappings:  <none>
    
    Label selector:  <none>
    
    Or label selector:  <none>
    
    Restore PVs:  auto
    
    CSI Snapshot Restores:
      sample-app/mysql-data:
        Snapshot: specify --details for more information
      sample-app/mysql-data1:
        Snapshot: specify --details for more information
    
    Existing Resource Policy:   <none>
    ItemOperationTimeout:       4h0m0s
    
    Preserve Service NodePorts:  auto
    
    
    HooksAttempted:   1
    HooksFailed:      1
    ```
    Observe the `Hook Status` section.

**Observed Result:**

The `Hook Status` typically shows `Hooks Attempted: 1` for the targeted resource (the Deployment), even though two `exec` post-hooks were defined. If the first `exec` hook fails, the overall post-hooks phase might be interpreted based on this initial failure, even if subsequent hooks succeed (when `onError: Continue` is used).

**Expected Result:**

The `Hook Status` should ideally reflect the number of individual `exec` post-hooks attempted per targeted resource (pod). In the example above with two post-hooks and two replicas, we might expect to see something indicating 4 attempts in a more detailed status view. Additionally, the status of the post-hooks phase should ideally provide a more granular view of the success or failure of each individual hook execution across all targeted pods.

 
[bundle-2025-05-07-00-43-28.tar.gz](https://github.com/user-attachments/files/20072436/bundle-2025-05-07-00-43-28.tar.gz)
