### ISSUE TITLE
Velero Backup Schedule Encounters HTTP 429 TooManyRequests and Creates Duplicate Snapshots

### ISSUE THREAD

**Issue by jespernylendklp** [vmware-tanzu/velero#8932]
**What steps did you take and what happened:**
I have a schedule to take a backup of our Azure Files (storage class with provisioner: file.csi.azure.com). This should take a backup of all our azure files volumes every 15 minutes. 
This works fine for a few hours, but suddenly Velero encounters a `HTTP 429 TooManyRequests` issue when trying to take a snapshot of the given volume. From the logs it looks like Velero
is retrying after 5 seconds. However, it seems the snapshot was successfully taken the initial time. At least we end up with quite many duplicates of the snapshot in Azure, and this is the 
only reason we can think of which would generate duplicates. Since Azure only allows a maximum of 200 snapshots per Azure File. This issue then messes with our backup schedule and TTL of the given backup. 

The error we get is:
```
error: Failed to check and update snapshot content: failed to take snapshot of the volume my-storage#mystoragesa#pvc-84948baf-cd38-4e5a-92d8-e3bd5680a451###kalypso-db: 
\"rpc error: code = Internal desc = failed to get file share(pvc-84948baf-cd38-4e5a-92d8-e3bd5680a451) quota: storage.FileSharesClient#Get: 
Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code=\\\"TooManyRequests\\\" 
Message=\\\"The request is being throttled as the limit has been reached for operation type - Read_ObservationWindow_00:05:00. For more information, see - https://aka.ms/srpthrottlinglimits\\\"\""
```
We are ok with the backups being throttled, but we don't want Velero to create duplicates if this happens. What it seems like to me is that Azure will still handle the initial request, or something like it.

**What did you expect to happen:**
We expected to have the snapshots work as normal, and not generate duplicates, even if Azure responds with `HTTP 429 TooManyRequests`.

**The following information will help us better understand what's going on**:

```
time="2025-05-13T08:40:04Z" level=warning msg="VolumeSnapshotContent snapcontent-8926e310-f9fe-4a17-a80c-e1b185571faf has error: Failed to check and update snapshot content: failed to take snapshot of the volume my-storage#mystoragesa#pvc-84948baf-cd38-4e5a-92d8-e3bd5680a451###kalypso-db: \"rpc error: code = Internal desc = failed to get file share(pvc-84948baf-cd38-4e5a-92d8-e3bd5680a451) quota: storage.FileSharesClient#Get: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code=\\\"TooManyRequests\\\" Message=\\\"The request is being throttled as the limit has been reached for operation type - Read_ObservationWindow_00:05:00. For more information, see - https://aka.ms/srpthrottlinglimits\\\"\"" backup=openshift-adp/kalypso-azure-files-frequent-backup-schedule-20250513083001 cmd=/velero logSource="/remote-source/velero/app/pkg/util/csi/volume_snapshot.go:745" pluginName=velero
time="2025-05-13T08:40:09Z" level=info msg="Waiting for VolumeSnapshotContents snapcontent-8926e310-f9fe-4a17-a80c-e1b185571faf to have snapshot handle. Retrying in 5s" backup=openshift-adp/kalypso-azure-files-frequent-backup-schedule-20250513083001 cmd=/velero logSource="/remote-source/velero/app/pkg/util/csi/volume_snapshot.go:740" pluginName=velero
time="2025-05-13T08:40:09Z" level=warning msg="VolumeSnapshotContent snapcontent-8926e310-f9fe-4a17-a80c-e1b185571faf has error: Failed to check and update snapshot content: failed to take snapshot of the volume my-storage#mystoragesa#pvc-84948baf-cd38-4e5a-92d8-e3bd5680a451###kalypso-db: \"rpc error: code = Internal desc = failed to get file share(pvc-84948baf-cd38-4e5a-92d8-e3bd5680a451) quota: storage.FileSharesClient#Get: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code=\\\"TooManyRequests\\\" Message=\\\"The request is being throttled as the limit has been reached for operation type - Read_ObservationWindow_00:05:00. For more information, see - https://aka.ms/srpthrottlinglimits\\\"\"" backup=openshift-adp/kalypso-azure-files-frequent-backup-schedule-20250513083001 cmd=/velero logSource="/remote-source/velero/app/pkg/util/csi/volume_snapshot.go:745" pluginName=velero
time="2025-05-13T08:40:14Z" level=info msg="Waiting for VolumeSnapshotContents snapcontent-8926e310-f9fe-4a17-a80c-e1b185571faf to have snapshot handle. Retrying in 5s" backup=openshift-adp/kalypso-azure-files-frequent-backup-schedule-20250513083001 cmd=/velero logSource="/remote-source/velero/app/pkg/util/csi/volume_snapshot.go:740" pluginName=velero
time="2025-05-13T08:40:14Z" level=warning msg="VolumeSnapshotContent snapcontent-8926e310-f9fe-4a17-a80c-e1b185571faf has error: Failed to check and update snapshot content: failed to take snapshot of the volume my-storage#mystoragesa#pvc-84948baf-cd38-4e5a-92d8-e3bd5680a451###kalypso-db: \"rpc error: code = Internal desc = failed to get file share(pvc-84948baf-cd38-4e5a-92d8-e3bd5680a451) quota: storage.FileSharesClient#Get: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code=\\\"TooManyRequests\\\" Message=\\\"The request is being throttled as the limit has been reached for operation type - Read_ObservationWindow_00:05:00. For more information, see - https://aka.ms/srpthrottlinglimits\\\"\"" backup=openshift-adp/kalypso-azure-files-frequent-backup-schedule-20250513083001 cmd=/velero logSource="/remote-source/velero/app/pkg/util/csi/volume_snapshot.go:745" pluginName=velero
time="2025-05-13T08:40:19Z" level=info msg="Waiting for VolumeSnapshotContents snapcontent-8926e310-f9fe-4a17-a80c-e1b185571faf to have snapshot handle. Retrying in 5s" backup=openshift-adp/kalypso-azure-files-frequent-backup-schedule-20250513083001 cmd=/velero logSource="/remote-source/velero/app/pkg/util/csi/volume_snapshot.go:740" pluginName=velero
```

**Anything else you would like to add:**

Schedule:
```
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: my-schedule
  namespace: openshift-adp
spec:
  schedule: '*/15 * * * *'
  skipImmediately: false
  template:
    volumeSnapshotLocations:
      - my-snapshot-location
    resourcePolicy:
      kind: configmap
      name: only-azure-files-policy
    defaultVolumesToRestic: false
    defaultVolumesToFsBackup: false
    csiSnapshotTimeout: 5m0s
    includedResources:
      - PersistentVolumeClaim
      - PersistentVolume
    ttl: 20h0m0s
    itemOperationTimeout: 10m0s
    metadata: {}
    storageLocation: my-storage-location
    hooks: {}
    snapshotVolumes: true
    snapshotMoveData: false
```

BackupStorageLocation
```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: my-storage-location
spec:
  config:
    resourceGroup: my-storage
    storageAccount: mystoragesa
    storageAccountURI: 'https://mystoragesa.blob.core.windows.net'
    useAAD: 'true'
  credential:
    key: credentials
    name: cloud-credentials-azure
  default: true
  objectStorage:
    bucket: kalypso-backup-container
    prefix: kalypso
  provider: azure
```

VolumeSnapshotLocation
```
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: my-snapshot-location
spec:
  config:
    incremental: 'true'
    resourceGroup: my-storage
  credential:
    key: credentials
    name: cloud-credentials-azure
  provider: azure
```

**Environment:**

- Velero version (use `velero version`): 
    ```
	Client:
        Version: v1.14.1-OADP
        Git commit: -
	Server:
        Version: v1.14.1-OADP
	```
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): `Server Version: v1.30.10`
- Kubernetes installer & version:
- Cloud provider or hardware configuration: `Azure - ARO`
- OS (e.g. from `/etc/os-release`): `Red Hat Enterprise Linux 9.5 (Plow)`

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
