### ISSUE TITLE
Documentation Request: Velero CLI Alias Workaround for DNS Resolution Issues

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#9001]
## Issue Description

Users frequently encounter DNS resolution errors when running the Velero CLI from outside the Kubernetes cluster, particularly when BackupStorageLocation (BSL) configurations use internal service DNS names (e.g., `minio-svc.minio-store.svc`).

**This issue is an invitation for discussion**: Should we recommend the CLI alias workaround as an official solution on the velero.io website? While this approach has proven effective for many users, we want community input on whether this should be part of our official documentation strategy.

## Current Problem

When executing commands like `velero describe backup` or `velero get backup` from a host outside the cluster, users see errors such as:
```
no such host error
```

This occurs because the Velero CLI cannot resolve internal Kubernetes service DNS names that are only accessible within the cluster network.

## Proposed Workaround: Velero CLI Alias

Instead of installing the Velero CLI locally and dealing with DNS resolution issues, users can create an alias that runs the CLI within a Kubernetes pod:

```bash
# Create an alias that runs velero CLI in a pod
alias velero='kubectl run velero-cli --rm -it --restart=Never \
  --image=velero/velero:latest \
  --serviceaccount=velero \
  -- velero'
```

### Benefits
- **No DNS configuration needed**: Runs within cluster network where service DNS works natively
- **Consistent behavior**: Same environment as the Velero server
- **No local installation**: Eliminates version mismatches between CLI and server
- **Security**: Uses appropriate service account with proper RBAC permissions

### Limitations
⚠️ **Important**: This workaround has limitations for commands that need to write files to the local filesystem:

- **`velero backup download`** will not work as expected since files are downloaded inside the ephemeral container and are lost when the pod terminates
- Any command that expects to read local files as input will require additional steps

### Usage Examples
After setting up the alias, most velero commands work seamlessly:

```bash
# List backups
velero get backups

# Describe a specific backup
velero describe backup my-backup

# Create a backup
velero backup create my-new-backup --include-namespaces=default

# Get backup logs
velero backup logs my-backup
```

## Questions for Discussion

1. **Should we officially endorse this workaround** on velero.io, or keep it as community knowledge?

## Related Issues

- Original issue: #7763
- Long-term solution: #6167

## Documentation Location

This workaround could be documented in:
1. **Troubleshooting section** of the official Velero documentation
2. **CLI installation guide** as an alternative method
3. **FAQ section** addressing common DNS issues

The CLI alias workaround provides an immediate solution while the community works on a more comprehensive fix via #6167.

**Comment by ParksBra** [comment]
When I had initially attempted the prementioned alias, I encountered a couple issues:
- `--serviceaccount=<service_account_name>` is no longer a valid as of kubectl version 1.24
  - Resolved with: `--overrides='{ "apiVersion": "v1", "spec": { "serviceAccountName": "<service_account_name>" } }'`
- `velero` not resolving to a valid executable via the environment's PATH
  - Resolved by using the absolute path of `/velero`

Resulting in:
```bash
alias velero='kubectl run velero-cli --rm -it --restart=Never \
  --image=velero/velero:latest \
  --overrides='\''{ "apiVersion": "v1", "spec": { "serviceAccountName": "velero" } }'\'' \
  -- /velero'
```

Though another work-around I implemented through ansible is updating the /etc/hosts file on the corresponding node you plan to use velero cli through.

```yaml
# Run after minio tenant has been created
- name: Get minio service cluster IP
  kubernetes.core.k8s_info:
    kind: Service
    namespace: <tenant_namespace>
    name: minio
    kubeconfig: <kubectl_config_path>
  register: minio_service_info
  retries: 12
  delay: 5
  until: minio_service_info.resources | length > 0 # If the tenant was just built, it might take a moment for the service to become available
 
# An alternative to using the k8s_info module would be to retrieve the cluster IP via shell:
# kubectl get service minio -n <tenant_namespace> -o jsonpath='{.spec.clusterIP}' --kubeconfig=<kubectl_config_path>

- name: Define minio service inter-cluster address
  ansible.builtin.set_fact:
    minio_service_address: "minio.<tenant_namespace>.svc.cluster.local"

- name: Add minio service IP to hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: "{{ minio_service_address }}"
    line: "{{ minio_service_info.resources[0].spec.clusterIP }} {{ minio_service_address }}"
    state: present
  become: true # Root privileges required
```

This allows you to use the locally installed velero cli, avoiding the limitations you mentioned.

However, depending on your cluster management practices, the service's cluster IP may change and misalign from the /etc/hosts configuration. Though for my current setup, that should only happen while doing deployments through my automation, which will align that change each run.

Please note that I'm quite new to k8s, so don't hesitate to share criticism or feedback!
